.travis.yml, xray/core/common.py, xray/core/dataset.py, xray/core/ops.py, xray/test/test_variable.py
TODO:
- ~~update documentation~~ (I'll do this later)
- ~~update minimum required numpy version to 1.9? (so we can use np.nanmedian)~~ (added an informative error message for median)
fixes #209
xref #130
=> Switch to use nan-skipping aggregation functions by default and add .median() method

xray/conventions.py, xray/test/test_conventions.py
This makes it possible to read datasets that don't follow CF datetime conventions perfectly, such as the following example which (surprisingly) comes from NCEP/NCAR (you'd think they would follow CF!)
```
ds = xray.open_dataset('http://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20150114_1200.grib2/GC')
print ds['time'].encoding['units']
u'Hour since 2015-01-14T12:00:00Z'
```
=> More robust CF datetime unit parsing

doc/whats-new.rst, xray/core/alignment.py, xray/core/dataarray.py, xray/core/dataset.py, xray/test/test_dataarray.py, xray/test/test_dataset.py
Fixes #186.
This will be a major breaking change for v0.4. For example, we can now do things like this:
```
In [5]: x = xray.DataArray(range(5), dims='x')
In [6]: x
Out[6]:
<xray.DataArray (x: 5)>
array([0, 1, 2, 3, 4])
Coordinates:
* x        (x) int64 0 1 2 3 4
In [7]: x[:4] + x[1:]
Out[7]:
<xray.DataArray (x: 3)>
array([2, 4, 6])
Coordinates:
* x        (x) int64 1 2 3
```
=> Automatic label-based alignment for math and Dataset constructor

README.rst, doc/api.rst, doc/data-structures.rst, doc/examples/weather-data.rst, doc/whats-new.rst, xray/conventions.py, xray/core/alignment.py, xray/core/coordinates.py, xray/core/dataarray.py, xray/core/dataset.py, xray/core/formatting.py, xray/core/variable.py, xray/test/__init__.py, xray/test/test_dataarray.py, xray/test/test_dataset.py
=> Rename Dataset.vars -> data_vars and remove deprecated aliases

xray/core/groupby.py, xray/test/test_dataarray.py
This is special cased for np.ndarrays: applying to DataArrays
is not only inefficient but would also be wrong if the applied
function wanted to change metadata.
Fixes #326
=> Cleanly apply generic ndarrays to DataArray.groupby

xray/core/dataset.py, xray/core/groupby.py, xray/core/utils.py, xray/test/test_dataset.py
This extends the recent change by @IamJeffG (#327).
=> Dataset.apply works if func returns like-shaped ndarrays

doc/whats-new.rst, xray/core/dataset.py, xray/test/test_dataset.py
Previously, I used numbers 1 through 4 for the sake of consistency with
pandas, but such labels really were impossible to keep track of.
=> Update time.season to use text labels like 'DJF'

.travis.yml, doc/whats-new.rst, xray/backends/netCDF4_.py, xray/conventions.py, xray/core/dataset.py, xray/test/test_backends.py
Fixes #273
and half of #272
To serialize a dataset to a string/bytes, simply use `ds.to_netcdf()`. This behavior copies `DataFrame.to_csv()` from pandas. The legacy `dump` and `dumps` methods are deprecated.
My main concern is that the default "format" option is depends on what dependencies the user has installed or if they are saving a file. That seems non-ideal, but may perhaps be the most pragmatic choice given the limitations of the netCDF4 format.
This change also adds:
- Support for writing datasets to a particular NETCDF4 group
- Support for opening netCDF3 files from disk even without netCDF4-python if scipy is installed.
CC @akleeman
=> Unify netCDF4 and scipy backends in the public API

doc/data-structures.rst, doc/indexing.rst, doc/whats-new.rst, xray/core/dataarray.py, xray/core/dataset.py, xray/core/groupby.py, xray/core/utils.py, xray/test/test_backends.py, xray/test/test_dataarray.py, xray/test/test_dataset.py
These are convenient shortcuts for removing variables or index labels from an xray object.
=> Add Dataset.drop and DataArray.drop

doc/api.rst, doc/examples/monthly-means.rst, doc/whats-new.rst, xray/core/formatting.py, xray/test/test_dataset.py
Only the first 500 characters are now shown, e.g.,
In [2]: xray.Dataset(attrs={'foo': 'bar' * 1000})
Out[2]:
<xray.Dataset>
Dimensions:  ()
Coordinates:
*empty*
*empty*
Attributes:
foo: barbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarb
arbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarba
rbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbar
barbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarb
arbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarba
rbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbar
barbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarb
arbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarba...
=> Truncate long attributes when printing datasets

README.rst, licenses/NUMPY_LICENSE, xray/backends/common.py, xray/core/dataset.py, xray/core/utils.py, xray/core/variable.py, xray/test/test_dataset.py, xray/test/test_utils.py
This manifested itself in some variables not being written to netCDF files, because they were determined to be trivial indexes (hence that logic was also updated to be slightly less questionable).
=> Fix bug where Coordinates could turn Variable objects in Dataset constructor

doc/data-structures.rst, doc/whats-new.rst, xray/core/dataarray.py, xray/core/dataset.py, xray/test/test_dataset.py
Fixes #345
This lets you write things like:
counts = time.groupby('time.month').count()
counts.sel(month=2)
instead of the previously valid
counts.sel(**{'time.month': 2})
which is much more awkward. Note that this breaks existing code which relied on the old usage.
CC @jhamman
=> Switch the name of datetime components from 'time.month' to 'month'

doc/api.rst, doc/examples/_code/monthly_averaging.py, doc/examples/weather-data.rst, doc/groupby.rst, doc/whats-new.rst, xray/core/common.py, xray/core/dataarray.py, xray/core/dataset.py, xray/core/groupby.py, xray/core/ops.py, xray/test/test_dataarray.py, xray/test/test_dataset.py, xray/test/test_ops.py
Fixes #354
`resample` lets you resample a dataset or array along a time axis to a coarser
resolution. The syntax is the same as pandas, except you need to supply the
time dimension explicitly:
In [1]: time = pd.date_range('2000-01-01', freq='6H', periods=10)
In [2]: array = xray.DataArray(np.arange(10), [('time', time)])
In [3]: array.resample('1D', dim='time')
Out[3]:
<xray.DataArray (time: 3)>
array([ 1.5,  5.5,  8.5])
Coordinates:
* time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03
You can specify how to do the resampling with the how argument and other
options such as closed and label let you control labeling:
In [4]: array.resample('1D', dim='time', how='sum', label='right')
Out[4]:
<xray.DataArray (time: 3)>
array([ 6, 22, 17])
Coordinates:
* time     (time) …
=> Add resample, first and last

xray/backends/netCDF4_.py, xray/backends/scipy_.py, xray/core/dataset.py, xray/core/utils.py, xray/test/test_backends.py, xray/test/test_dataarray.py, xray/test/test_dataset.py, xray/test/test_variable.py
xref #360
In this change:
- Fix tests that relied on implicit conversion to int64 (Python's int
on windows is int32).
- Be more careful about always closing files, even in tests.
Not addressed (yet):
- Issues with scipy.io.netcdf_file (#341)
=> Fix (most) windows issues

doc/whats-new.rst, xray/core/ops.py, xray/test/test_ops.py
Fixes #344
These warnings are typically spurious on xray objects.
Note that this does result in a *small* performance penalty for these
functions (e.g., a few percent). This can be avoided by install bottleneck.
CC @jhammon
=> Silenced warnings for all-NaN slices when using nan functions from numpy

xray/conventions.py, xray/test/test_conventions.py
Previously conflicting _FillValue and missing_value only raised an AssertionError, now it's more informative.
=> Raise informative exception when _FillValue and missing_value disagree

doc/api.rst, doc/whats-new.rst, xray/core/dataarray.py, xray/core/dataset.py, xray/core/variable.py, xray/test/test_dataarray.py, xray/test/test_dataset.py
Fixes #276
Exmaple usage:
In [8]: ds = xray.Dataset({'x': range(3), 'y': ('x', list('abc'))})
In [9]: ds
Out[9]:
<xray.Dataset>
Dimensions:  (x: 3)
Coordinates:
y        (x) |S1 'a' 'b' 'c'
In [10]: ds.swap_dims({'x': 'y'})
Out[10]:
<xray.Dataset>
Dimensions:  (y: 3)
Coordinates:
* y        (y) |S1 'a' 'b' 'c'
x        (y) int64 0 1 2
*empty*
This is a slightly more verbose API than strictly necessary, because the new
dimension names must be along existing dimensions (e.g., we could spell this
`ds.set_dims(['y'])`). But I still think it's a good idea, for two reasons:
1. It's more explicit. Users control know which dimensions are being swapped.
2. It opens up the possibility of specifying new dimensions with dictionary
like …
=> API: new methods {Dataset/DataArray}.swap_dims

doc/whats-new.rst, xray/conventions.py, xray/test/test_conventions.py
Fixed a regression in v0.4 where saving to netCDF could fail with the error
``ValueError: could not automatically determine time units``.
=> BUG: Fix failing to determine time units

doc/api-hidden.rst, doc/api.rst, doc/computation.rst, doc/examples/weather-data.rst, doc/io.rst, doc/whats-new.rst, doc/why-xray.rst, xray/core/dataarray.py, xray/core/dataset.py, xray/core/groupby.py, xray/core/ops.py, xray/core/variable.py, xray/test/test_dataarray.py, xray/test/test_dataset.py
This is a new method for Dataset, DataArray and GroupBy objects. For the most part, it follows standard broadcasting and alignment rules for binary operations.
Example usage
-------------
Setup:
In [1]: import xray
In [2]: import pandas as pd
In [3]: import numpy as np
In [4]: array = xray.DataArray(np.arange(75.0), [('time', pd.date_range('2000-01-01', periods=75, freq='5D'))])
In [5]: array[::3] = np.nan
In [6]: array
Out[6]:
<xray.DataArray (time: 75)>
array([ nan,   1.,   2.,  nan,   4.,   5.,  nan,   7.,   8.,  nan,  10.,
11.,  nan,  13.,  14.,  nan,  16.,  17.,  nan,  19.,  20.,  nan,
22.,  23.,  nan,  25.,  26.,  nan,  28.,  29.,  nan,  31.,  32.,
nan,  34.,  35.,  nan,  37.,  38.,  nan,  40.,  41.,  nan,  43.,
44.,  nan,  46.,  47.,  nan,  49.,  50.,  nan,  52.,  53.,  nan,
55., …
=> ENH: fillna method for Dataset, DataArray and GroupBy objects

doc/api-hidden.rst, doc/api.rst, doc/whats-new.rst, doc/why-xray.rst, xray/core/common.py, xray/core/coordinates.py, xray/core/dataset.py, xray/core/groupby.py, xray/test/test_dataarray.py, xray/test/test_dataset.py
Fixes #314
Based off the new pandas method of the same name.
An example:
In [3]: ds = xray.Dataset({'y': ('x', [1, 2, 3])})
In [4]: ds.assign(z = lambda x: x.y ** 2)
Out[4]:
<xray.Dataset>
Dimensions:  (x: 3)
Coordinates:
y        (x) int64 1 2 3
z        (x) int64 1 4 9
=> ENH: Add Dataset.assign and .assign_coords

doc/api.rst, doc/dask.rst, doc/io.rst, doc/whats-new.rst, xray/backends/api.py, xray/core/dataarray.py, xray/core/dataset.py, xray/core/variable.py, xray/test/test_backends.py, xray/test/test_dask.py, xray/test/test_dataarray.py, xray/test/test_dataset.py
Also rename `.chunk_data()` -> `.chunk()` (but nobody is using that, yet).
=> Rename .load_data() to the more succinct .load()

doc/api.rst, doc/whats-new.rst, xray/core/dataarray.py, xray/core/dataset.py, xray/test/__init__.py, xray/test/test_conventions.py, xray/test/test_dask.py, xray/test/test_dataarray.py, xray/test/test_dataset.py
These methods make it easy to switch back and forth between data arrays and datasets:
```
In [4]: ds = xray.Dataset({'a': 1, 'b': ('x', [1, 2, 3])},
...:                   coords={'c': 42}, attrs={'Conventions': 'None'})
...: 
In [5]: ds.to_array()
Out[5]: 
<xray.DataArray (variables: 2, x: 3)>
array([[1, 1, 1],
[1, 2, 3]])
Coordinates:
c          int64 42
* x          (x) int64 0 1 2
* variables  (variables) |S1 'a' 'b'
Attributes:
Conventions: None
In [6]: ds.to_array().to_dataset(dim='variables')
Out[6]: 
<xray.Dataset>
Dimensions:  (x: 3)
Coordinates:
c        int64 42
a        (x) int64 1 1 1
b        (x) int64 1 2 3
Attributes:
Conventions: None
```
Fixes #132
CC @IamJeffG
=> Dataset.to_array and DataArray.to_dataset methods

doc/whats-new.rst, xray/backends/api.py, xray/backends/common.py, xray/backends/netCDF4_.py, xray/backends/pydap_.py, xray/core/utils.py, xray/test/test_backends.py
Accessing data from remote datasets now has retrying logic (with exponential backoff) that should make it robust to occasional bad responses from DAP servers.
=> Add robust retry logic when accessing remote datasets

doc/api.rst, doc/whats-new.rst, xray/__init__.py, xray/core/formatting.py, xray/core/options.py, xray/test/test_dataset.py
Example usage:
In [12]: ds = xray.Dataset({'x': np.arange(1000)})
In [13]: with xray.set_options(display_width=40):
....:     print(ds)
....:
<xray.Dataset>
Dimensions:  (x: 1000)
Coordinates:
* x        (x) int64 0 1 2 3 4 5 6 ...
*empty*
In [14]: with xray.set_options(display_width=60):
....:     print(ds)
....:
<xray.Dataset>
Dimensions:  (x: 1000)
Coordinates:
* x        (x) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 ...
*empty*
=> Add display_width option

doc/indexing.rst, doc/whats-new.rst, xray/core/dataarray.py, xray/core/dataset.py, xray/core/indexing.py, xray/test/test_dataarray.py, xray/test/test_dataset.py, xray/test/test_indexing.py
sel() now supports the method parameter, which works like the paramter of the
same name on reindex(). It provides a simple interface for doing nearest-
neighbor interpolation:
In [12]: ds.sel(x=1.1, method='nearest')
Out[12]:
<xray.Dataset>
Dimensions:  ()
Coordinates:
x        int64 1
y        int64 2
In [13]: ds.sel(x=[1.1, 2.1], method='pad')
Out[13]:
<xray.Dataset>
Dimensions:  (x: 2)
Coordinates:
* x        (x) int64 1 2
y        (x) int64 2 3
=> ENH: Add .sel() method to Dataset and DataArray

xray/conventions.py, xray/test/test_backends.py, xray/test/test_conventions.py
Fixes #416
By the way, it turns out the simple work around for this was to install netCDF4 -- only scipy.io.netcdf returns the big-endian arrays directly.
CC @bareid
=> Decode non-native endianness

doc/api.rst, doc/data-structures.rst, doc/whats-new.rst, xray/core/common.py, xray/test/test_dataset.py
`xray.Dataset.assign` and `xray.Dataset.assign_coords` now assign new
variables in sorted (alphabetical) order, mirroring the behavior in pandas.
Previously, the order was arbitrary.
=> Assign order

doc/whats-new.rst, xray/backends/api.py, xray/core/dataset.py, xray/core/variable.py, xray/test/test_backends.py
=> Preprocess argument for open_mfdataset and threading lock

doc/api.rst, doc/whats-new.rst, xray/__init__.py, xray/backends/api.py, xray/backends/common.py, xray/backends/h5netcdf_.py, xray/backends/memory.py, xray/backends/netCDF4_.py, xray/backends/scipy_.py, xray/core/dataset.py, xray/test/test_backends.py
This function allows for saving multiple datasets to disk simultaneously, which
is useful when processing large datasets with dask.array. For example, to save
a dataset too big to fit into memory to one file per year, we could write:
>>> years, datasets = zip(*ds.groupby('time.year'))
>>> paths = ['%s.nc' % y for y in years]
>>> xray.save_mfdataset(datasets, paths)
=> Add xray.save_mfdataset

xray/test/test_dask.py
Resume this test when this bug is fixed:
https://github.com/ContinuumIO/dask/issues/391
=> Mark broken test with latest version of dask

doc/whats-new.rst, xray/backends/h5netcdf_.py, xray/test/test_backends.py
=> Bytes attributes are decoded to strings with engine='h5netcdf'

doc/whats-new.rst, xray/backends/api.py, xray/test/test_backends.py
=> Xray v0.5.2 updates

doc/whats-new.rst, xray/backends/api.py, xray/conventions.py, xray/test/test_conventions.py
NetCDF files which specify multiple missing_value or _FillValue values will
result in a warning being issues and any elements which match any of the
missing_value or _FillValue values being decoded as NaN.
closes #471
=> Allow for multiple values in missing_value or _FillValue

doc/faq.rst
The [CF conventions link](http://cf-pcmdi.llnl.gov/documents/cf-conventions/1.6/cf-conventions.html) in the FAQ is broken. This updates it to the standard location at http://cfconventions.org, which should be kept up to date.
=> Update broken link in FAQ

doc/api.rst, doc/indexing.rst, doc/whats-new.rst, xray/core/dataarray.py, xray/core/dataset.py, xray/test/test_dataarray.py, xray/test/test_dataset.py
This provides behavior equivalent to numpy slicing with multiple lists.
Example
-------
```python
>>> da = xray.DataArray(np.arange(56).reshape((7, 8)), dims=['x', 'y'])
>>> da
<xray.DataArray (x: 7, y: 8)>
array([[ 0,  1,  2,  3,  4,  5,  6,  7],
[ 8,  9, 10, 11, 12, 13, 14, 15],
[16, 17, 18, 19, 20, 21, 22, 23],
[24, 25, 26, 27, 28, 29, 30, 31],
[32, 33, 34, 35, 36, 37, 38, 39],
[40, 41, 42, 43, 44, 45, 46, 47],
[48, 49, 50, 51, 52, 53, 54, 55]])
Coordinates:
* x        (x) int64 0 1 2 3 4 5 6
* y        (y) int64 0 1 2 3 4 5 6 7
>>> da.isel_points(x=[0, 1, 6], y=[0, 1, 0])
<xray.DataArray (points: 3)>
array([ 0,  9, 48])
Coordinates:
y        (points) int64 0 1 0
x        (points) int64 0 1 6
* points   (points) int64 0 1 2
```
related: #475
=> Add pointwise indexing via isel_points method

README.rst, licenses/SEABORN_LICENSE, xray/plotting/__init__.py, xray/plotting/plotting.py, xray/test/test_plotting.py
A diverging colormap is inferred if the values span zero.
Some examples:
Day minus night temperature:
```
(ds.t2m[3] - ds.t2m[1]).plot()
```
With `robust=True`:
```
(ds.t2m[3] - ds.t2m[1]).plot(robust=True)
```
With `cmap='viridis'`:
```
(ds.t2m[3] - ds.t2m[1]).plot(robust=True, cmap='viridis')
```
cc @clarkfitzg
=> Add colormap heuristics copied from Seaborn

doc/api-hidden.rst, doc/api.rst, doc/computation.rst, doc/indexing.rst, doc/whats-new.rst, xray/core/common.py, xray/core/groupby.py, xray/core/ops.py, xray/core/variable.py, xray/test/test_dataset.py
Fixes #503
Example usage:
In [13]: x = xray.DataArray(np.arange(9).reshape(3, 3), dims=['x', 'y'])
In [14]: x.where(x > 4)
Out[14]:
<xray.DataArray (x: 3, y: 3)>
array([[ nan,  nan,  nan],
[ nan,  nan,   5.],
[  6.,   7.,   8.]])
Coordinates:
* y        (y) int64 0 1 2
Example from "What's new":
```
In [4]: ds = xray.Dataset(coords={'x': range(100), 'y': range(100)})
In [5]: ds['distance'] = np.sqrt(ds.x ** 2 + ds.y ** 2)
In [6]: ds.distance.where(ds.distance < 100).plot()
Out[6]: <matplotlib.image.AxesImage at 0x11a819690>
```
=> ENH: where method for masking xray objects according to some criteria

doc/api.rst, doc/indexing.rst, doc/whats-new.rst, xray/core/alignment.py, xray/core/dataarray.py, xray/core/dataset.py, xray/test/test_dataarray.py, xray/test/test_dataset.py
xref #475
Example usage:
In [1]: da = xray.DataArray(np.arange(56).reshape((7, 8)),
...:                     coords={'x': list('abcdefg'),
...:                             'y': 10 * np.arange(8)},
...:                     dims=['x', 'y'])
...:
In [2]: da
Out[2]:
<xray.DataArray (x: 7, y: 8)>
array([[ 0,  1,  2,  3,  4,  5,  6,  7],
[ 8,  9, 10, 11, 12, 13, 14, 15],
[16, 17, 18, 19, 20, 21, 22, 23],
[24, 25, 26, 27, 28, 29, 30, 31],
[32, 33, 34, 35, 36, 37, 38, 39],
[40, 41, 42, 43, 44, 45, 46, 47],
[48, 49, 50, 51, 52, 53, 54, 55]])
Coordinates:
* y        (y) int64 0 10 20 30 40 50 60 70
* x        (x) |S1 'a' 'b' 'c' 'd' 'e' 'f' 'g'
In [3]: da.isel_points(x=[0, 1, 6], y=[0, 1, 0], dim='points')
Out[3]:
<xray.DataArray (points: 3)>
array([ 0,  9, 48])
Coordinates:
y        (points) int64 …
=> Add sel_points for point-wise indexing by label

.travis.yml, doc/conf.py, doc/plotting.rst, doc/requirements.txt, xray/plot/plot.py, xray/test/test_plot.py
This PR adds a discrete colormap / colorbar option to xray plots.
closes #500 
```python
import matplotlib.pyplot as plt
import xray
x = np.arange(start=0, stop=10, step=2)
y = np.arange(start=9, stop=-7, step=-3)
xy = np.dstack(np.meshgrid(x, y))
distance = np.linalg.norm(xy, axis=2)
distance = xray.DataArray(distance, list(zip(('y', 'x'), (y, x))))
fig, axes = plt.subplots(2, 2, figsize=(8, 8), sharex=True, sharey=True)
distance.plot(ax=axes[0, 0])
axes[0, 0].set_title('Default')
distance.plot(vmin=0, vmax=12, levels=6, ax=axes[1, 0])
axes[1, 0].set_title('Setting with integer levels')
distance.plot(levels=[1, 2, 4, 5, 7, 9], extend='both', cmap='Spectral', ax=axes[0, 1])
axes[0, 1].set_title('Setting with list of levels')
flatui = ["#9b59b6", "#3498db", "#95a5a6", …
```
=> Discrete colormap/colorbar option

doc/api.rst, doc/whats-new.rst, xray/core/dataarray.py, xray/plot/plot.py, xray/test/test_dataarray.py
This PR adds convienience methods to convert DataArrays to numpy masked arrays.
`DataArray.to_masked_array(copy=True)` returns a numpy Masked array 
`DataArray.masked_array` returns a masked array that is a view to the `DataArray.values.`
closes #460
=> added to_masked_array method and masked_array property 

doc/whats-new.rst, xray/conventions.py, xray/test/test_conventions.py
=> Bug when encoding datetime64 with NaT as first value

doc/whats-new.rst, xray/core/ops.py, xray/test/test_dask.py
Previously, they would work by loading the arrays into memory.
=> BUG: .all() and .any() are now lazy on dask arrays

doc/whats-new.rst, xray/backends/api.py, xray/conventions.py, xray/test/test_conventions.py
Related to issue #457. I implemented this flag following the instructions given by @shoyer in the issue thread. I have a decent amount of experience with python, but this is the first pull request I set up in GitHub, and I am a begginer with git (more used to svn). I was careful but please check that I did not mess up something ; )
=> Add a --drop-variables flag to xray.open_dataset to exclude certain variables

doc/indexing.rst, doc/whats-new.rst, xray/core/indexing.py, xray/test/test_indexing.py
This mostly reorganizes/updates the indexing documentation.
It also catches an edge case where a slice based indexer could be converted silently into array indexer. This is a strange edge case involving unsorted or duplicate indexes that arguably pandas shouldn't allow anyways.
=> Clarify rules for copies vs views when indexing

xray/core/dataarray.py
Closes #534
The `formatting` for the `__repr__` work perfectly for this.
Didn't write any tests since it seems better to directly test the formatting module here.
=> fixes #534- use core.formatting.format_item for slice title

doc/api.rst, doc/whats-new.rst, xray/core/dataarray.py, xray/core/dataset.py, xray/test/test_dataarray.py, xray/test/test_dataset.py
adds `diff` method to both `DataArray` and `Dataset`. closes #490 
Still to be done:
- tests
Possible enhancements:
- allow numeric `axis` instead of `dim` for `DataArray` objects. The signature would then be `DataArray.diff(dim=None, n=1, axis=None)` and I would need to check that exactly one of `dim` and `axis` is `None`. I find it a bit ugly; `DataArray.diff(n=1, dim=None, axis=None)` would be nicer in my view.  But then the signatures for `DataArray.diff` and `Dataset.diff` would be different, which is also not nice.
- allow specifying the new coordinate array explicitly via a `coord` kwarg instead of just taking the coordinate values of the upper bounds.
What do you think?
=> ENH: finite difference method `diff`

doc/plotting.rst, xray/plot/plot.py
These are the plots that will be in the docs.
=> robust plot documentation

doc/plotting.rst, doc/whats-new.rst, xray/plot/plot.py, xray/test/test_plot.py
This fixes #537 by adding a check for the presence of the colors kwarg.
=> Fix contour color

doc/api-hidden.rst, doc/api.rst, doc/whats-new.rst, xray/core/dataarray.py, xray/core/dataset.py, xray/core/ops.py, xray/core/variable.py, xray/test/test_dataarray.py, xray/test/test_dataset.py, xray/test/test_variable.py
Fixes #553
Also ensures we skip NaN when aggregating with complex dtypes.
~~Still needs release notes.~~
=> Fixes for complex numbers

.travis.yml, doc/api.rst, doc/plotting.rst, xray/plot/__init__.py, xray/plot/facetgrid.py, xray/plot/plot.py, xray/test/test_plot.py
Opening this to provide visibility as I work on this PR.
Currently this has `x` and `y` string arguments for 2d plot working, but everything else still needs lots of work. I'll let people know when it's ready for review.
=> faceted plots

doc/whats-new.rst, xray/core/variable.py, xray/test/test_variable.py
Previous this raised TypeError:
Variable(('x'), [u'tmax'])[0][()]
=> Fixed bug with indexing arrays with unicode dtype

.travis.yml, doc/whats-new.rst, xray/core/common.py, xray/core/variable.py, xray/test/test_dask.py
We were using some internal routines in pandas to convert object of datetime
objects arrays to datetime64. Predictably, these internal routines have now
changed, breaking xray.
This is definitely my fault but also bad luck -- I had a guard against the
internal function dissappearing, but not against the keyword arguments
changing.
In any case, this fix ensures forwards compatibility with the next release of
pandas, which will be coming out next week.
=> BUG: ensure xray works with pandas 0.17.0

xray/core/formatting.py, xray/plot/facetgrid.py, xray/test/test_plot.py
`model = foo` looks better than `model = 'foo'` or `model = u'foo'`.
This is also consistent with what Seaborn does.
=> Don't quote strings in FacetGrid titles

doc/dask.rst, doc/whats-new.rst, xray/backends/api.py, xray/core/dataset.py, xray/core/pycompat.py, xray/core/variable.py, xray/test/test_backends.py, xray/test/test_dask.py
This will allow xray users to take advantage of dask's nascent support for
caching intermediate results (https://github.com/blaze/dask/pull/502).
For example:
In [1]: import xray
In [2]: from dask.diagnostics.cache import Cache
In [3]: c = Cache(5e7)
In [4]: c.register()
In [5]: ds = xray.open_mfdataset('/Users/shoyer/data/era-interim/2t/2014-*.nc', engine='scipy')
In [6]: %time ds.sum().load()
CPU times: user 2.72 s, sys: 2.7 s, total: 5.41 s
Wall time: 3.85 s
Out[6]:
<xray.Dataset>
Dimensions:  ()
Coordinates:
*empty*
t2m      float64 5.338e+10
In [7]: %time ds.mean().load()
CPU times: user 5.31 s, sys: 1.86 s, total: 7.17 s
Wall time: 1.81 s
Out[7]:
<xray.Dataset>
Dimensions:  ()
Coordinates:
*empty*
t2m      float64 279.0
In [8]: %time ds.mean().load() …
=> Use deterministic names for dask arrays from open_dataset

xray/plot/plot.py
```python
proj = ccrs.Orthographic(central_longitude=230, central_latitude=5)
fig, ax = plt.subplots(figsize=(20, 8), subplot_kw=dict(projection=proj))
x.plot.pcolormesh(ax=ax, transform=ccrs.PlateCarree())
ax.coastlines()
```
Before:
After:
=> Fix pcolormesh plots with cartopy

doc/whats-new.rst, xray/core/ops.py, xray/test/test_dask.py
`where` now uses dask instead of numpy if either the array or ``other`` is a
dask array. Previously, if ``other`` was a numpy array the method was
evaluated eagerly.
=> Make where lazy if either argument is a dask array

doc/whats-new.rst, xray/backends/pydap_.py, xray/test/test_backends.py
These should be unpacked as actual global attributes, instead of
being nested dicts under keys like "GLOBAL".
The netcdf4 opendap client already unpacks these attributes.
=> Handle global attribute with engine='pydap' more consistently

xray/plot/facetgrid.py, xray/test/test_plot.py
Fixes #592
Added test to check that all subplots in facet grid have same data range and colormap.
This fixes two issues present in the existing code: 
1) colormap was being selected for each subplot
2) range was being selected for each subplot and colorbar was the result of only the last subplot
Some sample code: 
```Python
data = (np.random.random(size=(20, 25, 12)) + np.linspace(-3, 3, 12)) # range is ~ -3 to 4
da = xray.DataArray(data, dims=['x', 'y', 'time'], name='data')
fg = da.plot.pcolormesh(col='time', col_wrap=4)
```
previously yielded this plot:
and now yields this plot:
=> Fix colormap for facet grid plots

doc/plotting.rst
Fixes #562
Apparently matplotlib 1.3 (which is all we can use on readthedocs) has a
bug when attempting to plot this data using contourf.
cc @clarkfitzg
=> Fix broken facet plot in docs

.gitignore, xray/backends/netCDF4_.py, xray/test/test_backends.py
add more informative error message when unsorted integer array is used to index netCDF4 variable on disk.
Closes #593
=> unsorted integer indexing on netCDF4 objections on disk

doc/api.rst, xray/plot/facetgrid.py, xray/plot/plot.py, xray/test/test_plot.py
This argument is only used in the FacetGrid class and allows users to pass arguments to subplot constructor.
The api change is a pretty simple and just accepts a single new argument (`subplot_kws`).  I think we need to think about how to tweak the subplots a bit more in terms of aspect.
Here's some example code that produces the plot below:
```Python
import xray
import cartopy.crs as ccrs
ds = xray.open_dataset('xray-data/ncep_temperature_north-america_2013-14.nc')
ds.lon -= 360 
lon0 = ds.lon.values.mean()
dss = ds.groupby('time.season').mean('time')
g = dss.air.plot.pcolormesh(col='season', col_wrap=2, transform=ccrs.PlateCarree(),
subplot_kws=dict(projection=ccrs.PlateCarree(lon0)))
for ax in g.axes.flat:
ax.coastlines()
ax.gridlines()
ax.set_extent((-161.25, -28.75, 20, 40))
``` …
=> Add subplot_kws arg to plotting interfaces

doc/plotting.rst, xray/plot/facetgrid.py, xray/plot/plot.py, xray/plot/utils.py, xray/test/test_plot.py
This allows us to use coordinate names as plotting arguments for `x` and `y`.  
I have a test for this that isn't quite working yet.
=> allow passing coordinate names as x and y to plot methods

doc/whats-new.rst, xray/core/npcompat.py, xray/core/nputils.py, xray/test/__init__.py, xray/test/test_dataarray.py, xray/test/test_variable.py
fixes #617 
@shoyer - can you take a look at `test_index_0d_not_a_time` and see if you can figure out why that test is failing?  I couldn't sort it out.
Also, we're now getting a ton of these warnings: 
```FutureWarning: numpy equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.```
I thought about trying to suppress the ones that come directly from xray but that seems tricky to do safely. matplotlib and numpy itself are raising the same warnings.  err...
=> numpy 1.10 compat fixes

xray/backends/api.py, xray/core/coordinates.py, xray/core/dataset.py
http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments
Not sure if you want this or not. I didn't see any cases where this was being used intentionally to store state between calls.
=> Remove all mutable arguments from functions

ci/requirements-py26.yml, doc/indexing.rst, doc/whats-new.rst, xray/core/alignment.py, xray/core/dataarray.py, xray/core/dataset.py, xray/core/indexing.py, xray/test/test_dataarray.py, xray/test/test_dataset.py
`.sel` and `.reindex` now support the ``tolerance`` argument for controlling nearest-neighbor selection:
In [5]: array = xray.DataArray([1, 2, 3], dims='x')
In [6]: array.reindex(x=[0.9, 1.5], method='nearest', tolerance=0.2)
Out[6]:
<xray.DataArray (x: 2)>
array([  2.,  nan])
Coordinates:
* x        (x) float64 0.9 1.5
This feature requires pandas v0.17 or newer.
=> ENH: add tolerance argument to .sel and .reindex

doc/plotting.rst, xray/plot/facetgrid.py, xray/plot/plot.py, xray/plot/utils.py, xray/test/test_plot.py
This, along with the ``.map`` method, provides a much more generally flexible API for making plots.
It still needs some examples for the docs. Here's something simple with synthetic data:
ds = xray.Dataset({'x': np.linspace(0, 10),
'y': [1, 2, 3],
'foo': ('x', np.random.randn(50)),
'bar': ('x', np.random.rand(50))})
ds *= ds.y
(xplt.FacetGrid(ds, col='y')
.map(plt.plot, 'x', 'foo')
.map(plt.scatter, 'x', 'bar', color='green'))
=> Ensure xplt.FacetGrid works on Dataset objects

.travis.yml, ci/requirements-py27-cdat+pynio.yml, doc/io.rst, doc/whats-new.rst, xray/backends/__init__.py, xray/backends/api.py, xray/backends/pynio_.py, xray/conventions.py, xray/test/__init__.py, xray/test/test_backends.py
This pull request adds read-only support for using pynio as an xray backend, by specifying `engine='pydap'` in `open_dataset`.
=> Read only support for PyNIO backend

doc/whats-new.rst, xray/core/dataset.py, xray/test/test_combine.py, xray/test/test_dataset.py
We now get:
In [2]: xray.Dataset({'x': (('x', 'y'), [[1]])})
ValueError: the variable 'x' has the same name as one of its
dimensions ('x', 'y'), but it is not 1-dimensional and thus
it is not a valid index
=> Better error message for variables with same name as a dimension

doc/whats-new.rst, xray/plot/plot.py, xray/plot/utils.py, xray/test/test_plot.py
**Motivation:** https://github.com/xray/xray/issues/642
User's `vmin`, `vmax` are no longer overwritten. You can prevent divergent cmaps and keep automatic vmin, vmax bei setting `center=False`. This is quite intuitive I think (first thing I tried when I wanted to avoid a divergent colormap).
See the new tests for examples of use.
=> More control on cmap params

doc/groupby.rst
=> Document pandas' better groupby performance.

doc/api.rst, doc/whats-new.rst, xray/core/dataarray.py, xray/core/dataset.py, xray/core/variable.py, xray/test/test_dask.py, xray/test/test_dataarray.py, xray/test/test_dataset.py, xray/test/test_variable.py
Fixes #624
New `shift` method for shifting datasets or arrays along a dimension:
In [1]: import xray
In [2]: array = xray.DataArray([5, 6, 7, 8], dims='x')
In [3]: array.shift(x=2)
Out[3]:
<xray.DataArray (x: 4)>
array([ nan,  nan,   5.,   6.])
Coordinates:
* x        (x) int64 0 1 2 3
Based on the API proposed for `roll` in https://github.com/xray/xray/issues/624
=> Shift method for shifting data

doc/whats-new.rst, xray/core/alignment.py, xray/core/combine.py, xray/core/common.py, xray/core/coordinates.py, xray/core/dataarray.py, xray/core/dataset.py, xray/core/groupby.py, xray/core/merge.py, xray/core/variable.py, xray/test/__init__.py, xray/test/test_backends.py, xray/test/test_combine.py, xray/test/test_dask.py, xray/test/test_dataarray.py, xray/test/test_dataset.py, xray/test/test_plot.py, xray/test/test_variable.py
Fixes #367
Fixes #634
Fixes #649
The internal data model used by `DataArray` has been rewritten to fix several outstanding issues (#367, #634 and [this stackoverflow report](http://stackoverflow.com/questions/33158558/python-xray-extract-first-and-last-time-value-within-each-month-of-a-timeseries)). Namely, if a DataArray has the same name as one of its coordinates, the array and the coordinate no longer share the same data.
This means that creating a DataArray with the same ``name`` as one of its dimensions no longer automatically uses that array to label the corresponding coordinate. You will now need to provide coordinate labels explicitly. Here's the old behavior:
In [2]: xray.DataArray([4, 5, 6], dims='x', name='x')
Out[2]:
<xray.DataArray 'x' (x: 3)>
array([4, 5, 6])
Coordinates:
* …
=> Rework DataArray internals

xray/core/common.py
To use the start of a quarter, we actually need to label things like QS.
=> Fix resample docstring

doc/api.rst, doc/whats-new.rst, xray/__init__.py, xray/core/alignment.py, xray/test/test_dataarray.py, xray/test/test_dataset.py
This is a renaming and update of the existing `xray.broadcast_arrays` function,
which now works properly in the light of #648.
xref #649
cc @rabernat 
Examples
--------
Broadcast two data arrays against one another to fill out their dimensions:
>>> a = xray.DataArray([1, 2, 3], dims='x')
>>> b = xray.DataArray([5, 6], dims='y')
>>> a
<xray.DataArray (x: 3)>
array([1, 2, 3])
Coordinates:
>>> b
<xray.DataArray (y: 2)>
array([5, 6])
Coordinates:
* y        (y) int64 0 1
>>> a2, b2 = xray.broadcast(a, b)
>>> a2
<xray.DataArray (x: 3, y: 2)>
array([[1, 1],
[2, 2],
[3, 3]])
Coordinates:
* y        (y) int64 0 1
>>> b2
<xray.DataArray (x: 3, y: 2)>
array([[5, 6],
[5, 6],
[5, 6]])
Coordinates:
* y        (y) int64 0 1
* x        (x) int64 0 1 …
=> Add broadcast function to the API

xray/core/merge.py, xray/test/test_dataarray.py
I noticed that the doc build was broken.
This was introduced by #648, so it hasn't appeared in a released version yet.
=> Fix a bug in alignment when assigning to DataArray.coords

xray/core/dataset.py, xray/test/test_dataset.py
Closes https://github.com/xray/xray/issues/697
@shoyer: am I missing something as to why the special case was there?
=> Allow empty DataFrame in Dataset construction

doc/data-structures.rst, doc/whats-new.rst, xray/core/dataset.py, xray/test/test_dataset.py
Closes a 'first-step' of https://github.com/xray/xray/issues/676. Works only for simple, non-MultiIndexed, pandas objects.
=> Dataset constructor can take pandas objects

xray/core/variable.py, xray/test/test_dask.py
There's no reason why `.copy()` needs to load them into memory as numpy arrays -- we have `.load()` for that.
xref https://github.com/blaze/dask/issues/911
=> Don't unnecessarily copy dask arrays

doc/whats-new.rst, xray/core/common.py, xray/core/dataarray.py, xray/core/dataset.py, xray/test/test_dataarray.py, xray/test/test_dataset.py
This should fail noisily rather than silently:
ds.foo = 12
Fixes #656
Fixes #714
=> Error when attempting to assign using attribute style syntax

doc/whats-new.rst, xray/core/indexing.py, xray/core/utils.py, xray/test/test_variable.py
Of course, we still need to coerce them to a numpy dtype for use in xray (e.g., object)
Fixes #716
=> Handle non-numpy dtypes without erroring

xray/core/alignment.py, xray/core/dataarray.py, xray/core/dataset.py, xray/core/merge.py, xray/test/test_dataset.py
This fixes the underlying issue that allowed #693.
=> Check that dimensions are all valid when using reindex

doc/api.rst, doc/computation.rst, doc/data-structures.rst, doc/index.rst, doc/reshaping.rst, doc/whats-new.rst, xray/backends/api.py, xray/core/dataarray.py, xray/core/dataset.py, xray/core/indexing.py, xray/core/utils.py, xray/core/variable.py, xray/test/test_dask.py, xray/test/test_dataarray.py, xray/test/test_dataset.py, xray/test/test_indexing.py, xray/test/test_variable.py
Fixes #164, #700
Example usage:
```
In [3]: df = pd.DataFrame({'foo': range(3),
...:                    'x': ['a', 'b', 'b'],
...:                    'y': [0, 0, 1]})
...: 
In [4]: s = df.set_index(['x', 'y'])['foo']
In [5]: arr = xray.DataArray(s, dims='z')
In [6]: arr
Out[6]: 
<xray.DataArray 'foo' (z: 3)>
array([0, 1, 2])
Coordinates:
* z        (z) object ('a', 0) ('b', 0) ('b', 1)
In [7]: arr.indexes['z']
Out[7]: 
MultiIndex(levels=[[u'a', u'b'], [0, 1]],
labels=[[0, 1, 1], [0, 0, 1]],
names=[u'x', u'y'])
In [8]: arr.unstack('z')
Out[8]: 
<xray.DataArray 'foo' (x: 2, y: 2)>
array([[  0.,  nan],
[  1.,   2.]])
Coordinates:
* x        (x) object 'a' 'b'
* y        (y) int64 0 1
In [9]: arr.unstack('z').stack(z=('x', 'y'))
Out[9]: 
<xray.DataArray 'foo' (z: 4)>
array([  0.,  nan,   1., …
```
=> Basic multiIndex support and stack/unstack methods

xarray/backends/api.py
This [ImportError](https://github.com/pydata/xarray/blob/master/xarray/backends/api.py#L161-L165) is raised when using open_mfdataset, even though my version of dask is > 0.6:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-6d05f9a40585> in <module>()
----> 1 dset = xarray.open_mfdataset('/Users/rafaguedes/work/campos20150709_0*.nc')
/source/xarray/xarray/backends/api.pyc in open_mfdataset(paths, chunks, concat_dim, preprocess, engine, lock, **kwargs)
297         lock = _default_lock(paths[0], engine)
298     datasets = [open_dataset(p, engine=engine, chunks=chunks or {}, lock=lock,
--> 299                              **kwargs) for p in paths]
300     file_objs = …
```
=> Make import error of tokenize more explicit

doc/whats-new.rst, xarray/core/dataset.py, xarray/test/test_dataset.py
=> Accept rename to same name

doc/whats-new.rst, xarray/core/common.py, xarray/test/test_dataarray.py
Fixes #738 
I have added a simple behaviour for complex numbers in _maybe_promote. This fix means that  _maybe_promote does indeed return (dtype, np.nan + 0j) for complex dtypes, and the complex -> object conversion shown in #738 does not occur.
=> BUG: reindexing an array with complex values should keep dtype=complex

doc/whats-new.rst, xarray/core/variable.py, xarray/test/test_dataset.py
Resolves https://github.com/pydata/xarray/issues/745
A bit of a 'convenient hack'. Let me know if you think there's a better way to do this
=> BUG: Don't transpose variables of one dimension

doc/whats-new.rst, xarray/core/dataarray.py, xarray/test/test_dask.py, xarray/test/test_dataarray.py
Not sure if this was a deliberate choice (maybe so integer indexing wasn't disrupted?). This allows objects as dataset keys / labels.
Let me know your thoughts and I'll add a what's new.
(I know I have a few PRs dangling - apologies - will go back and clean them up soon)
=> Retain label type in .to_dataset

doc/whats-new.rst, xarray/core/dataarray.py, xarray/test/test_dataarray.py
Fixes #758
This was a regression from v0.6.1 due to the big DataArray refactor.
=> BUG: dimensionality consistency checks in DataArray constructor

doc/whats-new.rst, xarray/core/groupby.py, xarray/test/test_dataarray.py, xarray/test/test_indexing.py
We need to supply how='mean' to resample because the resample API is changing.
=> Compatibility fixes for pandas 0.18 and numpy 1.11

doc/whats-new.rst, xarray/core/dataset.py, xarray/test/test_dataset.py
=> Fix converting a dataframe with categorical column and a multiindex

xarray/core/dataset.py, xarray/test/test_dataset.py
Resolves https://github.com/pydata/xarray/issues/740
=> Coerce Series to dict in Dataset constructor

xarray/core/common.py
minor update of `rolling` doc string.  Missed this update after @shoyer's last review.
xref: #668
=> update rolling doc string

xarray/core/common.py, xarray/core/utils.py
=> IDEs resolves ops

doc/data-structures.rst
This should fix the error in the docs here: http://xarray.pydata.org/en/latest/data-structures.html
It is a detail, but it occurred to me that the examples of this section don't use the (space, time) dimension order (e.g. `dims=['time', 'space']`). Most of the climate datasets I know of are using the numpy (lat, lon, time) dim order. Is it intentional?
=> fix value error in data-structures doc

doc/api.rst, doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/ops.py, xarray/test/test_dask.py, xarray/test/test_dataarray.py
=> Add tensordot to dataarray class also add its test to test_dataarray

doc/whats-new.rst, xarray/plot/plot.py, xarray/test/test_plot.py
This PR chooses not to infer interval breaks in pcolormesh if the axis is a Cartopy axis. Below is an example of a plot using the new behavior - compare to https://github.com/pydata/xarray/issues/781#issuecomment-191595449.
I'll come up with a few tests here.
closes #781.
=> dont infer interval breaks in pcolormesh when ax is a cartopy axis

doc/whats-new.rst, xarray/plot/plot.py, xarray/test/test_plot.py
Should fix https://github.com/pydata/xarray/issues/788
=> fix: transpose non-linked coordinates in 2d plots

ci/requirements-py26.yml
It turns out we need the latest toolz from pip, not conda
(which is no longer building packages for Python 2.6).
xref https://github.com/dask/dask/issues/1046
=> Fix failing CI tests on Python 2.6

xarray/backends/common.py
This fixes an error on an asynchronous write for `to_netcdf`
resulting in an `dask.async.RuntimeError: NetCDF: HDF error`
Resolves issue https://github.com/pydata/xarray/issues/793
following dask improvement at https://github.com/dask/dask/pull/1053
following advice of @shoyer.
=> Adds dask lock capability for backend writes

doc/api.rst
I noticed that `empty_like` is listed in the top-level function API:
http://xarray.pydata.org/en/latest/api.html#top-level-functions
But I think it doesn't exist in xarray.
This PR removes the entry from the automodsummary list.
Also: I was the 100th person to fork xarray a minute ago.
What's my prize? I could use a better :car:  or a :house_with_garden: .
=> Remove non-existing empty_like from Sphinx autosummary

doc/whats-new.rst, xarray/core/common.py, xarray/core/groupby.py, xarray/test/test_dataarray.py, xarray/test/test_dataset.py
Closes #825 and #828
This update might break some scripts, because of bugs that existed in the code before. resample was inconsistent as to when it would and would not keep attributes. In particular, Dataset resampling usually threw out attributes, but not when how='first' or how='last', and DataArray preserved attributes for everything I tested ('first', 'last', and 'mean').
=> keep_attrs for Dataset.resample and DataArray.resample

doc/whats-new.rst, xarray/conventions.py, xarray/test/test_conventions.py
Long time listener first time caller :wink: 
I am not 100% about this PR though. I think that there are cases when we need the actual data rather than the `timedelta`. In [this](http://nbviewer.jupyter.org/gist/ocefpaf/6ed33fb35fe526f677e215b3fb304847) notebook we have wave period (`'mper'`) that should be *seconds* ranging `0-30` and not those big numpy timedelta numbers.
I know that I can get that behavior with `decode_times=True` when opening the dataset, but then the `time` coordinate get decoded as well. (Maybe I am way off and there is a way to do this.)
=> Fix #665 decode_cf_timedelta 2D

README.rst, doc/api.rst, doc/computation.rst, doc/examples/_code/accessor_example.py, doc/index.rst, doc/installing.rst, doc/internals.rst, doc/io.rst, doc/whats-new.rst, xarray/__init__.py, xarray/core/dataarray.py, xarray/core/extensions.py, xarray/test/test_extensions.py
Fixes #706
New (experimental) decorators `xarray.register_dataset_accessor` and `xarray.register_dataarray_accessor` for registering custom xarray extensions without subclassing. They are described in the new documentation page on `internals`.
CC @rafa-guedes @rabernat @fmaussion @khaeru @ajdawson -- as people who might use such an interface, it would be great to get some feedback about how well this would work for you.
=> Decorators for registering custom accessors in xarray

doc/whats-new.rst, xarray/conventions.py, xarray/test/test_backends.py, xarray/test/test_conventions.py
This PR allows boolean datatypes to be faithfully roundtripped.  My approach follows @shoyer's suggestions in https://github.com/pydata/xarray/pull/401#issuecomment-96085330.
closes #401 
cc @klapo, @khaeru
=> roundtrip boolean datatype

doc/whats-new.rst, xarray/plot/plot.py, xarray/test/test_plot.py
Addresses https://github.com/pydata/xarray/issues/752 and allows to pass kwargs  to colorbar. For example, it is now possible to do:
```python
import matplotlib.pyplot as plt
x, y = np.meshgrid(np.arange(12), np.arange(12))
z = xr.DataArray(np.sqrt(x**2 + y**2))
ds = z.to_dataset(name='z')
fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(12, 12))
ds.z.plot.contourf(ax=ax1)
ds.z.plot.contourf(ax=ax2, cbar_kwargs={'orientation':'horizontal', 'label':'MyLabel'})
ds.z.plot.contourf(ax=ax3, cbar_ax=ax4, cbar_kwargs={'orientation':'horizontal',
'label':'Funny Cbar',
'drawedges':True})
plt.tight_layout()
plt.show()
```
=> ENH: more control on colorbar

doc/whats-new.rst, xarray/core/combine.py, xarray/core/groupby.py, xarray/core/nputils.py, xarray/core/ops.py, xarray/core/variable.py, xarray/test/test_combine.py, xarray/test/test_dataarray.py, xarray/test/test_ops.py, xarray/test/test_variable.py
We now have a dedicated method, Coordinate.concat that will correctly
concatenate pandas.Index objects, even if they can't be properly expressed as
NumPy arrays (e.g., PeriodIndex and MultiIndex).
As part of this change, I removed and replaced the internal `interleaved_concat`
routine. It turns out we can do this with an inverse permutation instead, which
results in much simpler and cleaner code. In particular, we no longer need a
special path to support dask.array.
This should help with #818.
=> Correctly concatenate pandas.Index objects

doc/whats-new.rst, xarray/core/variable.py, xarray/test/test_variable.py
=> Fix variable copy with multi-index 

doc/data-structures.rst, doc/indexing.rst, doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/indexing.py, xarray/core/variable.py, xarray/test/test_dataarray.py, xarray/test/test_dataset.py, xarray/test/test_indexing.py, xarray/test/test_variable.py
Follows #767.
This is incomplete (it still needs some tests and documentation updates), but it is working for both `Dataset` and `DataArray` objects. I also don't know if it is fully compatible with lazy indexing (Dask). 
Using the example from #767:
```
In [4]: da.sel(band_wavenumber={'band': 'foo'})
Out[4]:
<xarray.DataArray (wavenumber: 2)>
array([ 0.00017,  0.00014])
Coordinates:
* wavenumber  (wavenumber) float64 4.05e+03 4.05e+03
```
As shown in this example, similarily to pandas, it automatically renames the dimension and assigns a new coordinate when the selection doesn't return a `pd.MultiIndex` (here it returns a `pd.FloatIndex`).
In some cases this behavior may be unwanted (??), so I added a `drop_level` keyword argument (if `False` it keeps the multi-index and doesn't change …
=> Multi-index indexing

doc/data-structures.rst
The "by using the" in this paragraph looks like a typo.
=> Remove extra words in docs

xarray/core/coordinates.py, xarray/core/dataset.py, xarray/core/merge.py, xarray/test/test_dataset.py
=> Ensure Dataset.dims wraps a normal dict, not an OrderedDict

doc/whats-new.rst, xarray/test/test_ufuncs.py, xarray/ufuncs.py
=> Pickle xarray.ufunc functions

xarray/core/extensions.py, xarray/test/test_extensions.py
=> Fix silently ignored AttributeError in custom accessors

doc/api.rst, doc/whats-new.rst, xarray/core/dataset.py, xarray/test/test_dataset.py
This PR adds the `get_variables_by_attributes` method similar to the one in `netCDF4-python` and netcdf-java libraries. It is useful to filter a Dataset to known/expected attributes.
@shoyer I don't really like the docs nor the change log entry I created. I will look at them again tomorrow with fresh eyes to see if I can improve them.
Closes https://github.com/pydata/xarray/issues/567
xref: https://github.com/pydata/xarray/issues/567#issuecomment-216947679
=> Add a filter_by_attrs method to Dataset

README.rst, doc/faq.rst
=> add faq on how to cite xarray

doc/whats-new.rst, xarray/core/alignment.py, xarray/core/merge.py, xarray/test/test_dataset.py
Fixes #943
My plan is to issue a quick release tomorrow morning (assuming nothing else comes up tonight) since this could break some user code.
=> Fix assignment to Datasets with non-unique indexes

HOW_TO_RELEASE
For the benefit of @jhamman, and anyone else who may eventually step up to
be a maintainer!
=> Add HOW_TO_RELEASE guidelines

doc/pandas.rst
A start for some docs on transitioning from pandas Panel to xarray. 
This is some way from the final version - but putting it out there and will iterate.
=> WIP for transitioning from Panel docs

HOW_TO_RELEASE, doc/whats-new.rst, xarray/backends/h5netcdf_.py, xarray/backends/netCDF4_.py
This was caused by a recent PR I merged in h5netcdf which switched to using dtype=str in the legacy API (like netCDF4):
https://github.com/shoyer/h5netcdf/pull/11
=> Fix failing tests for h5netcdf that use dtype=str

doc/environment.yml, doc/pandas.rst, doc/whats-new.rst
This includes follow up to fix formatting in the new panel section from #832 and fixing where we said MultiIndex wasn't supported.
CC MaximilianR
=> Fixes to the xarray docs on pandas

xarray/core/alignment.py, xarray/core/coordinates.py, xarray/core/merge.py
This is a cleaner fix for the issues from #943
Moving the logic from `deep_align` into `_align_for_merge` gives us better separation of concerns between the modules for alignment and merging, and puts the special rules for alignment as part of merging in a much more obvious location (no more `skip_single_target`).
xref #927 (cc @crusaderky)
=> Refactor merge alignment into _align_for_merge

doc/api.rst, doc/io.rst, doc/whats-new.rst, xarray/core/common.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/test/test_dataarray.py, xarray/test/test_dataset.py
=> added to_dict function for xarray objects

HOW_TO_RELEASE, doc/whats-new.rst, xarray/core/alignment.py, xarray/core/combine.py, xarray/core/merge.py, xarray/test/test_combine.py, xarray/test/test_dataarray.py, xarray/test/test_dataset.py
- Removed partial_align()
- Added exclude and indexes optional parameters to align() public API
- Added exclude optional parameter to broadcast() public API
- Added various unit tests to check that align() and broadcast() do not perform needless data copies
- broadcast() to automatically align inputs
Note: there is a failed unit test, TestDataset.test_broadcast_nocopy, which shows broadcast on dataset doing a data copy whereas it shouldn't. Could you look into it?
=> Align broadcast

doc/whats-new.rst, xarray/core/variable.py, xarray/test/test_dataset.py
=> Better error message when assigning coordinates without dimensions

doc/whats-new.rst, xarray/core/alignment.py, xarray/core/coordinates.py, xarray/core/merge.py, xarray/test/test_dataset.py
Also give a more informative error message identifying the offending dimension
if reindex/align cannot succeed due to duplicate values along an index.
Fixes #956
=> Consistently skip identical indexes in align

doc/whats-new.rst, xarray/conventions.py, xarray/core/formatting.py, xarray/test/test_conventions.py, xarray/test/test_formatting.py
fixes: #975
work around: pydata/pandas#14068
I finally found 3 issues:
(1) pretty print fails when date is out of bounds
(2) pandas Overflow error (https://github.com/pydata/pandas/issues/14068)
(3) decode_cf_datetime when first date is in bound but later dates are not
from datetime import datetime
xr.core.formatting.format_timestamp(datetime(2800, 1, 1))
ds = xr.Dataset(coords={'time' : [0, 266 * 365]})
units = 'days since 2000-01-01 00:00:00'
ds.time.attrs = dict(units=units)
ds_decoded = xr.conventions.decode_cf(ds)
ds_decoded.time
import netCDF4 as nc
ncf = nc.Dataset('test_future.nc', 'w')
ncf.createDimension('time')
ncf.createVariable('time', np.int, dimensions=('time'))
ncf.variables['time'].units = 'days since 1850-01-01 …
=> fix datetime issues

doc/whats-new.rst, xarray/core/dataset.py, xarray/core/utils.py, xarray/test/test_dataarray.py, xarray/test/test_utils.py
=> Fix flipped array after stacking decreasing coordinate values

doc/whats-new.rst, xarray/conventions.py, xarray/test/test_backends.py
Previously, this resulted in an error: https://github.com/pydata/xarray/issues/873#issuecomment-241540585
=> Fix encoding if dtype is the same as the original

doc/whats-new.rst, xarray/__init__.py, xarray/core/alignment.py, xarray/core/combine.py, xarray/core/common.py, xarray/core/coordinates.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/formatting.py, xarray/core/groupby.py, xarray/core/utils.py, xarray/core/variable.py, xarray/test/test_combine.py, xarray/test/test_dataarray.py, xarray/test/test_dataset.py, xarray/test/test_utils.py, xarray/test/test_variable.py
- Renamed the ``Coordinate`` class from xarray's low level API to
``IndexVariable``. xref https://github.com/pydata/xarray/pull/947#issuecomment-238549129
- Deprecated supplying ``coords`` as a dictionary to the ``DataArray``
constructor without also supplying an explicit ``dims`` argument. The old
behavior encouraged relying on the iteration order of dictionaries, which is
a bad practice (fixes #727).
- Removed a number of methods deprecated since v0.7.0 or earlier:
``load_data``, ``vars``, ``drop_vars``, ``dump``, ``dumps`` and the
``variables`` keyword argument alias to ``Dataset``.
=> Coordinate -> IndexVariable and other deprecations

doc/whats-new.rst, xarray/backends/api.py, xarray/test/test_backends.py
This allows us to give nice errors if users try to save a Dataset with
attr values that can't be written to a netCDF file.
Fixes #911.
I've added tests to `test_backends.py` as I can't see a better place to put them. I've also made the tests fairly extensive, but also used some helper functions to stop too much repetition. Please let me know if any of this doesn't fit within the xarray style.
=> Added validation of attrs before saving to netCDF files

doc/api.rst, doc/io.rst, doc/whats-new.rst, xarray/__init__.py, xarray/backends/api.py, xarray/core/common.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/test/test_backends.py
Added a simple function to DataArray that creates a dataset with one variable
called 'data' and then saves it to a netCDF file. All parameters are passed through
to to_netcdf().
Added an equivalent function called `open_dataarray` to be used to load from these files.
Fixes #915.
=> Added convenience method for saving DataArray to netCDF file

doc/whats-new.rst, xarray/core/utils.py, xarray/test/test_conventions.py
Added test and code change to fix issue #997 
The first added testcase (using `np.nan`) passes even without the change in `core.utils.equivalent`.
=> Discovered conflicting _FillValue and missing_value, but both are NaN

doc/data-structures.rst, doc/indexing.rst, doc/whats-new.rst, xarray/core/coordinates.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/formatting.py, xarray/core/groupby.py, xarray/core/indexing.py, xarray/core/merge.py, xarray/core/variable.py, xarray/test/test_dataarray.py, xarray/test/test_dataset.py, xarray/test/test_indexing.py, xarray/test/test_variable.py
Implements 2, 4 and 5 in #719.
Demo:
```
In [1]: import numpy as np
In [2]: import pandas as pd
In [3]: import xarray as xr
In [4]: index = pd.MultiIndex.from_product((list('ab'), range(2)),
...:                                    names= ('level_1', 'level_2'))
In [5]: da = xr.DataArray(np.random.rand(4, 4), coords={'x': index},
...:                   dims=('x', 'y'), name='test')
In [6]: da
Out[6]: 
<xarray.DataArray 'test' (x: 4, y: 4)>
array([[ 0.15036153,  0.68974802,  0.40082234,  0.94451318],
[ 0.26732938,  0.49598123,  0.8679231 ,  0.6149102 ],
[ 0.3313594 ,  0.93857424,  0.73023367,  0.44069622],
[ 0.81304837,  0.81244159,  0.37274953,  0.86405196]])
Coordinates:
* level_1  (x) object 'a' 'a' 'b' 'b'
* level_2  (x) int64 0 1 0 1
* y        (y) int64 0 1 2 3
In [7]: da['level_1'] …
```
=> Multi-index levels as coordinates

xarray/core/common.py, xarray/core/coordinates.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/test/test_dataset.py
Follow-up on #947
This ensures that you can pull out MultiIndex levels via attribute style
access on Dataset objects, as well as DataArray objects.
CC @benbovy
=> MultiIndex level coordinates as Dataset attributes

doc/whats-new.rst, xarray/core/common.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/test/test_dataset.py
Fixes https://github.com/pydata/xarray/issues/1009
There is probably a more elegant way to do it, but the internals of xarray still confuse me. I'm happy to learn!
=> .where() and .fillna() should preserve attributes

doc/combining.rst, doc/whats-new.rst, xarray/backends/api.py, xarray/core/combine.py, xarray/core/dataset.py, xarray/core/merge.py, xarray/core/variable.py, xarray/test/test_backends.py, xarray/test/test_combine.py, xarray/test/test_merge.py, xarray/test/test_variable.py
- `xarray.merge` now uses `compat='no_conflicts'` by default.
- `compat='no_conflicts'` preserves attributes.
- `Variable.no_conflicts` broadcasts arguments, making it a strictly more
relaxed check than `broadcast_equals`.
- Allow `concat_dim=None` in `open_mfdataset` and `auto_combine` to disable
trying to infer a dimension for concatenating.
- Add `compat` as an argument to `open_mfdataset` to allow more control over
merging.
CC @jcmgray
=> Fixes for compat='no_conflicts' and open_mfdataset

doc/data-structures.rst, doc/whats-new.rst, xarray/core/common.py, xarray/core/groupby.py, xarray/test/test_dataarray.py
This PR fixes a bug in `groupby_bins` in which empty bins were dropped from the grouped results. Now `groupby_bins` restores any empty bins automatically. To recover the old behavior, one could apply `dropna` after a groupby operation.
Fixes #1019
=> Groupby bins empty groups

doc/whats-new.rst
This fixes a typo in the what's new documentation.
=> Fixes doc formating error

doc/api-hidden.rst, doc/api.rst, doc/whats-new.rst, xarray/core/common.py, xarray/core/npcompat.py, xarray/core/ops.py, xarray/core/variable.py, xarray/test/test_dask.py, xarray/test/test_dataarray.py, xarray/test/test_dataset.py, xarray/test/test_variable.py
This PR will add cumsum and cumprod as discussed in https://github.com/pydata/xarray/issues/791 as well ensuring `cumprod` works for the API, resolving issues discussed at https://github.com/pydata/xarray/issues/807.  
TO DO (dependencies)
This PR extends infrastructure to support `cumsum` and `cumprod` (https://github.com/pydata/xarray/issues/791).
References:
* https://github.com/numpy/numpy/pull/7421
cc @shoyer, @jhamman
=> Adds cummulative operators to API 

doc/internals.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs links for their .org -> .io migration for hosted projects

xarray/test/__init__.py
=> Relax assertWarns to fix Windows py27 build

doc/installing.rst
*Very* minor fix to poor formatting and clarification on new conda-forge blurb on the "Installation" docs page. This came about from 633aa112ae03214b76a913edbf3b1f43d0e9281b which addressed #944.
=> Update installing.rst to clarify and fix formatting

doc/whats-new.rst, xarray/backends/netCDF4_.py, xarray/core/combine.py, xarray/test/test_dataset.py
Alternative (and much easier) implementation to https://github.com/pydata/xarray/pull/1048
The problem with the coordinate variables remains the same
=> Preserve variables order in Dataset.concat()

doc/api.rst, doc/whats-new.rst, xarray/core/common.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/groupby.py, xarray/core/variable.py, xarray/test/test_dataarray.py, xarray/test/test_dataset.py, xarray/test/test_variable.py
This allows for consistent access to dimension lengths on ``Dataset`` and
``DataArray``
xref #921 (doesn't resolve it 100%, but should help significantly)
=> New properties `Dataset.sizes` and `DataArray.sizes`

doc/plotting.rst, doc/whats-new.rst, xarray/plot/plot.py, xarray/test/test_plot.py
Addresses https://github.com/pydata/xarray/issues/781
@jhamman what do you think? I'm not sure if ``infer_interval_breaks`` is the best name for the keyword but I didn't come up with anything better than that. (maybe ``infer_coord_intervals``?)
=> New infer_intervals keyword for pcolormesh

doc/conf.py, doc/environment.yml, doc/installing.rst
As discussed here: https://github.com/pydata/xarray/issues/1106
I also added a section somewhere to print the packages versions on RTD. It will be useful to pin the versions again once it works, and is useful enough to stay on the docs I think. I just didn't really knew where to put it, other ideas welcome!
=> Add default channel to conda on RTD

doc/io.rst
sorry if I messed up, I'm not a github master
=> missing return value in sample function calls (I think)

doc/data-structures.rst, doc/examples/monthly-means.rst, doc/whats-new.rst, xarray/core/common.py, xarray/core/dataarray.py
There are some uses of xray that needed to be fixed.
WIP: merge after you decide what to do with https://github.com/pydata/xarray/issues/1135
Also, I'd be in favor of removing the two notebooks in https://github.com/pydata/xarray/tree/master/examples since they are also available in the docs (http://xarray.pydata.org/en/latest/examples.html). The example on RTD have the disadvantage that it's less easy to do copy/paste with them, but notebooks are more error prone since they need to be maintained externally.
=> WIP: remove some refs to xray

doc/conf.py, doc/environment.yml
Now that we seem to have everything working on RTD, re-pin package versions
(follow-up to https://github.com/pydata/xarray/pull/1101)
=> Pin package versions on RTD

doc/environment.yml
Pinning python to 3.5 introduced new [problems](https://readthedocs.org/projects/xray/builds/4723418/).
Despite the default python being 3 [here](https://github.com/pydata/xarray/blob/master/readthedocs.yml#L4) and also in our RTD preferences (dashboard->advanced), RTD seems to still use py2 per default...
Anyway, going back to py2 is the easiest for now, I might come back to this when I have more time.
=> Unpin python on RTD

ci/requirements-py27-cdat+pynio.yml, ci/requirements-py27-netcdf4-dev.yml, ci/requirements-py27-pydap.yml, ci/requirements-py35.yml, doc/whats-new.rst, xarray/backends/api.py, xarray/backends/common.py, xarray/backends/h5netcdf_.py, xarray/backends/netCDF4_.py, xarray/backends/pynio_.py, xarray/backends/scipy_.py, xarray/core/common.py, xarray/core/dataset.py, xarray/core/indexing.py, xarray/core/utils.py, xarray/core/variable.py, xarray/test/__init__.py, xarray/test/test_backends.py, xarray/test/test_conventions.py, xarray/test/test_distributed.py, xarray/test/test_indexing.py, xarray/test/test_utils.py, xarray/test/test_variable.py
This is a follow-up to generalize the changes from #1024:
- Caching and copy-on-write behavior has been moved to separate array classes
that are explicitly used in `open_dataset` to wrap arrays loaded from disk (if
`cache=True`).
- Dask specific logic has been removed from the caching/loading logic on
`xarray.Variable`.
- Pickle no longer caches automatically under any circumstances.
- DataStore objects are now pickleable. This makes it feasible to use xarray's IO with dask-distributed or multi-processing.
~~Still needs tests for the `cache` argument to `open_dataset`, but everything
else seems to be working.~~
@crusaderky @kynan please review
=> Remove caching logic from xarray.Variable

doc/internals.rst, doc/whats-new.rst, xarray/core/extensions.py, xarray/test/test_extensions.py
Fixes #1080 #1082
CC @smartass101 @rabernat
=> Warn instead of erroring when overriding attributes with accessors

doc/whats-new.rst, xarray/plot/facetgrid.py, xarray/plot/plot.py, xarray/test/test_plot.py
Typical usage for xarray.DataArray's for us is to store directional wave data (time, location, direction and frequency). In order to plot directional data stored in DataArray's it would be convenient to use a combination of FacetGrid and polar projections.
Currently, this is not possible with the xarray.plot modules as axes are hard-coded set to be shared among subplots, which conflicts with the fact that polar axes are by definition "box"-adjustable. Therefore we need the ability to turn off axes sharing.
The simple modification attached exposes the sharex/y options to the xarray.plot routines.
=> Expose options for axis sharing between subplots

doc/whats-new.rst, xarray/plot/utils.py, xarray/test/test_plot.py
fixes https://github.com/pydata/xarray/issues/1159
=> Norm should be passed to facetgrid too

xarray/core/alignment.py
Potential mitigation for https://github.com/pandas-dev/pandas/issues/14822
=> PERF: Use len rather than size

doc/io.rst, doc/whats-new.rst, xarray/backends/api.py, xarray/conventions.py, xarray/test/test_backends.py
This PR attempts to solve #1163 by systematically including a default ``_FillValue`` of ``NaN`` whenever the user do not explicitly specify a FillValue. The idea is that third party software should work properly in these situations and if they don't then it is a bug on their side.
=> Set a default _FillValue of NaN for float types

doc/plotting.rst, doc/whats-new.rst, xarray/plot/facetgrid.py, xarray/plot/plot.py, xarray/plot/utils.py, xarray/test/test_plot.py
Extends and finishes https://github.com/pydata/xarray/pull/637
I chose to keep seaborn's convention for two reasons:
- it doesn't break existing code
- now that ``figsize`` is also available, I expect the ``size`` and ``aspect`` kwargs to be less used in non-facetgrid plots
Closes https://github.com/pydata/xarray/issues/897
=> Add figsize, size, and aspect arguments to plotting methods

.travis.yml, ci/requirements-py33.yml, doc/whats-new.rst
Even at the beginning of this year its downloads were 90% lower than 2.6: https://hynek.me/articles/python3-2016/
Impetus is that pytest no longer supports it, and some of the tests I recently wrote don't work on 3.3
=> End support for py3.3?

doc/whats-new.rst
Quick PR to attribute credit to Frederic Laliberte for the default fill value in the ``.to_netcdf()`` method.
=> Add mention of in breaking change about default fill value

doc/whats-new.rst, xarray/core/dataarray.py, xarray/test/test_dataarray.py
Attempt to fix #1177
Please let me know, if PR requires further refinement.
=> Fix inconsistent behaviour for xarray.DataArray.rename

.travis.yml, doc/api.rst, doc/whats-new.rst, setup.cfg, xarray/core/dataset.py, xarray/core/formatting.py, xarray/core/pycompat.py, xarray/test/test_dataset.py, xarray/test/test_formatting.py
I don't know if this is exactly what we want but here's an idea that emulates `ncdump -h`. I'm sure people will have thoughts on the implementation and output so I'll just throw this first cut up and let people discuss.
closes #1150 
fixes #244
xref: #1044, #820
=> add info method to dataset

doc/io.rst
Partly addresses https://github.com/pydata/xarray/issues/768#issuecomment-187226020 and https://github.com/pydata/xarray/issues/1154, mostly by making the tone less defensive. I also added  that we recommend the netCDF format for IO. (I think that the format is powerful enough for being useful in other disciplines than geosciences).
I agree with @rabernat that the current page title (Serialization and IO) could be changed to something more accessible, but I don't know how. Two possibilities, both quite long (it looks a bit ugly on RTD):
- "Reading and writing xarray data structures on disk"
- "Reading/writing xarray data structures"
=> DOC: small improvements to the netCDF docs

doc/installing.rst, doc/whats-new.rst, xarray/core/variable.py
Fixes #1166
xref https://github.com/dask/dask/pull/1840
I don't think there's a good way to test this prior to the release of the next version of dask.
For what it's worth, this will make the minimum version of dask 0.9.0, unless we want to add a hack to handle a non-existent `copy()` method.
=> Actually copy dask arrays in Variable.copy()

doc/whats-new.rst, xarray/plot/plot.py, xarray/plot/utils.py, xarray/test/test_plot.py
Follow-up to https://github.com/pydata/xarray/pull/1171#issuecomment-269556898
From the new docstring:
```
levels : int or list-like object, optional
Split the colormap (cmap) into discrete color intervals. If an integer
is provided, "nice" levels are chosen based on the data range: this can
imply that the final number of levels is not exactly the expected one.
Setting ``vmin`` and/or ``vmax`` with ``levels=N`` is equivalent to
setting ``levels=np.linspace(vmin, vmax, N)``.
```
The logic overhead is quite simple, which is an argument in favor of this simple solution. It is consistent with mpl, as long as neither vmin or vmax are set.
It _might_ change the outcome of some existing plots, though. Should I mention this in the "Breaking changes" section too?
=> Integer levels and vmin/vmax

doc/installing.rst, doc/whats-new.rst, xarray/backends/common.py, xarray/core/ops.py, xarray/core/rolling.py, xarray/test/__init__.py, xarray/test/test_dataarray.py
=> only use bottleneck version 1.0 and later

doc/io.rst
Fix small mistake in documentation.  It said NaN is not a valid dtype for integer dtypes, this surely should be NaN is not a valid value for integer dtypes.
=> DOC: fix small typo/mistake (NaN value not dtype)

doc/plotting.rst, xarray/plot/plot.py
This change explains
- how to pass projection arguments to faceted subplots
- how to access the Axes of the created subplots (not relevant only to cartopy), relevant to issue #1202
=> add info in doc on how to facet with cartopy

doc/whats-new.rst, xarray/core/formatting.py, xarray/test/test_formatting.py
Fixes #680
This shortens the array portion of the DataArray repr to reasonable lengths for high dimensional arrays:
| Array                         | Old length | New length
| ----------------------------- | ----------- | ----------
| np.random.randn(500)          | 167        | 1
| np.random.randn(20, 20)       | 150        | 7
| np.random.randn(5, 10, 15)    | 254        | 24
| np.random.randn(5, 10, 15, 3) | 248        | 19
| air_temperature['air']        | 41         | 24
| rasm['Tair']                  | 37         | 24
The last two entries refer to the corresponding datasets loaded from `xarray.tutorial.load_dataset`.
Importantly, this change does not preclude future improvements, such as those suggested in #1044.
Example of why I switched to lower precision:
```
In [24]: x = …
```
=> Shortened display of NumPy arrays in DataArray.__repr__

doc/api.rst, doc/combining.rst, doc/whats-new.rst, setup.py, xarray/core/common.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/extensions.py, xarray/core/ops.py, xarray/core/options.py, xarray/core/variable.py, xarray/testing.py, xray.py
Fixes #858
Fixes #925
xref #1167
=> Doc and build fixes for v0.9.0

doc/whats-new.rst, xarray/core/formatting.py, xarray/tests/test_conventions.py, xarray/tests/test_formatting.py
=> Fix decoding for multi-dimensional time variables

doc/data-structures.rst, doc/whats-new.rst, xarray/core/formatting.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
Old:
Dimensions:  (x: 1, y: 2)
Coordinates:
*empty*
Unindexed dimensions:
x, y
foo      (x, y) int64 1 2
New:
Dimensions:  (x: 1, y: 2)
Dimensions without coordinates: x, y
foo      (x, y) int64 1 2
=> Better repr for coordinates without dimensions

xarray/core/indexing.py
Bugfix: error message for `KeyError` has spurious `%r`, into which the dimension name is apparently intended to be substituted, but wasn't.  Substitute the dimension name so that the error message is more informative.
=> BUG: Add mixing dimension name to error message

xarray/core/computation.py, xarray/tests/test_computation.py
Leading dimensions do not need to be inserted because broadcasting already
inserts them. Not including them is handy for some uses of apply_ufunc that
don't really want the broadcasting part. Now, they can simply list all of an
argument's dimensions as "core" to avoid any broadcasting.
This is necessary for @jcmgray's proposed use of `apply_ufunc` in https://github.com/pydata/xarray/issues/60#issuecomment-275778443
=> Insert minimal dimensions when broadcasting in apply_ufunc

xarray/core/computation.py, xarray/tests/test_computation.py
This results in a much easier to use function signature than the previous
`signature` argument which required triply nested lists.
e.g., new:
def inner_product(a, b, dim):
return apply_ufunc(_inner, a, b, input_core_dims=[[dim], [dim]])
vs. old:
def inner_product(a, b, dim):
return apply_ufunc(_inner, a, b, signature=[[[dim], [dim]], []])
I also was able to remove the code related to parsing gufunc signatures from strings.
=> Replace 'signature' argument in apply_ufunc with *_core_dims

xarray/core/variable.py
I tried adding some tests but couldn't find a good way of doing that
There is a 20x speed-up though (see issues for prior):
```python
In [4]: In [51]: indexes = [pd.PeriodIndex(start=str((1776 + i)), freq='A', periods=300) for i in range(50)]
...: In [53]: das = [xr.DataArray(range(300), coords=[index]) for index in indexes]
...:
...: In [54]: %timeit xr.concat(das)
...:
10 loops, best of 3: 70.2 ms per loop
```
=> PERF: Override equals in IndexVariable

appveyor.yml, ci/requirements-py27-windows.yml, ci/requirements-py36-windows.yml
@shoyer here I'm reusing existing requirements files.  Is this along the lines of what you were looking for in #1127?
I think this should solve the AppVeyor test failures in #1252, as it should install version 1.2.7 of netCDF4, rather than version 1.2.4.
=> Switch AppVeyor CI to use conda env / requirements.yml

doc/whats-new.rst, xarray/core/rolling.py, xarray/tests/test_dataarray.py
Added 1 line to fix #1125.
I hope this is enough.
If another care is necessary, please let me know.
=> Restored dim order in DataArray.rolling().reduce() 

doc/whats-new.rst, xarray/plot/utils.py, xarray/tests/test_plot.py
=> Guess the complementary dimension when only one is passed to pcolormesh

doc/api.rst, doc/whats-new.rst, xarray/core/common.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
=> add assign_attrs method

xarray/plot/plot.py, xarray/tests/__init__.py, xarray/tests/test_plot.py
Currently, xarray/plot.py raises a `TypeError` if the data to be plotted are not among `[np.floating, np.integer, np.timedelta64, np.datetime64]`.
This PR adds `netCDF4.datetime` objects to the list of allowed data types. These occur, because xarray/conventions.py passes undecoded `netCDF4.datetime` objects if decoding to `numpy.datetime64` fails.
=> Allow for plotting dummy netCDF4.datetime objects.

doc/data-structures.rst
=> Clearer terminology for coordinate variables

xarray/backends/api.py, xarray/backends/common.py
LooseVersion plays nicer when development versions of other libraries (e.g.,
dask) are installed.
=> Use LooseVersion rather than StrictVersion

doc/whats-new.rst, xarray/backends/api.py, xarray/backends/common.py, xarray/backends/h5netcdf_.py, xarray/backends/netCDF4_.py, xarray/backends/pynio_.py, xarray/backends/scipy_.py, xarray/core/pycompat.py, xarray/core/utils.py, xarray/tests/__init__.py, xarray/tests/test_backends.py
Previously, DataStore  did not judiciously close files, resulting in opening a large number of files that
could result in an OSError related to too many files being open.  This merge provides a solution for the netCDF, scipy, and h5netcdf backends.
=> Fixes OS error arising from too many files open

xarray/backends/api.py, xarray/tests/test_backends.py
Ensures that attrs for open_mfdataset are now retained
cc @shoyer
=> Attributes from netCDF4 intialization retained

doc/whats-new.rst, xarray/core/common.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
Resolves error occurring for python 2.7 for the case of `where(mask, drop=True)` where the mask is empty.
=> Ensures drop=True case works with empty mask

doc/whats-new.rst, xarray/core/formatting.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_formatting.py, xarray/tests/test_variable.py
NetCDF files often have tens of attributes, including multi-paragraph summaries or the full modification history of the file.  It's great to have this available in the .attrs, but we can truncate it substantially
in the repr!  Hopefully this will stop people writing `data.attrs = {}` and discarding metadata in interactive workflows for the sake of cleaner output.
=> Shorter repr for attributes

.travis.yml, appveyor.yml, ci/requirements-py27-cdat+pynio.yml, ci/requirements-py27-windows.yml, ci/requirements-py35.yml, ci/requirements-py36-condaforge-rc.yml, ci/requirements-py36-dask-dev.yml, ci/requirements-py36-netcdf4-dev.yml, ci/requirements-py36-pandas-dev.yml, ci/requirements-py36-pydap.yml, ci/requirements-py36-windows.yml, ci/requirements-py36.yml, conftest.py, doc/whats-new.rst, xarray/tests/__init__.py, xarray/tests/test_backends.py, xarray/tests/test_plot.py
=> Marks slow, flaky, and failing tests

doc/api.rst, doc/reshaping.rst, xarray/core/alignment.py, xarray/core/combine.py, xarray/core/common.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/merge.py, xarray/core/variable.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_variable.py
I added a DataArray's method `expand_dims` based on the discussion in #1326 .
The proposed API is similar to `numpy.expand_dims` and slightly different from `Variables.expand_dims`, which requires whole sequences of `dims` of the result array.
My concern is that I do not yet fully understand the lazy data manipulation in xarray.
Does Variable.expand_dims do it?
=> Support for DataArray.expand_dims()

xarray/backends/netcdf3.py, xarray/conventions.py, xarray/core/alignment.py, xarray/core/computation.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/duck_array_ops.py, xarray/core/groupby.py, xarray/core/ops.py, xarray/core/utils.py, xarray/core/variable.py, xarray/testing.py, xarray/tests/__init__.py, xarray/tests/test_dataarray.py, xarray/tests/test_duck_array_ops.py, xarray/tests/test_utils.py, xarray/ufuncs.py
This PR splits xarray.core.ops into two modules:
- xarray.core.ops: for defining operations on xarray objects.
- xarray.core.duck_array_ops: for "duck array" operations defined on either dask or numpy arrays.
There should be no change to user facing API, since xarray.core.ops is strictly internal.
=> Internal cleanup: create xarray.core.duck_array_ops

doc/whats-new.rst, xarray/backends/api.py, xarray/tests/test_backends.py
=> Fix open_dataarray does not pass properly its parameters to open_dataset

doc/whats-new.rst, xarray/backends/api.py, xarray/core/dataset.py, xarray/tests/test_backends.py
Fixes #1320 (writing to file-like objects)
Fixed #1321 (explicitly setting ``engine='scipy'``)
=> Fixes for Dataset.to_netcdf

doc/whats-new.rst, xarray/core/common.py, xarray/tests/test_dataset.py
There might be cleaner ways to fix this than aligning twice, but this will do for now.
=> Fix .where(drop=True) when arguments do not have indexes

doc/time-series.rst, doc/whats-new.rst, xarray/__init__.py, xarray/core/accessors.py, xarray/core/common.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/tests/test_accessors.py
This uses the `register_dataarray_accessor` to add attributes similar to those in pandas` timeseries which let the users quickly access datetime fields from an underlying array of datetime-like values. The referenced issue (#358) also asks about adding similar accessors for `.str`, but this is a more complex topic - I think a compelling use-case would help in figuring out what the critical functionality is
Presumably this could be used to augment `Dataset._get_virtual_variable()`. A **season** field would need to be added as a special field to the accessor.
=> Add DatetimeAccessor for accessing datetime fields via `.dt` attribute

doc/whats-new.rst, xarray/core/dataset.py, xarray/tests/test_dataset.py
A small fix for the bug reported in #1337, where unselected coords were wrongly assigned as `data_vars` by `sel_points`.
I hope I did not forget anything.
=> Patch isel points

xarray/conventions.py, xarray/core/formatting.py
Since the last pandas update I get: 
```
/home/mowglie/Documents/git/xarray/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
from pandas.tslib import OutOfBoundsDatetime
```
=> Fix pandas.tslib deprecation warning

.travis.yml, conftest.py, doc/whats-new.rst, xarray/tests/__init__.py, xarray/tests/test_tutorial.py, xarray/tutorial.py
closes #1392
I'm not sure how to best add tests for this. Also not sure how best to import `shutil`. I followed the current pattern for `os`, but am not sure why that pattern exists in this file. I can clean up further if this is deemed useful.
=> dl tutorial files to tmp directory, then move them once successful

xarray/core/extensions.py
Just noticed this when reading through the code - VERY minor.
The Examples docstring for register_dataarray_accessor referred
to register_dataset_accessor instead.  Moved the example to
register_dataset_accessor.
^ hopefully don't need to fill these in
=> Moved register_dataset_accessor examples docs to appropriate docstring

doc/Makefile, doc/conf.py, doc/environment.yml, doc/examples.rst, doc/gallery/README.txt, doc/gallery/plot_cartopy_facetgrid.py, doc/gallery/plot_colorbar_center.py, doc/index.rst, doc/whats-new.rst
This uses [sphinx-gallery](http://sphinx-gallery.readthedocs.io) to illustrate some examples of the xarray workflow. See it rendered [here](http://xarray.pydata.org/en/fix-docs/auto_gallery/index.html)
It's nicer for the gallery if there is a plot to draw in the end but it doesn't *have* to be a plot. Once the gallery gets more examples it's possible to sort them by topic (see the sphinx gallery documentation for an overview of the possibilities).
I could think of several other things we could add (including moving or copying @jhamman and @rabernat 's examples to the gallery), but I thought it's better to merge quickly in order to encourage the community to contribute with more examples before the next release.
=> Add sphinx-gallery to the docs

xarray/tests/__init__.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
This is causing CI failures for some builds.
This is really a pytest bug (https://github.com/pytest-dev/pytest/issues/2430), but working around this on our end is easy enough (and cleans things up a little).
=> Fix errors in the test suite due to pytest warning changes

xarray/backends/scipy_.py, xarray/tests/test_backends.py
This is a suggested fix to #497. I am happy to clean it up, etc., if the maintainers think it is worthwhile.
=> attempt to fix #497

doc/plotting.rst
This is a trivial fix to point to the current location of the HoloViews documentation.
=> Fix broken holoviews link

doc/whats-new.rst, xarray/core/dataarray.py, xarray/tests/test_dataarray.py
this is needed for the Rasterio PR (https://github.com/pydata/xarray/pull/1260#discussion_r118824181)
There was no test for these functionalities in the xarray test suite for ``Dataset`` either, so I just added a dummy test for one of the keywords.
=> Add dask specific kwargs to DataArray.chunk()

doc/api.rst, doc/whats-new.rst, xarray/__init__.py, xarray/core/groupby.py, xarray/core/variable.py, xarray/tests/test_variable.py
Make `xarray.core.variable.as_variable` part of the public API and accessible as a top-level function: `xarray.as_variable`.
I changed the docstrings to follow the numpydoc format more closely.
I also removed the `copy=False` keyword arguments as apparently it was unused.
=> xarray.core.variable.as_variable part of the public API

xarray/backends/h5netcdf_.py
Solves this error:
```
TypeError: 'NotImplementedType' object is not callable
```
=> change NotImplemented to NotImplementedError for h5netcdf autoclose=True

doc/whats-new.rst, xarray/backends/rasterio_.py, xarray/tests/test_backends.py
Adds the 'res', 'is_tiled', and 'transform' attributes to xarray's rasterio backend.
EDIT: fixed typo; 'tiled' attribute name updated to 'is_tiled'
=> Add attributes to rasterio backend

doc/whats-new.rst, xarray/backends/rasterio_.py, xarray/tests/test_backends.py
Rasterio uses edge-based coordinates, which is a different convention from how xarray treats coordinates (based on description here: http://xarray.pydata.org/en/stable/plotting.html#coordinates). This PR centers them, offsetting by half of the resolution.
~- [ ] Closes #xxxx~
CCing @fmaussion since he may be interested.
=> Center the coordinates to pixels for rasterio backend

xarray/core/variable.py
I've spotted this wrong error message. 
In my opinion this is too small to justify an entry in `whats-new.rst`.
=> Fix text in error message, A leftover from #993

xarray/tests/test_dataset.py
This is a temporary work around for https://github.com/pandas-dev/pandas/issues/16896, which was introduced by pandas 0.20.3
We can safely revert it after the next pandas release.
=> Fix test suite failure in TestDataset.test_sel

doc/whats-new.rst, xarray/testing.py, xarray/tests/test_testing.py
~~This still probably should have a regression test.~~ Done
=> Fix a bug in assert_allclose where rtol and atol were ignored

doc/whats-new.rst, xarray/backends/pynio_.py, xarray/conventions.py, xarray/tests/test_backends.py, xarray/tests/test_conventions.py
=> Automate interpretation of _Unsigned attribute

doc/environment.yml
The pinned version of rasterio we use for the doc builds isn't available anymore: https://github.com/conda-forge/rasterio-feedstock/pull/36
Tests:
- builds: https://readthedocs.org/projects/xray/builds/5796746/
- displays correctly:  http://xarray.pydata.org/en/fix-docs/auto_gallery/plot_rasterio.html#sphx-glr-auto-gallery-plot-rasterio-py
=> Fix rasterio builds in docs

doc/api.rst, doc/computation.rst, doc/whats-new.rst, xarray/__init__.py, xarray/core/accessors.py, xarray/core/alignment.py, xarray/core/common.py, xarray/core/computation.py, xarray/core/dataset.py, xarray/core/dtypes.py, xarray/core/duck_array_ops.py, xarray/core/groupby.py, xarray/core/ops.py, xarray/core/variable.py, xarray/tests/__init__.py, xarray/tests/test_computation.py, xarray/tests/test_dataset.py
Example usage:
```python
>>> a.where(a.x + a.y < 5, -1)
<xarray.DataArray (x: 5, y: 5)>
array([[ 0,  1,  2,  3,  4],
[ 5,  6,  7,  8, -1],
[10, 11, 12, -1, -1],
[15, 16, -1, -1, -1],
[20, -1, -1, -1, -1]])
Dimensions without coordinates: x, y
```
CC @MaximilianR
=> ENH: three argument version of where

asv_bench/asv.conf.json
This should setup the proper links from the published output to the commit on Github.
FYI the benchmarks should be running stably now, and posted to http://pandas.pydata.org/speed/xarray. http://pandas.pydata.org/speed/xarray/regressions.xml has an RSS feed to the regressions.
=> Added show_commit_url to asv.conf

doc/data-structures.rst, xarray/core/dataarray.py
- Clarify in documentation that inferring DataArray dimensions from dictionary like ``coords`` has been deprecated.
- DataArray docstring
=> Small documentation fixes

doc/whats-new.rst, xarray/core/variable.py, xarray/tests/test_variable.py
=> raise TypeError in Variable.quantile if data is a dask array

doc/whats-new.rst, xarray/core/ops.py
=> Fix errors with isnull() that appear with pandas 0.21

doc/Makefile, doc/whats-new.rst, xarray/backends/api.py, xarray/tests/test_backends.py
=> raise error if objects other than datasets are passed to save_mfdataset

xarray/tests/test_dask.py
The fix for this issue went into dask v.0.13 (Jan 2, 2017).
xrefs https://github.com/dask/dask/pull/1799, https://github.com/dask/dask/issues/1764
=> stop skipping test_bivariate_ufunc in test_dask.py

ci/requirements-py36.yml, doc/installing.rst, doc/whats-new.rst, xarray/core/dask_array_ops.py, xarray/core/ops.py, xarray/core/rolling.py, xarray/tests/__init__.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
cc @shoyer, @darothen, @arbennett, @vnoel
=> support dask arrays in rolling computations using bottleneck functions

doc/io.rst, doc/whats-new.rst, xarray/backends/api.py, xarray/backends/pydap_.py, xarray/tests/test_backends.py
Changed `PydapDataStore` to be initialized with a Pydap dataset (returned by `pydap.client.open_url`). Also added a `open` classmethod to PydapDataStore, for opening with a url. The `open` classmethod also takes an optional session object, allowing the api discussed in #1068:
```
pydap_ds = pydap.client.open_url(url, session=session)
store = xarray.backends.PydapDataStore(pydap_ds)
ds = xarray.open_dataset(store)
```
or
```
store = xarray.backends.PydapDataStore.open(url, session=session)
ds = xarray.open_dataset(store)
```
I tested this with NASA Earthdata as you can see in the added testcase, so i used a session object returned from pydap.cas.urs.setup_session() as that function is tailored for that. However, it just returns a `Session` object from the requests library, so maybe …
=> Support opening password protected datasets over Opendap (Fixes #1068)

xarray/core/common.py, xarray/core/rolling.py
This idea for this PR was discussed here: https://stackoverflow.com/questions/45992983/python-xarray-rolling-mean-example
I wasn't able to drop the nans using min_periods so I used the dropna method.
If there is a more eloquent method to my example feel free to point me to it.
- [NA] Closes #xxxx
- [NA] Tests added / passed
- [NA] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API
=> DOC: Added examples to rolling.py

doc/dask.rst
It seems that the continuum folks moved the bolg. They have a redirect at the old URL, but unfortunately it's broken. This appears to be the new url: https://www.anaconda.com/blog/developer-blog/xray-dask-out-core-labeled-arrays-python/
=> Fix URL to dask example

xarray/tests/test_conventions.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
- [n.a.] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API
Currently some tests fail due to dask bug in #1591
=> Remove unused version check for pandas.

xarray/conventions.py
New behavior:
```
In [2]: ds = xarray.open_dataset('http://oos.soest.hawaii.edu/thredds/dodsC/hioos/tide_mhi', decode_cf=True)
...
ValueError: Conflicting _FillValue and missing_value attributes on a variable: -999.99 vs. -999.989990234
Consider opening the offending dataset using decode_cf=False, corrected the attributes and decoding explicitly using xarray.decode_cf().
```
I'm not writing new tests or a what's new notice for this.
=> Better error message for _FillValue vs missing_value conflicts

xarray/core/groupby.py, xarray/tests/test_dataarray.py
- ~[ ] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API~
cc @darothen
=> Fix resample/interpolate for non-upsampling case

ci/requirements-py27-min.yml, xarray/tests/test_dask.py
Our test suite is currently failing due to https://github.com/dask/dask/issues/2718. This marks the failure as expected, which will make our CI a reliable indicator again.
=> Fix the test suite on dask 0.15.3

xarray/core/computation.py, xarray/core/ops.py, xarray/tests/__init__.py, xarray/tests/test_computation.py
This lets you parallelize a function designed for numpy inputs just by adding a few keyword arguments to `apply_ufunc`.
Example usage, to calculate rank correlation between two variables (this will probably turn into an example for the docs):
```python
import bottleneck
def covariance_gufunc(x, y):
return ((x - x.mean(axis=-1, keepdims=True))
* (y - y.mean(axis=-1, keepdims=True))).mean(axis=-1)
def correlation_gufunc(x, y):
return covariance_gufunc(x, y) / (x.std(axis=-1) * y.std(axis=-1))
def spearman_correlation_gufunc(x, y):
x_ranks = bottleneck.rankdata(x, axis=-1)
y_ranks = bottleneck.rankdata(y, axis=-1)
return correlation_gufunc(x_ranks, y_ranks)
def spearman_correlation(x, y, dim):
return xr.core.compuation.apply_ufunc( …
```
=> Automatic parallelization for dask arrays in apply_ufunc

doc/whats-new.rst, xarray/backends/api.py, xarray/core/combine.py, xarray/tests/test_backends.py
There were some long lines that in my opinion look better when not broken, but I complied with flake8 request to shorten them.
=> data_vars option added to open_mfdataset

doc/whats-new.rst, xarray/backends/common.py, xarray/backends/h5netcdf_.py, xarray/backends/netCDF4_.py, xarray/backends/scipy_.py, xarray/tests/test_backends.py
(*these tests will fail until conda-forge get's an updated version of h5netcdf*)
=> Add unlim dims for h5netcdf

doc/api.rst, doc/computation.rst, doc/dask.rst, doc/whats-new.rst, xarray/__init__.py, xarray/core/computation.py
`apply_ufunc()` does not meet all our needs for wrapping unlabeled array routines with xarray (see #1618 for a proposal for `apply_raw()`), but it should be useful for many advanced users and isn't doing much in its current state as non-public API. So I'd like to make it public for the xarray 0.10 release.
@MaximilianR @rabernat @jhamman Review from any of you would be appreciated here!
=> Expose apply_ufunc as public API and add documentation

doc/api.rst, doc/whats-new.rst, xarray/core/dataset.py, xarray/tests/test_dataset.py
=> Deprecate Dataset.T as an alias for Dataset.transpose()

.travis.yml, ci/requirements-py36-rasterio1.0alpha.yml, doc/whats-new.rst, xarray/backends/rasterio_.py
First commit should fix rasterio backend for the current alpha release `rasterio=1.0a10` and for future stable releases. Behind the scenes rasterio converts to a `Window` using `Window.from_slices`. I thought about doing the conversion within xarray and passing a `Window` directly, but that would require importing rasterio within the `__getitem__`, which seems not very great.
Second commit updates the CI service configurations to use the conda-forge development channel that the rasterio alphas are published on. I put the dev channel behind existing channels, and pinned the version of rasterio to anything `1.0` and beyond. Not so sure what the best course of action here is and I'm happy to take suggestions.
Still have to add to the `whats-new`. I'm assuming I can ignore flake8 warnings …
=> Fix rasterio backend for rasterio=1.0a10

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/groupby.py, xarray/core/resample.py, xarray/core/rolling.py, xarray/tests/test_dataarray.py
In the future, this should check array values. For now, issue a FutureWarning.
=> Deprecate checking coordinates in DataArray.__contains__

doc/io.rst, doc/whats-new.rst, xarray/backends/common.py, xarray/core/dataset.py, xarray/tests/test_backends.py
~TODO: 
Additional tests needed to verify this works for all the write backends and that the correct errors are raised when dims are different between writes.~
=> fix to_netcdf append bug (GH1215)

doc/data-structures.rst, doc/whats-new.rst, xarray/backends/api.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/formatting.py, xarray/testing.py, xarray/tests/test_backends.py, xarray/tests/test_combine.py, xarray/tests/test_dataset.py
This will allow us to resolve a long-standing pain-point with consistency between pandas and xarray.
CC @pydata/xarray
=> Add a FutureWarning to Dataset.__iter__ and Dataset.__len__

doc/io.rst, doc/whats-new.rst, xarray/backends/common.py, xarray/backends/h5netcdf_.py, xarray/backends/netCDF4_.py, xarray/backends/netcdf3.py, xarray/conventions.py, xarray/testing.py, xarray/tests/__init__.py, xarray/tests/test_backends.py, xarray/tests/test_conventions.py
Unicode strings (``str`` on Python 3) are now round-tripped successfully even when written as character arrays (e.g., as netCDF3 files or when using ``engine='scipy'``). This is controlled by the ``_Encoding`` attribute convention, which is also understood directly by the netCDF4-Python interface.
This PR also resolves some long-standing technical debt in the test suite related to the hacky use of `decode_bytes` in `assert_allclose` (recently encountered by @jhamman in https://github.com/pydata/xarray/pull/1609). Once we're sure that we don't need it anymore, I'd like to deprecate and eventually remove the `decode_bytes` option.
Note that there are still a few unresolved issues with regards to serializing missing values in strings, so I've intentionally held off on documenting the …
=> Roundtrip unicode strings even when written as character arrays

xarray/core/computation.py, xarray/tests/test_computation.py
This provides an easier way to use `apply_ufunc`, for wrapping non-ufuncs that only act on core dimensions.
=> Add vectorize=True option to apply_ufunc

doc/whats-new.rst, xarray/plot/facetgrid.py, xarray/plot/plot.py, xarray/plot/utils.py, xarray/tests/test_indexing.py
Also fixes a test suite failure in test_indexing.py due to a changed pandas exception type.
=> Fix errors that appear after update to pandas 0.21

.travis.yml, doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/pycompat.py, xarray/core/variable.py, xarray/plot/facetgrid.py, xarray/tests/test_accessors.py, xarray/tests/test_backends.py, xarray/tests/test_combine.py, xarray/tests/test_conventions.py, xarray/tests/test_dask.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_duck_array_ops.py, xarray/tests/test_extensions.py, xarray/tests/test_formatting.py, xarray/tests/test_groupby.py, xarray/tests/test_indexing.py, xarray/tests/test_merge.py, xarray/tests/test_plot.py, xarray/tests/test_ufuncs.py, xarray/tests/test_utils.py, xarray/tests/test_variable.py
This first commit just includes the fixes for the warnings issued in our unit tests. I've temporarily added `-W error` to the travis builds so we can see the warnings/errors for all environments. Next step is to address the warnings in the xarray code itself.
=> fixes for warnings related to unit tests and nan comparisons

README.rst, doc/index.rst
Nobody consistently monitors Gitter, so it's not a good place to suggest for reaching out.
=> Remove Gitter links

xarray/core/dataset.py, xarray/tests/test_dask.py
Follow on to #1489.
- Add a `dim_order` argument
- Always write columns for each dimension
- Docstring to NumPy format
CC @jmunroe @jhamman
=> Tweak to to_dask_dataframe()

doc/whats-new.rst, xarray/core/dataset.py, xarray/tests/test_dataset.py
Remved `T` from `xr.Dataset.__dir__` to suppress a deprecation warning in Ipython autocompletion.
=> Removed `.T` from __dir__ explicitly

doc/whats-new.rst, xarray/core/utils.py, xarray/core/variable.py, xarray/tests/test_dataarray.py, xarray/tests/test_utils.py
xref: #1674
cc @shoyer, @mrocklin
=> fix bugs in is_scalar and as_variable for dask arrays

doc/whats-new.rst, xarray/tests/test_backends.py
The rasterio backend tests each currently have a netcdf roundtrip test without the appropriate `requires_scipy_or_netCDF4` decorator, which causes them to always fail when ran without either. They also do not seem to be necessary for testing the rasterio backend functionality, and just add an extra dependency to the tests. The netCDF roundtrip also seems to be already better tested by the other tests in the same file.
=> Remove netCDF dependency from rasterio backend tests

doc/whats-new.rst, xarray/backends/h5netcdf_.py, xarray/backends/netCDF4_.py, xarray/backends/pydap_.py, xarray/backends/pynio_.py, xarray/backends/rasterio_.py, xarray/backends/scipy_.py, xarray/conventions.py, xarray/core/indexing.py, xarray/core/variable.py, xarray/tests/__init__.py, xarray/tests/test_backends.py, xarray/tests/test_variable.py
This bug originates from the complicated structure around the array wrappers and their indexing,
i.e. different array wrappers support different indexing types, and moreover, some can store another array wrapper in it.
I made some cleanups.
+ Now every array wrapper is a subclass of `NDArrayIndexable`
+ Every array wrapper should implement its own `__getitem__` or just store another `NDArrayIndexable`.
I think I added enough test for it, but I am not yet fully accustomed with xarray's backend.
There might be many combinations of their hierarchical relation.
I would appreciate any comments.
=> Support orthogonal indexing in MemoryCachedArray (Fix for #1429)

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/variable.py, xarray/tests/test_dask.py, xarray/tests/test_distributed.py
This integrates the new dask interface methods into XArray.  This will place XArray as a first-class dask collection and help in particular with newer dask.distributed features.
Builds on work from @jcrist here: https://github.com/dask/dask/pull/2748
Depends on https://github.com/dask/dask/pull/2847
=> Support Dask interface

doc/whats-new.rst, xarray/core/computation.py, xarray/tests/test_computation.py
=> Fix apply_ufunc with dask='parallelized' for scalar arguments

.travis.yml, doc/whats-new.rst, xarray/plot/plot.py
=> Fix importing xarray with python -OO

doc/api.rst, doc/whats-new.rst, xarray/__init__.py, xarray/conventions.py, xarray/tests/test_backends.py
=> Warning for coordinate names with spaces in to_netcdf

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/variable.py, xarray/tests/test_dataarray.py
=> Validate shape of DataArray coords with same name as dimensions

doc/whats-new.rst, xarray/conventions.py, xarray/tests/test_backends.py
=> Raise NotImplementedError when attempting to save a MultiIndex to disk.

doc/whats-new.rst, xarray/backends/netCDF4_.py, xarray/tests/test_backends.py
=> Fix "Chunksize cannot exceed dimension size"

doc/indexing.rst
Fix typo in np.ix_ function as np.xi_.
=> Fix typo in np.ix_ function name

xarray/backends/common.py, xarray/backends/h5netcdf_.py, xarray/backends/netCDF4_.py, xarray/backends/pydap_.py, xarray/backends/pynio_.py, xarray/backends/rasterio_.py, xarray/backends/scipy_.py, xarray/conventions.py, xarray/core/formatting.py, xarray/core/indexing.py, xarray/core/pycompat.py, xarray/core/utils.py, xarray/core/variable.py, xarray/tests/__init__.py, xarray/tests/test_backends.py, xarray/tests/test_conventions.py, xarray/tests/test_dataset.py, xarray/tests/test_indexing.py, xarray/tests/test_variable.py
I'm not entirely sure this is a good idea. The advantage is that it ensures that
all our indexing code is entirely explicit: everything that reaches a backend
*must* be an ExplicitIndexer. The downside is that it removes a bit of
internal flexibility: we can't just use tuples in place of basic indexers
anymore. On the whole, I think this is probably worth it but I would appreciate
feedback.
@fujiisoup can you take a look?
=> Make Indexer classes not inherit from tuple.

doc/whats-new.rst, xarray/core/dataset.py, xarray/tests/test_dataset.py
=> Fix unexpected behavior of .set_index() since pandas 0.21.0

doc/whats-new.rst, xarray/core/formatting.py, xarray/tests/test_backends.py
Only a single missing underscore causes this issue :)
Added tests.
=> Fix unexpected loading after ``print``

doc/whats-new.rst, xarray/plot/plot.py, xarray/tests/test_plot.py
This PR teaches `plot.contourf()` to contour variables with both a 1D co-ordinate (e.g. time) and a 2D co-ordinate (e.g. time-varying depth) `da`:
```
<xarray.DataArray 'S' (z: 5, time: 85646)>
array([[       nan,        nan,        nan, ...,        nan,        nan,
nan],
[ 35.02816 ,  34.729567,  34.779223, ...,  34.57513 ,  34.671975,
34.334675],
[ 35.206943,  35.163239,  34.938674, ...,  34.780728,  34.836331,
34.70386 ],
[       nan,  35.184057,  35.10592 , ...,  34.656925,  34.776915,
34.429442],
[ 34.85562 ,  34.81994 ,  35.00963 , ...,  35.014522,  34.9747  ,
35.033848]])
Coordinates:
depth    (z, time) float16 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 53.5 ...
* time     (time) datetime64[ns] 2013-12-19T06:00:01 2013-12-19T06:10:01 ...
Dimensions without coordinates: z
```
Now we can do …
=> WIP: 1d+2d coord plotting

doc/whats-new.rst, xarray/core/common.py
=> use pandas Grouper instead of TimeGrouper

doc/whats-new.rst, xarray/core/dataarray.py, xarray/tests/test_dask.py
Previously this erroneously pointed to an optimize function, likely a
copy-paste error.
For testing this also redirects the .compute methods to use the
dask.compute function directly *if* dask.__version__ >= '0.16.0'.
Closes #1759
=> Fix DataArray.__dask_scheduler__ to point to dask.threaded.get

doc/whats-new.rst, xarray/backends/rasterio_.py, xarray/tests/test_backends.py
Proof of concept for reading info from rasterio `tags()` in `open_rasterio`. Not quite a solution to #1582, but possibly workable to a more general solution.
Currently implements the following:
- Reads `tags(band_idx)` for each band and extracts the wavelength values from the result dictionaries as a coordinate for the returned DataArray.
- Reads the wavelength_units from `tags(1)` and sets it as an attribute (assumes it's the same for each band, which it is for ENVI format files)
=> Parsing wavelength info from rasterio tags

xarray/coding/variables.py, xarray/tests/test_coding.py
Building off of discussion in #1087, I would like to propose refactoring xarray.conventions to use an interface based on VariableCoder objects with encode() and decode() methods.
The idea is make it easier to write new backends, by making decoding variables according to CF conventions as simple as calling decode() on each coder in a list of coders, with encoding defined by calling the same list of encoders in the opposite order.
As a proof of concept, here I implement only a single Coder. In addition to making use of xarray's existing lazy indexing behavior, I have written it so that dask arrays are decoded using dask (which would solve #1372)
Eventually, we should port all the coders in xarray.conventions to this new format. This is probably best saved for future PRs -- help would be …
=> Refactor xarray.conventions into VariableCoder

setup.py
Change unreleased version numbers as to respect PEP 440.  Rather than
`0.10.0-9-g89a1a98` we will have `0.10.0+dev9.g89a1a98`.  This means
automated setuptools requirements can be respected.  Closes #1300.
=> Respect PEP 440

xarray/core/indexing.py, xarray/core/variable.py, xarray/tests/test_indexing.py, xarray/tests/test_variable.py
This will be useful for multi-dimensional reindexing: marking masked items with
-1 is exactly the convention used by pandas.Index.get_indexer().
Example usage:
In [6]: variable = xr.Variable(('x',), [1, 2, 3])
In [7]: variable._getitem_with_mask([0, 1, 2, -1])
Out[7]:
<xarray.Variable (x: 4)>
array([  1.,   2.,   3.,  nan])
In [8]: variable._getitem_with_mask(xr.Variable(('x', 'y'), [[0, -1], [-1, 1]]), fill_value=-99)
Out[8]:
<xarray.Variable (x: 2, y: 2)>
array([[  1, -99],
[-99,   2]])
This uses where() so it isn't the most efficient (there is some wasted effort
doing indexing, as noted in the TODOs), but the implementation is pretty clean
and already works with dask.
For now, I'm leaving this as private API, but let's expose it publicly in the
future if we are happy with it. I would …
=> Indexing Variable objects with a mask

doc/api-hidden.rst, doc/api.rst, doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/variable.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_variable.py
=> Rank Methods

doc/whats-new.rst, xarray/backends/common.py, xarray/backends/h5netcdf_.py, xarray/backends/netCDF4_.py, xarray/backends/netcdf3.py, xarray/backends/scipy_.py, xarray/backends/zarr.py, xarray/core/variable.py
=> move backend append logic to the prepare_variable methods

doc/whats-new.rst, xarray/plot/plot.py, xarray/tests/test_plot.py
Adds support for plotting multiple lines if `plot.line()` is provided with a 2D dataarray.
kwarg `x` lets you specify co-ordinate for x-axis.
Example:
=> plot.line(): Draw multiple lines for 2D DataArrays.

doc/gallery/plot_lines_from_2d.py, doc/plotting.rst
Extends https://github.com/pydata/xarray/pull/1804 by adding some usage examples to the gallery.
Here is how the plot looks like:
cc @dcherian and @shoyer
=> Add gallery example for multiple lines plot

doc/gallery/plot_rasterio.py, doc/whats-new.rst, xarray/plot/facetgrid.py, xarray/plot/plot.py, xarray/plot/utils.py, xarray/tests/test_plot.py
This patch brings `xarray.plot.imshow` up to parity with `matplotlib.pyplot.imshow`:
- As well as 2D images (greyscale / luminance, using a colormap), it now supports a third dimension for RGB or RGBA channels.  For consistency with 2D arrays, missing data is plotted as transparent pixels
- Being Xarray, users need not care about the order of their dimensions - we infer the right one for color, and warn if it's ambiguous.
- ~~Using `robust=True` for easy saturation is really nice.  Having it adjust each channel and facet in the same way is essential for this to work, which it does.~~
- ~~Matplotlib wraps out-of-range colors, leading to crazy maps and serious interpretation problems if it's only a small region.  Xarray clips (ie saturates) to the valid range instead.~~
*I'm going to …
=> Support RGB[A] arrays in plot.imshow()

.gitignore, ci/requirements-py34.yml, xarray/conventions.py, xarray/core/dataset.py, xarray/core/dtypes.py, xarray/core/indexing.py, xarray/core/missing.py, xarray/core/utils.py, xarray/tests/__init__.py, xarray/tests/test_accessors.py, xarray/tests/test_backends.py, xarray/tests/test_coding_times.py, xarray/tests/test_combine.py, xarray/tests/test_conventions.py, xarray/tests/test_dask.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_distributed.py, xarray/tests/test_duck_array_ops.py, xarray/tests/test_extensions.py, xarray/tests/test_formatting.py, xarray/tests/test_indexing.py, xarray/tests/test_missing.py, xarray/tests/test_plot.py, xarray/tests/test_tutorial.py, xarray/tests/test_ufuncs.py, xarray/tests/test_utils.py, xarray/tests/test_variable.py
So far, only the changes that `unittest2pytest` could fix. Need to work out how to sort through the exisiting xarray ones
EDIT: ready to merge (and keen to get this in before there are divergences from other branches)
=> pytest-ification

doc/plotting.rst, doc/whats-new.rst, xarray/plot/plot.py, xarray/plot/utils.py, xarray/tests/test_plot.py
Follow-up to #1796, where normalisation and clipping of RGB[A] values were deferred so that we could match any upstream API.  matplotlib/matplotlib#10220 implements clipping to the valid range, but a strong consensus *against* RGB normalisation in matplotlib has emerged.
This pull therefore implements normalisation, and clips values only where our normalisation has pushed them out of range.
=> Normalisation for RGB imshow

doc/whats-new.rst, xarray/backends/rasterio_.py, xarray/tests/test_backends.py
=> rasterio backend: added nodatavals attribute

doc/whats-new.rst, xarray/core/duck_array_ops.py, xarray/tests/test_dataarray.py
Fixes #1838.
The new rule for reduce is 
+ If dtype is not None and different from array's dtype, use numpy's aggregation function instead of bottleneck's.
+ If out is not None, raise an error.
as suggested in [this comments](https://github.com/pydata/xarray/issues/1838#issuecomment-358851474).
=> Add dtype support for reduce methods.

doc/whats-new.rst, xarray/backends/rasterio_.py, xarray/tests/test_backends.py
This is a simple fix for token generation of non-filename targets for rasterio.
The problem is that I have no idea how to test it without actually hitting s3 (which requires boto and aws credentials).
=> fix rasterio chunking with s3 datasets

.github/PULL_REQUEST_TEMPLATE.md, doc/whats-new.rst, xarray/coding/variables.py, xarray/tests/test_backends.py, xarray/tests/test_coding.py
Most satellites produce images with color depth in the range of eight to sixteen bits, which are therefore often stored as unsigned integers (with the quality mask in another variable).  If you're lucky, they also have a `scale_factor` attribute and Xarray can automatically convert the integers to floats representing albedo.
This is fantastically convenient, and avoids all the bit-depth bugs from misremembered specifications.  However, loading data as float64 when float32 is sufficient *doubles* memory usage in IO (even on multi-TB datasets...).  While immediately downcasting helps, it's no substitute for doing the right thing first.
So this patch does some conservative checks, and if we can be sure float32 is safe we use that instead.
=> Read small integers as float32, not float64

doc/whats-new.rst, xarray/backends/h5netcdf_.py, xarray/tests/test_backends.py
=> Fix outer indexing on datasets loaded with h5netcdf

doc/installing.rst, doc/whats-new.rst
=> add warning stating that xarray will drop python 2 support at the end of 2018

xarray/tests/test_coding_times.py
=> test decoding num_dates in float types

doc/conf.py, doc/gallery/plot_rasterio.py, doc/gallery/plot_rasterio_rgb.py
https://github.com/pydata/xarray/pull/1796 introduced a bug in the doc gallery. This PR reverts the code to the previous greyscale example and adds a new case using imshow (the use case is different, as I tried to explain in the descriptions).
I also took care of https://github.com/pydata/xarray/issues/1789#issuecomment-356068358 : the docs should now build even when rasterio is not installed.
cc @Zac-HD , @shoyer
=> Fix rasterio example in docs

xarray/backends/api.py, xarray/core/computation.py
Adds links and inline prose to docstrings referencing relevant sections of online documentation.
=> links from docstrings to documentation for apply_ufunc and open_mfdataset

doc/contributing.rst
I think that pip install is the recommended way to install packages in dev mode (see also http://www.python3statement.org/practicalities/ )
=> Use pip install -e in contributing docs

doc/whats-new.rst, xarray/tests/test_backends.py
This PR restores the tests that were incorrectly removed in https://github.com/pydata/xarray/pull/1817 and adds the what's new entry I forgot in https://github.com/pydata/xarray/pull/1712
=> Simplify some rasterio tests

xarray/tests/test_distributed.py
This internal state was changed in the latest release
=> Replace task_state with tasks in dask test

doc/gallery/plot_rasterio_rgb.py, xarray/plot/plot.py, xarray/tests/test_plot.py
The cause of the bug in #1880 was that I had forgotten to specify the dtype when creating an alpha channel, and therefore concatenating it cast the all the data to float64.  I've fixed that, corrected the alpha value for integer arrays, and avoided a pointless copy to save memory.
=> Use correct dtype for RGB image alpha channel

.travis.yml, doc/environment.yml, doc/installing.rst
=> Build documentation on TravisCI

doc/whats-new.rst, xarray/plot/utils.py
Instead of relying on seaborn per default we now use mpl and fall back to seaborn if cmap is not recognized (e.g. with `cmap="husl"`).
=> _color_palette consistent with or without seaborn

doc/whats-new.rst, xarray/core/variable.py, xarray/tests/test_variable.py
Now Variable accepts 0d-np.ndarray indexer.
=> Support indexing with 0d-np.ndarray

xarray/plot/plot.py, xarray/tests/test_plot.py
I added a simple warning to `_infer_interval_breaks` in `xarray/plot/plot.py`. The warning does not currently say the name of the coordinate, because that would requiring introducing a new function or potentially passing a name argument, which seems overly complicated for such a small dit. Hopefully, this isn't a problem because the user can easily figure out which coordinate is not sorted by process of elimination.
=> Raise when pcolormesh coordinate is not sorted

.gitignore, .stickler.yml, asv_bench/benchmarks/__init__.py, asv_bench/benchmarks/dataarray_missing.py, asv_bench/benchmarks/indexing.py, doc/examples/_code/accessor_example.py, doc/examples/_code/weather_data_setup.py, doc/gallery/plot_cartopy_facetgrid.py, doc/gallery/plot_colorbar_center.py, setup.cfg, setup.py, xarray/backends/rasterio_.py, xarray/backends/zarr.py, xarray/core/dataset.py, xarray/core/indexing.py, xarray/core/pycompat.py, xarray/plot/plot.py, xarray/testing.py, xarray/tests/test_backends.py, xarray/tests/test_dataset.py, xarray/tests/test_duck_array_ops.py, xarray/tests/test_indexing.py, xarray/tests/test_ufuncs.py
I was still getting stickler errors for code I hadn't changed. Flake8 should now pass
=> flake8 passes

xarray/tests/test_coding_times.py
@jhamman I'm sorry I missed this in #1920.  The time decoding tests in the temporary Travis build with the new `netcdftime` library are all skipped because they are tagged with `@requires_netCDF4` decorators rather than `@requires_netcdftime` ones.  This PR fixes that.
In a local environment (after swapping these decorators) with the new `netcdftime`, I'm actually getting a failure, so there may be a bug we need to sort out upstream.
=> Use requires_netcdftime decorators in test_coding_times.py

doc/whats-new.rst, xarray/core/indexing.py, xarray/tests/test_variable.py
This precision drop was caused when converting `pd.Timestamp` to `np.array`
```python
In [7]: ts = pd.Timestamp(np.datetime64('2018-02-12 06:59:59.999986560'))
In [11]: np.asarray(ts, 'datetime64[ns]')
Out[11]: array('2018-02-12T06:59:59.999986000', dtype='datetime64[ns]')
```
We need to call `to_datetime64` explicitly.
=> Fix precision drop when indexing a datetime64 arrays.

doc/index.rst
Not a big change, but adds a little more clarity IMO.
I'm open to any suggestion for better section names and/or organization. Also I let "What's new" at the top, but not sure if "Getting started" is the right section.
=> DOC: add main sections to toc

doc/gallery/control_plot_colorbar.py, doc/gallery/plot_proportional_colorbar.py
Using 'cbar_kwargs' it is possible to extend the capabilities of colorbar ticks.
=> DOC: Plot discrete colormap with proportional colorbar

doc/api-hidden.rst, doc/api.rst, doc/computation.rst, doc/dask.rst, doc/environment.yml
=> Fix doc for missing values.

doc/plotting.rst, doc/whats-new.rst, xarray/plot/plot.py, xarray/tests/test_plot.py
`plot.line` now supports both 1D and 2D DataArrays as input. I've changed  some variable names to make code clearer:
1. set `xplt`, `yplt` to be values that are passed to `ax.plot()`
2. `xlabel`, `ylabel` are axes labels
3. `xdim`, `ydim` are dimension names
This code
```z = np.arange(10)
da = xr.DataArray(np.cos(z), dims=['z'], coords=[z], name='f')
xy = [[None, None],
[None, 'f'],
[None, 'z'],
['f', None],
['z', None],
['z', 'f'],
['f', 'z']]
f, ax = plt.subplots(2,4)
for aa, (x,y) in enumerate(xy):
da.plot(x=x, y=y, ax=ax.flat[aa])
ax.flat[aa].set_title('x='+str(x)+ ' | '+'y='+str(y))
```
yields
Should I refactor out the kwarg checking?
=> Add x,y kwargs for plot.line().

doc/whats-new.rst, xarray/plot/facetgrid.py, xarray/tests/test_plot.py
This seemed the cleanest way to fix this. If both `colors` and `cmap` are specified, raise an error. If `colors` is specified and `cmap` was None, I set the auto-inferred `cmap` to None.
=> facetgrid: unset cmap if colors is specified.

xarray/backends/zarr.py
=> Check for minimum Zarr version.

doc/whats-new.rst, xarray/core/computation.py
=> Better error message for vectorize=True in apply_ufunc with old numpy

doc/whats-new.rst, xarray/plot/utils.py, xarray/tests/test_plot.py
Not much more to say, really.  Thanks to @fmaussion for pinging me - definitely faster to track down when you know the code!
=> Fix RGB imshow with X or Y dim of size one

doc/whats-new.rst, xarray/backends/rasterio_.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_duck_array_ops.py
These have been getting a little out of hand.
Currently down from 255 to 104 warnings.
xref https://github.com/pydata/xarray/issues/1652
=> Resolve more warnings in the xarray test suite

asv_bench/benchmarks/rolling.py, doc/whats-new.rst, xarray/core/rolling.py
Quick fix of #1993.
With this fix, the script shown in #1993 runs
Bottleneck:  0.08317923545837402 s
Pandas:  1.3338768482208252 s
Xarray:  1.1349339485168457 s
=> Make constructing slices lazily.

doc/whats-new.rst, xarray/core/indexing.py, xarray/tests/test_dataarray.py
=> Fix using xarray's own times for slice indexing

.gitignore, .travis.yml, ci/requirements-py36-hypothesis.yml, properties/README.md, properties/test_encode_decode.py
This is a small property-based test suite, to give two examples of the kinds of tests that we could write for Xarray using Hypothesis.
1. For any array, encoding and decoding it with a CF coder outputs an identical array.  As you would hope, these tests pass.
2. For any 2D array, you can call the 2D plotting methods without raising an exception.  Alas, this is *not* the case, and Hypothesis will show you the failing inputs (and matplotlib-related tracebacks) to prove it.
(Contributing a very small feature to matplotlib was shockingly painful, so I'm not planning to take a similar suite upstream myself unless something changes)
Things that I would like to know:
- Have I build-wrangled something reasonable here?
- Will anyone else contribute property-based tests?  I'm happy to help people …
=> Starter property-based test suite

xarray/backends/netCDF4_.py
The warning introduced in #1835 has an extraneous full stop. This PR removes it.
=> Extraneous full stop in 88 char warning

doc/index.rst
We made this change several years ago now -- it's no longer timely news to
share with users.
=> Remove note about xray from docs index

doc/computation.rst
I like @fujiisoup's weighted mean demo in this stack overflow example:
https://stackoverflow.com/questions/48510784/xarray-rolling-mean-with-weights
I thought it'd be a useful addition to the docs on rolling.
=> Add weighted mean docs.

xarray/tests/test_backends.py
These are broken by SciPy 1.0.1.
For details, see https://github.com/pydata/xarray/issues/2019
=> xfail tests that append to netCDF files with scipy

pytest.ini, setup.cfg
Currently our pytest settings in `setup.cfg` are ignored, because they're overridden by the presence of a `pytest.ini`
This restores pytest looking at `setup.cfg`, gives us a single place to put configs, and retains the 'no hypothesis by default'. Hypothesis is still run in travis, which specifically calls `pytest properties`
=> One pytest config

xarray/backends/netCDF4_.py, xarray/tests/test_backends.py
This test was turning all warnings into errors. Now it's more robust, and only
converts the appropriate warning into an error.
=> Fix test_88_character_filename_segmentation_fault

doc/whats-new.rst, xarray/coding/variables.py, xarray/tests/test_conventions.py
The CF standard permits both values, and them to have different values, so we should not be treating this as an error--just mask out all of them.
=> Allow _FillValue and missing_value to differ (Fixes #1749)

doc/whats-new.rst, xarray/coding/times.py, xarray/tests/test_coding_times.py
Not sure yet if this is the best way to do this.
=> Fix an overflow bug in decode_cf_datetime

doc/whats-new.rst, xarray/core/dataset.py, xarray/tests/test_dataset.py
Makes `np.asarray(dataset)` issue an informative error. Currently,
`np.asarray(xr.Dataset({'x': 0}))` raises `KeyError: 0`, which makes no sense.
=> Raise an informative error message when converting Dataset -> np.ndarray

doc/whats-new.rst, xarray/core/combine.py, xarray/tests/test_backends.py, xarray/tests/test_combine.py
=> concat_dim for auto_combine for a single object is now respected

xarray/tests/test_backends.py
xref https://github.com/pydata/xarray/issues/2050
This should fix the test suite on Travis-CI again.
=> xfail test_cross_engine_read_write_netcdf3

doc/whats-new.rst, xarray/conventions.py, xarray/tests/test_conventions.py
This was a very simple fix for an issue that has vexed me for quite a while. Am I missing something obvious here?
=> Fix decode cf with dask

doc/whats-new.rst, xarray/backends/netCDF4_.py, xarray/tests/test_backends.py
=> Implement setncattr_string for attributes that are lists of strings

xarray/core/variable.py
Simple spelling correction.
Add space to end of line halfway through error message on line 682 to avoid 'bebroadcast' on string concatenation.
- ~~Tests added (for all bug fixes or enhancements)~~
- ~~Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API (remove if this change should not be visible to users, e.g., if it is an internal clean-up, or if this is part of a larger project that will be documented later)~~
=> resolve #2071: 'bebroadcast' in ValueError msg

xarray/backends/memory.py, xarray/backends/netCDF4_.py, xarray/backends/netcdf3.py, xarray/backends/zarr.py, xarray/coding/strings.py, xarray/coding/variables.py, xarray/conventions.py, xarray/tests/test_backends.py, xarray/tests/test_coding_strings.py, xarray/tests/test_conventions.py
Fixes #2057
This refactor will make it easier to use different coding for different backends. It also makes string decoding/encoding work properly with dask arrays, which I think was the issue responsible for #2057.
It includes using a special dtype with metadata (like h5py) to identify variable length strings. So in principle, we could now handle fixed width and variable length unicode differently.
I also took this opportunity to fix handling of strings in zarr. We now no longer convert into character arrays, but instead store as fixed length bytes (with UTF-8 encoding, if necessary). This wasn't really necessary, but it is a little cleaner, since zarr doesn't have the restriction of only supporting character arrays.
CC @rabernat @jhamman
=> Refactor string coding and fix string support in zarr

ci/requirements-py27-windows.yml
This should fix our build failures on Appveyor.
=> Install cftime with pip on Windows

doc/whats-new.rst, xarray/core/computation.py, xarray/core/duck_array_ops.py, xarray/tests/test_computation.py, xarray/ufuncs.py
Closes #2074 
Requires dask >= 0.17.3
=> xarray.dot is now based on da.einsum

doc/io.rst, doc/whats-new.rst
The documentation of Rasterio used to be at https://mapbox.github.io/rasterio/, but now you'll get a 404 and a pointer to https://rasterio.readthedocs.io/en/latest/. I've updated the links in `io.rst` and `whats-new.rst`.
Don't think I need to check the boxes below. :)
- [NA] Closes #xxxx (remove if there is no corresponding issue, which should only be the case for minor changes)
- [NA] Tests added (for all bug fixes or enhancements)
- [NA] Tests passed (for all non-documentation changes)
- [NA] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API (remove if this change should not be visible to users, e.g., if it is an internal clean-up, or if this is part of a larger project that will be documented later)
=> DOC: Update link to documentation of Rasterio

doc/plotting.rst, doc/whats-new.rst, xarray/plot/plot.py, xarray/plot/utils.py, xarray/tests/test_plot.py
`plot.line()` now accepts `xincrease`, `yincrease` kwargs (see bottom panel of image).
Additionally, instead of calling `autofmt_xdate()` which deletes all subplot x-axes except the last one, I rotate and set alignment for the x-axes labels manually. This allows for creating figures where not all subplots have time on the x-axis.
=> Plotting upgrades

xarray/backends/common.py
Need '::' to introduce a code literal block. This was causing MetPy's
doc build to warn (since we inherit AbstractDataStore).
=> Fix docstring formatting for load().

doc/whats-new.rst, xarray/core/dask_array_ops.py, xarray/core/rolling.py, xarray/tests/test_dataarray.py
Two bugs were found and fixed.
1. rolling a dask-array with center=True and bottleneck
2. rolling an integer dask-array with bottleneck
=> Fixes centerized rolling with bottleneck

doc/whats-new.rst, xarray/plot/utils.py, xarray/tests/test_plot.py
The current version uses `pd.isnull` to remove invalid values from input data when making a colorbar. `pd.isnull([np.inf])` is False which means `_determine_cmap_params` returns Inf for colorbar limits which screws everything up. This PR changes `pd.isnull` to `np.isfinite`.
=> Prevent Inf from screwing colorbar scale.

doc/environment.yml
cftime is now needed to build the documentation: http://xarray.pydata.org/en/latest/time-series.html#non-standard-calendars-and-dates-outside-the-timestamp-valid-range
Sorry I neglected this in #1252!
=> Add cftime to doc/environment.yml

asv_bench/benchmarks/rolling.py, doc/whats-new.rst, xarray/core/dask_array_ops.py, xarray/core/rolling.py
I noticed `rolling` with dask array and with bottleneck can be slightly improved by reducing the padding depth in `da.ghost.ghost(a, depth=depth, boundary=boundary)`.
@jhamman , can you kindly review this?
=> Reduce pad size in rolling

ci/requirements-py27-windows.yml, doc/time-series.rst, xarray/coding/times.py, xarray/tests/test_coding_times.py
I can confirm the docs now build properly locally:
=> Fix datetime.timedelta casting bug in coding.times.infer_datetime_units

doc/faq.rst, doc/internals.rst, doc/whats-new.rst
partially addresses #1850 
closes #946 
I tried to make an "awesome xarray" list by doing a github search for 'xarray'. I only put packages that looked like they were intended for general use. Also, I moved the list from `internals.rst` to `faq.rst`.
Let me know if there are any I've missed or any that should be added.
=> Add "awesome xarray" list to faq.

xarray/core/computation.py, xarray/tests/test_computation.py
=> xarray.dot to pass **kwargs to einsum

doc/whats-new.rst, xarray/convert.py, xarray/core/duck_array_ops.py, xarray/tests/test_dataarray.py
- Add test for issue fixed in #2047 
- Add workaround for da.ma.masked_invalid setting a bad chunksize when given a DataArray rather than a Dask array. Tested manually but unsure how best to add a unit test for this.
=> Fix to_iris conversion issues

doc/whats-new.rst, xarray/core/coordinates.py, xarray/core/dataarray.py, xarray/tests/test_dataarray.py
Now uses `dataset_merge_method` when a new coordinate is assigned to a xr.DataArray
=> Raise an Error if a coordinate with wrong size is assigned to a dataarray

doc/api.rst, xarray/__init__.py, xarray/coding/cftimeindex.py
~- [ ] Tests added (for all bug fixes or enhancements)~ 
cc @spencerkclark and @shoyer
=> expose CFTimeIndex to public API

doc/whats-new.rst, xarray/core/dataset.py, xarray/core/duck_array_ops.py, xarray/core/variable.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_duck_array_ops.py
Fixes GH1470, "Dataset.mean drops coordinates"
Fixes a bug where non-scalar data-variables that did not include the
aggregated dimension were not properly reduced:
Previously::
>>> ds = Dataset({'x': ('a', [2, 2]), 'y': 2, 'z': ('b', [2])})
>>> ds.var('a')
Dimensions:  (b: 1)
Dimensions without coordinates: b
x        float64 0.0
y        float64 0.0
z        (b) int64 2
Now::
>>> ds.var('a')
Dimensions:  (b: 1)
Dimensions without coordinates: b
x        int64 0
y        int64 0
z        (b) int64 0
Finally, adds support for n-dimensional cumsum() and cumprod(), reducing
over all dimensions of an array. (This was necessary as part of the above fix.)
=> Bug fixes for Dataset.reduce() and n-dimensional cumsum/cumprod

doc/whats-new.rst, xarray/coding/cftimeindex.py, xarray/tests/test_cftimeindex.py
The issue is that both `is_monotonic_decreasing` and `is_monotonic_increasing` return `True` for a length-1 index; therefore an additional check is needed to make sure the length of the index is greater than 1 in `CFTimeIndex._maybe_cast_slice_bound`.  This is similar to how things are done in [`DatetimeIndex._maybe_cast_slice_bound`](https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/datetimes.py#L1666) in pandas.
=> Fix string slice indexing for a length-1 CFTimeIndex

doc/whats-new.rst, xarray/backends/h5netcdf_.py, xarray/backends/netCDF4_.py, xarray/tests/test_backends.py
Our test suite was inadvertently not checking this.
=> BUG: fix writing to groups with h5netcdf

doc/computation.rst
An example of weighted rolling mean in doc is actually weighted rolling *sum*.
It is a little bit misleading [SO](https://stackoverflow.com/questions/50520835/xarray-simple-weighted-rolling-mean-example-using-construct/50524093#50524093), so I propose to change 
`weighted rolling mean` -> `weighted rolling sum`
=> weighted rolling mean -> weighted rolling sum

doc/whats-new.rst, xarray/core/utils.py, xarray/tests/test_dataarray.py, xarray/tests/test_utils.py
=> Fix DataArray.stack() with non-unique coordinates on pandas 0.23

doc/faq.rst
Justs adds [xyzpy](http://xyzpy.readthedocs.io) to the list of projects utilizing ``xarray``.
=> docs: add xyzpy to projects

doc/whats-new.rst, setup.cfg, xarray/core/coordinates.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/utils.py, xarray/core/variable.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_utils.py
I don't think this is the most efficient way of doing this, though it does work. Any ideas for a more efficient implementation?
=> Datasets more robust to non-string keys

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
=> Rename takes kwargs

doc/whats-new.rst, xarray/core/dataarray.py, xarray/tests/test_computation.py, xarray/tests/test_groupby.py
=> Fix DataArray.groupby().reduce() mutating input array

doc/whats-new.rst, xarray/core/computation.py, xarray/tests/test_computation.py
Related with #2203, I think it is better if `xr.DataArray.dot()` is working even with older dask, at least in the simpler case (as this is a very primary operation).
The cost is a slight complication of the code.
Any comments are welcome.
=> Support dot with older dask

doc/whats-new.rst, xarray/backends/h5netcdf_.py, xarray/backends/netCDF4_.py, xarray/coding/strings.py, xarray/conventions.py, xarray/tests/test_backends.py, xarray/tests/test_conventions.py
@crusaderky please take a look. Testing here is not as thorough as in https://github.com/pydata/xarray/pull/2150 yet, but it does include a regression test.
=> Fix dtype=S1 encoding in to_netcdf()

doc/plotting.rst
This fixes it for me locally. The height was forced to be 12in, while width is 100%. 
I'm not sure why this was added in the first place.
=> Remove height=12in from facetgrid example plots.

doc/plotting.rst, doc/whats-new.rst, xarray/plot/facetgrid.py, xarray/plot/plot.py, xarray/plot/utils.py, xarray/tests/test_plot.py
Uses attrs long_name/standard_name, units if available.
This PR basically uses @rabernat's `label_from_attrs` in #2135. 
Examples:
I also changed the way histograms are labelled
**Old:**
**New**:
=> Plot labels use CF convention information if available.

doc/interpolation.rst
I noticed an example I added to doc in #2104 consumes more than 1 GB memory, and it results in the failing in readthedocs build.
This PR changes this to a much lighter example.
=> Reduce memory usage in doc.interpolation.rst

doc/api.rst, doc/indexing.rst, doc/interpolation.rst, doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/missing.py, xarray/tests/test_interp.py
This adds `interp_like`, that behaves like `reindex_like` but using interpolation.
=> implement interp_like

doc/io.rst
I tried setting this up on GCS as an experiment, and found there's no `mode` kwarg to `open_zarr`. I'm not sure whether there are broader issues but thought I'd put this in regardless
(also - if anyone has any experience in deploying xarray over https://github.com/dask/dask-kubernetes and GCS, I'd be interested in your experience. We're currently working with either a) BigQuery for big data or b) in-memory xarray for small data, and I was interested whether there's a way of retaining the xarray model for bigger data without too much overhead)
=> Small error in open_zarr docs

xarray/plot/plot.py, xarray/tests/test_plot.py
Fixed a syntax inconsistency, allowing to pass unnamed arguments to faceted line plots. 
Example code:
```python
np.random.seed(0)
da = xr.DataArray(np.random.randn(3, 3, 3, 3),
dims=['x', 'y', 'z',  'w'],
coords=[range(3),  [3.5, 4.9, 6.7], ['a','b','c'], ['foo', 'bar', 'foobar']],
name='arr_name')
da.plot.line('o--',row='y', col='w',hue='z')
```
=> BUG: unnamed args in faceted line plots

xarray/core/common.py
The example code snippet in the `resample` docstring did not produced the desired result, and the output from running the code did not match the provided output. This PR fixes both issues.
Given that there are no code changes I haven't updated `whats-new.rst`, but can if that would be appropriate.
=> Fix resample docstring seasonal average example

doc/dask.rst
Closes #2295 (remove if there is no corresponding issue, which should only be the case for minor changes)
=> DOC: replace broken link by a link to @shoyer's personal blog

xarray/backends/h5netcdf_.py, xarray/backends/netCDF4_.py, xarray/backends/pseudonetcdf_.py, xarray/backends/pydap_.py, xarray/backends/pynio_.py, xarray/backends/rasterio_.py, xarray/coding/variables.py, xarray/core/computation.py, xarray/core/indexing.py, xarray/tests/test_backends.py
No external API changes.
This simplifies the boilerplate for supporting explicit indexing in a backend
array class.
CC @fujiisoup @jhamman
=> Add indexing.explicit_indexing_adapter and refactor backends to use it.

doc/conf.py, doc/environment.yml, readthedocs.yml
See https://github.com/pydata/xarray/issues/2306
This makes the builds a little bit faster. But we are still very close to the 900 s limit.
I tried to pin more packages this morning but this didn't work out. I'll merge this first (the latest build worked with this config, https://readthedocs.org/projects/xray/builds/) and try again at a later stage.
=> Make RTD builds faster

.travis.yml, ci/requirements-py36-dask-dev.yml, xarray/tests/test_variable.py
=> Test against dask master and xfail current failure

doc/interpolation.rst, xarray/core/dataarray.py
- [NA] Closes #xxxx (remove if there is no corresponding issue, which should only be the case for minor changes)
- [NA] Tests added (for all bug fixes or enhancements)
- [NA] Tests passed (for all non-documentation changes)
- [NA] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API (remove if this change should not be visible to users, e.g., if it is an internal clean-up, or if this is part of a larger project that will be documented later)
I wanted to add an example as googling 'xarray interp' takes me to http://xarray.pydata.org/en/stable/generated/xarray.Dataset.interp.html.
However, there lots of great examples in http://xarray.pydata.org/en/stable/interpolation.html
Perhaps I should edit it to:
```
Examples
--------
See …
```
=> DOC: add interp example

doc/whats-new.rst, xarray/tests/test_coding_times.py
pytest-xdist expects that test gathering produces the same results and in the same order.  Because sets, prior to python 3.7, do not guarantee ordering, this can cause pytest -n (from pytest-xdist) to fail.
=> Use sorted fixtures to ensure that test gathering is consistent.

doc/whats-new.rst, xarray/core/computation.py, xarray/tests/test_computation.py
Now raises a ValueError when the size of input_core_dims is inconsistent with number of argument.
=> apply_ufunc now raises a ValueError when the size of input_core_dims is inconsistent with number of argument

doc/whats-new.rst, xarray/core/dask_array_ops.py
Dask renamed `dask.ghost` -> `dask.overlap` in dask/dask#3830.
This PR follows up this.
=> dask.ghost -> dask.overlap

xarray/tests/test_dataarray.py
I just mark some to_cdms2 tests xfail. See #2332 for the details.
It is a temporal workaround and we may need to keep #2332 open until it is solved.
=> Mark some tests related to cdat-lite as xfail

doc/faq.rst, doc/index.rst, doc/related-projects.rst
Make xarray-related projects more discoverable, as it has been suggested in xarray mailing-list.
=> DOC: move xarray related projects to top-level TOC section

doc/whats-new.rst, xarray/core/variable.py, xarray/tests/test_dataset.py
Now it raises an Error to assign new dimension with the name conflicting with an existing level name.
Therefore, it is not allowed
```python
b = xr.Dataset(coords={'dim0': ['a', 'b'], 'dim1': [0, 1]})
b = b.stack(dim_stacked=['dim0', 'dim1'])
b['c'] = (('dim0',), [10, 11, 12, 13])
b['c'] = (('dim_stacked',), [10, 11, 12, 13])
```
=> Raises a ValueError for a confliction between dimension names and level names

xarray/backends/rasterio_.py, xarray/tests/test_backends.py
This removes the redundant code that ended up with the `transform` attribute being set twice - and being set to a nine-element long tuple rather than the correct six-element long tuple. It also adds tests to ensure that all `transform` attributes are six-element-long tuples.
I haven't made any changes to the documentation, as I wasn't sure if it was needed. This could potentially affect users as the documentation and the code differed and people may have written other interface code (as, in my case, code to export a DataArray to a GeoTIFF using rasterio) which relies on the transform element having 9 elements rather than the 6 it is meant to have. Any thoughts?
=> Remove redundant code from open_rasterio and ensure all transform tuples are six elements long

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
Will add the others stuff from the checklist soon.
=> Add option to not roll coords

xarray/core/common.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/rolling.py, xarray/core/variable.py
Following to #2174
In some methods, consistency of the dictionary arguments and keyword arguments are checked twice in `Dataset` and `Variable`. 
Can we change the API of Variable so that it does not take kwargs-type argument for dimension names?
=> More support of non-string dimension names

doc/whats-new.rst
Seems I left off a trailing `>` in the `whats-new.rst`. Here is a minor fix for that.
=> fix typo in uri in the docs

doc/related-projects.rst
Think my package should go in the 'extend xarray capabilities' section rather than the 'geoscience' section.
=> DOC: move xskillscore to 'Extend xarray capabilities'

xarray/coding/times.py, xarray/core/formatting.py, xarray/core/missing.py, xarray/plot/plot.py, xarray/plot/utils.py, xarray/tests/test_backends.py, xarray/tests/test_coding_times.py, xarray/tests/test_dask.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_missing.py, xarray/tests/test_plot.py
=> Silence some warnings.

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
Not sure if this is a desirable change but I thought it could be easily discussed as a PR. Just for context I was looking at flattening spatial data for machine learning pipelines and then reshaping after the output had been acquired. 
I have a NxM array called `b` and am flattening it like:
```python
flat_input = b.stack(z=('y', 'x'))
```
Then I use that flat_input in my ML pipeline and get back an `np.array` (called `output`) which I want to unstack using all the metadata that went into stacking my original NxM array b.
```python
xr.full_like(flat_input, output).unstack(dim='z')
```
This PR just makes the `dim` argument optional in unstack so that we can use 
```python
xr.full_like(flat_input, output).unstack()
```
As a follow on PR I was thinking of making a function called …
=> Make `dim` optional on unstack

doc/whats-new.rst, xarray/plot/plot.py, xarray/tests/test_plot.py
=> plot.imshow now obeys 'origin' kwarg.

README.rst, doc/index.rst
Xarray is now a fiscally sponsored project of NumFOCUS. This PR adds a few blurbs of text highlighting that on the main readme and index page of the docs. 
TODO:
- Update flipcause to xarray specific donation page
=> add some blurbs about numfocus sponsorship to docs

xarray/plot/plot.py, xarray/tests/test_plot.py
https://github.com/pydata/xarray/pull/2294 introduced the new ``xincrease`` and ``yincrease`` kwargs and a behavior documented as:
```
xincrease : None, True, or False, optional
Should the values on the x axes be increasing from left to right?
if None, use the default for the matplotlib function.
```
The default was ``None``, I suggest to set it to ``True``: it was the default before https://github.com/pydata/xarray/pull/2294 and I think it is what most users expect.
=> Plotting: restore xyincrease kwarg default to True

xarray/plot/facetgrid.py, xarray/tests/test_plot.py
Makes sure that `FacetGrid._finalize()` is only called once. This function sets axes labels and calls `tight_layout`. The user can do all that easily if they need to change the defaults.
See #2024 for example.
=> make facetgrid execute _finalize() only once

doc/whats-new.rst, xarray/core/nanops.py, xarray/tests/test_duck_array_ops.py
It looks that I wrongly remove `ddof` option for `nanstd` in #2236.
This PR fixes this.
=> restore ddof support in std

doc/interpolation.rst, doc/time-series.rst, doc/whats-new.rst, xarray/coding/cftimeindex.py, xarray/core/dataset.py, xarray/core/missing.py, xarray/core/utils.py, xarray/tests/test_cftimeindex.py, xarray/tests/test_dataset.py, xarray/tests/test_interp.py, xarray/tests/test_utils.py
As discussed in https://github.com/pydata/xarray/pull/2398#pullrequestreview-156804917, this enables the use of `differentiate` and `interp` on DataArrays/Datasets with `cftime.datetime` coordinates.
=> Enable use of cftime.datetime coordinates with differentiate and interp

xarray/coding/cftimeindex.py
With the latest version of pandas, checking the `date_type` of a CFTimeIndex produces a FutureWarning:
```
In [1]: import xarray as xr
In [2]: times = xr.cftime_range('2000', periods=5)
In [3]: times.date_type
/Users/spencerclark/xarray-dev/xarray/xarray/coding/cftimeindex.py:161: FutureWarning: CFTimeIndex.data is deprecated and will be removed in a future version
if self.data:
Out[3]: cftime._cftime.DatetimeProlepticGregorian
```
I think it was a typo to begin with to use `self.data` in `cftimeindex.get_date_type` (my mistake).  Here I switch to using `self._data`, which is used elsewhere when internally referencing values of the index.
=> Fix FutureWarning resulting from CFTimeIndex.date_type

doc/api-hidden.rst, doc/whats-new.rst, xarray/coding/cftimeindex.py, xarray/tests/test_cftimeindex.py
=> Add CFTimeIndex.shift

xarray/core/dask_array_compat.py
https://github.com/pydata/xarray/blob/f9c4169150286fa1aac020ab965380ed21fe1148/xarray/core/dask_array_compat.py#L47
But AxisError was [added](https://github.com/numpy/numpy/commit/eb642f1b6533fcd92e366377f5859e4ea56d5eed) in 1.13.
The fix is copied from Dask code: https://github.com/dask/dask/blob/0fb0f876bb974cfca1458903540ac389e6f89019/dask/array/utils.py#L15
=> np.AxisError was added in numpy 1.13

doc/whats-new.rst, xarray/plot/plot.py, xarray/tests/test_plot.py
By default, matplotlib draws dashed negative contours when a single color is passed to `Axes.contour`. We lost this feature by manually specifying cmap everytime.
Currently on master:
```
delta = 0.025
x = np.arange(-3.0, 3.0, delta)
y = np.arange(-2.0, 2.0, delta)
X, Y = np.meshgrid(x, y)
Z1 = np.exp(-X**2 - Y**2)
Z2 = np.exp(-(X - 1)**2 - (Y - 1)**2)
Z = xr.DataArray((Z1 - Z2) * 2, dims=['y', 'x'], coords={'x': x, 'y': y})
f, ax = plt.subplots(1, 2)
hdl = ax[0].contour(Z, colors='k')
hdlx = Z.plot.contour(ax=ax[1], colors='k')
```
=> plot.contour: Don't make cmap if colors is a single color.

xarray/coding/cftimeindex.py, xarray/tests/test_cftimeindex.py
Per @shoyer's comment, https://github.com/pydata/xarray/pull/2431#discussion_r221976257, this cleans up `_parse_array_of_cftime_strings`, making it robust to multi-dimensional arrays in the process.
=> Clean up _parse_array_of_cftime_strings

xarray/tests/__init__.py, xarray/tests/test_accessors.py, xarray/tests/test_backends.py, xarray/tests/test_combine.py, xarray/tests/test_conventions.py, xarray/tests/test_dask.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_duck_array_ops.py, xarray/tests/test_extensions.py, xarray/tests/test_formatting.py, xarray/tests/test_indexing.py, xarray/tests/test_merge.py, xarray/tests/test_plot.py, xarray/tests/test_tutorial.py, xarray/tests/test_utils.py, xarray/tests/test_variable.py
This replaces (by-and-large) any remaining unittest implementations with pytest implementations. This allows us to use fixtures on any test; the existing implementation does not let us use them on `TestCase` instances. It also directs future contributors away from using the legacy methods.
Would be great to merge this fairly soon, as there's some chance of merge conflicts (which git may not catch - e.g. someone writing `self.assertEqual`). I'll try and chase down any test breaks as soon as possible.
=> Replace the last of unittest with pytest

doc/whats-new.rst, xarray/backends/rasterio_.py, xarray/tests/test_backends.py
=> Fix indexing error for data loaded with open_rasterio

xarray/backends/pseudonetcdf_.py, xarray/tests/test_backends.py, xarray/tests/test_conventions.py
We accidentally stopped running many backend tests when we merged #2467,
because they no longer inherited from untitest.TestCase and didn't have a
name starting with "Test".
This PR renames the tests so they actually run. I also fixed a bug with the
pseudonetcdf backend that appears to have been introduced by a bad merge in
#2261. It wasn't caught because the tests weren't actually running.
cc @max-sixty
=> Fix backend test classes so they actually run

doc/whats-new.rst, xarray/coding/cftimeindex.py, xarray/tests/test_cftimeindex.py
=> Improve arithmetic operations involving CFTimeIndexes and TimedeltaIndexes

xarray/core/common.py, xarray/core/dataset.py, xarray/core/groupby.py
Minor documentation additions.
=> Add swap_coords to relevant 'See also' sections

xarray/core/dataset.py
This makes the docstring of Dataset.copy match the actual behavior. 
However, I noticed that DataArray.copy has the opposite behavior for the deep keyword. Is this intentional, or are they supposed to behave the same way?
=> Dataset.copy docstring matches behavior

ci/requirements-py36.yml, xarray/tests/test_backends.py
Fix `TestCfGrib` broken by a user-visible backward-incompatible change in *cfgrib>=0.9.2*.
No other user visible coordinate name change is expected so the test can remain like it is.
Sorry for the inconvenience!
- ~~Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API~~
=> Fix tests to new coordinate names in cfgrib>=0.9.2

doc/whats-new.rst, xarray/core/dataset.py, xarray/tests/test_dataset.py
=> Remove .T as shortcut for transpose()

doc/api-hidden.rst
Just a minor followup to #2509 to remove `Dataset.T` from the documentation.
=> Remove Dataset.T from api-hidden.rst

doc/whats-new.rst, xarray/core/variable.py, xarray/tests/test_variable.py
=> Make sure datetime object arrays are converted to datetime64

doc/whats-new.rst, xarray/coding/times.py, xarray/tests/test_coding_times.py
=> Fix bug in encode_cf_datetime

doc/whats-new.rst, xarray/core/dataarray.py, xarray/tests/test_dataarray.py
=> Finish deprecation cycle for DataArray.__contains__ checking array values

xarray/tests/test_coding_times.py
`cftime` version 1.0.2.1 (currently only installed on Windows, because it hasn't appeared on conda-forge yet) includes some changes that improve the precision of datetime arithmetic, which causes some results of `infer_datetime_units` to change.  These changes aren't really a concern, because it doesn't impact our ability to round-trip dates; it just changes the units dates are encoded with in some cases.  For that reason I've just deleted the tests where the answers change across versions.
=> Remove tests where results change in cftime 1.0.2.1

xarray/core/variable.py, xarray/tests/test_dataset.py, xarray/tests/test_variable.py
=> Raise more informative error when converting tuples to Variable.

doc/api-hidden.rst, doc/time-series.rst, doc/whats-new.rst, xarray/coding/cftimeindex.py, xarray/coding/times.py, xarray/core/common.py, xarray/core/options.py, xarray/core/utils.py, xarray/plot/plot.py, xarray/tests/test_backends.py, xarray/tests/test_cftimeindex.py, xarray/tests/test_coding_times.py, xarray/tests/test_dataarray.py, xarray/tests/test_options.py, xarray/tests/test_utils.py
As discussed in #2437 and #2505, this sets the option `enable_cftimeindex` to `True` by default.
=> Switch enable_cftimeindex to True by default

doc/whats-new.rst, xarray/backends/zarr.py, xarray/tests/test_backends.py
I don't fully understand the ins-and-outs of Zarr, but it seems that if it can be serialised with a smaller end-chunk to begin with, then saving a Dataset constructed from Zarr should not have an issue with that either.
=> Zarr chunking (GH2300)

xarray/backends/cfgrib_.py
This is a trivial fix to remove the use of the `mode` keyword in the `cfgrib.open_file` call. The keyword has always be ignored and will be deprecated with the next version of *cfgrib*.
Better to have this fix in before the v0.11 release.
=> Remove use of deprecated and unused keyword in cfgrib.open_file.

doc/indexing.rst, doc/interpolation.rst, doc/plotting.rst, doc/whats-new.rst, xarray/tests/test_tutorial.py, xarray/tutorial.py
In working on an xarray/dask tutorial, I've come to realize we eagerly load the tutorial datasets in `xarray.tutorial.load_dataset`. I'm going to just say that I don't think we should do that but I could be missing some rational. I didn't open an issue so please feel free to share thoughts here.
One option would be to create a new function (`xr.tutorial.open_dataset`) that does what I'm suggesting and then slowly deprecate `tutorial.load_dataset`. Thoughts?
xref: https://github.com/dask/dask-examples/pull/51
=> Stop loading tutorial data by default

ci/requirements-py37.yml
Just adding a full environment for python 3.7.
=> Expand test environment for Python 3.7

xarray/backends/cfgrib_.py
This is a minor cleanup of the `backend_kwargs` hack that was needed to support CachingFileManager and that I forgot to remove after I stopped using it.
I didn't include this bit in #2540 because I didn't want to pollute the important fix with cleanup noise.
=> Drop the hack needed by CachingFileManager in cfgrib_.py

doc/whats-new.rst, setup.py
=> DOC: reorganize whatsnew for xarray 0.11 release

xarray/util/print_versions.py
Example of what this looks like:
```
In [3]: xarray.show_versions()
INSTALLED VERSIONS
------------------
commit: ef0838812cb3715d86d9cf9630606c824f3d8efb
python: 3.6.5.final.0
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.3
libnetcdf: 4.6.1
xarray: 0.11.0+2.gef083881.dirty
pandas: 0.23.3
numpy: 1.14.2
scipy: 1.1.0
netCDF4: 1.4.2
pydap: installed
h5netcdf: 0.6.2
h5py: 2.8.0
Nio: None
zarr: 2.2.0
cftime: 1.0.1
PseudonetCDF: None
rasterio: None
cfgrib: installed
iris: None
bottleneck: 1.2.1
cyordereddict: None
dask: 0.19.0+120.g86da308e
distributed: 1.22.0
matplotlib: 2.2.2
cartopy: 0.16.0
seaborn: 0.8.1
setuptools: 39.2.0
pip: 10.0.1
conda: None
pytest: 3.6.0
IPython: 6.2.1 …
```
=> Add libnetcdf, libhdf5, pydap and cfgrib to xarray.show_versions()

xarray/backends/api.py
Add missing comma and article in error message when attribute values have the wrong type.
I tihnk this change is sufficiently minor that no documentation or whatsnew changes should be necessary.
=> add missing comma and article in error message

setup.py
You don't need to have pytest-runner before-hand.
=> python setup.py test now works by default

ci/requirements-py36-zarr-dev.yml, doc/io.rst, doc/whats-new.rst, xarray/backends/api.py, xarray/backends/zarr.py, xarray/core/dataset.py, xarray/tests/test_backends.py, xarray/tests/test_distributed.py
This PR adds support for reading and writing of [consolidated metadata](https://zarr.readthedocs.io/en/latest/tutorial.html#consolidating-metadata) in zarr stores.
=> Zarr consolidated

.github/PULL_REQUEST_TEMPLATE.md
This version should be a little less noisy, since instructions only for authors are put in commented out HTML.
=> Minor update to PR template

doc/environment.yml
As mentioned in https://github.com/pydata/xarray/issues/2597#issuecomment-446151329, the `dayofyr` and `dayofwk` attributes of `cftime.datetime` objects do not always work in versions of cftime prior to 1.0.2.  This issue comes up in the [latest doc build](http://xarray.pydata.org/en/latest/time-series.html#non-standard-calendars-and-dates-outside-the-timestamp-valid-range):
This updates the documentation environment to use the most recent version (1.0.3.4), which should fix things.
=> Update cftime version in doc environment

.travis.yml, doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/variable.py, xarray/tests/test_dask.py
Fixes https://github.com/dask/dask/issues/4291
=> Support HighLevelGraphs

doc/whats-new.rst, xarray/coding/variables.py, xarray/tests/test_backends.py
=> Fix parsing '_Unsigned' attribute

doc/dask.rst, doc/examples/multidimensional-coords.rst, doc/examples/weather-data.rst, doc/groupby.rst, doc/internals.rst, doc/pandas.rst, doc/plotting.rst, doc/reshaping.rst, doc/time-series.rst, doc/whats-new.rst, xarray/backends/api.py, xarray/core/combine.py, xarray/core/dataarray.py, xarray/core/dataset.py
Quickfixes to make things work locally.
=> doc fixes.

xarray/coding/cftime_offsets.py
This was caught by @jwenfai in #2593.  I hope no one was inadvertently trying to use this argument before.
Should this need a what's new entry?
=> Remove tz argument in cftime_range

appveyor.yml
There seems to be some sort of dependency issue on Appveyor, but it's not
worth tracking down given how we'll be dropping Python 2.7 in the new year
anyways.
=> Remove failing Appveyor Python 2.7 32-bit build

xarray/tests/test_ufuncs.py, xarray/ufuncs.py
Closes https://github.com/pydata/xarray/issues/2609
This removes PendingDeprecationWarnings for `xarray.ufuncs.{angle,iscomplex}` which appear to not be proper ufuncs and cannot be just used from numpy for now (as discussed in the parent issue).
Also adds more generic tests that numpy ufuncs do preserve the DataArray dtype.
=> FIX Don't raise a deprecation warning for xarray.ufuncs.{angle,iscomplex}

doc/whats-new.rst, xarray/core/indexing.py, xarray/tests/test_variable.py
=> Get 0d slices of ndarrays directly from indexing

doc/whats-new.rst, xarray/core/dataset.py, xarray/core/indexing.py, xarray/core/pdcompat.py, xarray/tests/test_dataarray.py
Fix using ` MultiIndex.remove_unused_levels()`
=> Fix multiindex selection

doc/whats-new.rst, xarray/coding/times.py, xarray/tests/test_coding_times.py
This is related to a bug fixed in https://github.com/pandas-dev/pandas/pull/18020#issuecomment-340477318 (this should return a `TimedeltaIndex`):
```
In [2]: times = pd.date_range('2000', periods=3)
In [3]: times - np.datetime64('2000-01-01')
Out[3]: DatetimeIndex(['1970-01-01', '1970-01-02', '1970-01-03'], dtype='datetime64[ns]', freq='D')
```
Subtracting a `Timestamp` object seems to work in all versions:
```
In [4]: times - pd.Timestamp('2000-01-01')
Out[4]: TimedeltaIndex(['0 days', '1 days', '2 days'], dtype='timedelta64[ns]', freq=None)
```
=> Fix failure in time encoding for pandas < 0.21.1

.travis.yml, xarray/core/pdcompat.py, xarray/tests/test_dataarray.py
=> Add flake check to travis

setup.cfg
These were adding a lot of noise to the output of our test suite -- something like 500 lines of useless warnings!
=> TST: silence warnings from bottleneck

setup.py
=> BUG: pytest-runner not required for setup.py

doc/whats-new.rst, xarray/core/resample.py, xarray/tests/test_dataarray.py
My main goal with this was to help out with #2593 (xarray's built-in interpolation method is compatible with cftime coordinates, so this refactor would simplify things there).  While doing this I realized that I could also add the simple bug-fix for #2197.  
cc: @jwenfai
=>  Use built-in interp for interpolation with resample

.pep8speaks.yml, .travis.yml, ci/requirements-py37.yml, setup.cfg, xarray/core/common.py, xarray/core/dataset.py, xarray/core/pycompat.py, xarray/tests/test_backends.py, xarray/tests/test_indexing.py
flake8 includes a few more useful checks, but it's annoying to only see it's
output in Travis-CI results.
This keeps Travis-CI and pep8speaks in sync.
=> Use pycodestyle for lint checks.

xarray/backends/api.py, xarray/core/combine.py, xarray/tests/test_backends.py
=> Change an `==` to an `is`. Fix tests so that this won't happen again.

doc/whats-new.rst, xarray/coding/times.py, xarray/tests/test_coding_times.py
I *think* this should be an appropriate fix for #2649, but I'd appreciate input from those who are more experienced dealing with timezones in NumPy/pandas.
My understanding is that NumPy dates are stored as UTC and do not carry any timezone information. Therefore converting the `ref_date` with `tz_convert(None)` here, which converts it to UTC and removes the timezone information, should be appropriate for encoding.
=> Convert ref_date to UTC in encode_cf_datetime

README.rst, doc/index.rst, setup.py
I have often complained that xarray's top-level package description assumes that the user knows all about pandas. I think this alienates many new users.
This is a first draft at revising that top-level description. Feedback from the community very needed here.
=> WIP: revise top-level package description

xarray/tests/test_coding_times.py
Currently, while we indeed do always decode to UTC, I'm not sure how well we test that.  In addition this tests both the `np.datetime64` and `cftime.datetime` pathways.
=> Improve test for #2649

README.rst, doc/faq.rst, doc/index.rst, doc/related-projects.rst, doc/why-xarray.rst, setup.py
This documentation revamp builds upon @rabernat's rewrite in #2430.
The main change is that the three paragraph description felt too long to me, so I moved the background paragraph on multi-dimensional arrays into the next section, on "Why xarray". I also ended up rewriting most of that page, and made a few adjustments to the FAQ and related projects pages.
=> DOC: refresh "Why xarray" and shorten top-level description

xarray/tests/test_cftimeindex.py
It was a nice idea to support CFTimeIndex in a pandas.MultiIndex, but pandas
seems to have inadvertently broken this, see
https://github.com/pandas-dev/pandas/issues/24263
(This should fix our failing CI tests with pandas 0.24 rc)
=> xfail cftimeindex multiindex test

xarray/core/combine.py, xarray/tests/test_combine.py
Explained in #2662. Also renamed some variables slightly for clarity.
Not sure how to add a test without refactoring the groupby into a separate function, as in it's current form the problem only manifests as a (huge) slowdown.
=> Hotfix for #2662

doc/whats-new.rst, xarray/core/formatting.py, xarray/testing.py, xarray/tests/test_formatting.py
- ~~Closes #xxxx~~
~~In addition to `Dataset` repr, the error message also shows the output of `Dataset.info()` for both datasets.~~
~~This may not be the most elegant solution, but it is helpful when datasets only differ by their attributes attached to coordinates or data variables (not shown in repr). I'm open to any suggestion.~~
The report shows the differences for dimensions, data values (``Variable`` and ``DataArray``), coordinates, data variables and attributes (the latter only for ``testing.assert_identical``).
There is currently not much tests for `xarray.testing` functions, but I'm willing to add more if needed.
Not sure if it's worth a what's new entry (EDIT: added one).
=> Detailed report for testing.assert_equal and testing.assert_identical

.travis.yml, ci/requirements-py36.yml
As described in #2683, our test suite is failing on Travis with an unfortunate segfault. For now, I've just taken `rasterio` (and therefore GDAL) out of the offending environment. I'll use this PR to test a few other options.
cc @max-sixty
=> try no rasterio in py36 env

.github/stale.yml
Initially set at two years, and max rate of one / hour - we can make more aggressive when we know it's working
=> Config for closing stale issues

.github/stale.yml
Currently the message is interpreted as a single line
Please post any other feedback
=> add line break to stale message

doc/whats-new.rst
I'll port these to master separately, given that this commit probably won't apply cleanly.
=> Write docs for 0.11.3 release

xarray/core/coordinates.py, xarray/tests/test_cftimeindex.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
This was introduced by the recent indexes refactor, but never made it into a
release.
=> BUG: ensure indexes are reset when coords are modified

doc/conf.py
This should make it easier to debug the doc build environment.
=> Print full environment fron conf.py

doc/whats-new.rst
I just pushed the 0.11.3 bug-fix release to pypi.
=> DOC: refresh whats-new for 0.11.3 / 0.12.0

doc/whats-new.rst, xarray/core/coordinates.py, xarray/core/dataset.py, xarray/tests/test_coding_times.py, xarray/tests/test_dataarray.py, xarray/tests/test_utils.py
=> Fix test failures / warnings for pandas 0.24

doc/whats-new.rst, xarray/plot/plot.py, xarray/tests/test_plot.py
=> Bugfix for line plot axes

xarray/tests/test_ufuncs.py
The only other warning is:
```
xarray/tests/test_dataset.py::TestDataset::test_convert_dataframe_with_many_types_and_multiindex
/Users/maximilian/workspace/xarray/xarray/core/dataset.py:3146: FutureWarning: Converting timezone-aware DatetimeArray to timezone-naive ndarray with 'datetime64[ns]' dtype. In the future, this will return an ndarray with 'object' dtype where each element is a 'pandas.Timestamp' with the correct 'tz'.
To accept the future behavior, pass 'dtype=object'.
To keep the old behavior, pass 'dtype="datetime64[ns]"'.
data = np.asarray(series).reshape(shape)
/usr/local/lib/python3.7/site-packages/pandas/core/apply.py:286: FutureWarning: Converting timezone-aware DatetimeArray to timezone-naive ndarray with 'datetime64[ns]' dtype. In the future, this will return an ndarray …
```
=> silence a couple of warnings in tests

doc/whats-new.rst, xarray/coding/cftimeindex.py, xarray/tests/test_cftimeindex.py
Thanks for the suggestion, @shoyer.
cc: @jwenfai
=> dropna() for a Series indexed by a CFTimeIndex

xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
=> add tests for handling of empty pandas objects in constructors

xarray/tests/test_backends.py
Fixes https://github.com/pydata/xarray/issues/2050
I'm not quite sure what was going on, but it passes now.
=> Reenable cross engine read write netCDF test

xarray/tests/test_backends.py
This is passing in my local test environment. We'll see on CI...
=> remove xfail from test_cross_engine_read_write_netcdf4

doc/whats-new.rst, xarray/backends/rasterio_.py
See https://github.com/mapbox/rasterio/blob/master/CHANGES.txt#L7 for the change in rasterio 1.0.14 and my conda-forge issue where I discovered this: https://github.com/conda-forge/gdal-feedstock/issues/262
This was put in a bugfix (micro version number) release of rasterio which made it harder to discover. @sgillies @snowman2 I saw that you brought this up and how it affected xarray (https://rasterio.groups.io/g/dev/message/68). If this pull request is a duplicate of a fix one of you made let me know.
To xarray devs, if I need to make any other changes (whats-new?) also let me know.
=> Fix CRS being WKT instead of PROJ.4

doc/installing.rst, doc/whats-new.rst, xarray/util/print_versions.py
=> remove references to cyordereddict

ci/requirements-py36.yml, xarray/core/alignment.py, xarray/core/computation.py, xarray/core/dataset.py, xarray/core/merge.py
Apparently I wasn't paying attention in my last PR :)
=> Fix mypy errors

doc/whats-new.rst, xarray/core/common.py, xarray/core/computation.py, xarray/tests/test_dataarray.py
I took a simple-minded strategy to fix: just mask and then rename the result to `self.name`. This is a slight overkill since the renaming will be done on every masking, not just on the edge cases when it's needed, but this is really a very small computational cost and it's much easier and bulletproof.
=> Fix name loss when masking

doc/whats-new.rst, xarray/coding/cftime_offsets.py, xarray/tests/test_cftime_offsets.py, xarray/tests/test_interp.py
=> Use DatetimeGregorian when calendar='standard' in cftime_range instead of DatetimeProlepticGregorian

doc/api.rst, doc/data-structures.rst, doc/indexing.rst, doc/whats-new.rst, xarray/core/dataset.py, xarray/tests/test_dataset.py
=> Add `Dataset.drop_dims`

doc/whats-new.rst, xarray/core/combine.py, xarray/tests/test_combine.py
=> Improve name concat

xarray/convert.py, xarray/core/utils.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
It got deprecated in numpy 1.16 and throws a ton of warnings due to that.
All the function does is returning .item() anyway, which is why it got deprecated.
I checked that it worked that way at least all the way down to numpy 1.12, which is the minimum required version according to setup.py.
=> Don't use deprecated np.asscalar()

doc/whats-new.rst, xarray/core/common.py, xarray/core/duck_array_ops.py, xarray/tests/test_dataset.py, xarray/tests/test_duck_array_ops.py
For now I've held off on making these changes dask-compatible (I could do it, but I'm not sure it is worth the extra complexity).
=> Add support for cftime.datetime coordinates with coarsen

xarray/tests/test_backends.py
These aren't valid for netCDF files.
Fixes #2803
=> Drop failing tests writing multi-dimensional arrays as attributes

xarray/backends/api.py, xarray/core/groupby.py, xarray/core/utils.py, xarray/tests/test_dataarray.py, xarray/tutorial.py
0.12 will already have a big change in dropping Python 2.7 support. I'd rather
wait a bit longer to finalize these deprecations to minimize the impact on
users.
xref https://github.com/pydata/xarray/issues/2776
=> Push back finalizing deprecations for 0.12

xarray/core/variable.py
`is` relies on interning, which is almost always OK for small strings, but reliant on language implementations
(unless there's something I'm missing about `.kind`?)
=> Small fix: use == to compare strings

xarray/backends/lru_cache.py
Looks like this occurrence was missing in #2574.
=> Remove py37 collections.abc deprecation warning from lru_cache module.

xarray/backends/api.py
The formatting of the `engine` parameter is wonky in the docs of [`open_dataset()`](https://xarray.pydata.org/en/stable/generated/xarray.open_dataset.html), [`open_mfdataset()`](https://xarray.pydata.org/en/stable/generated/xarray.open_mfdataset.html), [`open_dataarray()`](https://xarray.pydata.org/en/stable/generated/xarray.open_dataarray.html).
To maintain consistent format with the other parameters once the docs are build, text up through the word `optional` should be on the same line as the parameter name. Currently it's pushed down into the parameter description.
=> Fix formatting of engine parameter in docstrings

doc/whats-new.rst, xarray/core/dataset.py, xarray/tests/test_dataset.py
=> Fixing deepcopy for Dataset.attrs

doc/whats-new.rst, xarray/core/alignment.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/indexes.py, xarray/testing.py, xarray/tests/__init__.py, xarray/tests/test_combine.py, xarray/tests/test_dataset.py, xarray/tests/test_interp.py
I've added internal consistency checks to the uses of ``assert_equal`` in our
test suite, so this shouldn't happen again.
=> Various fixes for explicit Dataset.indexes

.travis.yml
This removes the `--verbose` flag from py.test in .travis.yml.
=> decreased pytest verbosity

xarray/core/common.py, xarray/core/dataarray.py, xarray/core/pycompat.py, xarray/core/utils.py, xarray/core/variable.py, xarray/tests/test_utils.py
=> WIP: type annotations

doc/whats-new.rst, xarray/backends/rasterio_.py, xarray/tests/test_backends.py
=> BUG: Fix #2864 by adding the missing vrt parameters

doc/whats-new.rst, xarray/core/dataset.py, xarray/tests/test_dataarray.py
Adds indexing over empty lists, e.g. `da[[]]`.
=> Indexing with an empty array

doc/whats-new.rst, xarray/core/duck_array_ops.py, xarray/tests/test_duck_array_ops.py
BUG: Fix #2770 by changing ~ to np.logical_not()
TST: Add test for scalar datetime64 value
DOC: Add to whats-new.rst
=> Return correct count for scalar datetime64 arrays

doc/contributing.rst
Added clearer instructions on how to build xarray documentation for contribution guide
=> Bugfix for docs build instructions

doc/data-structures.rst
Added example of `xarray.Dataset.get` method and alternative `ds[var_list]` syntax.
=> Added docs example for `xarray.Dataset.get()`

xarray/core/dataarray.py, xarray/core/dataset.py
See also pull-request #2860 - the same typo was at many places. Sorry, I have missed the other places when sending the first PR.
=> Fix minor typos in docstrings

xarray/core/dataset.py
This might help to avoid confusion. data_vars is always a mapping, not a
mapping, a variable or a tuple.
Passing just a tuple, does not work of course. But for xarray newbies, this might be less obvious and the error message is also not easy to interpret:
```
>>> xr.Dataset(('dim1', np.ones(5)))
...
TypeError: unhashable type: 'numpy.ndarray'
```
The correct version of the example above should be:
```
>>> xr.Dataset({'myvar': ('dim1', np.ones(5))})                                                                            
Dimensions:  (dim1: 5)
Dimensions without coordinates: dim1
myvar    (dim1) float64 1.0 1.0 1.0 1.0 1.0
```
=> Minor improvement of docstring for Dataset

.travis.yml, README.rst, doc/whats-new.rst, xarray/backends/zarr.py, xarray/coding/cftime_offsets.py, xarray/core/alignment.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/indexes.py, xarray/testing.py, xarray/tests/__init__.py, xarray/tests/test_backends.py, xarray/tests/test_combine.py, xarray/tests/test_dataset.py, xarray/tests/test_interp.py
This adds a `chunks` parameter that is analogous to Dataset.chunk. `auto_chunk` is kept for backwards compatibility and is equivalent to `chunks='auto'`. It seems reasonable that anyone manually specifying chunks may want to rewrite the dataset in those chunks, and the error that arises when the encoded Zarr chunks mismatch the variable Dask chunks may quickly get annoying. `overwrite_encoded_chunks=True` sets the encoded chunks to None so there is no clash.
=> Manually specify chunks in open_zarr

doc/examples.rst, doc/index.rst, doc/quick-overview.rst
I thought it'd be a good idea to make the "quick overview" example more prominent.
This PR moves that section one level up; adds some more text; talks about plotting and adding metadata.
=> docs: Move quick overview one level up

xarray/core/formatting.py, xarray/tests/test_formatting.py
Updates formatting to use .format() instead of % operator. Changed all instances of % to .format() and added test for using tuple as key, which errored using % operator.
=> Partial fix for #2841 to improve formatting.

doc/io.rst, doc/whats-new.rst, xarray/coding/strings.py, xarray/tests/test_coding_strings.py
=> Handle the character array dim name 

doc/gallery/plot_rasterio.py, doc/gallery/plot_rasterio_rgb.py
Simplify by using that rasterio can read directly from http. 
This also removes imports of requests and os.
=> DOC: avoid downloading .tif file

xarray/core/groupby.py
Existing output didn't format correctly
=> List formatting in docs

doc/whats-new.rst, xarray/core/alignment.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/merge.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_merge.py
This PR adds an optional `fill_value` parameter for the following functions/methods:
```
xarray.core.alignment.align()
xarray.core.alignment.deep_align()
xarray.core.dataset.reindex()
xarray.core.dataset.reindex_like()
xarray.core.dataset.merge()
xarray.core.dataarray.DataArray.reindex()
xarray.core.dataarray.DataArray.reindex_like()
xarray.core.merge.merge_coords()
xarray.core.merge.merge_core()
xarray.core.merge.merge()
xarray.core.merge.dataset_merge_method()
```
The value given to `fill_value` is used to fill missing values in the new object after the operation.  By default `fill_value` is NaN.
=> [WIP] Custom fill value for reindex, align, and merge operations

doc/whats-new.rst, xarray/core/variable.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
This pull request fixes a bug that prevented making a complete deep copy of a `DataArray` or `Dataset`, because the `coords` weren't being deep copied. It took a small fix in the `IndexVariable.copy method`. This method now allows both deep and shallow copies of `coords` to be made.
This pull request corresponds to this issue https://github.com/pydata/xarray/issues/1463.
=> BUGFIX: deep-copy wasn't copying coords, bug fixed within IndexVariable

xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
Mark test for copying coords of dataarray and dataset with `xfail`. It looks like the test fails for the shallow copy, and apparently only on Windows for some reason. In Windows coords seem to be immutable unless it's one dataarray deep copied from another (which is why only the deep=False test fails). So I decided to just mark the tests as xfail for now (but I'd be happy to create an issue and look into it more in the future).
=> Mark test for copying coords of dataarray and dataset with xfail

doc/related-projects.rst
This PR adds the [xclim](https://github.com/Ouranosinc/xclim) project to the list of related projects. Xclim is a reimplementation of ICCLIM indicators (and others) used in climate science research and leverages xarray, dask and pint to produce CF-Compliant climate indices in NetCDF4 format.
For more information, see: https://xclim.readthedocs.io/en/latest/
Cheers,
=> DOC: Added xclim to related projects

xarray/core/dataset.py
fix Docstring of xr.Dataset.info() to avoid failures when updating to numpydoc>=0.9
- [ X ] Closes #2959
=> fix Docstring of xr.Dataset.info() to avoid failures when updating to numpydoc>=0.9

xarray/core/rolling.py
The example was using the wrong name for the function (to_datarray), and used the wrong dimension for the window.
Cc: @fujiisoup, who added this in #1837
=> Fix rolling.constuct() example

conftest.py, doc/whats-new.rst, xarray/tests/__init__.py
I need to confirm whether this works with an installed version of xarray, because of https://github.com/pytest-dev/pytest/issues/1596. 
If pytest doesn't pick up this config, it will run all tests, because the default is to not skip.
I know I've generally been the point person for pytest - let me know if anyone has an immediate solution for this though
=> Remove deprecated pytest.config usages

xarray/core/combine.py, xarray/tests/test_combine.py
This PR adds the optional `fill_value` parameter to `concat()` and `auto_combine()` in `xarray.core.combine`, plus the associated underlying functions in the module.  This builds on the previous PR #2920 in addressing issue #2876, and gives users the option to avoid type-changing to `float` for arrays with missing values when using these functions as discussed in issue #2870.
=> Add fill_value for concat and auto_combine

ci/requirements-py36.yml, ci/requirements-py37.yml
This is a minor cleanup of the conda environment creation files:
* no direct reference to *ecCodes*
* conda-only dependency resolution
=> Simplify conda envs: cfgrib is now part of conda-forge

doc/api-hidden.rst, doc/time-series.rst, doc/weather-climate.rst, doc/whats-new.rst, xarray/coding/cftimeindex.py, xarray/core/accessors.py, xarray/tests/test_accessors.py, xarray/tests/test_cftimeindex.py
Building on #2144, I added dask support and returning the appropriate object type.  
The two initial commits show alternate approach to handling cftime values.  Either adding strftime to `cftimeindex` and accessing that way (commit 
5de4db1)  or just rolling the loop within the datetime accessor and not touching `cftimeindex` at all (
51239c9). can revert commit  5de4db1 if its preferred to not touch `cftimeindex` for any reason.  
Can clean up docstrings and minor formatting after some input on the implementation details.  
Is there a vectorized or better method for the cftime values? List comprehension was the best I could come up with, borrowing from similar logic elsewhere in the code.
=> Add strftime() to datetime accessor with cftimeindex and dask support

doc/computation.rst, xarray/core/rolling.py
* ~~When reducing over a rolling window, `DataArrayRolling.reduce()`
only returns values where the complete rolling window is fully
conatined within the base array; the remaining locations where
the window overlaps the array border are filled with `NaN`~~
* ~~However, in some situations, it is desirable to obtain values from the
reducer function for all locations.  This commit adds a keyword
argument, `include_border`, to `DataArrayRolling.reduce()` and
`DataSetRolling.reduce()` to allow this behavior.~~
~~If this seems okay, I have some questions:~~
~~1. Should this behavior be added to specific reducing functions (sum, mean, etc.)?  As an alternative, all of the specialized functions for `DataArrayRolling` have corresponding numpy `nan*` functions, so support could be added for those. …
=> Add examples for `DataArrayRolling.reduce()` 

doc/whats-new.rst, xarray/coding/cftimeindex.py, xarray/core/utils.py, xarray/tests/test_dataarray.py
=> BUG: fix safe_cast_to_index

xarray/core/dataarray.py
I ran in to this issue when using `imshow` on a dask-based `DataArray` and dask's `ProgressBar()` context manager. I noticed that when using `my_data_arr.plot.imshow` the dask array was being computed twice. This PR fixes that.
Suggestions for tests and documenting this fix are welcome.
=> Fix 'to_masked_array' computing dask arrays twice

doc/whats-new.rst, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_plot.py
`message` was always going being ignored, and with the newer pytest version raises a warning that an unknown kwarg is supplied
=> Pytest capture uses match, not message

doc/whats-new.rst, xarray/coding/variables.py, xarray/conventions.py, xarray/tests/test_coding.py
=> More support for missing_value.

doc/whats-new.rst, setup.cfg, xarray/tests/test_dataset.py
These are now required; I was getting warnings 
``` 
/usr/local/lib/python3.7/site-packages/_pytest/mark/structures.py:337: PytestUnknownMarkWarning: 
Unknown pytest.mark.network - is this a typo?  
You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html`
```
=> Add pytest markers to avoid warnings

.travis.yml, setup.cfg
As part of https://github.com/pydata/xarray/pull/2929#issuecomment-502302695, I looked at enabling travis to check types. 
What do people think? As a more cautious option I could add to `allowed_failures` for the moment
=> Check types in travis

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
This addresses #2994 by adding an "errors" keyword argument to `Dataset.drop()`, `Dataset.drop_dims()`, and `DataArray.drop()`. 
I stuck with pandas' convention of using either `errors='raise'`, now the default that maintains previous behavior by raising an error if any passed label is not found in the dataset/array, or `errors='ignore'` in which case any missing labels are silently ignored. 
This seems like a pretty straightforward change; mainly it is just skipping checks for missing labels when `errors == 'ignore'` and passing the errors keyword over to the pandas method when using `index.drop()`. Hopefully there are no subtleties that I've missed. 
I added documentation to the appropriate methods, although I have been struggling to build the docs locally and am unsure if they look …
=> Add "errors" keyword argument to drop() and drop_dims() (#2994)

doc/whats-new.rst, xarray/plot/utils.py, xarray/tests/test_plot.py
Unfortunately my fix in #2935 broke some major functionality. A proper fix would involve some facetgrid refactoring I think; so that'll take some time. This reverts that commit and adds a test.
```
xr.DataArray(np.random.randn(10, 20)).plot(levels=10, cmap=mpl.cm.RdBu)
```
=> Revert cmap fix

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/variable.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_variable.py
Add new option `keepdims` to xarray reduce operations, following the behaviour of Numpy.
`keepdims` may be passed to reductions on either Datasets or DataArrays, and will result in the reduced dimensions being still present in the output with size 1.
Coordinates that depend on the reduced dimensions will be removed from the Dataset/DataArray
The name `keepdims` is used here to be consistent with Numpy, `keep_dims` was an alternative name proposed in #2170.
The functionality has only been added to `Variable.reduce()`, `Dataarray.reduce()` and `DataSet.reduce()` to start off with, it is not implemented for `GroupBy`, `Rolling` or `Resample`.
=> ENH: keepdims=True for xarray reductions

.travis.yml
ref https://github.com/pydata/xarray/issues/3009#issuecomment-502432894
=> Dask-dev tests reenabled

.travis.yml, xarray/core/indexing.py, xarray/core/variable.py, xarray/tests/test_indexing.py
Fixes https://github.com/pydata/xarray/issues/3009
Previously, indexing an ImplicitToExplicitIndexingAdapter object could directly return an ExplicitlyIndexed object, which could not be indexed normally, e.g., `x[index]` could result in an object that could not be indexed properly. This resulted in broken behavior with dask's new `_meta` attribute.
I'm pretty sure this fix is appropriate, but it does introduce two failing tests with xarray on dask master. In particular, there are now errors raised inside two tests from dask's `blockwise_meta` helper function:
```
>       return meta.astype(dtype)
E       AttributeError: 'ImplicitToExplicitIndexingAdapter' object has no attribute 'astype'
```
cc @mrocklin  @pentschev
=> Ensure explicitly indexed arrays are preserved

ci/requirements-py36.yml, xarray/core/common.py
Quicker than expected follow-up to the typing PR, but realized that a newer version of mypy catches https://github.com/pydata/xarray/blob/master/xarray/core/common.py#L831 as `__getitem__` isn't implemented
=> Upgrade mypy & DataWithCoords check

doc/api.rst, doc/combining.rst, doc/computation.rst, doc/io.rst, doc/whats-new.rst, xarray/__init__.py, xarray/backends/api.py, xarray/core/combine.py, xarray/tests/test_backends.py, xarray/tests/test_combine.py
Finishes #2616 by renaming 
`combine_manual` -> `combine_nested`,
`combine_auto` -> `combine_by_coords`,
and renaming the arguments to `open_mfdataset`:
`combine='manual'` -> `combine='nested'`
`combine='auto'` -> `combine='by_coords'`
[x] code changes
[x] docs changes
[x] what's new updated
=> Rename combine functions

xarray/tests/test_combine.py
We weren't trying to do this in the first place, so somewhat coincidental:
```
xarray/tests/test_combine.py::TestManualCombine::test_manual_concat_too_many_dims_at_once
/home/vsts/work/1/s/xarray/tests/test_combine.py:347: PytestDeprecationWarning: raises(..., 'code(as_a_string)') is deprecated, use the context manager form or use `exec()` directly
```
=> pytest deprecation

doc/whats-new.rst, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
This fixes test failures on master, as noted in #2706
=> Fix test suite use of str(exception)

doc/pandas.rst, doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/merge.py
It's being removed in the next pandas 0.25 release
(see https://github.com/pandas-dev/pandas/pull/27101).
=> Ensure xarray imports (and docs build) even without pandas.Panel

xarray/backends/pseudonetcdf_.py, xarray/core/alignment.py, xarray/core/dask_array_compat.py, xarray/core/groupby.py, xarray/core/missing.py, xarray/core/nanops.py, xarray/core/npcompat.py, xarray/core/nputils.py, xarray/core/resample.py, xarray/plot/facetgrid.py, xarray/plot/plot.py, xarray/plot/utils.py, xarray/tests/test_backends.py, xarray/tests/test_concat.py, xarray/tests/test_plot.py
- Clean up everywhere the pattern
```
def my_func(*args, **kwargs):
my_optional_arg = kwargs.pop('my_optional_arg', None)
```
which was inherited from not being able to put named keyword arguments after ``*args`` in Python 2.
- Fix bug in SplineInterpolator where the ``__init__`` method would write to the class attributes of BaseInterpolator.
- ``map_dataarray`` was unintentionally and subtly relying on ``_process_cmap_cbar_kwargs`` to modify the kwargs in place. ``_process_cmap_cbar_kwargs`` is now strictly read-only and the modifications in kwargs have been made explicit in the caller function.
- Rename all 'kwds' to 'kwargs' for sake of coherency
=> kwargs.pop() cleanup

setup.py
Apparently some users have IT polices prohibiting the use of "beta" software!
=> Mark xarray as "Production" in setup.py rather than "eta"

.codecov.yml, ci/.coveragerc
- Exclude `_version.py` from coverage, since it was generated from versioneer.
- Remove the "reach" graph from comments.
- Don't give PRs a failing status if they decrease coverage.
=> Tweak codecov.io configuration

xarray/backends/file_manager.py
=> Internal cleanup in xarray.backends.file_manager

xarray/tests/test_backends.py
See https://github.com/pydata/xarray/pull/3058/checks?check_run_id=158702766 for an example failure
=> Fix another OS X test that can be flakey on Azure

xarray/core/combine.py
=> Removed rogue print statement in N-D combine

azure-pipelines.yml, ci/azure/install.yml, ci/azure/unit-tests.yml, conftest.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
The old setup didn't seem to work on CI, even when we explicitly passed the
relevant flags.
=> Fix the ability to run network and flaky tests

doc/whats-new.rst, xarray/core/formatting.py, xarray/tests/test_dataarray.py
Since merging #2293 summarize_variable displays the first and last few entries,
so we have to pass all along.
MWE:
```python
x = np.arange(0, 90, 0.5)
y = np.arange(0, 90, 0.5)
da = xr.DataArray(np.random.random((len(x), len(y))), [('x', x), ('y', y)])
da.stack(z=('x', 'y'))
```
gives on master:
```
<xarray.DataArray (z: 32400)>
array([0.497724, 0.793955, 0.140193, ..., 0.05734 , 0.884105, 0.479093])
Coordinates:
* z        (z) MultiIndex
- x        (z) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0 0.0
- y        (z) float64 0.0 0.5 1.0 1.5 2.0 2.5 ... 12.5 13.0 13.5 14.0 14.5
```
and on this branch
```
<xarray.DataArray (z: 32400)>
array([0.497724, 0.793955, 0.140193, ..., 0.05734 , 0.884105, 0.479093])
Coordinates:
* z     (z) …
```
=> Fix printing summaries of multiindex coords

xarray/backends/api.py, xarray/core/combine.py, xarray/tests/test_backends.py
=> Improve open_mfdataset deprecation warnings

xarray/tests/test_missing.py
Stumbled upon a unit test which didn't test anything.
=> Add missing assert to unit test

doc/environment.yml, doc/examples.rst, doc/examples/visualization_gallery.ipynb
Today @jhamman and I discussed how to refactor our somewhat fragmented "examples". We decided to basically copy the approach of the [dask-examples](https://github.com/dask/dask-examples) repo, but have it live here in the main xarray repo. Basically this approach is:
- all examples are notebooks
- examples are rendered during doc build by nbsphinx
- we will eventually have a binder that works with all of the same examples
This PR removes the dependency on sphinx_gallery and replaces the existing gallery with a standalone notebook called `visualization_gallery.ipynb`. However, not all of the links that worked in the gallery work here, since we are now using nbsphinx to render the notebooks (see https://github.com/spatialaudio/nbsphinx/issues/308).
Really important to get @dcherian's …
=> Replace sphinx_gallery with notebook

azure-pipelines.yml, ci/azure/install.yml, ci/azure/unit-tests.yml, ci/requirements/py35-min.yml, ci/requirements/py36-hypothesis.yml, ci/requirements/py36.yml, ci/requirements/py37-windows.yml, ci/requirements/py37.yml, doc/contributing.rst
This PR changes the test environment name from `test_env` to `xarray-tests` for clarity and to be consistent with the documentation environment name (`xarray-docs`).
=> Change name of testing conda environment

doc/environment.yml, xarray/tutorial.py
Together with https://github.com/pydata/xarray-data/pull/15, this allows us to generalize out tutorial datasets to non netCDF files. But it is backwards compatible--if there is no file suffix, it will append `.nc`.
=> Allow other tutorial filename extensions

doc/io.rst
This PR is related to the discussion in #2916.  In https://xarray.pydata.org/en/stable/io.html#netcdf there are statements like
>  netCDF files on disk directly correspond to Dataset objects.
This is useful conceptually but can be confusing when working with netCDF groups which are not supported as part of the data model.  I thought it would be clearer if the description of how to work with groups explicitly said this.
=> [DOC] Be more explicit about netCDF groups and xarray.Dataset relationship.

.codecov.yml
In theory, this should make codecov wait until reports from Azure are back (and require that all Azure checks pass) before posting its comment.
=> Tell codecov that Azure is a CI provider

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/indexing.py, xarray/tests/test_indexing.py
=> Better docs and errors about expand_dims() view

xarray/tests/__init__.py, xarray/tests/test_backends.py, xarray/tests/test_coding_times.py, xarray/tests/test_duck_array_ops.py
These tests are expected to fail on ARM due to the following issue in NumPy:
https://github.com/numpy/numpy/issues/8325
=> XFAIL tests failing on ARM

xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_formatting.py
=> Fix tests on big-endian systems

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/tests/test_dataarray.py
This PR fixed the forked code connected to #3129.
=> Merge broadcast_like docstrings, analyze implementation problem

ci/requirements/py36.yml
The upstream issue that required the constraint seems to have been fixed:
https://github.com/barronh/pseudonetcdf/issues/69
=> Remove the matplotlib=3.0 constraint from py36.yml

xarray/util/print_versions.py
I surrounded the whole check for h5py & netcdf with a blanket try / except, consistent with the other modules (but maybe too broad?
=> Fix h5py version printing

doc/whats-new.rst, xarray/core/groupby.py, xarray/tests/test_groupby.py
Using groupby on an empty DataArray or Dataset raises StopIteration. It should raise a more meaningful error.
=> BUG: fix+test groupby on empty DataArray raises StopIteration

doc/io.rst, doc/whats-new.rst, xarray/backends/api.py, xarray/core/dataset.py, xarray/tests/test_backends.py
=> to_zarr(append_dim='dim0') doesn't need mode='a'

ci/requirements/py36-hypothesis.yml, ci/requirements/py36.yml, ci/requirements/py37-windows.yml, ci/requirements/py37.yml, xarray/tests/test_backends.py
fix failing rasterio network test by simplifying test and using same image url as rasterio library test suite
- [x ] Closes #3083
=> changed url for rasterio network test

doc/whats-new.rst, xarray/core/combine.py, xarray/tests/test_combine.py
=> Hotfix for case of combining identical non-monotonic coords

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/utils.py, xarray/tests/test_utils.py
=> Fix distributed.Client.compute applied to DataArray

doc/conf.py
This PR removes all the type hints from method signatures generated by sphinx.ext.autodoc. See http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_typehints
The sphinx documentation doesn't say which version this was added in, but I imagine it is quite recent.
=> remove type annotations from autodoc method signatures

doc/conf.py
Enables the napoleon extension in sphinx. This will interpret the numpydoc style parameters and types and convert them to sphinx `:param type name:` Note that `sphinx.ext.napoleon` must come before the `numpydoc` extension.
Eventually the numpydoc dependency might be able to be removed but currently removing it makes the wrapped `ufunc` documentation omit the "parameters" and "returns", see the attached screenshot for what one of these ufuncs looks like with `numpydoc` removed.
=> enable sphinx.ext.napoleon

xarray/plot/plot.py
Still don't know how to test this.
=> Call darray.compute() in plot()

doc/environment.yml
This is hopefully a fix for #3182 but I wasn't sure how to really test this on read the docs (RTD) itself.
There may be a few things going on:
* Local testing showed removing the "auto_gallery" dir would cause the failing gallery examples to actually be recognized as failing (i.e. bust the cache)
* https://github.com/conda-forge/rasterio-feedstock/issues/118 and some examining of the `conda list` output on RTD for led me to think this was a deeper problem. Local testing with a bumped version of rasterio resulted in conda-forge being the channel source (rather than pip?), it also fixed the failing builds which relied on rasterio.
=> bump rasterio to 1.0.24 in doc building environment

doc/related-projects.rst
This adds [`climpred`](https://climpred.readthedocs.io) to the `xarray` related projects page.
=> Add climpred to related projects

doc/dask.rst
Another attempt at getting the docs to build again on RTD (#3182).
The current failure is due to high memory usage in the dask examples. I've converted the two most memory expensive code blocks into `:verbatim:` blocks so they don't use any additional memory. The contents of these blocks were taken from the last time the docs successfully built on RTD
=> reduce the size of example dataset in dask docs

doc/whats-new.rst, xarray/backends/api.py, xarray/core/combine.py, xarray/core/concat.py, xarray/core/merge.py, xarray/tests/test_backends.py, xarray/tests/test_combine.py, xarray/tests/test_concat.py
I won't work on it for the next few days if someone else wants to take over...
=> mfdataset, concat now support the 'join' kwarg.

doc/computation.rst
Without the escape the markup was a bit broken.
=> Escape code markup

doc/contributing.rst
This needed updating with the relevant commit post-black change
I also added a line to apply the patch of manual changes we made on top of the black changes. It makes the list of steps a bit burdensome. But I've tested them a couple of times and, where people have lots of code changes, it's still going to be much easier than resolving manually.
I generally wouldn't want to suggest people curl data from the internet (even if we trust the individual). I think it's probably OK in this instance: the address contains a hash of the contents, and it's only being fed into `git apply -`, not executed. But lmk if that's still a security concern.
I'll update the issue I opened on `black` with the above issue; we should have done one commit with only the `black` changes, and then another with any …
=> Update black instructions

.pre-commit-config.yaml, asv_bench/benchmarks/__init__.py, asv_bench/benchmarks/dataarray_missing.py, asv_bench/benchmarks/dataset_io.py, asv_bench/benchmarks/indexing.py, asv_bench/benchmarks/interp.py, asv_bench/benchmarks/reindexing.py, asv_bench/benchmarks/rolling.py, asv_bench/benchmarks/unstacking.py, doc/conf.py, doc/gallery/plot_cartopy_facetgrid.py, setup.cfg, versioneer.py
Not sure why these weren't picked up in some of the previous python3-ifying
=> Remove future statements

doc/contributing.rst
I'm not sure if people really use this? If they do, it could use another run through. Potentially some of our explanations could become links to better maintained docs; e.g. how to use git / pytest
This makes a couple of small tweaks, in pursuit of incrementalism :)
=> Small updates to contributing.rst

.gitignore
``open_dataset("<name>.grib", engine="cfgrib")`` creates a new file in the same directory called ``<name>.grib.<numbers>.idx``
=> Ignore example.grib.0112.idx

.pre-commit-config.yaml, ci/requirements/py36.yml, ci/requirements/py37.yml, xarray/core/dataset.py
Pre-commit hook is currently failing because of an issue detected by mypy 0.720 but not by mypy 0.650
=> Match mypy version between CI and pre-commit hook

xarray/core/duck_array_ops.py, xarray/tests/test_sparse.py
It has some questionable coercion logic that no longer seems to be necessary.
Not a user facing change.
=> Remove duck_array_ops.as_like_arrays()

doc/whats-new.rst, xarray/core/duck_array_ops.py, xarray/core/variable.py, xarray/tests/test_sparse.py
Closes #3191
@shoyer I completely disabled wrapping in ImplicitToExplicitIndexingAdapter for sparse arrays, cupy arrays, etc.
I'm not sure if it's desirable; the chief problem is that I don't think I understand the purpose of ImplicitToExplicitIndexingAdapter to begin with... some enlightenment would be appreciated.
=> chunk sparse arrays

doc/internals.rst
This is an attempt at clarifying accessor docs to help with the confusion I had in #3205. I'm not sure how many other xarray doc pages use `.. note::` but it seemed useable here. I'm not sure this is worth the explanation or if it is worded the best, but thought this could start the discussion.
=> Add note about accessor instance creation

azure-pipelines.yml, ci/azure/install.yml, ci/azure/unit-tests.yml, ci/requirements/py35-min.yml, ci/requirements/py36-hypothesis.yml, ci/requirements/py36.yml, ci/requirements/py37-windows.yml, ci/requirements/py37.yml, doc/contributing.rst, doc/examples.rst, doc/examples/ROMS_ocean_model.ipynb, doc/whats-new.rst, xarray/tutorial.py
This is an example of reading and visualizing ROMS model output. A highlight is adding a lazily calculated vertical coordinate. This notebook will need an example ROMS output file to run, called ROMS_example.nc. This will be uploaded to the data repository.
=> Added ROMS ocean model example notebook

setup.cfg, xarray/coding/cftime_offsets.py, xarray/coding/cftimeindex.py, xarray/core/computation.py, xarray/core/formatting.py, xarray/core/variable.py, xarray/tests/test_dask.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_formatting.py, xarray/tests/test_sparse.py
I also did a bit of cleanup (e.g., renaming methods) in xarray.core.formatting.
Sparse arrays were previously not shown in the Dataset repr:
Dimensions:  (x: 4)
Coordinates:
y        (x) int64 ...
Dimensions without coordinates: x
a        (x) float64 ..."""
Now they are:
Dimensions:  (x: 4)
Coordinates:
y        (x) int64 <COO: shape=(4,), nnz=3, fill_value=0>
Dimensions without coordinates: x
a        (x) float64 <COO: shape=(4,), nnz=4, fill_value=0.0>"""
=> Array formatting fixes for sparse and NEP-18 arrays.

doc/contributing.rst, doc/whats-new.rst
I'm a new contributor working on a couple PRs for Xarray and wished I had a short checklist of things to do before pushing a commit. First, I think such an overview list is useful per se. Second, CI takes a while, and it's much faster to just run `black .` or to build the docs manually than it is easy wait for CI to fail.
Inspired by [Scikit-learn's checklist](https://scikit-learn.org/stable/developers/contributing.html#pull-request-checklist). This is just a first draft; happy for suggestions or to add anything I'm missing.
=> Add PR checklist to contributing docs

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
=> Add examples of set_index and provide more clear error message

xarray/tests/test_dask.py
We shouldn't be checking the details of dask's repr.
=> Fix xarray's test suite with the dask master

doc/whats-new.rst, xarray/core/common.py, xarray/core/groupby.py, xarray/tests/test_dataset.py, xarray/tests/test_groupby.py
=> Support for dict-like arguments for assign_coords

doc/environment.yml, doc/io.rst, doc/whats-new.rst, xarray/backends/api.py, xarray/backends/h5netcdf_.py, xarray/core/dataset.py, xarray/tests/test_backends.py
Hi all,
I prepared a little PR which could close #2243 and would allow for a IMO clean way of writing data with complex dtypes (and others).
What do you think? 
TODOs:
----------
=> Allow invalid_netcdf=True in to_netcdf()

doc/contributing.rst
The testing environment name has been updated to `xarray-tests` in the package and we should do this in the documentation as well.
=> Updater to testing environment name

doc/indexing.rst, doc/whats-new.rst, xarray/core/dataset.py, xarray/tests/test_dataset.py
- Addresses issue https://github.com/pydata/xarray/issues/2910 and completes PR https://github.com/pydata/xarray/pull/3128.
- Passes `black .` and `flake8`.
- Documented in `whats-new.rst` and `indexing.rst`.
=> Drop keyword support: small fixes

xarray/core/dataset.py, xarray/tests/test_dataset.py
This will allow `filter_by_attrs` to filter coordinates as well as variables. @ocefpaf
=> Update filter_by_attrs to use 'variables' instead of 'data_vars'

doc/whats-new.rst
I missed this in my previous pull request. @dcherian
=> New feature of filter_by_attrs added to whats-new.rst

xarray/core/nputils.py, xarray/core/variable.py, xarray/tests/test_sparse.py
min and max are now working.
notnull was already fixed by one of my earlier PRs.
std/var/median are still broken, but only because sparse hasn't implemented
the corresponding NumPy functions yet (nanstd, nanvar and nanmedian).
rank needs pure NumPy implementation (not via bottleneck) if we want it to
work on sparse or dask arrays.
=> Fix duck array ops that were calling bottleneck on sparse arrays

xarray/backends/rasterio_.py, xarray/tests/test_backends.py
GeoTIFF and TIFF include tags that are useful in geo-processing. In particular the `AREA_OR_POINT` tag is commonly used. Although GDAL corrects the geo-referencing it is important to know which scheme is being used. An example of when this is useful is when aligning digital elevation models (which can be geotiff) with a raster data source.
=> added support for rasterio geotiff tags

doc/whats-new.rst, xarray/core/indexing.py, xarray/core/variable.py, xarray/tests/test_indexing.py, xarray/tests/test_sparse.py
=> Sparse fixes for reindex

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/tests/__init__.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_duck_array_ops.py
Fixes https://github.com/pydata/xarray/issues/3206
Example usage:
In [3]: import pandas as pd
...: import numpy as np
...: import xarray
...: df = pd.DataFrame({
...:     'w': range(10),
...:     'x': list('abcdefghij'),
...:     'y': np.arange(0, 100, 10),
...:     'z': np.ones(10),
...: }).set_index(['w', 'x', 'y'])
...:
In [4]: ds = xarray.Dataset.from_dataframe(df, sparse=True)
In [5]: ds.z.data
Out[5]: <COO: shape=(10, 10, 10), dtype=float64, nnz=10, fill_value=nan>
=> sparse=True option for from_dataframe and from_series

xarray/core/dataarray.py, xarray/tests/test_dataarray.py
As explained here https://github.com/pydata/xarray/pull/3159#discussion_r316230281 , when a user uses a scalar array to build a `DataArray` with `coords` given as a dictionary the error is not self explanatory.
```python
>>> xr.DataArray(np.array(1), coords={'x': np.arange(4), 'y': 'a'}, dims=['x'])
...
KeyError: 'x'
```
This PR makes sure that when `data` is a scalar array and `dims` is not empty, it sets the shape to `(0,)` to make it fail with the proper raise message 
```python
>>> xr.DataArray(np.array(1), coords={'x': np.arange(4), 'y': 'a'}, dims=['x'])
...
ValueError: conflicting sizes for dimension 'x': length 0 on the data but length 4 on coordinate 'x'
```
=> Raise proper error for scalar array when coords is a dict

doc/gallery/plot_cartopy_facetgrid.py
It is deprecated in Matplotlib 2.2, removed in 3.1, and appears to have no effect on the result.
- [N/A] Tests added
- [N/A] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API
=> Don't set box-forced in Cartopy example.

doc/api.rst, doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
I feel like there's room for improvement in the docstrings, any change or suggestion is welcome!
=> Add head, tail and thin methods

doc/whats-new.rst, xarray/plot/utils.py, xarray/tests/test_plot.py
=> allow np-array levels and colors in 2D plots

doc/whats-new.rst, xarray/core/concat.py, xarray/tests/test_concat.py
=> Remove deprecated concat kwargs.

doc/whats-new.rst, xarray/core/concat.py, xarray/core/dataarray.py, xarray/core/dataset.py
Per https://github.com/pydata/xarray/issues/3280
=> Compat and encoding deprecation to 0.14

doc/computation.rst, xarray/tests/test_backends.py
Just increased expected number of warnings by 1 till `h5netcdf` is fixed to not throw a warning (xref https://github.com/shoyer/h5netcdf/issues/62)
=> ignore h5py 2.10.0 warnings and fix invalid_netcdf warning test.

doc/api.rst
Seems like I forgot to point `head`, `tail` and `thin` to the right direction in the `DataArray` api documentation
=> Fix DataArray api doc

doc/whats-new.rst, xarray/core/dataset.py, xarray/core/variable.py, xarray/tests/test_dataarray.py
Note that I've set the default to True (if keep_attrs is None). This sounded reasonable since quantiles share the same units and properties as the original array, but I can switch it to False if that's the usual default.
=> Honor `keep_attrs` in DataArray.quantile

doc/whats-new.rst, xarray/core/dataset.py, xarray/core/groupby.py, xarray/core/resample.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_groupby.py
=> Deprecation: groupby, resample default dim.

xarray/backends/api.py, xarray/core/combine.py, xarray/tests/test_combine.py
This undoes the `auto_combine` deprecation until we figure out the best way to proceed.
(I am not very familiar with `auto_combine` so someone else should look over this. The tests all pass though...)
=> move auto_combine deprecation to 0.14

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
=> Allow weakref

asv_bench/benchmarks/indexing.py, xarray/core/dataset.py
xref #2227
Before:
indexing.BooleanIndexing.time_indexing      898±0ms
After
indexing.BooleanIndexing.time_indexing      401±0ms
=> Fix isel performance regression

xarray/core/dataarray.py, xarray/core/dataset.py
=> fix the name of the return value in the swap_dims docstrings

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py
This adds examples to both `Dataset.swap_dims` and `DataArray.swap_dims` (and fixes an oversight on my part in #3329).
From #2838, it seems that there was the intention to rename it, but as far as I can tell, that decision is not official yet (and `Dataset` even got its own new `rename_dims`).
=> Improve the documentation of swap_dims

doc/api.rst, doc/reshaping.rst, xarray/core/dataarray.py
While going through the docs, I noticed several issues:
* in `reshaping.rst`, a code block gets hidden because of a missing newline
* in `api.rst`, the section `What parts of xarray are considered public API?` is referenced (I think), but the link is broken.
* the code samples in `DataArray.plot` are not recognized as such because of missing newlines
* the documentation of `Dataset.plot.scatter` in the API reference is broken
This PR tries to fix all of those, but while the first three issues are easy to fix, I'm not sure whether my proposed fix for the one involving `scatter` is correct: I've added `plot.dataset_plot.scatter` to `plot.__all__` (exposing `xr.plot.scatter`) and changed `api.rst` to reference `plot.scatter` instead of `Dataset.plot.scatter`. It seems harmless to me, but the …
=> More doc fixes

doc/related-projects.rst
The [hypothesis-gufunc](https://pypi.org/project/hypothesis-gufunc/0.0.5rc2/) project recently added hypothesis strategies for generating xarray data structures in version 0.0.5rc2. This links to it in the related projects page.  It currently uses xarray as a package extra and must be installed as
```
pip install hypothesis-gufunc[xarray]==0.0.5rc2
```
The documentation is [here](https://hypothesis-gufunc.readthedocs.io/en/latest/).
=> Add hypothesis support to related projects

doc/environment.yml, doc/examples/ERA5-GRIB-example.ipynb
This was from the SciPy sprint, but failed to get submitted as a PR yet. This was developed by myself and @stephansiemen to demonstrate visualizing ERA5 GRIB data. The data was already added in https://github.com/pydata/xarray-data/pull/14.
=> Add an example of ERA5 and GRIB data & visualization to the gallery

xarray/core/dataarray.py
It calls DataSet.to_netcdf, which returns Union[bytes, "Delayed", None].  So this should as well.
=> Fix DataArray.to_netcdf type annotation

doc/io.rst, doc/whats-new.rst
I assume this is related to https://github.com/pydata/xarray/issues/3297 or an associated issue. Basically, a file, `complex.nc`, is being added to `doc/` after running `make clean && make html`. Would be nice to suppress this.
=> Remove `complex.nc` from built docs

doc/index.rst, doc/terminology.rst, doc/whats-new.rst
This is my attempt at closing https://github.com/pydata/xarray/issues/2410. I've borrowed a bit of text from that PR (thanks @horta), from https://github.com/pydata/xarray/issues/1295, and from the xarray docs. I avoided verbose examples—it makes quickly searching and reading the glossary difficult—and put most of the effort into explaining dimension vs non-dimension coordinates, which in my experience opens the door to true xarray enlightenment.
Corrections, comments, or suggestions for additional terminology welcome.
=> Add glossary to documentation

doc/_static/style.css, doc/howdoi.rst, doc/index.rst, doc/time-series.rst, doc/whats-new.rst
Thoughts on adding something like this?
=> Add how do I ... section

asv_bench/benchmarks/__init__.py, asv_bench/benchmarks/dataarray_missing.py, doc/examples/_code/weather_data_setup.py, doc/gallery/plot_cartopy_facetgrid.py, setup.py, xarray/backends/api.py, xarray/backends/locks.py, xarray/conventions.py, xarray/core/alignment.py, xarray/core/common.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/indexing.py, xarray/core/merge.py, xarray/core/rolling_exp.py, xarray/testing.py, xarray/tests/__init__.py, xarray/tests/test_accessor_str.py, xarray/tests/test_backends.py, xarray/tests/test_coding_times.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_distributed.py, xarray/tests/test_indexing.py, xarray/tests/test_sparse.py, xarray/tests/test_ufuncs.py, xarray/tests/test_variable.py
Revisit all ``# noqa`` annotation. Remove useless ones; replace blanket ones with specific error messages.
Work around https://github.com/PyCQA/pyflakes/issues/453.
note: ``# noqa: F811`` on the ``@overload``'ed functions works around a pyflakes bug already fixed in git master (https://github.com/PyCQA/pyflakes/pull/435) but not in a release yet, so it has to stay for now.
=> Revisit # noqa annotations

setup.cfg
Universal wheels indicate that one wheel supports Python 2 and 3. This
is no longer the case for xarray. This causes builds to generate files
with names like xarray-0.13.0-py2.py3-none-any.whl, which can cause
pip to incorrectly install the wheel on Python 2 when installing from a list of
wheel files.
=> Remove setting of universal wheels

doc/whats-new.rst, xarray/core/concat.py, xarray/tests/test_combine.py, xarray/tests/test_concat.py
This fixes the following behaviour. (downstream issue https://github.com/xgcm/xgcm/issues/154)
```
def test_concat(self, data):
split_data = [
data.isel(dim1=slice(3)),
data.isel(dim1=3), # this wouldn't work on master
data.isel(dim1=slice(4, None)),
]
assert_identical(data, concat(split_data, "dim1"))
```
=> Fix concat bug when concatenating unlabeled dimensions.

xarray/core/alignment.py, xarray/tests/test_dataset.py
I really should have known better than to remove this check -- there was a whole comment I had written explaining why it was there! I guess this is a lesson in why it's always important to write regression tests.
=> BUG: overrides to a dimension coordinate do not get aligned

xarray/backends/file_manager.py, xarray/backends/lru_cache.py
Very minor type annotations work
=> Annotate LRUCache

doc/faq.rst, doc/whats-new.rst, doc/why-xarray.rst
Fixes documentation typos in:
- faq.rst
- whats-new.rst
- why-xarray.rst
=> Fix documentation typos

doc/whats-new.rst, xarray/core/common.py
The docs of `resample` fail to mention that resampling only works with datetime-like coords: the only part where one could get this from is the examples (the pandas docs are much more explicit). I'm not sure whether it would be good to also point this out in the function description. Thoughts?
=> Fixes to the resample docs

xarray/core/common.py
The where docstring was a little confusing to me.  I misunderstood "Same type as caller' to mean the values in the xarray not the xarray itself.  I think this small change will clean it up for most users.  Thanks.
=> Update where docstring to make return value type more clear

xarray/core/groupby.py, xarray/tests/test_groupby.py
Testing could be improved, but as-is it would fix the same issue from happening again.
=> Fix and add test for groupby_bins() isnan TypeError.

ci/requirements/py36.yml, ci/requirements/py37-windows.yml, ci/requirements/py37.yml
Related to #3409 
The crashes caused by pseudonetcdf-3.1 are blocking all PRs.
Sorry I don't know anything about pseudonetcdf. This PR takes the issue out of the critical path so that whoever knows about the library can deal with it in due time.
=> Restore crashing CI tests on pseudonetcdf-3.1

doc/whats-new.rst, xarray/backends/locks.py
Revert changes made in #3358 which cause errors if cloudpickle is not installed.
Closes #3401
=> Revert changes made in #3358

ci/azure/install.yml, ci/requirements/py36-min-all-deps.yml, ci/requirements/py36.yml, ci/requirements/py37-windows.yml, ci/requirements/py37.yml, doc/whats-new.rst
temporarily pin cftime so that we can keep merging.
=> Add cftime git tip to upstream-dev + temporarily pin cftime

doc/whats-new.rst, xarray/coding/cftime_offsets.py, xarray/coding/cftimeindex.py
-  Don't need `dayofwk=-1` for cftime>=1.0.4
----
=> Sync with latest version of cftime (v1.0.4)

xarray/backends/rasterio_.py
Very minor change to address this DeprecationWarning:
```
xarray\backends\rasterio_.py:260: DeprecationWarning: Right multiplication will be prohibited in version 3.0
x, _ = (np.arange(nx) + 0.5, np.zeros(nx) + 0.5) * riods.transform
```
=> Address multiplication DeprecationWarning in rasterio backend

xarray/tests/test_dataset.py
=> Test that Dataset and DataArray resampling are identical

ci/azure/install.yml, ci/min_deps_check.py, ci/requirements/py36-min-all-deps.yml, ci/requirements/py36.yml, ci/requirements/py37-windows.yml, ci/requirements/py37.yml, doc/whats-new.rst
Let all CI tests become green again to avoid hindering developers who are working on PRs unrelated to the present incompatibilities (numpy=1.18, cftime=1.0.4, pseudonetcdf=3.1.0).
=> MAGA (Make Azure Green Again)

ci/azure/install.yml
Follow-up on #3436, needed now that https://github.com/Unidata/cftime/pull/127 has been merged.
=> Use cftime master for upstream-dev build

doc/contributing.rst, doc/terminology.rst, doc/whats-new.rst
As discussed in https://github.com/pydata/xarray/pull/3352, this PR modifies the Terminology page in the docs to briefly address multidimensional coordinates. Sorry for the delay in getting this in!
Also, when attempting to test the doc build, I found that the `doc/environment.yml` file was no longer present, so I updated it to `ci/requirements/doc.yml`.
=> Update Terminology page to account for multidimensional coordinates

xarray/backends/h5netcdf_.py, xarray/backends/zarr.py, xarray/core/accessor_dt.py, xarray/core/arithmetic.py, xarray/core/coordinates.py, xarray/core/dataset.py, xarray/core/indexing.py, xarray/core/missing.py, xarray/core/resample.py, xarray/core/rolling.py, xarray/plot/__init__.py, xarray/plot/facetgrid.py, xarray/tests/test_dataarray.py, xarray/tutorial.py
- Ran pyflakes 2.1.1
- Some f-string tweaks
- Ran black -t py36
- Ran mypy 0.740. We'll need to skip it and jump directly to 0.750 once it's released because of https://github.com/python/mypy/issues/7735
=> minor lint tweaks

xarray/core/formatting_html.py, xarray/tests/test_formatting_html.py
Follow-on to https://github.com/pydata/xarray/pull/3425 to make html_repr work with dtypes like '<U5'
=> Escaping dtypes

doc/examples/multidimensional-coords.rst, doc/groupby.rst, doc/whats-new.rst, xarray/core/common.py, xarray/core/dataset.py, xarray/core/groupby.py, xarray/core/variable.py, xarray/tests/test_dask.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_groupby.py, xarray/tests/test_plot.py, xarray/tests/test_sparse.py
This is a more drastic version of the suggested change, making `xr.ALL_DIMS` equal the ellipsis, `...`. 
The only downside I can see is that printing `xr.ALL_DIMS` will print `...`. The upside is that we get compat 'for free'
=> change ALL_DIMS to equal ellipsis

xarray/static/css/style.css
Follow on to #3425 to include support for jupyterlab dark theme. Note that this includes slight color changes. The most striking of which is that in jupyterlab light and regular notebook the even rows are white like the background.
=> jupyterlab dark theme

xarray/core/dataset.py, xarray/tests/test_dataset.py
I'm less up to speed on this behavior, but IIUC this part of the docstring refers to [deprecated behavior](https://github.com/pydata/xarray/compare/master...max-sixty:drop-docstring?expand=1#diff-921db548d18a549f6381818ed08298c9R3586-R3592)—is that correct or am I missing something?
xref https://github.com/pydata/xarray/issues/3266
=> Remove deprecated behavior from dataset.drop docstring

xarray/backends/api.py, xarray/core/alignment.py, xarray/core/combine.py, xarray/core/computation.py, xarray/core/concat.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/groupby.py, xarray/core/indexing.py, xarray/core/merge.py, xarray/core/variable.py, xarray/plot/plot.py, xarray/tests/test_cftime_offsets.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
﻿Black version 19.10b0 recently came out. Looks like the biggest change is assigning to a one-item-tuple
=> upgrade black verison to 19.10b0

doc/whats-new.rst
Couple of small changes for https://github.com/pydata/xarray/issues/3434
=> Whatsnew cleanup

ci/requirements/py36-min-all-deps.yml, ci/requirements/py36.yml, ci/requirements/py37-windows.yml, ci/requirements/py37.yml, doc/whats-new.rst
I think the cftime problems should be fixed after the release of [v1.0.4.2](https://github.com/Unidata/cftime/releases/tag/v1.0.4.2rel)
#3434
=> unpin cftime

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py
This updates the name in the parameter list of `Dataset.integrate` and adds an example. Also, the note in `DataArray.integrate` referred to `coord` which does not exist. I guess in the end to make it match `Dataset.integrate` it would be better to rename that parameter from `dim` to `coord`, but that would mean changing the API.
=> Fix integrate docs

xarray/tests/test_duck_array_ops.py
=> fix test suite warnings re `drop`

xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/utils.py
I did this before I realized it only works on mypy master! But posting so no one else does it. We can wait to merge until the next version of mypy is out
=> Type check sentinel values

azure-pipelines.yml, ci/requirements/py38.yml, doc/whats-new.rst
Adds some minimal Python 3.8 tests
Scipy doesn't seem to yet work, neither installing packages via conda. But at least we show we're compatible, and we can change the tests to align with our standard setup when available
=> python 3.8 tests

xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/groupby.py, xarray/core/indexes.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py
Works by propagating indexes in DataArray._replace.
xref #2227. Tests pass!
=> Propagate indexes in DataArray binary operations.

xarray/tests/test_backends.py
Previous test relied on CF generated metadata, but this test is more robust.
Development machine is missing python3.6 environment, using azure to check. This should help me get this fix in faster.
=> uamiv test using only raw uamiv variables

doc/data-structures.rst, doc/indexing.rst, doc/whats-new.rst, xarray/core/concat.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/groupby.py, xarray/core/merge.py, xarray/core/resample.py, xarray/tests/test_backends.py, xarray/tests/test_dask.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_duck_array_ops.py, xarray/tests/test_interp.py, xarray/tests/test_plot.py, xarray/tests/test_units.py
Introduces `drop_vars`, and deprecates using `drop` for variables. `drop` is widely used for the deprecated case, so this is a fairly wide blast radius.
It's more churn than is ideal, but I do think it's a much better API.
This is ready for review, though I'm sure I'm missed references in the docs etc (took my peak regex skills to find/replace only the deprecated usages!)
Originally discussed [here](https://github.com/pydata/xarray/pull/3460)
=> drop_vars; deprecate drop for variables

doc/whats-new.rst
Follow up to https://github.com/pydata/xarray/pull/3475#discussion_r343924765 + an entry I forgot to add
=> Whatsnew corrections

ci/requirements/py36.yml, ci/requirements/py37-windows.yml, ci/requirements/py37.yml
It should be possible to run the tests with pseudonetcdf 3.1.0 again. 
xref #3434, #3409, #3485
thanks @barronh
=> unpin pseudonetcdf

ci/azure/install.yml, xarray/core/dataarray.py
This PR makes `DataArray.__init__` ignore the pandas `attrs`. 
Not sure what we want to do about these attributes in the long term. One option would be to pop the `name` attribute, assign to `DataArray.name` and keep the rest as `DataArray.attrs`? But what if `name` clashes with the provided `name`?
=> fix pandas-dev tests

doc/computation.rst, doc/groupby.rst, doc/howdoi.rst, doc/quick-overview.rst, doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/groupby.py, xarray/core/resample.py, xarray/tests/test_dataarray.py, xarray/tests/test_dataset.py, xarray/tests/test_groupby.py, xarray/tests/test_sparse.py
This is the first step towards organizing these functions a bit better, as outlined in https://github.com/pydata/xarray/issues/1251, https://github.com/pydata/xarray/issues/1618, https://github.com/pydata/xarray/pull/2674
While this one is a fairly easy decision, others are going to be harder. Open to a more methodical up-front process before we start making changes, if we think that's necessary.
=> Dataset.map

xarray/plot/plot.py
Currently raises a `SyntaxWarning` (though I don't think causing any issues)
```
/home/vsts/work/1/s/xarray/plot/plot.py:291: SyntaxWarning: "is" with a literal. Did you mean "=="?
if args is ():
```
=> Remove syntax warning

doc/api.rst
As spotted by @dcherian in https://github.com/pydata/xarray/pull/3459#discussion_r344462719
=> Add drop_sel, drop_vars, map to api.rst

doc/computation.rst, doc/dask.rst, doc/installing.rst, doc/whats-new.rst, setup.cfg
The bottleneck repo url has changed as part of a maintainership handover, so updating in the documentation here.
=> DOC: update bottleneck repo url

doc/whats-new.rst, xarray/tests/test_units.py
This adds the tests that were missed by #3238 and #3447.
This should be ready to merge, but I'm almost certain that while going through #3238 and #3447 and trying to fix obvious mistakes I will find more missing tests.
Missing tests:
=> add missing pint integration tests

doc/indexing.rst
I struggled to parse some of the code in the docs, and so formatted some of the hardest-to-read code (e.g. `     mask = (ds.coords['lat']>20)&(ds.coords['lat']<60)&(ds.coords['lon']>220)&(ds.coords['lon']<260) `!) with black.
I'm not sure whether there's a more automated solution for this?
On a related point, I'm not sure why some of the code examples are colorized and some are B&W? I couldn't see anything obvious in the rst.
=> Format some of the docs code

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/variable.py, xarray/tests/test_dask.py, xarray/tests/test_sparse.py
After misreading the dask documentation  <https://docs.dask.org/en/latest/custom-collections.html#deterministic-hashing>, I was under the impression that the output of ``__dask_tokenize__`` would be recursively parsed, like it happens for ``__getstate__`` or ``__reduce__``. That's not the case - the output of ``__dask_tokenize__`` is just fed into a str() function so it has to be made explicitly recursive!
=> Recursive tokenization

doc/whats-new.rst, xarray/core/rolling.py, xarray/tests/test_dataarray.py
=> warn if dim is passed to rolling operations.

doc/whats-new.rst, xarray/backends/api.py, xarray/tests/test_dataset.py
AFAICT, the type checking in the `_validate_datatypes_for_zarr_append` is simply too strict, and relaxing it seems to work fine. But this is my first time digging into the xarray source code, so please let me know if this issue is more complex.
=> Allow appending datetime & boolean variables to zarr stores

doc/whats-new.rst, xarray/coding/variables.py, xarray/tests/test_coding.py
As pointed out in https://github.com/jbusecke/cmip6_preprocessing/issues/5, xarray appears to be very strict during the *encoding* and *decoding* steps even when there are (harmless) discrepancies between `missing_value` and `_FillValue`. For instance, when dtypes of `missing_value` and `_FillValue` are different, xarray gives up: 
```python
In [74]: from xarray.coding import variables                                                    
In [75]: import numpy as np                                                                     
In [76]: import xarray as xr                                                                    
In [77]: original = xr.Variable( 
...:         ("x",), 
...:         [0.0, -1.0, 1.0], 
...:         encoding={"_FillValue": np.float32(1e20), "missing_value": …
```
=> Harmonize `FillValue` and `missing_value` during encoding and decoding steps

doc/whats-new.rst, xarray/tests/test_units.py
This PR adds tests that cover the module level functions of the public API, similar to #3238 and #3447.
As a reference for myself, these are the functions listed by the docs:
Functions not covered by this PR:
* `auto_combine` (deprecated)
* `map_blocks` (dask specific, should be the same as `apply_ufunc` without dask)
=> Tests for module-level functions with units

doc/whats-new.rst, xarray/core/variable.py, xarray/tests/test_variable.py
Is there anything we need to consider here beyond the obvious?
=> add Variable._replace

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/tests/test_dataarray.py
There was a bug in `set_index`, where an old dimension was not updated if it becomes a level of MultiIndex.
=> Fix set_index when an existing dimension becomes a level

xarray/tests/test_units.py
Couple of methods were deprecated while PRs were outstanding; this PR reconciles
=> units / deprecation merge

xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/extensions.py
Save a few bytes and nanoseconds for the overwhelming majority of the users that don't use accessors.
Lay the groundwork for potential future use of ``@pandas.utils.cache_readonly``.
xref https://github.com/pydata/xarray/issues/3514
=> Leave empty slot when not using accessors

doc/whats-new.rst, xarray/core/dataset.py, xarray/tests/test_dataset.py
=> ensure rename does not change index type

doc/whats-new.rst, xarray/core/groupby.py, xarray/tests/test_groupby.py
This adds `DatasetGroupBy.quantile` by moving `DataArrayGroupBy.quantile` to `GroupBy` as proposed in https://github.com/pydata/xarray/issues/3018#issuecomment-507749287.
The tests are a modified copy of the ones from #2828. What confuses me is that `expected_yy` in `test_ds_groupby_quantile` needs the `transpose` whereas the equivalent in `test_da_groupby_quantile` doesn't. Does anyone have an idea about why that is?
=> Add DatasetGroupBy.quantile

doc/whats-new.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/variable.py, xarray/tests/test_dataset.py
Added an option `fill_value` for `unstack`.
I am trying to add `sparse` option too, but it may take longer.
Probably better to do in a separate PR?
=> Added fill_value for unstack

xarray/core/dataset.py
=> small simplification of rename from #3532

doc/conf.py, doc/whats-new.rst
get whats-new ready for release.
=> tweak whats-new.

ci/azure/install.yml, ci/requirements/py36.yml, ci/requirements/py37.yml, doc/whats-new.rst, xarray/core/dataset.py, xarray/core/duck_array_ops.py, xarray/tests/test_dataset.py, xarray/tests/test_duck_array_ops.py
Fix mean() and nanmean() for datetime64 arrays on numpy backend when upgrading from numpy 1.17 to 1.18.
All other nan-reductions on datetime64s were broken before and remain broken.
mean() on datetime64 and dask was broken before and remains broken.
=> Numpy 1.18 support

doc/README.rst, doc/api-hidden.rst, doc/combining.rst, doc/computation.rst, doc/dask.rst, doc/data-structures.rst, doc/pandas.rst, doc/whats-new.rst, xarray/backends/api.py, xarray/coding/cftimeindex.py, xarray/core/alignment.py, xarray/core/combine.py, xarray/core/common.py, xarray/core/computation.py, xarray/core/concat.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/groupby.py, xarray/plot/plot.py, xarray/ufuncs.py
This PR tries to silence most sphinx warnings. 5d9d263 is a collection of changes that silence warnings, but they also reduce the readability of the plain text docstrings, so I'd especially appreciate feedback on these.
There are still some warnings left, due to various reasons:
* the ufunc warnings are inherited from numpy
* some are due to duplicate target names in `whats-new.rst` (e.g. `CF Conventions` but also developer names).
* two files are not included in any toctree (`README.rst` and `api-hidden.rst`)
* references in `whats-new.rst` to labels that were either renamed or removed
* conflicting definitions for properties
* the CI also lists a lot of broken references to other functions / methods, which do not show for me
To fix these, I would
* update the numpy docstrings upstream …
=> Silence sphinx warnings

doc/whats-new.rst, xarray/core/alignment.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/duck_array_ops.py, xarray/core/variable.py, xarray/tests/test_dataset.py, xarray/tests/test_variable.py
Added `sparse` option to `reindex` and `unstack`.
I just added a minimal set of codes necessary to `unstack` and `reindex`.
There is still a lot of space to complete the sparse support as discussed in #3245.
=> sparse option to reindex and unstack

doc/whats-new.rst
=> 0.14.1 whatsnew

HOW_TO_RELEASE.md, doc/whats-new.rst
A few small tweaks, including a script for getting all recent contributors (feel free to edit if my bash is bad).
=> Tweaks to release instructions

doc/indexing.rst, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/groupby.py, xarray/core/indexes.py, xarray/tests/test_dataarray.py
=> propagate indexes in to_dataset, from_dataset

doc/whats-new.rst, xarray/core/computation.py, xarray/core/coordinates.py, xarray/core/dataarray.py, xarray/core/dataset.py, xarray/tests/test_dataarray.py
From a recent PR review, noticed we have a method that's strictly dominated by another
=> replace duplicate method _from_vars_and_coord_names

doc/related-projects.rst
As it says, this is just to add the https://github.com/obidam/pyxpcm xarray related project to the documentation page.
pyXpcm is a python package to create and work with ocean Profile Classification Model that consumes and produces Xarray objects.
=> Add pyXpcm to Related Projects doc page

doc/conf.py
Now that Unidata/cftime#133 is merged, we can link to the `cftime` documentation using intersphinx (silencing a few more sphinx warnings).
=> use cftime's intersphinx

xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/groupby.py
Following up to #3527, this adds examples for `DataArray.quantile`, `Dataset.quantile` and `GroupBy.quantile` (which is inherited by both `DatasetGroupBy` and `DataArrayGroupBy`).
=> Examples for quantile

doc/whats-new.rst
Since I forgot to add them before the merge of #3576, this needs a new PR.
=> add a whatsnew entry for quantile examples

ci/requirements/doc.yml, doc/conf.py, readthedocs.yml
The trick mentioned in https://github.com/pydata/xarray/issues/3567#issuecomment-561270215 works locally, but I don't know whether that's also the case for RTD. Since my own RTD setup cannot go past the environment creation stage: can someone with the appropriate rights on the official setup try this out for me?
Adding `xarray` to `doc.yml` is something temporary that has to be removed before the merge, but I think it is necessary to make sure the version collision occurs.
=> Resolve the version issues on RTD

doc/whats-new.rst, xarray/core/parallel.py, xarray/tests/test_dask.py
[x] closes #3599
This fixes an issue with the HighLevelGraph noted in
https://github.com/pydata/xarray/pull/3584, and exposed by a recent
change in Dask to do more HLG fusion.
cc @dcherian.
=> Fix map_blocks HLG layering

xarray/tests/test_units.py
This cleans up the tests which became a bit of a mess. Once that is done, we can actively work on fixing #3594.
=> Fix pint integration tests

doc/api.rst, doc/plotting.rst, doc/whats-new.rst, xarray/plot/facetgrid.py, xarray/tests/test_plot.py
This allows labels to be changed later using `Facetgrid.set_titles`. We now save handles in `Facetgrid.row_labels` and `Facetgrid.col_labels`. I also added some API docs for facetgrid.
Example
```
g = darray.plot.imshow(row="row", col="col")
g.set_titles("abc={value}")
```
**before** (see row labels; the column labels work because those are set using `set_title`. )
**after**
=> Add Facetgrid.row_labels & Facetgrid.col_labels

xarray/core/dataarray.py, xarray/core/dataset.py, xarray/core/variable.py
Really minor docstring fixes, just added 's' at the end of `kwarg` and deleted ` Default n = 5` from `thin` method's docstring since it doesn't have a default value.
=> Minor docstring fixes

xarray/core/variable.py
While it is easy enough to obtain this info from `%debug`, putting it
in the error messages is helpful when those messages come from user
reports (e.g. emails).
I am guessing that this change does not call for a new test or a
documentation update, but I'm happy to add one if asked.
=> Provide shape info in shape mismatch error.
