pydata/xarray

xray/core/common.py
xray/test/test_variable.py

Fix coercion of numeric strings to objects

---

xray/core/groupby.py
xray/test/test_dataset.py

This makes xray consistent with the behavior of pandas.

Skip NA in groupby groups

---

xray/core/alignment.py
xray/core/indexing.py
xray/core/utils.py
xray/test/test_indexing.py

As identified here:
https://github.com/perrette/dimarray/commit/ad4ab4d049f49881b28120d276337b2cab5e4061

BUG: Fix slicing with negative step size

---

xray/conventions.py
xray/test/test_conventions.py

Fix decoding missing coordinates

---

xray/conventions.py
xray/test/test_conventions.py

Fall back to netCDF4 if pandas can’t parse a date

---

doc/whats-new.rst
xray/core/alignment.py
xray/core/dataarray.py
xray/core/dataset.py
xray/test/test_dataarray.py
xray/test/test_dataset.py

e.g., pad, backfill or nearest

Support reindexing with an optional fill method

---

xray/conventions.py
xray/test/test_conventions.py

Fixes #323
We now get an error message with a lovely traceback when opening a dataset with invalid time units. For example:
```
File "/Users/shoyer/dev/xray/xray/test/test_conventions.py", line 340, in test_invalid_units_raises_eagerly
decode_cf(ds)
File "/Users/shoyer/dev/xray/xray/conventions.py", line 775, in decode_cf
decode_coords)
File "/Users/shoyer/dev/xray/xray/conventions.py", line 716, in decode_cf_variables
decode_times=decode_times)
File "/Users/shoyer/dev/xray/xray/conventions.py", line 676, in decode_cf_variable
data = DecodedCFDatetimeArray(data, units, calendar)
File "/Users/shoyer/dev/xray/xray/conventions.py", line 340, in __init__
raise ValueError(msg)
ValueError: unable to decode time units 'foobar since 123' with the default …
```

Improved error handling for datetime decoding errors

---

xray/core/dataset.py
xray/test/test_dataset.py

Fix Dataset aggregate boolean

---

xray/conventions.py
xray/test/test_conventions.py

Fix Dataset repr with netcdf4 datetime objects

---

.travis.yml
xray/conventions.py
xray/test/test_conventions.py

Partial fix for netCDF4 datetime issues

---

doc/combining.rst
doc/examples/weather-data.rst
doc/indexing.rst
xray/core/dataarray.py

Fixes #343
(among other small changes)

Documentation updates

---

xray/test/test_conventions.py

xref #340
These triggered an error with netCDF4 v1.1.5.

Fix reference dates used in test_dataset_repr_with_netcdf4_datetimes

---

doc/whats-new.rst
xray/backends/common.py
xray/backends/scipy_.py
xray/core/dataset.py
xray/test/__init__.py
xray/test/test_backends.py

Add "engine" argument and fix reading mmapped data with scipy.io.netcdf

---

appveyor.yml
ci/install_python.ps1
doc/whats-new.rst
xray/test/test_backends.py
xray/test/test_variable.py

Fixes #360
Note: several tests for netCDF4 were previously defined twice, by accident.

Add Appveyor for CI on Windows

---

xray/conventions.py
xray/core/formatting.py
xray/test/test_conventions.py
xray/test/test_formatting.py

The previous tests were actually not being run because I named the test method incorrectly :(

Fixes for dataset formatting

---

.travis.yml
doc/dask.rst
xray/backends/api.py
xray/backends/h5netcdf_.py
xray/core/dataarray.py
xray/core/dataset.py
xray/core/variable.py
xray/test/test_backends.py
xray/test/test_dask.py
xray/test/test_dataarray.py
xray/test/test_dataset.py

This involves a big internal rename: `block` -> `chunk`

Update xray to use updated dask.array and h5netcdf on pypi

---

.travis.yml
xray/backends/api.py
xray/backends/h5netcdf_.py
xray/test/test_backends.py

H5nc cleanup

---

xray/conventions.py
xray/test/test_conventions.py

Support reading and writing milliseconds/microseconds

---

xray/core/dataset.py
xray/test/test_dataset.py

Fix concat for identical index variables

---

doc/whats-new.rst

sorry, my OCD forces me to edit this.

2015 not 2005

---

doc/data-structures.rst
doc/whats-new.rst
xray/core/common.py
xray/core/dataset.py

The implementation here is directly copied from pandas:
https://github.com/pydata/pandas/pull/10253

Add pipe method copied from pandas

---

doc/indexing.rst

Update indexing docs

---

xray/test/test_backends.py

Not sure how this suddenly showed up.

Fix failing test on Travis

---

doc/whats-new.rst
xray/core/ops.py
xray/test/test_dataset.py

Fix min/max for arrays with string or unicode types

---

.gitignore
examples/xray_seasonal_means.ipynb

closes #424 
related: #465 and https://github.com/xray/xray-data/issues/1

add weighted seasonal means example ipython notebook

---

doc/whats-new.rst
xray/backends/common.py
xray/test/test_backends.py

Save netcdf variables in order when possible

---

doc/api.rst
xray/core/dataarray.py
xray/plotting.py
xray/test/test_plotting.py

Add plot_pcolormesh

---

doc/whats-new.rst
xray/core/ops.py
xray/test/test_variable.py

Fix aggregation on big-endian arrays with bottleneck installed

---

doc/whats-new.rst
xray/core/dataset.py
xray/test/test_dataset.py

Fix dataset aggregation functions for uint dtypes

---

doc/conf.py

build local docs using matplotlib Agg backend

---

doc/whats-new.rst
xray/core/common.py
xray/core/dataarray.py
xray/core/dataset.py
xray/test/test_dataarray.py

Fix pickle on DataArray objects

---

xray/test/test_backends.py

Fix broken build

---

doc/plotting.rst
doc/whats-new.rst

release notes for plotting

---

doc/whats-new.rst
xray/core/dataset.py
xray/test/test_dataset.py

Fixes #449
(also needs what's new line item)

Raise an error for non-unique columns in Dataset.from_dataframe

---

doc/dask.rst
xray/backends/api.py

minor changes in dask docs

---

xray/test/test_variable.py

Fix failing test case on i686

---

doc/whats-new.rst
xray/backends/api.py
xray/core/dataset.py
xray/core/utils.py
xray/test/test_backends.py
xray/test/test_conventions.py
xray/test/test_dataset.py
xray/test/test_utils.py

Raise an error if DataArray name is not able to be written to netCDF.

---

doc/plotting.rst
doc/whats-new.rst
xray/core/dataarray.py
xray/core/utils.py
xray/plot/facetgrid.py
xray/plot/plot.py
xray/plot/utils.py
xray/test/__init__.py
xray/test/test_plot.py

Allows this syntax:
```
In [52]: t4d.plot(x='lon', y='lat', col='time', row='fourth_dim')
Out[52]: <xray.plot.facetgrid.FacetGrid at 0x1184ffcd0>
```

Convenient faceting

---

xray/plot/facetgrid.py
xray/plot/plot.py
xray/test/test_plot.py

Fix FacetGrid.map and allow specifying size/aspect with .plot shortcut

---

xray/backends/api.py
xray/backends/common.py
xray/backends/netcdf3.py
xray/backends/scipy_.py
xray/conventions.py
xray/core/combine.py
xray/core/common.py
xray/core/coordinates.py
xray/core/dataarray.py
xray/core/dataset.py
xray/core/formatting.py
xray/core/groupby.py
xray/core/npcompat.py
xray/core/ops.py
xray/core/pycompat.py
xray/core/utils.py
xray/core/variable.py
xray/test/test_backends.py
xray/test/test_combine.py
xray/test/test_conventions.py
xray/test/test_dask.py
xray/test/test_dataarray.py
xray/test/test_indexing.py
xray/test/test_ops.py
xray/test/test_tutorial.py
xray/test/test_ufuncs.py
xray/test/test_utils.py
xray/test/test_variable.py

This is basically just a style/pep cleanup.  I removed a bunch of unused variables from internal modules.
I should say that I'm somewhat sheepishly submitting this PR, especially after seeing [this](https://youtu.be/wf-BqAjZb8M?list=PLP1xYYjBXksOm402NpkV1Ah5TRUKiQThn) talk by Raymond Hettinger.  However, since my [linter](https://atom.io/packages/linter-flake8) was constantly complaining about many of these, I figured I'd knock off all of them at once.  
There are quite a few line changes here but none of them should result in different behavior.

Spring cleaning

---

.landscape.yml
README.rst

@shoyer - we can ignore any warnings you don't like (e.g. `dangerous-default-value`).
xref #594

add landscape.yml config file

---

.travis.yml
xray/backends/api.py
xray/test/test_backends.py

This was introduced by #555, but never made it into a release.

BUG: fix open_dataset with remote URIs and chunking

---

doc/whats-new.rst
xray/conventions.py
xray/test/test_conventions.py

keep coordinates encoding even when coordinates are decoded

---

doc/whats-new.rst
xray/core/indexing.py
xray/test/test_dataset.py
xray/test/test_variable.py

Resolves the most pressing issue in #645

Selection works with PeriodIndex-like indexes 

---

doc/data-structures.rst
xray/core/dataarray.py
xray/core/dataset.py
xray/test/test_dataset.py

I think these should be `variables` rather than `data_vars` / `data`?

docs consistent with Dataset constructor taking variables

---

doc/data-structures.rst
doc/whats-new.rst
xray/core/alignment.py
xray/test/test_dataset.py

closes https://github.com/xray/xray/issues/664. 
What's new & docs forthcoming

Align pandas objects with named indexes

---

doc/data-structures.rst

No margin of error in these...

Doc formatting fix

---

doc/whats-new.rst
xray/core/dataarray.py
xray/test/test_dataarray.py

Should fix https://github.com/xray/xray/issues/684

DataArray.to_masked_array always returns array

---

licenses/PYTHON_LICENSE
xray/core/common.py
xray/core/indexing.py
xray/core/pycompat.py
xray/test/test_dask.py
xray/test/test_tutorial.py
xray/test/test_variable.py

Fixes #645
Now we have:
In [1]: import pandas as pd
In [2]: import xray
In [3]: idx = pd.period_range('2000', '2003', freq='M')
In [4]: xray.Dataset({'t': idx})
Out[4]:
<xray.Dataset>
Dimensions:  (t: 37)
Coordinates:
* t        (t) object 2000-01 2000-02 2000-03 2000-04 2000-05 2000-06 ...
*empty*
In [5]: xray.DataArray(idx, [('t', idx)])
Out[5]:
<xray.DataArray (t: 37)>
array([Period('2000-01', 'M'), Period('2000-02', 'M'),
Period('2000-03', 'M'), Period('2000-04', 'M'),
Period('2000-05', 'M'), Period('2000-06', 'M'),
Period('2000-07', 'M'), Period('2000-08', 'M'),
Period('2000-09', 'M'), Period('2000-10', 'M'),
Period('2000-11', 'M'), Period('2000-12', 'M'),
Period('2001-01', 'M'), Period('2001-02', 'M'),
Period('2001-03', 'M'), Period('2001-04', 'M'),
Period('2001-05', …

Fix PeriodIndex display

---

doc/data-structures.rst

Just stumble upon a typo while skimming through documentation.

Fix a typo

---

README.rst

We already disabled the CI hook.

Remove landscape.io from readme

---

setup.py
xarray/__init__.py

xref: discussion in https://github.com/pydata/xarray/pull/741

Better error message when version.py is missing

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/groupby.py
xarray/core/ops.py
xarray/test/test_dataarray.py
xarray/test/test_dataset.py

Resolves https://github.com/pydata/xarray/issues/739
@shoyer let me know your thoughts and I'll add what's new note

Allow empty result of numerical operations between DataArrays

---

doc/whats-new.rst
xarray/core/merge.py
xarray/test/test_dataarray.py

BUG: fix improper alignment of DataArray index coordinates

---

xarray/core/common.py

remove extra line from rolling doc string

---

xarray/core/ops.py
xarray/core/rolling.py
xarray/test/test_dataarray.py

fixes #776 
~~Still need to add a regression test~~

minor refactor of Rolling.reduce to handle nans

---

doc/api.rst
doc/computation.rst
doc/installing.rst
doc/whats-new.rst
xarray/core/common.py

Doc cleanup for v0.7.2 release

---

doc/indexing.rst
doc/whats-new.rst
xarray/core/common.py
xarray/core/dataarray.py
xarray/test/test_dataset.py

Addresses #811 to provide a Dataset and DataArray `sel_where` which returns a Dataset or DataArray of minimal coordinate size.

Add drop=True option for where on Dataset and DataArray

---

doc/data-structures.rst

To entirely add or removing coordinate arrays, you can use dictionary like
to 
To entirely add or remove coordinate arrays, you can use dictionary like

Fixes doc typo

---

.travis.yml
ci/install_python.ps1
ci/requirements-py27-min.yml

This should (hopefully) fix our failing builds.

Fix CI on Travis and Appveyor

---

doc/installing.rst
doc/plotting.rst

Follow-up on https://github.com/pydata/xarray/issues/869#issuecomment-223776182
I am no native speaker, so feel free to change everything.

DOC: mention conda-forge

---

xarray/core/dataarray.py
xarray/core/dataset.py

Fix drop docstring

---

doc/whats-new.rst
xarray/backends/api.py
xarray/backends/common.py

Fix incorrect test for dask version

---

doc/whats-new.rst
xarray/test/test_dask.py
xarray/ufuncs.py

Fix xarray.ufuncs dispatching between constant and dask array

---

doc/whats-new.rst
xarray/core/common.py
xarray/core/coordinates.py
xarray/core/dataset.py
xarray/core/formatting.py
xarray/core/pycompat.py
xarray/test/test_dataset.py
xarray/test/test_formatting.py

Fix printing of unicode attributes on Python 2

---

doc/index.rst
doc/internals.rst

Fix "Internals" link in What's New

---

doc/installing.rst

- List all optional dependencies
- Clarify when conda-forge is recommended
CC @ocefpaf @jhamman

Update "Installation" docs page

---

xarray/core/dataarray.py
xarray/core/dataset.py

~~I am not sure how to build the docs locally (yet) to test these changes.~~
---
Edit: I found the env file in the `docs` and tested the docs locally. These changes looks fine in the HTML.

Two minor docs fixes

---

doc/whats-new.rst
xarray/core/utils.py
xarray/test/test_dataset.py

Closes https://github.com/pydata/xarray/issues/847
The method here might be a bit sweeping. Let me know your thoughts

BUG: Allow arbitrary objects to be Dataset values

---

doc/whats-new.rst
xarray/backends/api.py

Fix open_mfdataset with engine='pynio'

---

doc/whats-new.rst
xarray/core/groupby.py
xarray/test/test_dataarray.py

groupby_bins sorted bin labels as strings

---

doc/whats-new.rst
xarray/core/alignment.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/test/test_dataset.py

Also ensure that reindexing always returns a new xarray object.
xref #927
cc @crusaderky

Clarify "copy" argument for reindex

---

.github.com/PULL_REQUEST_TEMPLATE.md

This should make it more obvious to new contributors what we expect.

Add PULL_REQUEST_TEMPLATE copied from pandas

---

doc/installing.rst

mini improvement of the install doc 

---

doc/whats-new.rst

This is another really minor typo...

Fixes documentation typo

---

doc/api.rst
doc/indexing.rst

DOC: indexes (#1054)

---

xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/utils.py
xarray/test/test_dataarray.py
xarray/test/test_dataset.py

Makes it easier to dump to json (after conversation on #917)

catch numpy arrays in attrs before converting to dict

---

xarray/test/test_dask.py

Disable broken test for dask ufuncs

---

doc/dask.rst

This adds some dask optimization tips from the mailing list (closes #1103).

add optimization tips

---

doc/environment.yml
doc/examples/multidimensional-coords.rst
readthedocs.yml

Sorry @shoyer you might get a few of these debugging PRs today again.

Another attempt to get netCDF4 working on RTD + py3

---

xarray/conventions.py
xarray/test/test_conventions.py

Fixes https://github.com/pydata/xarray/issues/1111

Bug in DecodedCFDatetimeArray

---

doc/environment.yml

The idea came from here: https://github.com/Unidata/netcdf4-python/issues/574#issuecomment-235435628
I could test it on another repo, so I'm confident that this should work here too. Obviously, this is a temporary solution. 
hopefully fixes https://github.com/pydata/xarray/issues/1106

Further attempt to get netCDF4 working on RTD

---

doc/environment.yml
doc/examples/weather-data.rst

sorry about the many PRs :-(
Let's see what happens with this one

Try py3 again on RTD

---

doc/combining.rst
doc/environment.yml

Another attempt to solve a cryptic error: https://readthedocs.org/projects/xray/builds/4727274/
But this time we are getting closer! I've found a report on ipython (https://github.com/ipython/ipython/issues/8850), an I've been able to reproduce it locally and solve it by updating to ipython 5

Update ipython on RTD

---

.gitignore
xarray/test/test_dataarray.py

A couple of tests weren't actually testing anything.
I may add things onto this PR if I see them

Minor test fixes

---

doc/conf.py

This implements a more robust solution based on the location of ``conf.py``...

RTD: furter attempt to fix savefig

---

.travis.yml
appveyor.yml
doc/plotting.rst

follow-up to https://github.com/pydata/xarray/pull/1203

RTD: fix facetted maps example

---

.gitignore
MANIFEST.in

Add licenses/ and docs/ to release tar-ball

---

xarray/__init__.py

Let me know if you want tests and/or what's new; wasn't sure since this is so small.

ENH import ufuncs module in toplevel namespace

---

doc/environment.yml

For some reason I can't reach the webpage but @shoyer seems to be able to do so:
https://github.com/pydata/xarray/issues/1167#issuecomment-274966778

mpl v2 for the docs

---

xarray/core/ops.py
xarray/core/rolling.py
xarray/tests/__init__.py

Use LooseVersion for bottleneck checks

---

README.rst
doc/faq.rst

Quick update to docs to use latest zenodo doi

use latest doi badge for zenodo

---

doc/api.rst

add DataArray.pipe to api docs

---

.gitattributes

Inspired by https://github.com/numpy/numpy/pull/8612

Reduce merge conflicts in whats-new.rst

---

doc/time-series.rst

fixed a small type in the docs

fixed simple typo

---

MANIFEST.in

Exclude .DS_Store files from the release tarball

---

xarray/tests/test_distributed.py

This should resolve the failing tests on master.

Fix dask-distributed tests

---

README.rst
setup.py
xarray/core/npcompat.py
xarray/core/pycompat.py
xarray/plot/utils.py

They are all now called out explicitly in the README as well.

Clarify licenses for bundled code

---

xarray/tests/test_backends.py

More explicit check for dtype roundtripping in backends

---

doc/computation.rst

DOC: remove mention errors in math without label overlap

---

appveyor.yml
doc/whats-new.rst
xarray/backends/pydap_.py
xarray/core/dataset.py
xarray/core/groupby.py
xarray/core/indexing.py
xarray/core/pycompat.py
xarray/core/variable.py
xarray/tests/test_dataset.py

Add Python 2.7 64-bit Windows to Appveyor build matrix

---

doc/whats-new.rst

Fix what's new for v0.9.2

---

doc/api.rst
doc/dask.rst
doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/tests/test_dask.py

Fixes https://github.com/pydata/xarray/issues/1344

Add persist method to DataSet

---

doc/faq.rst
doc/index.rst

A few doc updates to reflect the newly published status of our xarray paper.

update docs to reflect recently published paper on xarray

---

xarray/core/dataset.py

This was introduced by https://github.com/pydata/xarray/pull/1368 (@shoyer)

Remove debug print()

---

doc/whats-new.rst
xarray/tests/test_dataarray.py

Fix groupby bins tests

---

.github/PULL_REQUEST_TEMPLATE.md

per https://github.com/pydata/xarray/pull/1389#issuecomment-300947995
Preview:

Mention api.rst in PR template

---

doc/whats-new.rst
xarray/core/indexing.py
xarray/tests/test_indexing.py

BUG: fix "indexing error in sel subsets"

---

doc/internals.rst

[Salem](https://github.com/fmaussion/salem) is likely to remain a small project but it has a more-than-one user base and might provide some inspiration for the future [pangeo](https://pangeo-data.github.io) projects.

DOC: add salem to the list of projects extending xarray

---

doc/examples/monthly-means.rst

The PR just removes a repeated paragraph on an example so no tests and other stuff.
Please, let me know if you need anything else in order to merge the PR. I didn't see a 'How to contribute secttion in the docs'.

Remove repeated paragraph

---

doc/whats-new.rst
setup.cfg
xarray/core/ops.py
xarray/tests/test_dataarray.py

closes https://github.com/pydata/xarray/issues/1138

Rolling count

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_dataset.py

Fixes dataset rename bug (GH1477)

---

doc/whats-new.rst
xarray/backends/rasterio_.py

Made this fix for the issue #1520. I simpy added a test for None in the code and tested it with my ENVI-file that caused the problem that I reported. 
If I understood the test report correctly, the tests also passed.

Fixed issue #1520, by adding a if-else that checks for None

---

doc/whats-new.rst
xarray/backends/rasterio_.py
xarray/core/coordinates.py
xarray/tests/test_dataarray.py

Don't always make a MultiIndex when converting to pandas

---

doc/io.rst

They have fallen out of sync with the (relatively) recent changes by @crusaderky.

DOC: update docs on pickling

---

doc/dask.rst
doc/whats-new.rst

Blog post now at https://www.anaconda.com/blog/developer-blog/xray-dask-out-core-labeled-arrays-python/

DOC: Update broken link to dask blog post

---

doc/whats-new.rst
xarray/backends/netCDF4_.py
xarray/tests/test_backends.py

fix nc4 shuffle option roundtrip

---

xarray/core/computation.py
xarray/core/dataarray.py
xarray/core/dtypes.py
xarray/core/utils.py
xarray/tests/test_computation.py
xarray/tests/test_utils.py

This is safer default behavior than an inner join.

Default to join='exact' for apply_ufunc

---

doc/whats-new.rst
xarray/core/common.py
xarray/core/coordinates.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/tests/test_dataset.py

Support autocompletion dictionary access in ipython.

---

doc/io.rst

Just a docs change. Updated instructions for installing PyNIO to use conda-forge.

[DOCS] PyNIO is now available on conda-forge

---

.travis.yml
appveyor.yml

This should make the failures easier to debug.

Add "conda list" to CI builds

---

.gitignore
doc/computation.rst
doc/conf.py
doc/faq.rst

This pull updates the comparison between Xarray and Pandas ND-Panels, fixes the zenodo links, and improves our configuration for the docs build.  Closes #1541.

Minor documentation fixes

---

pytest.ini

fix CI builds (pytest/hypothesis) 

---

doc/io.rst
doc/whats-new.rst
xarray/conventions.py
xarray/tests/test_backends.py

Disable default _FillValue with encoding _FillValue=None

---

xarray/tests/test_backends.py

This PR simply adds a particular test pointed out in #1694 .

Add dropna test.

---

xarray/tests/test_distributed.py

Mark dask-distributed tests on Windows as xfail

---

.github/PULL_REQUEST_TEMPLATE.md

I have two goals here:
1. I'd like to clarify for new contributors what we actually expect here.
2. I'd like to ensure smaller, self-contained changes, e.g., for major new
features or refactoring, and make it clear that it's OK to merge parts of
larger projects before they are entirely documented.
Large changes (more a few hundred lines of code) are hard to review and
collaborate on. As long as the code is tested (even if some are marked
xfail), we should try to get these changes in faster so we can iterate on them.
It's OK if documentation comes later, as long as we document everything before
it's released. It's also OK to copy code when refactoring and delete old code
later: that is often the easiest way to make large changes.
@rabernat's recent zarr PR (#1528) is probably a good …

Clarify our pull request template.

---

doc/environment.yml

This fixes an issue where the in the current docs on dask didn't build properly because we were installing an old version of dask:
http://xarray.pydata.org/en/stable/dask.html
See the fixed page for an example:
http://xarray.pydata.org/en/doc-fix-dask/dask.html

Update docs environment.yml

---

xarray/core/dataarray.py

- [NA] Closes #xxxx (remove if there is no corresponding issue, which should only be the case for minor changes)
- [NA] Tests added (for all bug fixes or enhancements)
- [NA] Tests passed (for all non-documentation changes)
- [NA] Passes ``git diff upstream/master **/*py | flake8 --diff`` (remove if you did not edit any Python files)
- [NA] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API (remove if this change should not be visible to users, e.g., if it is an internal clean-up, or if this is part of a larger project that will be documented later)

DOC: added sortby example

---

doc/plotting.rst

As requested, I've added a section to the 1D plotting documentation.
I don't like the title. but couldn't think of a better one...

Docs for multiple line plots.

---

doc/whats-new.rst
xarray/conventions.py
xarray/tests/test_conventions.py

Fix multidimensional coordinates

---

xarray/backends/api.py

DOC: Added parameter list to open_dataarray

---

doc/examples/weather-data.rst
doc/whats-new.rst

- Closes #1844 with an example for using apply_ufunc
- No python code changed
- Added comment to `whats-new.rst`

added apply_ufunc example to toy weather data

---

README.rst
doc/installing.rst

As discussed in #1851, I added a link in doc/installing.rst and a badge on README.

Adding a link to asv benchmark.

---

xarray/util/print_versions.py

add h5py to show_versions()

---

doc/whats-new.rst
xarray/core/dataset.py

- [ 0] Tests added 
- [ 0] Tests passed

COMPAT: MultiIndex checking is fragile (#1833)

---

xarray/backends/zarr.py
xarray/core/dataset.py

drop zarr variable name from the dask chunk name

---

README.rst
doc/README.rst
doc/contributing.rst

- [NA] Closes #xxxx (remove if there is no corresponding issue, which should only be the case for minor changes)
- [NA] Tests added (for all bug fixes or enhancements)
- [NA] Tests passed (for all non-documentation changes)
- [NA] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API (remove if this change should not be visible to users, e.g., if it is an internal clean-up, or if this is part of a larger project that will be documented later)
These were inspired by a discussion on the mailing list:
https://groups.google.com/forum/#!topic/xarray/FyCFkuWbFSk

DOC: Add contributing section in README.rst and README.rst in doc/

---

README.rst

This will hopefully make it easier to keep track of our build status between releases.

Add ReadTheDocs badge to README.rst

---

README.rst

Fix rtd link on readme

---

doc/contributing.rst

@jhamman what are your thoughts on the flake8 instruction change?

DOC: Contributing / isort

---

doc/environment.yml

See https://github.com/pydata/xarray/pull/1957

Update some packages on RTD

---

xarray/tests/test_backends.py

Fix for failing zarr test

---

doc/_static/style.css
doc/_templates/layout.html
doc/conf.py
doc/index.rst

Based on https://github.com/dask/dask/pull/3360
Preview:

Include xarray logo on all docs pages

---

xarray/core/computation.py

Docs formatting

---

ci/requirements-py27-cdat+iris+pynio.yml
ci/requirements-py27-windows.yml
ci/requirements-py35.yml
ci/requirements-py36-bottleneck-dev.yml
ci/requirements-py36-condaforge-rc.yml
ci/requirements-py36-dask-dev.yml
ci/requirements-py36-netcdf4-dev.yml
ci/requirements-py36-pandas-dev.yml
ci/requirements-py36-pynio-dev.yml
ci/requirements-py36-rasterio1.0alpha.yml
ci/requirements-py36-windows.yml
ci/requirements-py36-zarr-dev.yml
ci/requirements-py36.yml
doc/installing.rst
doc/time-series.rst
xarray/coding/times.py
xarray/tests/__init__.py
xarray/tests/test_coding_times.py
xarray/tests/test_conventions.py

Addresses https://github.com/pydata/xarray/pull/1252#issuecomment-381131366
Perhaps I should have waited until `cftime` was up on conda-forge, but once that happens I can update this PR to use that in setting up the CI environments rather than pip.  
I made updates to the installing and time series pages of the docs.  Does this need a what's new entry?    I'm not sure which heading I would classify it under.

Updates for the renaming of netcdftime to cftime

---

xarray/core/merge.py
xarray/tests/test_dataset.py

Fix a bug introduced in #2087

---

doc/whats-new.rst
xarray/core/computation.py
xarray/tests/test_computation.py

Support keep_attrs for apply_ufunc for xr.Variable

---

doc/indexing.rst
doc/whats-new.rst
xarray/core/dataarray.py

Added examples to select and assign values to a DataArray using .loc() and xr.where() in the [Assign values with indexing](http://xarray.pydata.org/en/stable/indexing.html#assigning-values-with-indexing)

DOC: Added text to Assign values with Indexing

---

doc/faq.rst

Same as https://github.com/pydata/compilers-webpage/pull/9 ;-)

Hyperlink DOI against preferred resolver

---

doc/whats-new.rst
xarray/backends/api.py
xarray/tests/test_backends.py

fix unlimited dims bug

---

doc/whats-new.rst

DOC: misc fixes to whats-new for 0.10.7

---

doc/whats-new.rst
xarray/backends/zarr.py
xarray/tests/test_backends.py

fix zarr chunking bug

---

xarray/plot/facetgrid.py
xarray/tests/test_plot.py

Closes #2239 
Fixes a broken doc image: http://xarray.pydata.org/en/stable/plotting.html#id4
The tests passed previously because there was no metadata associated with the test DataArray. I've assigned some now, that should be good enough.

Bugfix for faceting line plots.

---

doc/whats-new.rst
xarray/backends/api.py
xarray/tests/test_backends.py

Write inconsistent chunks to netcdf

---

doc/whats-new.rst
xarray/plot/plot.py
xarray/tests/test_plot.py

Plotting: do not check for monotonicity with 2D coords

---

doc/contributing.rst

This PR addresses numerous small issues within `contributing.rst`. Some rationale is provided in the commit messages.

doc: corrections of contributing.rst

---

doc/whats-new.rst
xarray/backends/api.py
xarray/backends/common.py
xarray/tests/test_backends.py

fix dask get_scheduler warning

---

doc/whats-new.rst
xarray/core/formatting.py
xarray/core/pycompat.py
xarray/tests/test_dataset.py
xarray/tests/test_formatting.py

ENH: format_array_flat() always displays first and last items.

---

doc/index.rst
doc/roadmap.rst

See here for the rendered version:
https://github.com/shoyer/xarray/blob/4dd4463d5f79c07eb3a01f67b7329f2f4a60dd31/doc/roadmap.rst

DOC: add initial draft of a development roadmap for xarray

---

doc/interpolation.rst
xarray/core/dataarray.py

I merged #2312 without making sure the building test passing, but there was a typo.
Ths PR fixes it.

fix doc build error after #2312

---

.travis.yml
ci/requirements-py36-rasterio-0.36.yml

See https://github.com/pydata/xarray/issues/2316

Remove test on rasterio rc and test for 0.36 instead

---

doc/whats-new.rst
xarray/core/variable.py
xarray/tests/test_dataset.py

Better error message on invalid types

---

xarray/backends/zarr.py
xarray/convert.py
xarray/plot/utils.py

Trivial changes to pass local flake8 tests.

local flake8

---

doc/faq.rst

Potentially fixes #1115 as I have a correlation function. http://xarray.pydata.org/en/stable/dask.html?highlight=spearman#automatic-parallelization probably fixes #1115 as well

DOC: Add xskillscore to project lists

---

xarray/backends/api.py
xarray/core/missing.py

Just fix a spelling error in two error messages.

Fix spelling -- change recieved to received

---

.travis.yml

uncomment python -OO test

---

xarray/core/alignment.py
xarray/core/combine.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/merge.py
xarray/core/ops.py
xarray/core/variable.py
xarray/tests/test_backends.py
xarray/tests/test_variable.py

[MAINT] Avoid using duck typing

---

doc/whats-new.rst
xarray/core/options.py
xarray/plot/utils.py
xarray/tests/test_plot.py

add options for nondivergent and divergent cmap

---

doc/related-projects.rst

I believe this is a minor fix that means I don't need the things above, but If I'm mistaken please let me know and I can update the PR.
Thanks in advance!

Fix small typo in docs

---

doc/io.rst

from pydata.cas.urs import setup_session
should be:
from pydap.cas.urs import setup_session

fixed possible typo

---

doc/data-structures.rst

As pointed out by @FaustinCarter in #1949

Remove incorrect statement about "drop" in the text docs

---

doc/whats-new.rst

Ref https://github.com/pydata/xarray/pull/2466

Merge stable to master

---

.github/PULL_REQUEST_TEMPLATE.md

Do we need this bullet? I don't generally ensure tests pass before submitting for review. (Although if I should be, then lmk)

Tests passing in PR template

---

xarray/tests/__init__.py
xarray/tests/test_dataarray.py

- [N.A.] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API (remove if this change should not be visible to users, e.g., if it is an internal clean-up, or if this is part of a larger project that will be documented later)
A fix for #2468.

Inhouse LooseVersion

---

doc/groupby.rst

Include multidimensional stacking groupby in docs (#2493)

---

doc/reshaping.rst

as reported on the mailing list

DOC: remove example using Dataset.T

---

.travis.yml

Temporarily mark dask-dev build as an allowed failure

---

xarray/core/indexing.py

Next version can remove the Py2 path

silence import warning

---

xarray/tests/test_variable.py

Fixes https://github.com/pydata/xarray/issues/2673
Note that these were only test failures, not a real bug.

Fix test failures with numpy=1.16

---

.github/stale.yml

I think this requires a label
Thanks for everyone's understanding re needing to test it live

Probot stale tweak

---

ci/requirements-py36.yml
xarray/tests/test_backends.py

reintroduce pynio/rasterio/iris to py36 test env

---

doc/whats-new.rst

typo in whats_new

---

doc/data-structures.rst

This deprecation was finished in v0.11.0.

DOC: remove outdated warning

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_dataset.py

Fix indexes created by Dataset.swap_dims

---

README.rst

update links to https

---

xarray/coding/cftime_offsets.py

Fix mypy typing error in cftime_offsets.py

---

doc/related-projects.rst

Added xarray-related projects "xcube" and "xcube-viewer"

---

appveyor.yml

We don't want 10000 lines printing every single test :)

Less verbose tests on Appveyor

---

doc/computation.rst
doc/whats-new.rst
xarray/core/dataarray.py
xarray/tests/test_dataarray.py

Is it really this easy? What am I missing?

Implement @ operator for DataArray

---

.travis.yml

In lieu of fixing the issues, move these into allow_failures

Dask-dev tests to allow_failures in travis

---

xarray/core/dataarray.py
xarray/core/pdcompat.py
xarray/tests/test_dataarray.py

Should I still add a `whatsnew`? It's very small and very internal

Pandas labels deprecation

---

doc/whats-new.rst

typo in whats-new

---

README.rst
ci/azure/unit-tests.yml
doc/contributing.rst

Replace Appveyor with Azure Pipelines in README and contributor guide

---

HOW_TO_RELEASE
doc/whats-new.rst

xref https://github.com/pydata/xarray/issues/2977

DOC: reorganize whats-new for 0.12.2

---

ci/azure/unit-tests.yml

Upload coverage from Azure to codecov.io

---

ci/azure/unit-tests.yml
ci/requirements-py35-min.yml
ci/requirements-py36-dask-dev.yml
ci/requirements-py36-hypothesis.yml
ci/requirements-py36-pandas-dev.yml
ci/requirements-py36-rasterio.yml
ci/requirements-py36-windows.yml
ci/requirements-py36-zarr-dev.yml
ci/requirements-py36.yml
ci/requirements-py37-windows.yml
ci/requirements-py37.yml

See https://github.com/tonybaloney/pytest-azurepipelines
No user facing changes

Try installing pytest-azurepipelines

---

asv_bench/benchmarks/indexing.py
asv_bench/benchmarks/interp.py
asv_bench/benchmarks/reindexing.py
asv_bench/benchmarks/rolling.py
asv_bench/benchmarks/unstacking.py
xarray/core/indexing.py
xarray/core/merge.py
xarray/core/resample.py
xarray/core/rolling.py
xarray/core/variable.py
xarray/tests/test_backends.py
xarray/tests/test_dataset.py
xarray/tests/test_variable.py

Cleanup uses of super() to use Python 3 only syntax

---

xarray/core/computation.py

`rechunk` is not a methode of DataArray or Dataset, `chunk` does rechunk.

Fix error message

---

doc/api.rst
doc/faq.rst

xref https://github.com/Unidata/MetPy/issues/1077

Add FAQ entry clarifying what parts of xarray are public API

---

.gitignore
xarray/core/common.py
xarray/core/coordinates.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/merge.py

A little incremental addition to type annotations. By no means complete, but it should be ready for merge in its own right nonetheless.

More annotations

---

.coveragerc
ci/requirements/py36.yml
doc/whats-new.rst
xarray/backends/common.py
xarray/coding/variables.py
xarray/core/computation.py
xarray/core/concat.py
xarray/core/dask_array_compat.py
xarray/core/utils.py
xarray/plot/facetgrid.py
xarray/tests/test_backends.py
xarray/tests/test_backends_common.py
xarray/tests/test_computation.py
xarray/tests/test_print_versions.py
xarray/util/print_versions.py

- Suppressed various warnings.
- PsuedoNetCDF was not getting tested. Now it is.
- Added test coverage for `print_versions.py`

Suppress warnings and add test coverage

---

ci/requirements/py35-min.yml
doc/installing.rst
doc/whats-new.rst
setup.py
xarray/backends/api.py
xarray/coding/cftime_offsets.py
xarray/core/computation.py
xarray/core/coordinates.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/merge.py
xarray/core/pycompat.py
xarray/core/utils.py

Increase minimum Python version to 3.5.3

---

doc/whats-new.rst

Update whats-new for #3125 and #2334

---

.github/ISSUE_TEMPLATE/bug_report.md

If anyone has suggestions for better language...

Issue template: 'about' field is required

---

ci/requirements/py36.yml

This should get things building again.
xref https://github.com/pydata/xarray/issues/3154

Temporarily remove pynio from py36 CI build

---

.pre-commit-config.yaml

fix precommit file

---

xarray/tests/test_concat.py

small cleanup in `test_concat.py`

Refactor concat tests.

---

doc/whats-new.rst

When I read this, I thought it was referring to scattering data somehow :).

Clarify that "scatter" is a plotting method in what's new.

---

ci/azure/unit-tests.yml

WIP: Fix codecov.io upload on Windows

---

doc/data-structures.rst

Just two minor typographical errors fixed.

Typo correction in docs

---

ci/azure/install.yml

Temporary hack around #3440 to get green CI

pandas-dev workaround

---

doc/contributing.rst

Clarify conda environments for new contributors

---

.binder/environment.yml

add environment file for binderized examples

---

doc/related-projects.rst

I added my [project](https://github.com/CNES/pangeo-pyinterp) on the list of projects using Xarray. The library allows you to perform fast interpolations on unstructured, Cartesian grids and to fill indefinite values in grids.

added pyinterp to related projects

---

licenses/DASK_LICENSE

I'm not sure how this got here, but it was probably my fault at one point :)

Remove garbage text inserted in DASK_LICENSE

---

.github/ISSUE_TEMPLATE/bug_report.md

Comment in markdown rather than python

Format issue template comment as md comment

---

xarray/tests/test_formatting_html.py

Let test_repr_of_dataset pass on big-endian systems

---

ci/requirements/py36-min-all-deps.yml
ci/requirements/py36-min-nep18.yml

PIn msgpack so that tests pass.

pin msgpack

---

.github/ISSUE_TEMPLATE/bug_report.md

This currently de facto happens. And is reasonable

Add short summary at the top of issue template

---

ci/requirements/doc.yml
readthedocs.yml
xarray/tests/test_formatting_html.py

We fixed the docs for 0.15.0 by pinning versions for RTD on the stable branch. This brings that change over to master.

merge stable

---

.github/PULL_REQUEST_TEMPLATE.md
doc/whats-new.rst

`Closes` doesn't seem to add the issue to "Linked Issues" and auto-close. `Fixes` works elsewhere.

Use `fixes` in PR template

---

doc/whats-new.rst

Misplaced quote in whatsnew

---

.github/PULL_REQUEST_TEMPLATE.md
doc/whats-new.rst

Reverts pydata/xarray#3886, given @keewis 's point

Revert "Use `fixes` in PR template"

---

xarray/util/print_versions.py

add pint to the output of show_versions

---

xarray/core/dataset.py

DOC: add pandas.DataFrame.to_xarray

---

doc/io.rst

Io docs typo fix

---

doc/whats-new.rst

Our usual small reorg to push the most impactful changes to the top + add a list of contributors, as per https://github.com/pydata/xarray/blob/master/HOW_TO_RELEASE.md
I'm not sure of the bright line between "Enhancement" and "New Features"?

Minor reorg of whatsnew for 0.16.0

---

setup.cfg

Amended recommendation by @keewis

enh: fixed #4302

---

doc/roadmap.rst

Add @mathause to current core developers.

---

setup.cfg

and put the comment on the same line

mention all ignored flake8 errors

---

doc/whats-new.rst
xarray/core/computation.py
xarray/tests/test_computation.py

I'm not that excited about how this is tested, very open to alternatives. And the mechanics could take another set of eyes too.

Allow cov & corr to handle missing values

---

.pre-commit-config.yaml
ci/requirements/py36-min-all-deps.yml
ci/requirements/py36.yml
ci/requirements/py37-windows.yml
ci/requirements/py37.yml
ci/requirements/py38-all-but-dask.yml
doc/whats-new.rst

Align mypy versions

---

xarray/core/computation.py

Following the suggestion of @kmuehlbauer, I am using just a shallow copy since a deep one is not required.

Use a copy of dask_gufuc_kwargs

---

doc/whats-new.rst
xarray/core/variable.py
xarray/tests/test_dask.py

As a test to see whether this passes given the discussion at https://github.com/pydata/xarray/pull/4432

Revert "Fix optimize for chunked DataArray"

---

xarray/core/combine.py
xarray/core/groupby.py

Fix doctests

---

HOW_TO_RELEASE.md

ref https://github.com/pydata/xarray/pull/4440#issuecomment-695836637
Not sure this is the best approach; very open minded to alternatives

Add docs re stable branch

---

ci/requirements/doc.yml

Fixes the failing doc builds, see #4521

doc.yml: pin eccodes

---

doc/whats-new.rst
xarray/tests/__init__.py
xarray/tests/test_accessor_dt.py
xarray/tests/test_dask.py
xarray/tests/test_dataarray.py

fix all-but-dask tests

---

doc/whats-new.rst
xarray/plot/utils.py
xarray/tests/test_plot.py

Our step plots were not working, and the tests weren't working either!

Fix step plots

---

doc/contributing.rst
doc/whats-new.rst

This PR fixes grammar and typos in the [Contributing to xarray](http://xarray.pydata.org/en/stable/contributing.html) guide.

Fix grammar and typos in contributing guide

---

doc/whats-new.rst
xarray/core/alignment.py
xarray/core/concat.py

Improve alignment typehints

---

doc/related-projects.rst

The new link is where development now occurs.

Update xESMF link to pangeo-xesmf in related-projects

---

doc/whats-new.rst
xarray/core/computation.py
xarray/tests/test_computation.py

Fix: make copy of dask_gufunc_kwargs before changing content

---

.pre-commit-config.yaml
ci/requirements/py36.yml
ci/requirements/py37-windows.yml
ci/requirements/py37.yml
ci/requirements/py38-all-but-dask.yml
ci/requirements/py38.yml
xarray/core/utils.py

update mypy to 0.790

---

doc/whats-new.rst
xarray/core/duck_array_ops.py
xarray/core/utils.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

Found a couple more gremlins. Have added better test coverage so we catch any of these in the future.

Remove numpy warnings, add more complete tests

---

ci/requirements/doc.yml

Thanks for the pointer @keewis. Let's see if this works.

update sphinx to v3.3

---

doc/whats-new.rst

Looks like only minor cleanups were necessary.

Update whats-new for 0.16.2

---

xarray/tests/test_weighted.py

I feel I overdid it a bit with the parameterizations of the weighted tests. This brings the number of tests of `test_weighted.py` from about 1000 down to less than 200 without changing the coverage.

weighted: de-parameterize tests

---

.pre-commit-config.yaml
doc/contributing.rst
doc/io.rst
xarray/core/computation.py
xarray/core/dataset.py
xarray/core/options.py
xarray/core/parallel.py

This updates `blackdoc` (because that had a bugfix release) and commits the changes made by `pre-commit run -a`.

Update pre-commit hooks

---

doc/roadmap.rst

Add @andersy005 to the list of core devs

---

ci/azure/install.yml
ci/azure/unit-tests.yml
ci/min_deps_check.py
ci/requirements/py36-bare-minimum.yml
ci/requirements/py36-min-all-deps.yml
ci/requirements/py36-min-nep18.yml
ci/requirements/py36.yml
ci/requirements/py37-windows.yml
ci/requirements/py37.yml
ci/requirements/py38-all-but-dask.yml
ci/requirements/py38.yml
doc/whats-new.rst
xarray/tests/test_plot.py
xarray/tests/test_sparse.py
xarray/tests/test_units.py

CI: run tests in parallel (pytest-xdist)

---

doc/combining.rst
doc/whats-new.rst
xarray/core/concat.py

DOC: add examples to concat

---

.coveragerc

.coveragerc omit: wildcards

---

.github/workflows/parse_logs.py

fix the indentation of the nightly CI issue template

---

azure-pipelines.yml

Inspired by @Illviljan in https://github.com/pydata/xarray/pull/4750

Write black diff on errors

---

.github/PULL_REQUEST_TEMPLATE.md

Causes some odd formatting if there's a list immediately above it

(tweak) Fix PR template indenting

---

doc/related-projects.rst

Update hyperlink for xskillscore

DOC: update hyperlink for xskillscore

---

xarray/core/dataset.py
xarray/tests/test_dataarray.py

- Passes `pre-commit run --all-files`
- Fix typo in test of `Dataarray.drop_isel`
- Change docstrings of drop_sel to use `np.arange`
- Change drop to drop_isel and drop_sel respectively

fix issues in drop_sel and drop_isel

---

asv_bench/benchmarks/combine.py
asv_bench/benchmarks/dataset_io.py
asv_bench/benchmarks/repr.py

Mostly adjust to deprecated behaviour

Fix some asv benchmarks

---

doc/io.rst

Small doc fix, see http://xarray.pydata.org/en/stable/io.html#formats-supported-by-pynio (the `..note::` did not get picked up)

[skip-ci] doc: fix pynio warning

---

doc/whats-new.rst

Whatsnew for 0.17.1

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py

add polyval to polyfit see also

---

.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml
.github/workflows/upstream-dev-ci.yaml

upgrade ci-trigger to the most recent version

---

doc/user-guide/dask.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/parallel.py

Improve map_blocks docs

---

doc/user-guide/data-structures.rst

fixes small typo in documentation

---

.github/dependabot.yml

Add dependabot config (for updating github actions)

---

xarray/core/dataset.py

DOC: add see also for to_zarr

---

xarray/backends/api.py
xarray/core/computation.py
xarray/core/coordinates.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/indexing.py
xarray/core/nanops.py
xarray/core/variable.py
xarray/core/weighted.py
xarray/plot/dataset_plot.py
xarray/testing.py
xarray/tests/test_accessor_dt.py
xarray/tests/test_backends.py
xarray/tests/test_computation.py
xarray/tests/test_dataset.py
xarray/tests/test_interp.py
xarray/tests/test_variable.py

One line per file, for 17 files :)

Fix latest black version

---

.github/workflows/pypi-release.yaml

This fixes https://github.com/pydata/xarray/issues/5232#issuecomment-833729171

Release-workflow: Bug fix

---

doc/whats-new.rst

Add whats new for dataset interpolation with non-numerics

---

doc/contributing.rst
xarray/coding/cftimeindex.py
xarray/core/accessor_dt.py
xarray/core/alignment.py
xarray/core/combine.py
xarray/core/common.py
xarray/core/computation.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/merge.py

Another "snacking" PR. Ideally these allow future contributions to copy from a good template. But otherwise not a great use of time...

Remove standard imports from docstrings

---

xarray/tests/test_coding_times.py

A quick fix for a missing commit of PR #5288

Move encode expected test failures to own function

---

xarray/core/dataset.py
xarray/core/variable.py

Found some checks that should always be true nowadays.

Remove version checks for older versions than the min deps

---

xarray/core/dataarray.py

fix the drop_duplicates docs

---

xarray/core/dataarray.py

Making PR from github code editor. Hopefully this works out,

Remove precipitation var from dataarray docstring

---

.github/workflows/upstream-dev-ci.yaml
xarray/tests/test_plot.py

#5267 seems to accidentally have disabled the scheduled CI.

fix the upstream-dev CI

---

doc/whats-new.rst

This was not in the 0.18.2 release

Fix whatsnew formatting

---

xarray/tests/test_dataarray.py

Tiny step to unify some of our tests across backends

Use dask fixture in DataArray tests

---

doc/whats-new.rst
xarray/core/weighted.py
xarray/tests/test_weighted.py

Check dimensions before applying weighted operations

---

.github/workflows/ci.yaml
doc/whats-new.rst

Run tests only on python 3.7 & 3.9

---

doc/tutorials-and-videos.rst

Added today's seminar by @andersy005 to the tutorials and videos page per conversation with @dcherian.

add xarray tutorial

---

.github/workflows/ci-additional.yaml
.pre-commit-config.yaml
ci/requirements/mypy_only
xarray/core/computation.py
xarray/core/utils.py

On top of https://github.com/pydata/xarray/pull/5467, given I'm not sure this is correct.
With `additional_dependencies`, we may not need the additional CI run.
But OTOH there's nothing confirming that the `additional_dependencies` has the correct dependencies and there's no material cost to the additional step.

Run mypy in pre-commit only in CI?

---

.github/workflows/upstream-dev-ci.yaml
HOW_TO_RELEASE.md
README.rst
asv_bench/asv.conf.json
doc/conf.py
doc/contributing.rst
doc/getting-started-guide/installing.rst
doc/whats-new.rst

towards #5516. With this, all references to the `master` branch have been updated to point to `main`.

update references to `master`

---

xarray/core/options.py

Correct default display style

---

.github/workflows/ci.yaml
.github/workflows/publish-test-results.yaml
doc/whats-new.rst

Fix junit test results

---

doc/getting-started-guide/installing.rst
setup.cfg

See: https://github.com/pydata/xarray/pull/5503#discussion_r655550526
cc: @dcherian

specify typing-extensions version

---

xarray/core/dask_array_ops.py

- [n/a] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [n/a] New functions/methods are listed in `api.rst`

Fix type inference for dask push.

---

xarray/backends/zarr.py

Makes life a little easier when navigating the docs

DOC: add open_mfdataset in See Also

---

doc/api.rst

Del duplicate set_options in api.rst

---

doc/conf.py

update the link to `scipy`'s intersphinx file

---

doc/roadmap.rst

fixing typo spelling grammar and replace to correct words

fix: typo spelling grammar

---

doc/user-guide/time-series.rst

I added a small bit to the [time series data](https://xarray.pydata.org/en/stable/user-guide/time-series.html) section of the user guide, detailing how to subset for a particular month from a dataset.
This solution is described in a [stack overflow solution](https://stackoverflow.com/questions/60791186/select-xarray-dataset-based-on-month), and figured users would benefit from knowing how to do this.

first pass at adding to month indexing time series

---

ci/requirements/doc.yml
doc/roadmap.rst

update development roadmap

---

doc/user-guide/dask.rst

Original link to pangeo use-cases was dead, updated to point at pangeo gallery

Update dead link per #5810

---

doc/whats-new.rst
xarray/core/formatting.py
xarray/tests/test_plot.py

fix float formatting in a plot's title

---

doc/ecosystem.rst

Since recently, Darts uses `DataArray` as the core data structure underpinning its `TimeSeries` class to represent all time series in the library. It's working great for us, so I also want to take the chance to thank the xarray community here!

Add Darts to ecosystem file

---

doc/whats-new.rst
xarray/plot/plot.py
xarray/tests/test_plot.py

Closes #5791 
If the feature request is accepted :)

Set scalar coords title to histogram plots

---

doc/whats-new.rst

@pydata/xarray the release notes for your approval
#5889

v0.20 Release notes

---

doc/ecosystem.rst

One of the PTSA authors told me about the new URL by email.

Docs: fix URL for PTSA

---

xarray/core/dataarray.py

A very modest contribution... I miss contributing to xarray!
Believe it or not, I did not know about `to_pandas` until today...

Add "see also" in to_dataframe docs

---

doc/developers-meeting.rst
doc/index.rst

Related to https://github.com/pydata/xarray/issues/4001#issuecomment-779556647

DOC: add link to Developers Meeting

---

doc/whats-new.rst

DOC: fix sphinx warning

---

doc/ecosystem.rst

Adding the xnemogcm package, designed to read NEMO gcm output files and add the necessary attributes to make it easy to be used with xgcm.

Adding a package in ecosystem.rst

---

ci/requirements/environment-windows.yml
ci/requirements/environment.yml

Continuing from https://github.com/pydata/xarray/pull/6077 & https://github.com/dask/dask/pull/8484

Make CI pass by limiting dask version

---

.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml

Reverts pydata/xarray#6077 (after dask has been pinned in #6111)

Revert "disable pytest-xdist (to check CI failure)"

---

xarray/core/dataarray.py

as per https://github.com/pydata/xarray/issues/6136

Remove paren from DataArray.from_dict docstring

---

xarray/core/concat.py

Import Literal from typing instead of typing_extensions

---

xarray/tests/test_groupby.py

Add tests for groupby math

---

doc/user-guide/computation.rst

Fix link to "Generalized Universal Function API" of Numpy's doc

DOC: fix dead link

---

xarray/backends/h5netcdf_.py
xarray/core/_reductions.py
xarray/core/dask_array_compat.py
xarray/core/dataset.py
xarray/core/duck_array_ops.py
xarray/tests/test_accessor_dt.py
xarray/tests/test_cftime_offsets.py
xarray/tests/test_dataarray.py
xarray/tests/test_plugins.py
xarray/tests/test_sparse.py
xarray/util/generate_reductions.py

I hunted down some version checks that should no longer be necessary as we have moved beyond the minimum versions.

remove no longer necessary version checks

---

xarray/tutorial.py

Allow controlling the randomness of the dataset. It's difficult to catch issues with the dataset if it always changes each run.

Add seed kwarg to the tutorial scatter dataset

---

xarray/tests/test_distributed.py
xarray/tests/test_variable.py

As per https://github.com/pydata/xarray/issues/6209#issuecomment-1025116203

Xfail failing test

---

.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml

`GHA` `concurrency` followup

---

.github/PULL_REQUEST_TEMPLATE.md

Revert "Remove old PR template"

---

ci/install-upstream-wheels.sh

pydata/bottleneck#378 was merged - so this should work again.

test bottleneck master in upstream CI [test-upstream] [skip-ci]

---

xarray/core/weighted.py

Clean up a little in preparation for #6059.
xref: #6244

Run pyupgrade on core/weighted

---

.pre-commit-config.yaml

Update pyupgrade to py38-plus

---

doc/ecosystem.rst

This PR adds a new wrapper made for xarray around the gsw package

Adding the new wrapper gsw-xarray

---

xarray/core/dataarray.py
xarray/core/dataset.py

Convert the code block in `xr.DataArray.from_dict` and `xr.Dataset.from_dict` to doctest/ examples.

from_dict: doctest

---

doc/internals/how-to-add-new-backend.rst

Fix class attributes versus init parameters

---

xarray/core/groupby.py

Minor touch up looking through #5950.

Run pyupgrade on core/groupby

---

xarray/core/groupby.py
xarray/tests/test_groupby.py

Fix Dataset groupby returning a DataArray

---

doc/whats-new.rst

Add kwarg-only breaking change to whats-new

---

xarray/core/concat.py
xarray/tests/test_concat.py

Fix concat with scalar coordinate (dtype)

---

.github/ISSUE_TEMPLATE/config.yml

We seem to get a decent number of questions regarding raster analysis. Thought it would be good to redirect them over to the rioxarray repo.
cc @snowman2 @scottyhq

[skip-ci] Redirect raster analysis questions to rioxarray

---

.github/stale.yml

Restrict stalebot on projects & milestones

---

.pre-commit-config.yaml

As recommended in https://github.com/keewis/blackdoc/issues/122

Pin version of black in pre-commit blackdoc

---

README.md

- Add a slighly cheesy contributors panel to readme

Add a contributors panel to readme

---

.github/workflows/ci-additional.yaml

Almost all the way there on rolling back everything I've done recently :)

Skip mypy tests in CI

---

.github/workflows/ci-additional.yaml

So we can at least see the result

Run mypy tests (but always pass)

---

xarray/core/computation.py
xarray/tests/test_computation.py

change polyval dim ordering

---

doc/user-guide/combining.rst

added and highlighted keywords as in the chapters on merge and combine.

concatenate docs style

---

xarray/tests/test_distributed.py

import `cleanup` fixture from `distributed`

---

doc/user-guide/index.rst
doc/user-guide/options.rst
xarray/core/options.py

Better documentation of options

---

doc/index.rst

xref https://github.com/xarray-contrib/xarray-tutorial/pull/85#issuecomment-1159518073

[skip-ci] Add sphinx module directive

---

doc/whats-new.rst
xarray/backends/api.py
xarray/backends/rasterio_.py

I don't really know how to test this...
Is it ok to leave it untested?

Expanduser (~) for open_dataset with dask

---

doc/api.rst

One top level heading with Dataset, DataArray, and
Faceting subsections.

[skip-ci] Reorganize the Plotting section of API Reference

---

xarray/core/common.py

DOC: Updated reference link for resample method

---

doc/ecosystem.rst

Adds https://github.com/pyvista/pyvista-xarray to the visualization ecosystem

Add pyvista-xarray to visualization ecosystem

---

doc/whats-new.rst

Add import change to whats-new

---

xarray/tutorial.py

edited `tutorial.py` docstring
goes toward closing https://github.com/xarray-contrib/xarray-tutorial/issues/117

added ASE ice velocity to tutorial docstring

---

xarray/core/indexing.py

Some minor import oddities I noticed while reading the code.

Remove generic utils import

---

xarray/core/dataarray.py
xarray/core/dataset.py

Help navigation in the docs of going between the DataArray method and the Dataset method.

DOC: link DataArray.expand_dims to Dataset.expand_dims

---

xarray/plot/utils.py

Reduce diffs in #6778. I remember finding it annoying that I got a list of the valid strings but not the actual string used.

Better error message in _infer_meta_data

---

doc/conf.py

Fix documentation builds

---

xarray/tests/test_backends.py
xarray/tests/test_backends_file_manager.py

Get rid of some warnings in the tests.

tests don't use `pytest.warns(None)`

---

xarray/tutorial.py

Add some typing to the open_dataset functions. Was doing some debugging and I only got `Any` when trying to simplify the problem with tutorial data.

Type xr.tutorial

---

xarray/plot/facetgrid.py

Minor tweak to reduce diffs in #6778.

Reuse total width calculation

---

xarray/util/deprecation_helpers.py

I [forgot to remove](https://github.com/pydata/xarray/pull/6910#discussion_r948145640) some debug print statements in #6910 - thanks for noting @shoyer & @dcherian

deprecate_positional_args: remove stray print

---

.github/labeler.yml

Use `topic-documentation` and automatically run benchmarks

Update PR labels

---

doc/user-guide/terminology.rst

@zmoon - obviously it would be nice if we had a linter for this but this is for another time.

terminology: fix italics [skip-ci]

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/core/variable.py
xarray/tests/test_variable.py

Fix bug where indexes were changed inplace

---

.github/labeler.yml

[skip-ci] Stop applying topic-documentation label

---

setup.cfg
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/variable.py

Improve quantile method docstring + error

---

xarray/tests/test_dataarray.py
xarray/tests/test_groupby.py
xarray/tests/test_variable.py

This PR removes several warnings from the tests and improves their typing on the way.

Even less warnings in tests

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/core/merge.py

Update merge docstrings

---

xarray/plot/facetgrid.py

* Fix outdated typing.
* Clearer variable names.

Clearer variable names in FacetGrid._set_lims

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/utils.py
xarray/core/variable.py

Fill in missing docstrings for ndarray properties

---

doc/whats-new.rst

Thumbs up if it looks fine to you

2022.09.0 release summary

---

pyproject.toml
xarray/tests/test_dataset.py

- silences some user warning from renaming dims.
- fix coverage config

Minor tests improvements

---

xarray/core/dataarray.py

Fix warning in doctest

---

xarray/core/dataset.py

...as python List sort() is in-place

make clearer that sortby() do not run inplace

---

xarray/tests/test_plot.py
xarray/tests/test_units.py

Follow up to #7194. This fixes all the warnings related to the change.

Rename FacetGrid.axes to FacetGrid.axs in tests

---

doc/whats-new.rst
xarray/core/formatting.py
xarray/tests/test_formatting.py

Avoid loading any data for reprs 

---

doc/whats-new.rst
xarray/plot/dataarray_plot.py
xarray/tests/test_plot.py

Raise TypeError if plotting empty data

---

doc/whats-new.rst
xarray/core/rolling.py
xarray/tests/test_coarsen.py

Ensure Coarsen.construct keeps all coords

---

doc/user-guide/reshaping.rst

typo in xarray/doc/user-guide/reshaping.rst

---

xarray/tests/__init__.py

fix doctests: supress urllib3 warning

---

doc/whats-new.rst
xarray/core/computation.py
xarray/tests/test_computation.py

Handle numpy-only attrs in `xr.where`

---

xarray/core/dataset.py

Since groupby is a bit like resample on non contiguous data

groupby in resample doc and vice-versa 

---

ci/requirements/doc.yml

This should fix our doc build.

pin scipy version in doc environment

---

xarray/core/dataarray.py

Make text match code example

---

doc/ecosystem.rst

Add xCDAT to list of Xarray related projects

---

xarray/tests/test_plot.py

add a test for scatter colorbar extend

---

xarray/core/indexes.py

Avoid recasting a CFTimeIndex

---

requirements.txt

Remove pandas<2 pin

---

doc/whats-new.rst
xarray/core/groupby.py
xarray/tests/test_groupby.py

Fix `min_count` behaviour with flox.

---

doc/conf.py

Thanks @pierre-manchon for the report!

Fix link to xarray twitter page

---

doc/developers-meeting.rst

The old calendar was on @jhamman's UCAR account, which he no longer has access to!
xref https://github.com/pydata/xarray/issues/4001

Update calendar for developers meeting

---

xarray/core/groupby.py
xarray/tests/test_groupby.py

Fix regression with grouper object on an IndexVariable

---

doc/whats-new.rst

Add new what's new section

---

.pre-commit-config.yaml

We could even go down to `quarterly`

Reduce pre-commit update frequency to monthly from weekly.

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/core/merge.py
xarray/tests/test_dataset.py
xarray/tests/test_merge.py

Fix merge with compat=minimal (coord names)

---

requirements.txt

No longer needed, ref https://github.com/pydata/xarray/pull/8183#issuecomment-1721969842

Remove `requirements.txt`

---

xarray/tests/test_distributed.py

Skip flaky test

---

xarray/namedarray/core.py
xarray/tests/test_namedarray.py

Binding allows typing the .data property.

Bind T_DuckArray to NamedArray

---

doc/ecosystem.rst
doc/whats-new.rst

I was asked to open a PR to add our `xarray-regrid` extension to the ecosystem list (#8260), so here it is.

Add xarray-regrid to ecosystem.rst

---

.github/workflows/ci-additional.yaml

This seems to be fixed according to #6551.

Remove if condition to trigger mypy

---

xarray/tests/test_backends.py

Would be better to fix it, but in lieu of fixing, better to skip it

xfail flaky test

---

.github/labeler.yml

Update labeler.yml to add NamedArray

---

xarray/core/dataarray.py

Refine curvefit doctest

---

xarray/core/dataarray.py
xarray/core/dataset.py

This wasn't clear to me so I added some examples & a reference to `broadcast_like`

Add docs to `reindex_like` re broadcasting

---

doc/whats-new.rst

[skip-ci] dev whats-new

---

asv_bench/benchmarks/dataset_io.py

With more realistic array sizes maybe the improvements in #8339 should be noticeable.

Add better ASV test cases for open_dataset

---

.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml

xref #8448 
get back to green checks for now.

Pin mypy < 1.7

---

xarray/core/nputils.py

I was seeing an error in #8475

Fix mypy tests

---

doc/whats-new.rst

Sorry, forgot in the original PR

Add whatsnew for #8475

---

doc/whats-new.rst

[skip-ci] fix RTD docs build

---

.github/workflows/ci-additional.yaml
ci/requirements/bare-minimum.yml
ci/requirements/min-all-deps.yml
doc/whats-new.rst
pyproject.toml

Bump min deps.

---

xarray/conventions.py

By chance I saw that in #4700 the same code block was added twice. I think this can be removed.
cc @andersy005

_infer_dtype: remove duplicated code

---

doc/whats-new.rst
xarray/coding/cftimeindex.py
xarray/tests/test_cftimeindex.py
xarray/tests/test_formatting.py

Otherwise `da.indexes` and the html repr raise a `ValueError`. I first had `"<undefined>"` but I think `None` is better. cc @spencerkclark @keewis

fix and test empty CFTimeIndex

---

.pre-commit-config.yaml
pyproject.toml

Fix ruff config flagged by repo review

---

doc/whats-new.rst

Someone give this a thumbs up if it looks good

Release summary for release v2024.01.0

---

doc/getting-started-guide/installing.rst

Follow up to https://github.com/pydata/xarray/pull/8586

Update min deps in docs

---

ci/min_deps_check.py
ci/requirements/environment.yml

Currently getting a error without pyarraw in CI: https://github.com/pydata/xarray/actions/runs/7577666145/job/20693665924

Partially fix doctests

---

xarray/tests/test_cftime_offsets.py

https://github.com/pydata/xarray/pull/8636#issuecomment-1902775153

xfail a cftime test

---

xarray/core/weighted.py

Allows subtypes.
(I had this in my git stash, so commiting it...)

Use `T_DataArray` in `Weighted`

---

doc/internals/how-to-add-new-backend.rst

Minor change but if i can save someone else some debugging time then i figured it was worth the issue.

Fixed typo in custom backend registration documentation

---

doc/whats-new.rst

new whats-new section

---

xarray/tests/test_backends.py

This fixes the failure locally for me. 
cc @max-sixty

Fix NetCDF4 C version detection

---

ci/requirements/environment.yml
conftest.py

Closes #8732. Not the most elegant implementation but it's only temporary

Silence dask doctest warning

---

ci/requirements/environment-3.12.yml
ci/requirements/environment-windows-3.12.yml
ci/requirements/environment-windows.yml
ci/requirements/environment.yml

Remove fsspec exclusion from 2021

---

doc/conf.py
doc/whats-new.rst

release summary for 2024.02.0

---

doc/whats-new.rst
xarray/core/indexing.py
xarray/core/variable.py

introduce `.vindex` property for Explicitly Indexed Arrays

---

xarray/core/dataset.py

Update documentation for clarity

---

ci/requirements/environment-3.12.yml

xref https://github.com/pydata/xarray/actions/runs/8269168819/job/22623800305?pr=8777

Add `dask-expr` to environment-3.12.yml

---

ci/requirements/doc.yml

- #8827 follow up to fix https://readthedocs.org/projects/xray/builds/23743522/

[skip-ci] Add dask-expr dependency to doc.yml

---

ci/requirements/environment-windows-3.12.yml
ci/requirements/environment-windows.yml
xarray/tests/test_dataarray.py

Add dask-expr for windows envs

---

.github/workflows/upstream-dev-ci.yaml
ci/install-upstream-wheels.sh

[skip-ci] Fix upstream-dev env

---

xarray/core/dataset.py
xarray/tests/test_indexes.py

xref #8844
Closes https://github.com/xarray-contrib/flox/issues/342

pandas 3 MultiIndex fixes

---

doc/whats-new.rst

Should have been done as part of the last release https://github.com/pydata/xarray/releases/tag/v2024.03.0

New empty whatsnew entry

---

.github/workflows/hypothesis.yaml

Trigger hypothesis stateful tests nightly

---

.github/workflows/hypothesis.yaml

Update hypothesis action to always save the cache

---

xarray/core/indexing.py

A drive-by PR as I was trying to figure out how these functions works.

Add typing to some functions in indexing.py

---

ci/requirements/doc.yml

MAINT: use sphinxext-rediraffe conda install

---

doc/whats-new.rst

Responding to call-out at https://github.com/pydata/xarray/pull/9021 !

Add whatsnew entry for #8974

---

doc/user-guide/computation.rst

Clarify __matmul__ does xarray.dot

---

CITATION.cff

I didn't have an orcid when this was set up.

citation / orcid

---

.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml

Revert "Run tests on changes to root dotfiles (#9062)"
This reverts commit 1f3bc7e96ec0b0c32250ec3f8e7e8a2d19d9a306.
Revert "Trigger CI only if code files are modified. (#9006)"
This reverts commit 2ad98b132cf004d908a77c40a7dc7adbd792f668.

Always run code tests 

---

CITATION.cff

Add scottyhq to CITATION.cff

---

CITATION.cff

add Jessica to citation

---

CITATION.cff

Adds Matt Savoie to CITATION.cff

---

CITATION.cff

@owenlittlejohns, if you have an orcid feel free to open a new PR to add it.

add remaining core-dev citations

---

doc/whats-new.rst

release v2024.06.0

---

xarray/tests/test_missing.py

Consolidate some numbagg tests

---

doc/getting-started-guide/installing.rst

- ~[ ] Tests added~
- ~[ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`~
- ~[ ] New functions/methods are listed in `api.rst`~

DOC: fix minimum dependency versions in getting started guide

---

xarray/core/dataarray.py

Fix pirate arrgragation

---

.github/workflows/hypothesis.yaml

try to fix scheduled hypothesis test

---

doc/user-guide/duckarrays.rst

Fix typo in docs.
The world's smallest PR!

Remove duplicate word from docs

---

design_notes/flexible_indexes_notes.md
design_notes/grouper_objects.md
design_notes/named_array_design_doc.md
doc/user-guide/dask.rst
doc/user-guide/data-structures.rst
doc/user-guide/pandas.rst
doc/whats-new.rst
xarray/coding/cftime_offsets.py
xarray/core/dataset.py
xarray/core/datatree.py
xarray/core/datatree_ops.py
xarray/core/indexes.py
xarray/core/merge.py
xarray/core/variable.py
xarray/datatree_/docs/source/data-structures.rst
xarray/datatree_/docs/source/hierarchical-data.rst
xarray/plot/dataset_plot.py
xarray/plot/utils.py
xarray/tests/test_backends.py
xarray/tests/test_dask.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_plot.py
xarray/tests/test_variable.py

Fix typos across the code, doc and comments

---

asv_bench/benchmarks/datatree.py

Add ASV for datatree.from_dict

---

properties/test_index_manipulation.py

Stateful test: silence DeprecationWarning from drop_dims

---

xarray/core/datatree.py

Remove out of date comment on DataTree inheritance

---

doc/api.rst
doc/user-guide/hierarchical-data.rst
doc/whats-new.rst
xarray/__init__.py
xarray/core/datatree.py
xarray/core/datatree_mapping.py
xarray/core/datatree_ops.py
xarray/tests/test_datatree.py
xarray/tests/test_datatree_mapping.py

A simple find-replace taking `map_over_subtree` -> `map_over_datasets`

map_over_subtree -> map_over_datasets

---

doc/user-guide/io.rst

Fix error and missing code cell in io.rst

---

doc/conf.py

This was causing doc build failures.

fix zarr intersphinx

---

xarray/tests/test_backends.py

Change URL for pydap test

---

doc/whats-new.rst

(I can't push to `main` so have to do this)

New blank whatsnew after v2024.10.0

---

ci/requirements/environment.yml

MNT: use new conda-forge package pydap-server

---

.pep8speaks.yml

Get rid of the pep8speaks config file.

CI runs ruff instead of pep8speaks

---

xarray/tests/test_variable.py

This is a regression test for GH9822.

Test type annotations for Variable.get_axis_num

---

xarray/backends/zarr.py

Fix upstream Zarr compatibility

---

doc/whats-new.rst
xarray/coding/cftime_offsets.py
xarray/coding/cftimeindex.py
xarray/core/types.py
xarray/tests/test_cftimeindex.py

Add "unit"-parameter to date_range, enhance iso time parser to us

---

xarray/coding/times.py

cast type to PDDatetimeUnitOptions

---

doc/user-guide/terminology.rst

Remove unnecessary a article

---

doc/user-guide/pandas.rst

Fixed a typo in User Guide -> Working with pandas -> Dataset and Dataframe

Remove repetitive that (replace it with the)

---

xarray/core/groupby.py
xarray/core/resample.py
xarray/tests/test_groupby.py

This reverts commit a848044684ca8c8f90f91539f3d3f322f29377b7.
Opens #9647
Closes #9993
Looks like this wasn't properly tested somehow :/

Revert "Use flox for grouped first, last (#9986)"

---

doc/whats-new.rst

add new section in whats-new.rst

---

.github/workflows/ci-additional.yaml
xarray/core/groupby.py
xarray/core/indexing.py
xarray/core/resample.py

Seems easy locally; maybe too easy and something will break in CI...

Upgrade mypy to 1.15

---

.gitignore
xarray/backends/api.py
xarray/core/chunk.py
xarray/core/dataset.py
xarray/core/merge.py
xarray/core/utils.py

Continues on from https://github.com/pydata/xarray/pull/10039 with a set of small changes.
I have thoughts re the overall layout, will open an issue

Another reduction in the size of `dataset.py`

---

doc/api.rst
doc/whats-new.rst
xarray/core/datatree.py
xarray/tests/test_datatree.py

Prune data tree for Isomorphic operations

---

xarray/tests/test_array_api.py

Skip failing array api test.

---

doc/whats-new.rst
xarray/backends/api.py
xarray/tests/test_backends_datatree.py

Pass node path to tokenize in `open_datatree`

---

ci/requirements/environment-3.14.yml
ci/requirements/environment-windows-3.14.yml
ci/requirements/environment-windows.yml
ci/requirements/environment.yml

Get tests passing mypy given #10110

Pin pandas stubs

---

xarray/tests/test_distributed.py

Fix test_distributed::test_async

---

xarray/tests/test_backends.py

Update flaky pydap test

---

doc/whats-new.rst

Add dev whats-new

---

xarray/core/groupby.py
xarray/groupers.py
xarray/tests/test_groupby.py

Preserve label ordering for multi-variable GroupBy

---

xarray/computation/fit.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/tests/test_dataarray.py

Part of https://github.com/pydata/xarray/issues/10089

Move fit computation code to dedicated new file

---

xarray/compat/pdcompat.py
xarray/core/extension_array.py
xarray/tests/test_pandas_to_xarray.py

Vendor pandas to xarray conversion tests

---

doc/whats-new.rst

Quick bugfix release to get #10173 out

release 2025.03.1

---

doc/whats-new.rst

Add new whats-new section

---

doc/getting-started-guide/faq.rst

DOC: Remove mention of netcdf pypi package

---

doc/whats-new.rst
pyproject.toml

add `scipy-stubs` as extra `[types]` dependency

---

doc/whats-new.rst

Release notes for 2025.04.0

---

xarray/computation/rolling.py
xarray/tests/test_rolling.py

Fix rolling mean on bool arrays

---

doc/user-guide/ecosystem.rst

This is just a one-line change in `doc/user-guide/ecosystem.rst`. I'm quite certain the CI failure (labelled as "flaky") is unrelated to this change.
__Not applicable__

added movement to Xarray related projects

---

doc/user-guide/io.rst

I summarize the conclusions from the discussion in https://github.com/zarr-developers/zarr-python/issues/2706#issuecomment-2787552432, taking leaves from Tom and Ryan's books. I found that these docs didn't reflect the default state of Zarr and Xarray, and I hope this makes for less painful debugging for the next person.

Up-to-date instructions for reading & writing to Zarr with Xarray

---

doc/user-guide/ecosystem.rst

DOC: Add cf_xarray to ecosystem page

---

xarray/tests/arrays.py

Unassigned string statement

---

xarray/core/coordinates.py
xarray/structure/merge.py

Iterate the dictionary directly instead of calling `.keys()`

---

xarray/util/generate_ops.py

Appending to dictionary immediately following its definition

---

.pre-commit-config.yaml
xarray/core/duck_array_ops.py

Bump _ruff_ from 0.11 to 0.12 and address new issues.

Update pre-commit hook pre-commit

---

pyproject.toml
xarray/tests/test_backends.py

Enforce ruff/flake8-2020 rules (YTT)

---

xarray/plot/facetgrid.py

Keyword argument passed twice

---

doc/contribute/index.rst
doc/index.rst

Rename toplevel header from Contribute to Development

---

doc/whats-new.rst

Note that the release guide tells me to push this to `main`, but I can't, because we changes the repo branch permission rules since that guide was written.

New whatsnew section

---

.pre-commit-config.yaml

Changes
```
ruff (legacy alias)......................................................Passed
```
into:
```
ruff check...............................................................Passed
```

Update pre-commit ruff legacy alias

---

xarray/core/dataset.py

As per title. There are many more and would be great to convert more but I don't have time right now and this is the one I used in my code...

drop_vars: use emit_user_level_warning

---

.github/workflows/hypothesis.yaml
.github/workflows/upstream-dev-ci.yaml

CI: update actions location

---

doc/conf.py

This will hopefully get RTD to pass.

change the type of `ogp_custom_meta_tags` to `tuple`

---

doc/whats-new.rst

empty whats new

---

pyproject.toml

responsibel for 1400 / 1440 warnings; and don't think there's much we can do about them

Silence Zarr v3 warnings

---

.github/ISSUE_TEMPLATE/bugreport.yml

Follow up to https://github.com/pydata/xarray/pull/10746
You can try it out here: https://github.com/ianhi/git-expt/issues/new?template=bug3.yml
cc @max-sixty @gronniger

cleanup bug report template

---

.readthedocs.yaml

Enable htmlzip documentation build

---

HOW_TO_RELEASE.md
doc/whats-new.rst

blank release notes for 2025.10.1

---

HOW_TO_RELEASE.md
doc/whats-new.rst

Blank whats new for 2025.10.2
