pydata/xarray

doc/whats-new.rst
xarray/core/concat.py
xarray/core/variable.py
xarray/tests/test_concat.py
xarray/tests/test_variable.py

concat keeps attrs from first variable.

---

doc/whats-new.rst
xarray/core/combine.py
xarray/tests/test_combine.py

allow incomplete hypercubes in combine_by_coords

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_dataset.py

add multiindex level name checking to .rename()

---

doc/api.rst

Typo in Universal Functions section

---

xarray/core/parallel.py

This PR adds an example to the `xr.map_blocks()` docs. 
It is modeled off of @rabernat's example here: https://nbviewer.jupyter.org/gist/rabernat/30e7b747f0e3583b5b776e4093266114 and was encouraged to be opened via the gitter.
It might be slightly large for an example, but I think it shows an applied case to use this in and clears up some common pitfalls (e.g. how to pass args/kwargs).

Add map_blocks example to docs

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_dataset.py

Is `ValueError` the appropriate error here? I'm also not sure about the addition to the documentation of `rename_dims`.

raise an error when renaming dimensions to existing names

---

doc/whats-new.rst

This simply adds the `map_blocks` example from https://github.com/pydata/xarray/pull/3667 to the changelog.

Add map_blocks example to whats-new

---

doc/data-structures.rst
doc/howdoi.rst

Closes #3678 
I don't have the full build environment: someone who does will have to make sure that I got the sphinx formatting right.

How do I add a new variable to dataset.

---

xarray/core/dataset.py

The return type in the docstring should be a Dataset, not a DataArray.

Fix docstring for combine_first: returns a Dataset

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_merge.py

ds.merge(da) bugfix

---

xarray/tests/test_coding_times.py

This fixes `test_cf_datetime_nan` for upcoming releases of pandas.  See failure class (2) reported in #3673.

Fix test_cf_datetime_nan under pandas master

---

xarray/core/dataset.py

Hopefully fixes the type checking error introduced in #3677, as [pointed out](https://github.com/pydata/xarray/pull/3618#issuecomment-573678101) by @kmuehlbauer.

Fix mypy type checking tests failure in ds.merge

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_dataset.py

This fixes a regression in the deprecated `drop` method.

allow passing any iterable to drop when dropping variables

---

doc/whats-new.rst
xarray/coding/variables.py
xarray/tests/test_coding.py

This uses `encoding['dtype']` over `data.dtype` when possible within `CFMaskCoder.encode` to decide what type to cast `encoding['missing_value']` or `encoding['_FillValue']` to; this is one way to fix #3624.  Another possible way would be to ensure the times have the proper `dtype` coming from `CFDatetimeCoder.encode`.  I'm not sure what is the preferred solution.
cc: @andersy005, @spencerahill

Use encoding['dtype'] over data.dtype when possible within CFMaskCoder.encode

---

xarray/tests/test_units.py

As promised in #3493, this adds integration tests for units. I'm doing this now rather than later since I encountered a few cases in #3643 where a increased test coverage for variables would have been helpful.

Tests for variables with units

---

ci/requirements/py36-min-all-deps.yml
doc/whats-new.rst
xarray/core/computation.py
xarray/tests/test_backends.py
xarray/tests/test_computation.py
xarray/tests/test_sparse.py

This makes `vectorize=True` works with functions that add new dimensions.
cc @smartass101 @jbusecke

apply_ufunc: Add meta kwarg + bump dask to 2.2

---

doc/whats-new.rst
xarray/plot/plot.py
xarray/plot/utils.py
xarray/tests/test_plot.py

Currently 1D plot functions only allow binned coordinates (of `pd.Interval` type, produced with `groupby_bins`) on the y-axis (issue #3571). This pull request enables plotting intervals on either or both axes of 1D plots.

Allow binned coordinates on 1D plots y-axis.

---

setup.cfg
xarray/__init__.py
xarray/backends/api.py
xarray/backends/cfgrib_.py
xarray/backends/h5netcdf_.py
xarray/backends/netCDF4_.py
xarray/backends/netcdf3.py
xarray/backends/pseudonetcdf_.py
xarray/backends/pydap_.py
xarray/backends/pynio_.py
xarray/backends/rasterio_.py
xarray/backends/scipy_.py
xarray/backends/zarr.py

Follow-up on https://github.com/pydata/xarray/pull/3714
- Fix regression in mypy if pip creates a zipped archive
- Avoid breakage in the extremely unlikely event that setuptools is not installed
- Guarantee ``xarray.__version__`` to be always PEP440-compatible. This prevents a breakage if you run pandas without xarray installed and with the xarray sources folder in PYTHONPATH.
- Apply isort to ``xarray.__init__``

setuptools-scm and isort tweaks

---

doc/contributing.rst

The links to the main Sphinx page and the intro to reStructuredText were broken since the pages have been moved from sphinx.pocoo.org to sphinx-doc.org. This PR provides the updated links.

Fix Sphinx links on contributing doc page

---

requirements.txt

Fix https://github.com/pydata/xarray/pull/3714#issuecomment-578626605
@shoyer I have no way of testing if this fixes github - please see by yourself after merging to master.

setuptools-scm (3)

---

doc/contributing.rst

I don't think these should be needed any longer

remove PR pre-black instructions

---

ci/azure/install.yml
ci/requirements/py36-bare-minimum.yml
ci/requirements/py36-min-nep18.yml

Avoid unsafe use of pip

---

doc/api-hidden.rst
doc/dask.rst

The recent update of `pandas` makes our documentation raise warnings. This disables building documentation pages for the index attributes removed / renamed by `pandas` and ignores a warning raised by `dask.dataframe` (this should be fixed there, instead).
I didn't check for new attributes / broken links on the object pages (e.g. the page for `CFTimeIndex`), I'll do that in a new PR.

Documentation fixes

---

.binder/environment.yml
.pre-commit-config.yaml
asv_bench/asv.conf.json
azure-pipelines.yml
ci/requirements/doc.yml
ci/requirements/py36.yml
ci/requirements/py37-windows.yml
ci/requirements/py38-windows.yml
ci/requirements/py38.yml
readthedocs.yml

- Run full-fat suite of tests for Python 3.8
- Move asv, MacOSX tests, readthedocs, binder, and more to Python 3.8
- Test windows against latest numpy version
- Windows tests remain on Python 3.7 because of a couple of Python 3.8 tests that fail exclusively in CI. Will investigate later.

Python 3.8 CI

---

doc/installing.rst
doc/pandas.rst
doc/whats-new.rst
xarray/plot/utils.py
xarray/tests/__init__.py
xarray/tests/test_plot.py

remove seaborn.apionly compatibility

---

doc/whats-new.rst
xarray/tests/test_backends.py

Avoid running test_open_mfdataset_list_attr without dask

---

xarray/core/formatting.py
xarray/tests/test_formatting.py

This allows to have `ndarray` instances in attributes, which is the case for the dataset from `xarray/tests/data/example.uamiv`. It won't fix the cause for the error of #3711, though, because that seems to non-deterministic.

allow formatting the diff of ndarray attributes

---

doc/whats-new.rst
xarray/core/dask_array_compat.py
xarray/core/duck_array_ops.py

This makes sure we use `dask_array_type` instead of `dask_array.Array` for `isinstance` calls.

always use dask_array_type for isinstance calls

---

doc/whats-new.rst
xarray/backends/h5netcdf_.py

This adds support for the new `phony_dims` keyword for the h5netcdf backend which is available from `h5netcdf` version 0.8.0.

Add new h5netcdf backend phony_dims kwarg

---

doc/whats-new.rst
xarray/core/concat.py
xarray/tests/test_combine.py
xarray/tests/test_concat.py

```
da1 = xr.DataArray([1, 2, 3], dims="x", coords={"x": [1, 2, 3], "y": 1})
da2 = xr.DataArray([4, 5, 6], dims="x", coords={"x": [4, 5, 6]})
xr.concat([da1, da2], dim="x")
```
This use case is quite common since you can get `da1` from something like `bigger_da1.sel(y=1)`
On master this raises an uninformative  `KeyError` because `'y'` is not present in all datasets. This is because `coords="different"` by default which means that we are checking for equality. However `coords='different'`(and the equality check) is meaningless when the variable is only present in one of the objects to be concatenated.
This PR skips equality checking when a variable is only present in one dataset and raises a nicer error message when it is present in more than one but not all datasets.

concat now handles non-dim coordinates only present in one dataset

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

Fix swap_dims() index names (issue #3748)

---

xarray/tests/test_cftimeindex.py
xarray/tests/test_interp.py

@max-sixty @shoyer -- I agree we've let these linger far too long.  This should hopefully get things back to being green.

xfail tests due to #3751

---

doc/whats-new.rst
xarray/core/duck_array_ops.py
xarray/tests/test_units.py

Since it does not make sense to try to wrap `datetime` objects in `pint`, I'm removing those tests. They still exposed a bug in the compatibility code of `isnat`: if `dask` is installed, the code would always use `pd.isnull`.

remove datetime tests with pint

---

doc/whats-new.rst
xarray/core/common.py
xarray/tests/test_groupby.py

From the comment:
While we don't generally check the type of every arg, passing
multiple dimensions as multiple arguments is common enough, and the
consequences hidden enough (strings evaluate as true) to warrant
checking here.
A future version could make squeeze kwarg only, but would face
backward-compat issues.

Raise on multiple string args to groupby

---

doc/weather-climate.rst
doc/whats-new.rst
xarray/coding/cftimeindex.py
xarray/core/accessor_dt.py
xarray/tests/test_accessor_dt.py
xarray/tests/test_cftimeindex.py

This is particularly useful for removing microsecond noise that can sometimes be added from decoding times via `cftime.num2date`, though also applies more generally.  The methods used here for rounding dates in the integer domain are copied from pandas.
On a somewhat more internal note, this adds an `asi8` property to `CFTimeIndex`, which encodes the dates as integer values representing microseconds since 1970-01-01; this encoding is made exact via the `exact_cftime_datetime_difference` function.  It's possible this could be useful in other contexts.
Some examples:
```
In [1]: import xarray as xr
In [2]: times = xr.cftime_range("2000", periods=5, freq="17D")
In [3]: time = xr.DataArray(times, dims=["time"], name="time")
In [4]: time.dt.floor("11D")
Out[4]:
<xarray.DataArray 'floor' (time: …
```

Enable pandas-style rounding of cftime.datetime objects

---

doc/whats-new.rst
xarray/core/options.py
xarray/tests/test_options.py

Turn on html repr by default

---

doc/whats-new.rst
xarray/core/common.py
xarray/core/rolling.py
xarray/core/variable.py
xarray/tests/test_dataset.py
xarray/tests/test_variable.py

I also noticed missing attributes when attempting certain operations, so I have created this pull request to attempt a fix. I modified code in `DataWithCoords.coarsen()` to try applying the same logic used for other methods since #2482 was successfully merged.
I added two new tests that adapt the bug reported by @jejjohnson. I believe they should pass when this is fixed. One uses `Dataset.coarsen()` and the other uses `Variable.coarsen`. Both tests currently fail.
xarray/tests/test_dataset.py::TestDataset::test_coarsen_keep_attrs 
- fails because my attempted fix does not retain the attributes.
xarray/tests/test_variable.py::TestVariable::test_coarsen_keep_attrs
- also fails, but unexpectedly this seems to be because the attributes are _not_ removed by default, or even when explicitly …

Coarsen keep attrs 3376

---

doc/examples.rst
doc/io.rst

DOC: Add rioxarray and other external examples

---

xarray/core/dataarray.py
xarray/core/dataset.py

This surprised me so I thought worth calling out. 
Ref https://github.com/pydata/xarray/pull/3800

Add note on diff's n differing from pandas

---

azure-pipelines.yml
doc/whats-new.rst

update macos image

---

doc/whats-new.rst
xarray/core/common.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

The first one; I'll await feedback before adding to docs or doing other methods

Allow `where` to receive a callable

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/groupby.py
xarray/core/variable.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_variable.py

Implement skipna kwarg in xr.quantile

---

doc/related-projects.rst

Following discussion in https://github.com/pydata/xarray/issues/3771 this PR is to add [nxarray](https://github.com/nxarray/nxarray) package to the list of related projects.

Add nxarray to related-projects.rst

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/tests/test_dataarray.py

remove panel conversion

---

doc/whats-new.rst
xarray/tests/test_backends.py

un-xfail tests that append to netCDF files with scipy

---

doc/installing.rst
doc/whats-new.rst

update installation instruction

---

doc/related-projects.rst

We've recently released [Xpublish](https://xpublish.readthedocs.io/en/latest/).  This PR adds the project to the _related-projects` page in the Xarray documentation. To find out more about Xpublish, check out the [docs](https://xpublish.readthedocs.io/en/latest/) or the [release announcement blogpost](https://medium.com/pangeo/xpublish-ff788f900bbf).

Add xpublish to related projects

---

conftest.py
doc/contributing.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/rolling.py

Starting to get some fixes in. 
It's going to be a long journey though. I think maybe we whitelist some files and move gradually through before whitelisting the whole library.

Doctests fixes

---

doc/whats-new.rst
xarray/core/alignment.py
xarray/tests/test_concat.py

Fix alignment with join="override" when some dims are unindexed

---

doc/whats-new.rst
xarray/core/indexes.py
xarray/tests/test_dataset.py

@fujiisoup Would you mind reviewing this PR?
The bug was actually straightforward.

Fix multi-index with categorical values.

---

doc/whats-new.rst
xarray/core/groupby.py
xarray/tests/test_groupby.py

When a a Dataset or DataArray is recombined after a groupby operation, xarray tries to restore the original coordinate. This causes problems if the group operation changes the size of the groups along the grouped dimension (e.g. some filtering operation that removes entries).
Restoring the original coordinate appears to be necessary only if it was squeezed from the groups, otherwise it is already restored by concatenation of the groups. This fix: 
1. avoids reordering if the size of the dimension has changed;
2. avoids restoring a coordinate that has not been squeezed out.

Fix recombination in groupby when changing size along the grouped dimension

---

xarray/backends/api.py
xarray/tests/test_accessor_dt.py
xarray/tests/test_backends.py
xarray/tests/test_concat.py
xarray/tests/test_dask.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_duck_array_ops.py
xarray/tests/test_groupby.py
xarray/tests/test_plot.py

what's left is mostly a lot of `UnitStrippedWarnings`. cc @keewis

Fix some warnings

---

doc/whats-new.rst
xarray/core/computation.py
xarray/core/dataset.py

The `x, y ` doesn't carry over to the online docs: http://xarray.pydata.org/en/stable/generated/xarray.where.html#xarray.where, lmk if there's a hack for representing that in a better way

Improve where docstring

---

doc/reshaping.rst
doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

Allow ellipsis to be used in stack

---

doc/whats-new.rst
xarray/core/formatting_html.py
xarray/tests/test_formatting_html.py

Fix html repr on non-str keys

---

azure-pipelines.yml

I think fine to pause the macos build, given the relative cost of fixing vs chance of finding a bug only in macos

remove macos build while waiting for libwebp fix

---

doc/whats-new.rst
xarray/core/coordinates.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

@shoyer do you think this is the right thing to do?

Delete associated indexes when deleting coordinate variables.

---

.github/ISSUE_TEMPLATE/bug_report.md

This was causing new lines issues when reports were pasted without added line breaks.

add spacing in the versions section of the issue report

---

ci/azure/install.yml
xarray/coding/cftimeindex.py
xarray/tests/test_cftimeindex.py
xarray/tests/test_interp.py

Re-enable tests xfailed in #3808 and fix new CFTimeIndex failures due to upstream changes

---

doc/plotting.rst
doc/whats-new.rst
xarray/core/variable.py
xarray/tests/test_accessor_dt.py
xarray/tests/test_dask.py
xarray/tests/test_variable.py

Raise error when assigning to IndexVariable.values & IndexVariable.data

---

doc/whats-new.rst

Reword the `whats-new.rst` entry for #3611 and #3706 so we can release without claiming full unit support.

reword the whats-new entry for unit support

---

doc/pandas.rst

As per https://github.com/pydata/xarray/issues/3869#issuecomment-602752633

update panel documentation

---

xarray/tests/test_backends.py
xarray/tests/test_cftime_offsets.py

xfail test_uamiv_format_write

---

doc/whats-new.rst
xarray/core/combine.py
xarray/core/concat.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/merge.py
xarray/core/utils.py
xarray/tests/test_combine.py
xarray/tests/test_concat.py
xarray/tests/test_dataarray.py
xarray/tests/test_merge.py
xarray/tests/test_utils.py

`combine_attrs` argument for `merge()`, `concat()`, `combine_by_coords()` and `combine_nested()` controls what attributes the result is given. Defaults maintain the current behaviour. Possible values (named following `compat` arguments) are:
- 'drop': empty attrs on returned Dataset.
- 'identical': all attrs must be the same on every object.
- 'no_conflicts': attrs from all objects are combined, any that have the same name must also have the same value.
- 'override': skip comparing and copy attrs from the first dataset to the result.

Control attrs of result in `merge()`, `concat()`, `combine_by_coords()` and `combine_nested()`

---

xarray/core/utils.py
xarray/tests/test_utils.py

`xarray` does not use `OrderedDicts` any more, so name did not make sense. As suggested here https://github.com/pydata/xarray/pull/3877#discussion_r396620551.

Rename ordered_dict_intersection -> compat_dict_intersection

---

doc/whats-new.rst
xarray/plot/plot.py
xarray/plot/utils.py
xarray/tests/test_plot.py

Mixing the two is deprecated in Matplotlib 3.1, and breaks the doc build
if warnings are set to errors (which they are in new IPython sphinx
extensions.)

Use drawstyle instead of linestyle in plot.step.

---

xarray/backends/zarr.py
xarray/tests/test_backends.py

expose a few zarr backend functions as semi-public api

---

doc/whats-new.rst
xarray/core/formatting.py
xarray/tests/test_formatting.py

This also more strictly limits the length of array reprs where the max_width is small, such that it doesn't always display the first and last item. Lmk if that could have a adverse impact anywhere.

Limit repr of arrays containing long strings

---

xarray/tests/test_cftime_offsets.py

With Unidata/cftime#163 merged, this test, [which we temporarily xfailed in #3885](https://github.com/pydata/xarray/pull/3885#issuecomment-603406294), should pass with cftime master.

Un-xfail test_dayofyear_after_cftime_range

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py

As per #1040, don't document the `dim` parameter of `Dataset.diff` and `DataArray.diff` as optional.

update the docstring of diff

---

doc/api.rst
doc/whats-new.rst
xarray/core/computation.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/duck_array_ops.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

This implements `idxmax` and `idxmin` functions similar to thier pandas equivalents.
This is my first time contributing to the project so I am not certain the structure or approach is the best.  Please let me know if there is a better way to implement this.
This also includes two other changes.
First, it drops some code for backwards-compatibility with numpy 1.12, which isn't supported.  This code was hiding an error I needed to have access to in order to get the function working.
Second, it adds an option to `Dataset.map` to let you map `DataArray` methods by name.  I used this to implement the `Dataset` versions of `idxmax` and `idxmin`.

Implement idxmax and idxmin functions

---

azure-pipelines.yml

the packaging issue has been closed, so this tries to reactivate the MacOS CI.

reactivate the macos CI

---

doc/whats-new.rst
xarray/core/groupby.py
xarray/tests/test_dataarray.py

I've added a check within `groupby.__init__` for monotonicity of the coords, which makes my test pass, but it causes three existing tests to fail.  Getting the logic right that properly distinguishes among these different cases is escaping me for now, but it does seem like this call to `unique_value_groups` within `groupby.__init__` is where the re-sorting is occurring.  Feedback welcome.  TIA!

Fix for stack+groupby+apply w/ non-increasing coord

---

xarray/tests/test_backends.py

The warning we want to avoid in these tests is:
```
SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range
dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)
```
Other warnings could occur, but shouldn't cause the tests to fail.  This modifies these tests to only fail if a warning with this message occurs.
The warning that is occurring seems to be stemming from [within the netcdf4-python library](https://github.com/Unidata/netcdf4-python/blob/06e58422204cc77946fa21effd31ffb9421bd139/netCDF4/_netCDF4.pyx#L1416-L1419):
```
DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
attributes = {k: var.getncattr(k) for k in var.ncattrs()}
```

Only fail certain use_cftime backend tests if a specific warning occurs

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/utils.py
xarray/core/variable.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_variable.py

Note: only added to `DataArray.isel()` and `Variable.isel()`. A `Dataset` should include all dimensions, so presumably it should always be an error to pass a non-existent dimension when slicing a `Dataset`?

Add missing_dims argument allowing isel() to ignore missing dimensions

---

doc/whats-new.rst
xarray/plot/utils.py
xarray/tests/test_plot.py

facetgrid: fix case when vmin == vmax

---

doc/whats-new.rst
xarray/plot/plot.py
xarray/plot/utils.py
xarray/tests/test_plot.py

as @dcherian said:
> matplotlib can plot `bool` values so we should add that to the check in `_ensure_plottable`.

Allow plotting bool data

---

doc/whats-new.rst
xarray/plot/plot.py
xarray/tests/test_plot.py

Simple fix for #3933 - just required transposing y data before passing to matplotlib.

Bugfix plot 2d coords transpose

---

doc/whats-new.rst
xarray/plot/utils.py
xarray/tests/test_plot.py

Use divergent colormap if lowest and highest level span 0

---

doc/groupby.rst

`results.append(group - alt.sel(x=label))` must be changed to:
`results.append(group - alt.sel(letters=label))`

Modify code in "Grouped arithmetic"

---

doc/roadmap.rst
doc/whats-new.rst

Names listed in order of date added.

Updated list of core developers

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/core/indexes.py
xarray/tests/test_dataarray.py

It looks 
`dataframe.set_index(index).index == index` is not always true.
Added a workaround for this...

Fix wrong order of coordinate converted from pd.series with MultiIndex

---

xarray/plot/utils.py

If you think this is relevant, I'll go ahead and start working on the items above, even though I'm not sure new tests are needed.

implement a more threadsafe call to colorbar

---

doc/whats-new.rst
xarray/core/common.py

New coords to existing dim (doc)

---

xarray/core/common.py

Related to #3958 an empty is probably missing for the [example section](http://xarray.pydata.org/en/latest/generated/xarray.Dataset.assign_coords.html#xarray.Dataset.assign_coords)

Empty line missing for DataArray.assign_coords doc

---

doc/whats-new.rst
xarray/backends/rasterio_.py

When a `vrt` is opened, a deprecation warning will be shown:
```python
/home/taher/.local/apps/miniconda/envs/hydrodata/lib/python3.8/site-packages/xarray/backends/rasterio_.py:241: RasterioDeprecationWarning: dst_nodata will be removed in 1.1, use nodata
riods = WarpedVRT(riods, **vrt_params)
/home/taher/.local/apps/miniconda/envs/hydrodata/lib/python3.8/site-packages/xarray/backends/rasterio_.py:35: RasterioDeprecationWarning: dst_nodata will be removed in 1.1, use nodata
riods = WarpedVRT(riods, **vrt_params)
/home/taher/.local/apps/miniconda/envs/hydrodata/lib/python3.8/site-packages/xarray/backends/rasterio_.py:122: RasterioDeprecationWarning: dst_nodata will be removed in 1.1, use nodata
riods = WarpedVRT(riods, **self.vrt_params)
```
This change can be confirmed in `rasterio`'s …

RasterioDeprecationWarning

---

doc/whats-new.rst
xarray/plot/facetgrid.py
xarray/plot/plot.py
xarray/plot/utils.py
xarray/tests/test_plot.py

facetgrid: Ensure that colormap params are only determined once.

---

.github/ISSUE_TEMPLATE/bug_report.md

Using backticks does not work in the summary, so we need to use html tags (i.e. `<tt>xr.show_versions()</tt>`) instead.
A demo:
<details><summary>Output of <tt>xr.show_versions()</tt></summary>
```
...
```
</details>

use preformatted text for the code in the issue template

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/missing.py
xarray/tests/test_missing.py

`dataarray.interpolate_na` was dropping attrs because even though the internal `apply_ufunc` call was being passed `keep_attrs=True`, the order of arguments `index, da` to `apply_ufunc` meant that it was trying to keep only the non-existent attrs from the first argument. I just swapped them round, and added a globally-aware `keep_attrs` kwarg.

keep attrs in interpolate_na

---

doc/interpolation.rst
doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py

This corrects an error in the documentation of using `interp` to extrapolate. Apparently the argument `fill_value` changed at some point and now uses `None` instead of `'extrapolate'` to indicate that extrapolation should be done.

Add multi-dimensional extrapolation example and mention different behavior of kwargs in interp

---

doc/whats-new.rst
xarray/tests/test_distributed.py

Fix distributed tests on upstream-dev

---

doc/whats-new.rst
xarray/backends/zarr.py
xarray/tests/test_backends.py

Make some zarr error messages more helpful.

Better chunking error messages for zarr backend

---

.deepsource.toml
xarray/convert.py
xarray/core/computation.py
xarray/core/formatting.py
xarray/core/groupby.py
xarray/plot/plot.py

- Fix dangerous default argument
- Remove unnecessary comprehension
---
Find the other issues found here - [https://deepsource.io/gh/pnijhara/xarray/issues/?category=all](https://deepsource.io/gh/pnijhara/xarray/issues/?category=all)
This PR also adds `.deepsource.toml` configuration file to run DeepSource analysis on the repo with. Upon enabling DeepSource, the analysis will run on every PR and commit to detect 560+ types of issues in the changes — including bug risks, anti-patterns, security vulnerabilities, etc.
To enable DeepSource analysis after merging this PR, please follow these steps:
1. [Signup](https://deepsource.io/signup/) on DeepSource with your GitHub account and grant access to this repo.
2. Activate analysis on this repo [here](http://deepsource.io/gh/pydata/xarray)
You …

Fix some code quality and bug-risk issues

---

doc/whats-new.rst
xarray/coding/times.py
xarray/tests/test_coding_times.py

By default, xarray tries to decode times with pandas and falls back to
cftime. This fixes the exception handler to fallback properly in the
cases an unhandled abbreviated unit is passed in.
An additional item here would be to add support for msec, etc. to xarray's handling, but I wasn't sure the best way to handle that. I'm happy just if things properly fall back to cftime.

Fix handling of abbreviated units like msec

---

doc/whats-new.rst
xarray/core/formatting_html.py
xarray/tests/test_formatting_html.py
xarray/tests/test_variable.py

Thanks for all the good work guys :)

ensure Variable._repr_html_ works

---

doc/combining.rst
doc/computation.rst
doc/contributing.rst
doc/dask.rst
doc/data-structures.rst
doc/faq.rst
doc/groupby.rst
doc/indexing.rst
doc/internals.rst
doc/interpolation.rst
doc/io.rst
doc/pandas.rst
doc/plotting.rst
doc/quick-overview.rst
doc/reshaping.rst
doc/time-series.rst
doc/weather-climate.rst
doc/whats-new.rst
xarray/core/common.py
xarray/core/dataarray.py
xarray/core/dataset.py

This applies `black` to the code in the documentation using [`blackdoc`](https://github.com/keewis/blackdoc). The tool itself is not stable or released yet, but this demonstrate the upcoming support for `rst` code blocks, including the ipython sphinx directive. There are a few issues with the latter, e.g. the semi-colon to suppress output will be removed by `black`. In a few cases this changes the other outputs, mostly plots. I think we might fix/work around that by moving the line decorator to the last line that should be plotted (which is what I did), but we could also use the ipython syntax with cell decorators:
```python
@savefig ...
In [1]: # code
...: # with multiple lines
```
Also, while I checked the changes manually, please don't take my word for it: I'm really not sure I didn't …

Apply blackdoc to the documentation

---

doc/whats-new.rst
xarray/core/groupby.py
xarray/core/pdcompat.py
xarray/core/variable.py

chore: Remove unnecessary comprehension

---

doc/whats-new.rst
xarray/backends/api.py
xarray/backends/zarr.py
xarray/core/dataset.py
xarray/tests/test_backends.py

This is nice for consistency with `to_netcdf`. It should be useful for cases where users want to update values in existing Zarr datasets.

Support overriding existing variables in to_zarr() without appending

---

doc/plotting.rst

Fixes https://github.com/pydata/xarray/issues/4030
It looks like this is triggered by the new cartopy version now being installed
on RTD (version 0.17.0 -> 0.18.0).
Long term we should fix this, but for now it's better just to disable the
warning.
Here's the message from RTD:
```
Exception occurred:
File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/latest/lib/python3.8/site-packages/IPython/sphinxext/ipython_directive.py", line 586, in process_input
raise RuntimeError('Non Expected warning in `{}` line {}'.format(filename, lineno))
RuntimeError: Non Expected warning in `/home/docs/checkouts/readthedocs.org/user_builds/xray/checkouts/latest/doc/plotting.rst` line 732
The full traceback has been saved in /tmp/sphinx-err-qav6jjmm.log, if you want to report the issue to the …
```

Allow warning with cartopy in docs plotting build

---

xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

We don't support creating a Panel with to_pandas() with *any* version of
pandas at present, so this test was previous broken if pandas < 0.25 was
installed.

Remove broken test for Panel with to_pandas()

---

doc/whats-new.rst
xarray/core/merge.py
xarray/util/print_versions.py

---
It is slower to call e.g. `list()` than using the empty literal, because the name list must be looked up in the global scope in case it has been rebound. Same for the other two types like `dict()` and `tuple()`.

Use literal syntax instead of function calls to create the data structure

---

doc/whats-new.rst
xarray/static/css/style.css

Now it looks like
I'm pretty sure that this workaround is not the best (maybe the second worst), as it only supports the dark mode of vscode but not other environments.
I couldn't find a good way to make a workaround for the general dark-mode.
Any advice is welcome.

support darkmode

---

xarray/backends/common.py
xarray/backends/memory.py

With its recent release, `pycodestyle` introduced `E741` which flags parameters named `l` (lowercase `L`) since that tends to be confused with `1` (the digit) or maybe even `(` or `)` depending on the font. The names actually don't matter in both cases since the first method is abstract and the second method is a dummy.

fix the failing flake8 CI

---

doc/whats-new.rst
xarray/backends/api.py
xarray/backends/zarr.py
xarray/conventions.py
xarray/tests/test_conventions.py

Releated to ticket #1621. Add `decode_timedelta` kwargs in open_dataset, `xr.open_datarray`, `xr.open_zarr`, `xr.decode_cf`. If not passed explicitly the behaviour is not changed.

#1621 optional decode timedelta

---

ci/requirements/doc.yml
doc/conf.py

The reason for those fragments is that `napoleon` and `numpydoc` somehow conflict with each other. From a quick glance I couldn't find anything that breaks without `numpydoc`, but I might be missing something.
For reference, here's the new [API page](https://xarray-keewis.readthedocs.io/en/fix-signature-escapes/api.html).

remove the backslash escapes and typehint fragments in the API docs

---

doc/internals.rst
doc/io.rst

When we implemented the Zarr backend, we made some _ad hoc_ choices about how to encode NetCDF data in Zarr. At this stage, it would be useful to explicitly document this encoding. I decided to put it on the "Xarray Internals" page, but I'm open to moving if folks feel it fits better elsewhere.
cc @jeffdlb, @WardF, @DennisHeimbigner

Document Xarray zarr encoding conventions

---

doc/whats-new.rst
xarray/backends/netcdf3.py
xarray/tests/test_backends.py

Add NetCDF3 dtype coercion for unsigned integer types

---

doc/whats-new.rst
xarray/core/missing.py
xarray/testing.py
xarray/tests/test_interp.py

Now n-dimensional interp works sequentially if possible.
It may speed up some cases.

Improve interp performance

---

xarray/core/computation.py
xarray/tests/test_dask.py

Fixing typo in recent PR #4089

Corrcov typo fix

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_dataarray.py

~Doesn't have a proper test. Need some help here~. cc @bnaul

Fix conversion of multiindexed pandas objects to sparse xarray objects

---

doc/related-projects.rst

We have released [xarray-custom](https://github.com/astropenguin/xarray-custom), a Python package which helps to create custom DataArray in the same manner as [the Python's native dataclass](https://docs.python.org/3/library/dataclasses.html). This PR adds the project to the "Extend xarray capabilities" section in `doc/related-projects.rst`. It would be appreciated if you could merge it (if this PR fits the purpose of the xarray documentation).

Add xarray-custom to related projects

---

doc/whats-new.rst
xarray/core/groupby.py
xarray/tests/test_groupby.py

Ran across the issue describe in #158 the other day and decided to implement Stephan's suggestion of assigning a default name of 'group' to the DataArray passed to groupby if name=None. Previously when name=None on the DataArray a ValueError: `group` must have a name was raised. 
This is my first pull request so let me know if I missed anything. Thanks!

Assign default group name in groupby if name=None (#158)

---

doc/conf.py

With the recent documentation changes, `numpy` also changed the location of the intersphinx inventory (`objects.inv`). This makes sure we use the new location.

use numpy's new intersphinx url

---

doc/whats-new.rst
xarray/core/computation.py
xarray/core/dataset.py
xarray/core/missing.py
xarray/tests/test_missing.py

Pull #3733 added `da.polyfit` and `xr.polyval` and is using `xr.core.missing.get_clean_interp_index` in order to get the fitting coordinate. However, this method is stricter than what polyfit needs: as in `numpy.polyfit`, non-unique and non-monotonic indexes are acceptable. This PR adds a `strict` keyword argument to `get_clean_interp_index` so we can skip the uniqueness and monotony tests.
`ds.polyfit` and  `xr.polyval` were modified to use that keyword. I only added tests for  `get_clean_interp_index`, could add more for `polyfit` if requested.

Allow non-unique and non-monotonic coordinates in get_clean_interp_index and polyfit

---

doc/whats-new.rst
xarray/backends/rasterio_.py
xarray/tests/test_backends.py

Fix bug when passing a `WarpedVRT` object, for which `src_crs` was explicitly specified, to `open_raster()`.
`open_rastario()` creates a new `WarpedVRT` object by getting init params from the original `vrt`. This PR adds some of those params (e.g. `src_crs`) which were missing.

Fix open_rasterio() for WarpedVRT with specified src_crs

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

Modifies the code in `reset_index` to keep attributes when converting an indexing coordinate to non indexing coordinate. I have added tests for single index for both dataarray and dataset. Not sure if both are needed as they end up calling the same base function.
Regarding multiindex, I think it is not possible to keep the metadata as it is removed when creating the multiindex/stacking.

keep attrs in reset_index

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/parallel.py
xarray/tests/test_dask.py

It parses `args` and breaks any xarray objects into appropriate blocks before passing them on to the user function.
e.g.
```python
da1 = xr.DataArray(
np.ones((10, 20)), dims=["x", "y"], coords={"x": np.arange(10), "y": np.arange(20)}
).chunk({"x": 5, "y": 4})
da1
def sumda(da1, da2):
#print(da1.shape)
#print(da2.shape)
return da1 - da2
da3 = (da1 + 1).isel(x=1, drop=True).rename({"y": "k"})
mapped = xr.map_blocks(sumda, da1, args=[da3])
xr.testing.assert_equal(da1-da3, mapped) # passes
```

map_blocks: Allow passing dask-backed objects in args

---

ci/azure/install.yml

As pointed out by @TomAugspurger in https://github.com/pydata/xarray/issues/4133#issuecomment-641332231, there are pre-built nightly wheels for `numpy`, `scipy` and `pandas` in the [scipy-wheels-nightly repository](https://anaconda.org/scipy-wheels-nightly/).
Not sure how frequently these are updated, though, at least the `numpy` wheel doesn't really seem to be built daily.

Fix the upstream-dev pandas build failure

---

xarray/core/accessor_dt.py

Noticed this today.  This note in the `DatetimeAccessor` docstring is no longer relevant; these fields have been calendar-aware for some time.

Remove outdated note from DatetimeAccessor docstring

---

xarray/core/parallel.py

I'm not sure if I broke something, but this is what I would suggest to use instead of putting xarray objects into an object array. The list of arguments is normally far less than 100 elements, so using python for that should not be a problem.
Edit: we're back to a more reasonable 6 minutes for the CI (the build itself takes about 3 minutes)

speed up map_blocks

---

doc/whats-new.rst
xarray/core/dataarray.py

I noticed yesterday that `DataArray.sel` doesn't document its parameters. Instead, it points to `Dataset.sel` (using the `See Also` section).

parameter documentation for DataArray.sel

---

xarray/coding/times.py

Updates the error message in #4127 to recommend installing cftime.

Recommend installing cftime when time decoding fails.

---

.pre-commit-config.yaml
ci/requirements/py38.yml
xarray/core/dataset.py
xarray/core/weighted.py

To resolve some common type-related errors, this PR adds some overload type hints to `Dataset.__getitem__`. Now mypy can correctly infer that hashable inputs return DataArrays.

Improve typehints of xr.Dataset.__getitem__

---

azure-pipelines.yml
ci/azure/install.yml

Instead, we'll use RTD's new doc builder instead. For an example, click on
"docs/readthedocs.org:xray" below or look at GH4159

Fix failing upstream-dev build & remove docs build

---

doc/io.rst

- [NA] Tests added
- [NA] Passes `isort -rc . && black . && mypy . && flake8`
- [NA] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

DOC: drop eccodes in docs

---

.github/PULL_REQUEST_TEMPLATE.md
HOW_TO_RELEASE.md

See below for the new language, to clarify that documentation is only necessary
for "user visible changes."
I added "including notable bug fixes" to indicate that minor bug fixes may not
be worth noting (I was thinking of test-suite only fixes in this category) but
perhaps that is too confusing.
cc @pydata/xarray for opinions!
(including notable bug fixes) and `api.rst` for new API

Revise pull request template

---

xarray/coding/times.py
xarray/conventions.py
xarray/core/common.py
xarray/core/formatting.py
xarray/tests/test_backends.py
xarray/tests/test_conventions.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_dtypes.py
xarray/tests/test_plot.py

Not sure if this enough, but that's something the CI will tell me, right?

use builtin python types instead of the numpy alias

---

xarray/core/dataarray.py
xarray/tests/test_dataarray.py

Trying to make error message slightly more informative when the user might expect automatic alignment with in-place operation.

Proposal for better error message about in-place operation

---

xarray/core/formatting_html.py
xarray/tests/test_formatting_html.py

Using `<pre>` messes up the display of nested HTML reprs, e.g., from dask. Now we only use the `<pre>` tag when displaying raw text reprs.
Before (Jupyter notebook):
After:

Remove <pre> from nested HTML repr

---

ci/requirements/py36-min-nep18.yml
ci/requirements/py36.yml
ci/requirements/py37-windows.yml
ci/requirements/py37.yml
ci/requirements/py38-all-but-dask.yml
ci/requirements/py38.yml
xarray/tests/test_units.py

I can't really test this, but I think the errors in #4172 should be fixed by using `assert_allclose` instead of `assert_equal` / `assert_identical`.

use assert_allclose in the aggregation-with-units tests

---

doc/whats-new.rst
xarray/core/formatting_html.py
xarray/tests/test_formatting_html.py

Show data by default in HTML repr for DataArray

---

xarray/plot/plot.py

Fix typo in error message in plot.py

Fix typo in error message in plot.py

---

readthedocs.yml

This switches back to using the `latest` image on RTD (we tried using `stable` when we had build issues a few months ago and forgot to switch back after they were resolved).

use the latest image of RTD

---

asv_bench/benchmarks/pandas.py
doc/whats-new.rst
xarray/core/dataset.py
xarray/core/dtypes.py
xarray/core/indexes.py
xarray/tests/test_dataset.py

Before:
pandas.MultiIndexSeries.time_to_xarray
======= ========= ==========
--             subset
------- --------------------
dtype     True     False
======= ========= ==========
int    505±0ms   37.1±0ms
float   485±0ms   38.3±0ms
======= ========= ==========
After:
pandas.MultiIndexSeries.time_to_xarray
======= ============ ==========
--               subset
------- -----------------------
dtype      True       False
======= ============ ==========
int    10.7±0.4ms   22.6±1ms
float   10.0±0.8ms   21.1±1ms
======= ============ ==========
~~There are still some cases where we have to fall back to the existing
slow implementation, but hopefully they should now be relatively rare.~~ Edit: now we always use the new implementation

Improve the speed of from_dataframe with a MultiIndex (by 40x!)

---

ci/requirements/py36-min-all-deps.yml
ci/requirements/py36-min-nep18.yml
doc/whats-new.rst

Bump minimum versions for 0.16 release

---

xarray/tests/test_plot.py

These tests were failing because a private attribute was removed.

fix the failing matplotlib upstream-dev tests

---

doc/api.rst
doc/whats-new.rst
readthedocs.yml

This adds back the fail-on-warnings flag we lost during the move the RTDs PR preview, and also fixes the warnings that have accumulated since then.

fix sphinx warnings

---

xarray/tests/test_cupy.py

Added some initial unit tests for cupy. Mainly to create a place for cupy tests to go and to check some basic functionality.
I've created a fixture which constructs the dataset from the Toy weather data example and converts the underlying arrays to cupy. Then I've added a test which checks that after calling operations such as `mean` and `groupby` the resulting DataArray is still backed by a cupy array.
The main penalty with working on GPUs is accidentally shunting data back and forth between the GPU and system memory. Copying data over the PCI bus is slow compared to the rest of the work so should be avoided. So this first test is checking that we are leaving things on the GPU.
Because this data copying is so expensive cupy have intentionally broken the `__array__` method and introduced …

Add initial cupy tests

---

.github/PULL_REQUEST_TEMPLATE.md
.pre-commit-config.yaml
azure-pipelines.yml
ci/requirements/py36-min-all-deps.yml
ci/requirements/py36.yml
ci/requirements/py37-windows.yml
ci/requirements/py37.yml
ci/requirements/py38-all-but-dask.yml
ci/requirements/py38.yml
conftest.py
doc/contributing.rst
xarray/backends/scipy_.py
xarray/conventions.py
xarray/convert.py
xarray/core/common.py
xarray/core/computation.py
xarray/core/concat.py
xarray/core/dataset.py
xarray/core/groupby.py
xarray/core/indexing.py
xarray/core/nanops.py
xarray/core/parallel.py
xarray/tests/test_backends.py
xarray/tests/test_coding_times.py
xarray/tests/test_dataarray.py

Now that the conda-forge feedstock has been updated, we would see a failing `isort` CI because of the removed `-rc` (short for `--recursive`). I also updated the version used by `pre-commit` to the `5.0.4` version released about an hour ago, which allows us to remove the file regex as recommended by @asottile in https://github.com/pydata/xarray/issues/3750#issuecomment-624402070 (we couldn't follow that advice before since we were using the `use_parentheses` setting which was broken on `4.3.21`)

update isort CI and pre-commit hook

---

doc/plotting.rst

This attempts to fix the RTD timeouts. I think these are due to a warning from `matplotlib`, which we can probably just ignore for now.

fix the RTD timeouts

---

HOW_TO_RELEASE.md
doc/whats-new.rst

This PR:
- Proposes adding a Release Summary with a PR. This is something that maybe more people read than anything else we send, and yet it's the least reviewed text of anything I write; and I'm making guesses on what's important.
- Proposes pasting the release summary into the GH Release page; to the extent people follow xarray by following our releases, it's nice to have something there.
- Some touch-ups

Add release summary, some touch-ups

---

doc/examples.rst
doc/index.rst
doc/related-projects.rst

update docs to point to xarray-contrib and xarray-tutorial

---

doc/related-projects.rst

Closes https://github.com/makepath/xarray-spatial/issues/86

Added xarray-spatial and updated geoviews link

---

doc/whats-new.rst
xarray/core/ops.py

Could not confirm in the web-based documentation (see #4257), but manually confirmed to work:
```python
>>> import xarray as xr
>>> help(xr.DataArray.count)
Help on function count in module xarray.core.common:
count(self, dim=None, axis=None, **kwargs)
Reduce this DataArray's data by applying `count` along some dimension(s).
Parameters
----------
dim : str or sequence of str, optional
Dimension(s) over which to apply `count`.
axis : int or sequence of int, optional
Axis(es) over which to apply `count`. Only one of the 'dim'
and 'axis' arguments can be supplied. If neither are supplied, then
`count` is calculated over axes.
keep_attrs : bool, optional
If True, the attributes (`attrs`) will be copied from the original
object to the new one.  If False (default), the new object will be …
```

Removed skipna argument from count, any, all [GH755]

---

doc/whats-new.rst
xarray/core/dataarray.py

Fix DataArray.copy documentation: remove confusing mention of 'dataset' (Gh3606)

---

setup.cfg
xarray/core/duck_array_ops.py
xarray/core/pycompat.py
xarray/core/variable.py
xarray/tests/test_cupy.py

This implements solution 2 for #4231.
cc @quasiben

Support cupy in as_shared_dtype

---

xarray/core/computation.py
xarray/core/groupby.py
xarray/core/options.py

Makes some error messages clearer

Improve some error messages: apply_ufunc & set_options.

---

xarray/tests/test_plot.py

Master ~has been failing for a while now~ recently started failing — while xfailing these isn't ideal, I think it's probably better than the having master continue to fail — any thoughts?
If there's some middle ground — like the "allowed failures" we had in Travis a few years ago, that could be ideal.

xfail failing upstream plotting tests

---

xarray/tests/test_plot.py

Closes #4265 
The change that broke these tests in NumPy master has now been relaxed to trigger a DeprecationWarning (https://github.com/numpy/numpy/pull/16943).

Un-xfail cftime plotting tests

---

xarray/core/duck_array_ops.py

#3847 added compatibility code for `dask < 2.9.1`. Since we bumped to `2.9` this code can be safely removed. If we can't require `dask >= 2.9.1` yet, we can wait with the merge of this PR until we can bump `dask` again.

remove the compatibility code in duck_array_ops.allclose_or_equiv

---

HOW_TO_RELEASE.md

#4217 didn't update the task item numbers, this fixes that. I'm also hoping to reuse this PR to document the push-to-`master` rules from #4218, but where would I put those?

update howto release guide numbers

---

readthedocs.yml

RTD's sphinx extension released a new version since #4199, so let's try enabling the `fail_on_warning` setting again.

enable fail_on_warning for the docs CI

---

doc/api.rst

As noted in #4116, using the functions in `xarray.ufuncs` will emit a warning stating that we'd remove those functions after support for `numpy < 1.17` was dropped. This also adds that to the API docs.

warn about the removal of the ufuncs

---

doc/whats-new.rst
xarray/core/formatting_html.py

- Marginal speed-up and RAM footprint reduction when not running in Jupyter Notebook
- Closes #4294

Lazily load resource files

---

xarray/core/dataarray.py
xarray/core/dataset.py

This reference an `obj` argument that only exists in parallel. The
object being referenced is actually `self`.

Update map_blocks and map_overlap docstrings

---

doc/whats-new.rst
setup.py

Fix ``pip install .`` when no ``.git`` directory exists; namely when the xarray source directory has been rsync'ed by PyCharm Professional for a remote deployment over SSH.

Support PyCharm deployment over SSH

---

xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/variable.py

Incorrect value "exception" was given in the description of `missing_dims` argument - "exception" was renamed to "raise".

Fix docstring for missing_dims argument to isel methods

---

xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/parallel.py

The examples on master raised with
```pytb
ValueError: Result from applying user function has unexpected coordinate variables {'month'}.
```
This PR updates the example to include the `month` coordinate. `pytest --doctest-modules` passes on these three now.

Fix map_blocks examples

---

xarray/backends/common.py

@shoyer this could be the first pass of the simplification of the current backend API. It not needed for #4309, but it make more obvious that we'd be free to keep the AbstractDataStore class if we wanted to.
The reason the change can be considered reasonably innocuous is that warnings would have been printed on access to any of the removed methods, but you never know. Your call (but I'd love to have a delete-only contribution to *xarray* :D).
Please note that:
1. this change is the absolute lowest hanging fruit,
2. removing `__enter__` and `__exit__` appears feasible as they are used only in tests, but it is a slightly bigger change,
3. removing `load` is marginally more complex because it handle the special case when a variable name is equal to `None`.

Remove all unused and warn-raising methods from AbstractDataStore

---

ci/requirements/doc.yml
doc/api-hidden.rst

In order to get our docs CI running again and to help find issues with the documentation (we already missed a few), this pins `pandas` to 1.0 (copied from #4296). Once we merged #4292 and fixed #4287 (mostly by using the upcoming `sphinx` 3.2 release), we can undo this.

silence the known docs CI issues

---

doc/whats-new.rst
xarray/backends/locks.py

This is a fix for Issue 4164. I haven't written any tests since this issue involves partial installation of dask, and while I know ways to fake the results of failed imports, I'm not sure these are appropriate for a test bed. The test script from the issue no longer raises an error.

Implicit dask import 4164

---

doc/computation.rst
doc/whats-new.rst
xarray/core/common.py
xarray/core/dask_array_ops.py
xarray/core/dataset.py
xarray/core/nputils.py
xarray/core/rolling.py
xarray/core/variable.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_nputils.py
xarray/tests/test_testing.py
xarray/tests/test_units.py

I noticed that the implementation of nd-rolling is straightforward.
The core part is implemented but I am wondering what the best API is, with keeping it backward-compatible.
Obviously, it is basically should look like
```python
da.rolling(x=3, y=3).mean()
```
A problem is other parameters, `centers` and `min_periods`.
In principle, they can depend on dimension. 
For example, we can have `center=True` only for `x` but not for `y`.
So, maybe we allow dictionary for them?
```python
da.rolling(x=3, y=3, center={'x': True, 'y': False}, min_periods={'x': 1, 'y': None}).mean()
```
The same thing happens for `.construct` method.
```python
da.rolling(x=3, y=3).construct(x='x_window', y='y_window', stride={'x': 2, 'y': 1})
```
I'm afraid if this dictionary argument was a bit too redundant.
Does …

nd-rolling

---

ci/requirements/doc.yml

The recently released `sphinx` 3.2 version includes a new type preprocessor that will warn about a few issues. These will be fixed / silenced in #4286, but to avoid a failing docs CI let's pin `sphinx` for now. I'm also pinning to `sphinx=3.1` instead of `sphinx<=3.1` because that is required for `sphinx-autosummary-accessors` to work properly.

pin sphinx

---

xarray/core/dataarray.py

DOC: fix typo argmin -> argmax in DataArray.argmax docstring

---

doc/computation.rst
xarray/core/rolling.py
xarray/tests/test_dataarray.py

There was a bug in `rolling.__repr__` but it was not tested.
Fixed and tests are added.

ndrolling repr fix

---

ci/requirements/doc.yml
doc/conf.py
doc/internals.rst

Since I released a initial version of `sphinx-accessors-autosummary` (to `PyPI`, `conda-forge` requires a bit more work), I think we can start using it in `xarray`, too.
This also extends the docs on accessors to mention that package.

Use sphinx-accessors-autosummary

---

ci/requirements/doc.yml

`sphinx-autosummary-accessors` is now on [`conda-forge`](https://github.com/conda-forge/sphinx-autosummary-accessors-feedstock) and I hopefully fixed all issues with the package (but it would probably be good if someone with more experience with conda-forge packaging than me could review the feedstock).
This makes our docs CI install from `conda-forge` instead of PyPI.

install sphinx-autosummary-accessors from conda-forge

---

ci/min_deps_check.py
ci/requirements/doc.yml
ci/requirements/py36-bare-minimum.yml
ci/requirements/py36-min-all-deps.yml
ci/requirements/py36-min-nep18.yml
doc/installing.rst
doc/whats-new.rst
requirements.txt
setup.cfg
xarray/tests/test_duck_array_ops.py

Closes #4295
Increase width of the sliding window for minimum supported version:
- setuptools from 6 months sliding window to hardcoded >= 38.4, and to 42 months sliding window starting from July 2021
- dask and distributed from 6 months sliding window to hardcoded >= 2.9, and to 12 months sliding window starting from January 2021
- all other libraries from 6 months to 12 months sliding window

Increase support window of all dependencies

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

Support explicitly setting a dimension order with to_dataframe()

---

ci/requirements/doc.yml

I realised that matplotlib is not listed in `ci/requirements/doc.yml` I think it is drawn as cartopy is required.
But that's not the reason for this PR - matplotlib 3.3.1 came out 3 hours ago (https://anaconda.org/conda-forge/matplotlib) and I think this breaks the doc build. So let's test this.

pin matplotlib in ci/requirements/doc.yml

---

doc/whats-new.rst
xarray/core/accessor_str.py
xarray/tests/test_accessor_str.py

str accessor inconsistencies #4334

---

doc/whats-new.rst
xarray/core/duck_array_ops.py
xarray/tests/test_duck_array_ops.py

Going through `pandas.TimedeltaIndex` within `duck_array_ops._to_pytimedelta` leads to overflow problems (presumably it casts to a `"timedelta64[ns]"` type internally).  This PR updates the logic to directly use NumPy to do the casting, first to `"timedelta64[us]"`, then to `datetime.timedelta`.

Fix overflow-related bug in computing means of cftime.datetime arrays

---

ci/requirements/doc.yml
doc/conf.py

The versions were broken because instead of installing we simply extended `sys.path`. That way, `sphinx` is able to find the correct version, but `setuptools_scm` can't put the version in the `METADATA` file in the installed egg. Instead, `pkg_resources.get_distribution("xarray").version` gets its version from a released version of `xarray` that was pulled in by a dependency (hence the old version in the title bar). To fix that, we need to install before building the documentation.
However, since RTD installs with `--upgrade --upgrade-strategy=eager` (which upgrades all packages to the most recent version), we can't install using their `pip` method. The `setuptools` method doesn't work either because `cfgrib` pulls in the most recent released version of `xarray`, and `setuptools` can't …

install the project on RTD

---

doc/whats-new.rst
xarray/core/concat.py
xarray/core/dataarray.py

The issue mentions `xr.Dataset.to_dataframe` and `xr.concat`. `xr.Dataset.to_dataframe` was [annotated](https://github.com/pydata/xarray/blob/26547d19d477cc77461c09b3aadd55f7eb8b4dbf/xarray/core/dataset.py#L4566) in #4333, so only `xr.concat` is left.

annotate concat

---

doc/contributing.rst
doc/whats-new.rst

Our contributing guide is out-of-date, we usually use merge commits instead of rebasing (which would require force-pushing). This has already lead to confusion, see #4314.
Also, I noticed that in `Delete your merged branch` it recommends to use `git branch -d <feature-branch>` after updating `master`. That doesn't work anymore because we've switched to squash-merges.

update the instructions in the contributing guide

---

doc/whats-new.rst
xarray/core/dask_array_ops.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/nputils.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

Fixes #4190. In cases where the input matrix had a deficient rank (matrix rank != order) because of the number of NaN values, polyfit would fail, simply because numpy's lstsq returned an empty array for the residuals (instead of a size 1 array). This fixes the problem by catching the case and returning `np.nan` instead.
The other point in the issue was that `RankWarning` is also not raised in that case. That was due to the fact that `da.polyfit` was computing the rank from the coordinate (Vandermonde) matrix, instead of the masked data. Thus, is a given line has too many NaN values, its deficient rank was not detected. I added a test and warning at all places where a rank is computed (5 different lines). Also, to match np.polyfit behaviour of no warning when `full=True`, I changed the …

Fix polyfit fail on deficient rank

---

doc/whats-new.rst
xarray/core/nanops.py
xarray/tests/test_duck_array_ops.py

Test may be insufficient, but here's a first go

Allow multiple dims to be passed with min_count

---

doc/whats-new.rst
xarray/plot/facetgrid.py
xarray/plot/utils.py
xarray/tests/test_plot.py

I gave a try to silence some of the warning for the plotting functions. I brought it down from 67 to 5 (4 of which come from external libraries).
I cannot exclude that one of these changes has an effect on the plots that is not tested in the suite... Tests pass locally for py38 and py36-bare-minimum.

Silence plot warnings

---

xarray/core/variable.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

(Not sure this is worth noting in whats-new)

Use deepcopy recursively on numpy arrays

---

xarray/tests/test_concat.py
xarray/tests/test_interp.py

Remove deprecated usages of drop

---

setup.cfg

I don't think these lines do anything, and I see this warning on each run. 
People wiser than me (@jhamman ) put it here — is there something it does do?
```
/usr/local/lib/python3.8/site-packages/_pytest/config/__init__.py:1148
/usr/local/lib/python3.8/site-packages/_pytest/config/__init__.py:1148: PytestConfigWarning: Unknown config ini key: env
self._warn_or_fail_if_strict("Unknown config ini key: {}\n".format(key))
-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

Remove null pytest env option

---

.pre-commit-config.yaml
doc/whats-new.rst

I had some issues with the version changing — this approach seems more explicit and less likely to cause hard-to-debug issues

Pin pre-commit versions

---

.pre-commit-config.yaml

Follow-up to #4388. Updates the versions of `isort` and `blackdoc` (by calling `pre-commit autoupdate`). The most recent version of `blackdoc` is important because it fixes the broken compatibility with `black` 20.08b1.

update the isort and blackdoc pre-commit hooks

---

doc/whats-new.rst
xarray/backends/zarr.py
xarray/tests/test_backends.py

Expose use_cftime option in open_zarr #2886

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/nanops.py
xarray/core/variable.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_duck_array_ops.py
xarray/tests/test_groupby.py
xarray/tests/test_weighted.py

Is this the right approach? Or should we be using `np.errstate` machinery?

Silencing numpy warnings

---

doc/related-projects.rst

We have released [xarray-compare](https://github.com/astropenguin/xarray-compare), a Python package which provides extra data-comparison features (e.g., `dataarray.isbetween(lower, upper)`).
This PR adds the project to the "Extend xarray capabilities" section in `doc/related-projects.rst`.
We have a concern: This package **directly** adds some methods to `xarray.DataArray` by using [the accessor feature](https://xarray.pydata.org/en/stable/internals.html#extending-xarray).
For example, `dataarray.isbetween()` is implemented by registering an accessor whose name is `'isbetween'`.
This usage may not be what is expected by the xarray's developers.
So it would be appreciated if you could merge it, but if you feel that it does not fit the docs, please reject the PR.
Thank you!

Add xarray-compare to related projects

---

doc/whats-new.rst
xarray/plot/plot.py

This fixes the documented signature of the plotting functions. Not sure if using a decorator to override `__wrapped__` is the best way to achieve this, though.

override the signature of plotfunc

---

doc/whats-new.rst
xarray/core/computation.py
xarray/tests/test_computation.py

FIX: handle dask ValueErrors in `apply_ufunc` (set ``allow_rechunk=True``)

---

xarray/core/dataarray.py

Or would you prefer to have the parameter documentation from `Dataset.to_netcdf` copied over?
@raybellwaves @keewis 
https://xray--4424.org.readthedocs.build/en/4424/generated/xarray.DataArray.to_netcdf.html#xarray.DataArray.to_netcdf

fix doc dataarray to netcdf

---

doc/whats-new.rst
xarray/core/variable.py
xarray/tests/test_dask.py

Previously we generated in invalidate Dask task graph, becuase the lines
removed here dropped keys that were referenced elsewhere in the task
graph. The original implementation had a
comment indicating that this was to cull:
https://github.com/pydata/xarray/blob/502a988ad5b87b9f3aeec3033bf55c71272e1053/xarray/core/variable.py#L384
Just spot-checking things, I think we're OK here though. Something like
`dask.visualize(arr[[0]], optimize_graph=True)` indicates that we're OK.

Fix optimize for chunked DataArray

---

doc/indexing.rst
doc/whats-new.rst

I found the existing example not that clear as to why it was selecting `[[1,1],[5,5]]`, I think this is more obvious (open to disagreement of course!)
Before
```python
In [37]: da = xr.DataArray(
....:     np.arange(12).reshape((3, 4)),
....:     dims=["x", "y"],
....:     coords={"x": [0, 1, 2], "y": ["a", "b", "c", "d"]},
....: )
....: 
In [38]: da
Out[38]: 
<xarray.DataArray (x: 3, y: 4)>
array([[ 0,  1,  2,  3],
[ 4,  5,  6,  7],
[ 8,  9, 10, 11]])
Coordinates:
* y        (y) <U1 'a' 'b' 'c' 'd'
In [39]: da[[0, 1], [1, 1]]
Out[39]: 
<xarray.DataArray (x: 2, y: 2)>
array([[1, 1],
[5, 5]])
Coordinates:
* x        (x) int64 0 1
* y        (y) <U1 'b' 'b'
```
After:
```python
In [4]:     da[[1, 2, 2], [0, 3]]
Out[4]:
<xarray.DataArray (x: 3, y: 2)>
array([[ 4, …
```

Clearer Vectorized Indexing example

---

ci/requirements/py36-min-nep18.yml
doc/whats-new.rst
xarray/core/concat.py
xarray/core/coordinates.py
xarray/core/dataset.py
xarray/tests/test_testing.py

In #4408, The formatting of `coords` turned out to be non-deterministic. This sorts the data variables, coordinates and dimensions without coordinates sections as well as the dimensions summary of `Dataset` objects.
No tests, yet, because I'm not quite sure sorting using the `str` representation of the key is the best way to make the formatting deterministic (so I'd appreciate reviews). 
It might also be good to document somewhere that these sections are now sorted, and that it only makes sense to look at the order in the dimension summary of `DataArray` and `Variable` objects.

Keep the original ordering of the coordinates

---

xarray/core/indexing.py
xarray/tests/test_backends.py

Fix for h5py deepcopy issues

---

doc/whats-new.rst
xarray/core/concat.py
xarray/tests/test_concat.py

The problem is that the `result_vars`-dict is filled in two separate loops, handling variables and coordinates (AFAICT). This can change the ordering of dimensions and coordinates depending over which dimensions is concatenated.
This fix hooks into the second loop and reinsert the variable in question at the appropriate position by popping it out of the `result_vars`. There might be a more elegant solution to this.

preserve original dimension, coordinate and variable order in ``concat``

---

azure-pipelines.yml

Now that #4409 is merged, we can add a CI that makes sure all examples actually work.

add a ci for doctests

---

HOW_TO_RELEASE.md

Small updates to How-to-release + lint

---

doc/whats-new.rst

Please make suggestions for any changes!

Release notes for 0.16.1

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/core/variable.py
xarray/tests/test_dask.py

Another attempt to fix #3698. The issue with my fix in is that we hit
`Variable._dask_finalize` in both `dask.optimize` and `dask.persist`. We
want to do the culling of unnecessary tasks (`test_persist_Dataset`) but
only in the persist case, not optimize (`test_optimize`).

Fixed dask.optimize on datasets

---

doc/whats-new.rst

Add doctests to release notes

---

doc/whats-new.rst

As per https://github.com/pydata/xarray/pull/4440

Fix release notes formatting

---

xarray/backends/api.py

#4187 contained broken rst (a missing backtick), this fixes that.

fix the sphinx build on RTD

---

HOW_TO_RELEASE.md
xarray/backends/api.py
xarray/backends/zarr.py
xarray/tests/test_backends.py

This ports the clean up of the messy if-else-chain from #3166. It should make adding the new back-end API easier.
The change is relatively trivial, but it touches code in `xr.open_dataset` so extra care should be used by reviewers. We think the change is safe and it does pass all tests.
I cannot add reviewers myself, but we agreed this should go to @jhamman.

Refactor of the big if-chain to a dictionary in the form {backend_name: backend_open}.

---

.pre-commit-config.yaml

When opening the current url https://github.com/timothycrosley/isort it points to a new url https://github.com/PyCQA/isort.
This PR replaces the old url with the new one

update url for isort in .pre-commit-config.yaml

---

doc/whats-new.rst
xarray/backends/api.py
xarray/backends/h5netcdf_.py
xarray/backends/netCDF4_.py
xarray/tests/test_backends.py

Always use the `engine` explicitly selected by the user and perform auto detection only when `engine=None`.
The refactor complexity stems mostly from moving or duplicating some logic from `_get_engine_from_magic_number` to the backend stores. The current, rather ugly, code minimizes changes to the error conditions and messages.
Later in the backend refactor the plugins will provide the functionalities to identify the format from the file content and the duplication should be eliminated.
@jhamman do you think I need to acknowledge the CZI sponsorship in the changelog?

Autodetect the engine only when `engine=None`

---

doc/whats-new.rst
xarray/core/parallel.py
xarray/core/variable.py
xarray/tests/test_variable.py

Use _possibly_convert_obhects to raise an error when converting datetime64 or timedelta64 objects that are in some units other than ns to ns as per pandas requirements, resulting in dates outside the valid range for ns precision being silently changed to incorrect values.

Raise error when datetime64 or timedelta64 values that are outside the valid range for ns precision are converted to ns precision

---

.pre-commit-config.yaml

this updates the version of `blackdoc` pinned in `.pre-commit-hooks.yaml` (using `pre-commit autoupdate` so `isort` is also updated)

update the pre-commit hooks

---

doc/related-projects.rst
doc/whats-new.rst
xarray/core/duck_array_ops.py
xarray/tests/test_duck_array_ops.py

I see two methods how to fix this (see code). I would prefer Method 1 - but maybe you don't want to add method-specific code to `_create_nan_agg_method`? Anyone an opinion?

fix: min_counts for non-nan sum and prod

---

ci/requirements/doc.yml

mpl 3.3.2 is out so we can try to unpin the version of the docs again. #4313

unpin matplotlib for docs again

---

xarray/backends/api.py

This is a small, pure code-refactor PR that removes some of the cruft left in `open_dataset` from #4187 and #4431 
Note that `mode="r"` is the default in `open_group`.

Cleanup logic inside `open_dataset`, mostly `extra_kwargs`

---

xarray/backends/api.py
xarray/backends/zarr.py
xarray/core/dataset.py

I propose this small change with a view to unifying in `open_dataset` the logic of zarr chunking with that of the other backends.
Currently, the function `maybe_chunk` is duplicated: it is defined inside the function `dataset.chunks` and as method of `zarr.ZarrStore`. This last function has been added with the recent merge of #4187 . 
I merged the two functions in a private function `_maybe_chunk` inside the module `dataset`.

Remove maybe chunck duplicated function

---

xarray/backends/api.py
xarray/tests/test_backends.py

This should result in a better user experience, e.g., specifically
pointing out the attribute with an invalid value.

Add variable/attribute names to netCDF validation errors

---

ci/requirements/py36.yml
ci/requirements/py37.yml
ci/requirements/py38-all-but-dask.yml
ci/requirements/py38.yml
doc/installing.rst
doc/io.rst

remove pynio from most test envs

---

xarray/core/dataset.py
xarray/core/variable.py
xarray/tests/test_variable.py

Remove deprecated allow_lazy

---

doc/io.rst
doc/whats-new.rst
xarray/coding/variables.py
xarray/tests/test_backends.py

The h5netcdf engine exposes single-valued attributes as arrays of shape
(1,), which is correct according to the NetCDF standard, but may cause
a problem when reading a value of shape () before the scale_factor and
add_offset have been applied.  This PR adds a check for the dimensionality
of add_offset and scale_factor and ensures they are scalar before they
are used for further processing, adds a unit test to verify that this
works correctly, and a note to the documentation to warn users of this
difference between the h5netcdf and netcdf4 engines.

Handle scale_factor and add_offset as scalar

---

doc/whats-new.rst
xarray/core/combine.py
xarray/tests/test_combine.py

Let's see if all tests pass or if the `numeric_only` keyword is new in pandas.

combine_by_coords: error on differing calendars

---

setup.cfg

Purely aesthetic simplification

Use black profile for isort

---

xarray/tests/test_coding_times.py

This is a minor cleanup to remove our use of calendar-naive cftime datetime objects (it just occurs in one test).  The behavior of the `cftime.datetime` constructor is set to change in Unidata/cftime#202.  By default it will create a calendar-aware datetime with a Gregorian calendar, instead of a calendar-naive datetime.  In xarray we don't have a real need to use calendar-naive datetimes, so I think it's just best to remove our use of them.

Eliminate use of calendar-naive cftime objects

---

ci/requirements/doc.yml

That was fast - eccodes already fixed the issue.

unpin eccodes again

---

.github/ISSUE_TEMPLATE/config.yml

I've been trying to answer most questions on SO over the past month or so. The quality of questions is not great — is there a way we could encourage people to post reproducible examples? I think our push to do that on GH issues has been broadly successful. 
I occasionally reply asking for a reproducible example, but it's not that friendly an approach.
There are some SO docs: https://stackoverflow.com/help/minimal-reproducible-example, but they're not explicitly linked to from SO.

Request a reproducible example for SO questions

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/tests/test_dataarray.py

When attempting to convert a scalar to a dataframe, as e.g.:
`xarray.DataArray([1], coords=[('onecoord', [2])]).sel(onecoord=2).to_dataframe(name='name')`
raise 
`ValueError: cannot convert a scalar to a Dataframe`
instead of 
`ValueError: no valid index for a 0-dimensional object`
> I was not sure if this was "notable". Please let me know if I should add.
> n / a
I was not able to run all tests, but was able to run the changed one (more on that in the issue).

GH4228 Clearer error on scalar to dataframe

---

doc/io.rst
doc/plotting.rst
doc/quick-overview.rst
doc/whats-new.rst

Suggesting an update geoviews URL 
(this was automatically forked via GitHub "edit" feature and for some reason this branch picked up some other grammar suggestions made previously)

update geoviews URL in docs

---

doc/io.rst
doc/whats-new.rst

This PR fixes grammar and typos in the [Reading and writing files](http://xarray.pydata.org/en/stable/io.html) user guide.

Fix grammar and typos in the Reading and writing files guide

---

xarray/core/indexing.py

pandas-dev/pandas#20393 was resolved in pandas version 0.23, so this should no longer be necessary. The relevant test is
https://github.com/pydata/xarray/blob/063606b90946d869e90a6273e2e18ed24bffb052/xarray/tests/test_dataarray.py#L955-L957
so let's see if this passes

maint: pandas can now index with np.timedelta64

---

doc/contributing.rst
doc/whats-new.rst

I updated the link to the NumPy docstring standard in the [contributing guide](http://xarray.pydata.org/en/stable/contributing.html).

Update link to NumPy docstring standard in contributing guide

---

asv_bench/benchmarks/indexing.py
doc/whats-new.rst
xarray/core/indexing.py

I noticed that reading small slices of huge datasets (>1e8 rows) was very slow, even if they were properly chunked. I traced the issue back to `xarray.core.indexing.slice_slice`, which essentially calls `np.arange(ds_size)` to compute a slice. This is obviously `O(ds_size)`, even if the actual slice to be read is tiny.
You can see the issue in this gist:
https://gist.github.com/dionhaefner/a3e97bae0a4e28f0d39294074419a683
I took the liberty to optimize the function by computing the resulting slice arithmetically. With this in place, reading from disk is now the bottleneck as it should be. I saw performance increases by about a factor of 10, but this obviously varies with dimension size, slice size, and chunk size.
---

Optimize slice_slice for faster isel of huge datasets

---

xarray/core/dataset.py
xarray/tests/test_dataset.py

This PR follows a TypeError I got
```
ds = xr.open_dataset('https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GFS/Global_0p25deg/Best')
ds.rename({'lat': 'latitude', 'lon': 'longitude'}, inplace=True)
TypeError: The `inplace` argument has been removed from xarray. You can achieve an identical effect with python's standard assignment.
```
I saw the option of the inplace in the docs
http://xarray.pydata.org/en/stable/generated/xarray.Dataset.rename.html
Removing this argument.
TODO:

rm inplace arg to rename

---

ci/requirements/py36.yml
ci/requirements/py37-windows.yml
ci/requirements/py37.yml
ci/requirements/py38-all-but-dask.yml
ci/requirements/py38.yml

There is a compatibility issue with h5py v3. Pin h5py to version 2 for the moment. I can open an issue shortly.

pin h5py to v2.10

---

doc/whats-new.rst
xarray/core/weighted.py
xarray/tests/test_weighted.py

Dask friendly check in `.weighted()`

---

doc/whats-new.rst
xarray/core/alignment.py

Pandas will change `pd.Index.__or__` and `pd.Index.__and__`. Use `pd.Index.union` and `pd.Index.intersection` inseated. There should be no change in functionality.

pd.Index: replace set operations

---

.pre-commit-config.yaml
ci/requirements/py38.yml

`pre-commit autoupdate` also wants to update `mypy` to `0.790`, but running that prints a error:
```
xarray/core/utils.py:466: error: Value of type variable "_LT" of "sorted" cannot be "K"
```
I'm not sure how to fix that, so I'll leave the upgrade to someone else.

Update pre-commit hook versions

---

xarray/core/formatting.py
xarray/tests/test_formatting.py

This is a simple change to format_item in core/formatting.py that allows other float type (e.g. numpy.float16, numpy.float32) to be formatted the same as any other float.

Match all float types in formatitem

---

xarray/core/groupby.py

This doesn't seem to be used? Unless it's required for compatibility with an interface?

Remove unused kwarg

---

xarray/tests/test_coding_times.py
xarray/tests/test_conventions.py

Follow up to #4506
Suppress some `"Ambiguous reference date string"` warnings. See e.g.: https://dev.azure.com/xarray/xarray/_build/results?buildId=4233&view=logs&j=2280efed-fda1-53bd-9213-1fa8ec9b4fa8&t=175181ee-1928-5a6b-f537-168f7a8b7c2d&l=361

suppress 'ambiguous reference date string' warning

---

doc/whats-new.rst
xarray/core/rolling_exp.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

rolling_exp: keep_attrs and typing

---

xarray/static/css/style.css

xref https://github.com/pandas-dev/pydata-sphinx-theme/issues/284 
The current CSS had the consequence that those rules were applied to all `<dd>` elements, and not only the ones with the `xr-attrs` class. 
I don't know if there is a smarter way in CSS to select two element types using the class rather than repeating the class name as I did here, but this works.
cc @benbovy

BUG: fix the CSS for dt / dd to only apply to xarray repr

---

.github/workflows/upstream-dev-ci.yaml

follow-up to #4583, which also added a PR upstream-dev CI. However, because the output of `pytest` has been redirected to a file, the failures are hard to diagnose. The fix is to duplicate `stdout` using `tee`.
~Additionally, we now have two upstream-dev CI, so I guess we should remove the old one?~ #4584 will probably set the upstream-dev CI to `allow_failure: true`, so it might be better to remove the new CI (or to somehow mark the new PR CI with `allow_failure: true` while not changing the scheduled CI).

clean up upstream-dev CI

---

doc/api-hidden.rst
doc/whats-new.rst
xarray/coding/cftime_offsets.py
xarray/coding/cftimeindex.py
xarray/tests/test_cftimeindex.py

add freq as CFTimeIndex property and to CFTimeIndex.__repr__

---

.github/ISSUE_TEMPLATE/config.yml

Towards https://github.com/pydata/xarray/issues/4549

Direct users to GitHub discussions page for usage questions

---

doc/whats-new.rst
xarray/core/common.py

document the option to pass a function to where

---

.github/workflows/parse_logs.py
.github/workflows/upstream-dev-ci.yaml

As mentioned in #4604, I think being able to run `parse_logs.py` by hand is pretty useful, so I refactored the current script.
cc @andersy005

Refactor the pytest test summary info parsing script

---

doc/whats-new.rst
xarray/core/common.py
xarray/core/duck_array_ops.py
xarray/core/ops.py
xarray/core/variable.py

As suggested in #2760 this moves the `isnull` and `notnull` to `DataWithCoords`. The body is adapted from `DataWithCoords.isin`, but I'm not certain `dask="allowed"` is the right option for `duck_array_ops.isnull`. Can someone with more experience with `apply_ufunc` confirm?

docstrings for isnull and notnull

---

xarray/core/dataarray.py
xarray/core/dataset.py

This adds examples for `interp` and `interpolate_na` (`interp_like` still needs to be done). Also, is there a reason why `interp` and `interpolate_na` accept `kwargs` differently?

examples for interp and interpolate_na

---

doc/whats-new.rst
xarray/core/merge.py
xarray/tests/test_merge.py

fixes bug #4627 to make a copy of the attrs in the merged object

---

xarray/backends/api.py
xarray/backends/apiv2.py
xarray/backends/zarr.py
xarray/core/dataset.py
xarray/tests/test_dataset.py

The aim is to split the PR https://github.com/pydata/xarray/pull/4595 in small PRs. 
In this smaller PR  there aren't changes in xarry interfaces, it's only a small code refactor:
- Move `get_chunks` from zarr.py to dataset.py
- Align `apiv2` to `apiv1`: in `apiv2`  replace `zarr.ZarrStore.maybe_chunk`  with `dataset._maybe_chunk` and `zarr.ZarrStore.get_chunk`  with `dataset._get_chunks`.
- remove `zarr.ZarrStore.maybe_chunk` and `zarr.ZarrStore.get_chunks` (no more used)
- No user visible changes (including notable bug fixes) are documented in `whats-new.rst`
- No new functions/methods are listed in `api.rst`

Move get_chunks from zarr.py to dataset.py

---

xarray/backends/apiv2.py

Related to PR https://github.com/pydata/xarray/pull/4595.
In this smaller PR, there aren't changes functional changes, it's only a small code refactor needed to simplify pydata#4595.
Changes in `apiv2.dataset_from_backend_dataset`:
- rename `ds` in `backend_ds` and `ds2` in `ds`.
- simplify if in chunking and split code adding `function _chunks_ds`
- add `_get_mtime` specific function
Make `resolve_decoders_kwargs` and `dataset_from_backend_dataset` private

Refactor apiv2.open_dataset

---

ci/requirements/py38.yml

Our upstream-dev is failing again. See numpy/numpy#17885 and pypa/pip#9186 for the probable cause. So this will need to be fixed upstream first.

pin pip for upstream-dev

---

.github/workflows/upstream-dev-ci.yaml

Amend upstream-dev GitHub action + Bug fixes

---

xarray/core/dataarray.py

What it says on the tin, changed `xarrray.open_dataset` to `xarray.open_dataset`.
The mistake was in documentation so no changes to any code have been made

corrected a minor spelling mistake

---

.github/workflows/upstream-dev-ci.yaml

It seems [the only way](https://github.community/t/do-not-run-cron-workflows-in-forks/17636) to stop running the scheduled CI on forks is by skipping the jobs if they are run on a fork.
~I'm not sure if I have to make an exception for PR CI (i.e. also check for `github.event_name != 'schedule'`), but I guess we can just try it out.~
Edit: apparently we don't need that, it runs just fine.
cc @andersy005

Run the scheduled nightly CI only on the main repo

---

doc/io.rst
doc/whats-new.rst

There are a few external libraries that add support for more I/O formats. This adds `xarray-mongodb` to a new section in `io.rst`, but we might just as well maintain that list in `related-projects.rst` and point to that list in `io.rst`. Same for #4530, where I started a list of duck array support libraries (currently only `pint-xarray`).

Document external io libraries

---

xarray/backends/api.py
xarray/backends/apiv2.py
xarray/backends/zarr.py
xarray/core/dataset.py
xarray/tests/test_backends.py

Part of https://github.com/pydata/xarray/pull/4595
The changes involve only `open_dataset(..., engine=zarr)` (and marginally `open_zarr`), in particular, `_get_chunks` has been modified to fit #4496 (comment) option 1 chunking behaviour and align open_dataset chunking with `dataset.chunk`:
- with `auto` it uses dask auto-chunking (if a preferred_chunking is defined, dask will take it into account as done in `dataset.chunk`)
- with `-1` it uses dask but no chunking.
- with `{}` it uses the backend encoded chunks (when available) for on-disk data (`xr.open_dataset`) and the current chunking for already opened datasets (`ds.chunk`)
Add some test

Modify zarr chunking as suggested in #4496

---

ci/install-upstream-wheels.sh

sparse is removed as conda package but not re-installed (https://github.com/pydata/xarray/blob/9802411b35291a6149d850e8e573cde71a93bfbf/ci/install-upstream-wheels.sh)
I assume this is not intentional, @andersy005?

upstream-dev: mention sparse

---

xarray/backends/apiv2.py

It's the last part of, and closes #4595.
Here we unify the code for chunking in `apiv2.open_dataset`. Note the code unification is only a refactor, there aren't functional changes since the zarr chunking has been already aligned with the others.

unify zarr chunking with other chunking in apiv2.open_dataset

---

xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/variable.py

The aim is to split the PR #4595 in small PRs.
The scope of this smaller PR is to modify the default of `chunks` in `dataset.chunk` to align the behaviour to `xr.open_dataset`. 
The main changes are:
- Modify the default of chunk in `dataset.chunk`, `datarray.chunk` and `variable.chunk` from None to {}.
- If the user pass `chunk=None` inside is set to `{}`
- Add a future warning to advice that the usage of `None` will raise an error in the future. 
Note that the changes currently don't modify the behaviour of `dataset.chunk`

change default in ds.chunk and datarray.chunk variable.chunk

---

xarray/tests/test_backends.py

rasterio slightly changed an error message, so it's no longer ignored. Also switched to `pytest.mark.filterwarnings`. This makes the diff larger but saves a level of indendation.
https://github.com/pydata/xarray/runs/1508035460#step:6:322

rasterio no geotransform: update warning message

---

xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/utils.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

As in #4561 this has been around for about 3 major versions. Not sure if it's too soon to remove it altogether, but I guess if we decide it is we can just wait with the merge until it is not.

remove all inplace parameters from the public API

---

doc/internals.rst
doc/whats-new.rst

We currently have a example for a accessor class in our `internals` page, but we didn't explicitly say what we require of these classes. This PR adds that information, and also fixes the displayed text for the link to `sphinx-autosummary-accessors`.

improve the documentation on accessors

---

xarray/tests/test_units.py

To reduce the build time of the CI, all tests that depend on units in indexes are marked as skipped. There were also a few previously failing tests that were fixed upstream.
Among these, there are the `prod` tests which pass for `int` dtypes but not for `float`: for `float`, `nanops.nanprod` is used which tries to replace all `nan` with a `1` and fails because `1` (unlike `0`) is only compatible with dimensionless units.

mark most failing units tests as skipped

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/tests/test_dataarray.py

Remove dictionary unpacking when using `.loc` to avoid collision with `.sel` parameters

---

doc/conf.py
doc/whats-new.rst
xarray/core/common.py
xarray/core/duck_array_ops.py
xarray/core/variable.py
xarray/tests/test_dataarray.py

Readd order and subok parameters to astype (GH4644)

---

doc/whats-new.rst
xarray/core/weighted.py
xarray/tests/test_weighted.py

Fixing non-lazy behavior of sampled+weighted

---

ci/azure/install.yml

#4694 was just merged a bit too soon. Unfortunately using `mamba` to uninstall the packages for upstream dev did not work - it uninstalled too much, thus switch back to conda. I'll just merge right away.
@dcherian

use conda for upstream dev uninstall again

---

xarray/backends/netCDF4_.py
xarray/backends/zarr.py

- Related to #4309 and in particular: https://github.com/pydata/xarray/issues/4309#issuecomment-747055666
- No user visible change
Once `ZarrStore.open_group` and `NetCDF4DataStore.open` accepts `pathlib.Path` objects we can remove `_normalize_path` from `apiv2.open_dataset`. All other backends accept them.
Note that `zarr` itself doesn't support them, yet. See: https://github.com/zarr-developers/zarr-python/issues/601

Allow pathlib.Path to be passed to all engines

---

.github/workflows/parse_logs.py
.github/workflows/upstream-dev-ci.yaml

If more than a single test fails, the nightly CI would create a issue with a malformed issue body. The reason for that was that the string interpolation would happen before dedenting the template, so we would have had to partially indent the failure summary.
Also, if a required dependency (such as `pandas` or `numpy`) failed to import, the nightly CI would still try to run the test.
This should fix both issues.
cc @andersy005

fix the formatting of the nightly CI

---

xarray/backends/api.py
xarray/backends/apiv2.py

- No test added, but all tests pass.
- No new functions/methods.
**The change affects only APIv2.**
Pros:
- `open_dataset` passes the dataset description object `filename_or_obj` to the backends without fiddling with it. This is more and more important as several backends know how to open `dict`s, `file`'s `str`s that are not paths (*rasterio* for example accepts GDAL strings that are not paths and that is one of the reasons `engine="rasterio"` cannot be used in `open_dataset`)
Cons:
- at the moment backends expect paths to always be absolute, not sure if they use this info.

APIv2: pass user defined `filename_or_obj` to backends as is

---

xarray/backends/cfgrib_.py
xarray/backends/netCDF4_.py
xarray/backends/pseudonetcdf_.py
xarray/backends/pydap_.py
xarray/backends/pynio_.py
xarray/backends/scipy_.py
xarray/backends/store.py
xarray/backends/zarr.py

Remove `close_on_error` in store.py. This change involves only apiv2.
Currently, `api_v2.open_dataset` can take in input a store instead of a file. In case of error, xarray closes the store.
Xarray should manage the closure of a store that has been instantiated externally. 
This PR correct this behaviour in apiv2

Remove close_on_error store.py

---

xarray/backends/api.py
xarray/backends/apiv2.py
xarray/backends/plugins.py

Stop importing `api.py` in `apiv2.py` and other internal cleanups.
This is needed by another change that results in a cyclic import due to `api`.

APIv2 internal cleanups

---

xarray/core/dataset.py
xarray/tests/test_backends.py

This PR fixes https://github.com/pydata/xarray/issues/4708. It's a very small change.
Changes:
- In `dataset._check_chunks_compatibility` now it doesn't raise a warning if the last chunk % preferred_chunk != 0.
- Update tests
- Style: rename a variable inside `dataset._check_chunks_compatibility`

Fix warning on chunks compatibility

---

xarray/backends/plugins.py
xarray/tests/test_backends.py
xarray/tests/test_plugins.py

- #4646 add tests on chunking without using a `with` statement, causing unexpected warnings. 
- Add filterwarnings in test_plugins.test_remove_duplicates tests and backend_tests.test_chunking_consintency

Remove unexpected warnings in tests

---

doc/whats-new.rst
xarray/backends/api.py
xarray/backends/apiv2.py
xarray/tests/test_backends.py

This PR remove `autoclose` option from `open_dataset` (both api.py and apiv2.py) and the corresponding test `test_autoclose_future_warning` from test.py
`autoclose=True` option was deprecated in  https://github.com/pydata/xarray/pull/2261 since xarray now uses a LRU cache to manage open file handles.

remove autoclose in open_dataset and related warning test

---

setup.cfg
xarray/backends/cfgrib_.py
xarray/backends/common.py
xarray/backends/h5netcdf_.py
xarray/backends/netCDF4_.py
xarray/backends/plugins.py
xarray/backends/pseudonetcdf_.py
xarray/backends/pydap_.py
xarray/backends/pynio_.py
xarray/backends/scipy_.py
xarray/backends/store.py
xarray/backends/zarr.py
xarray/tests/test_plugins.py

This PR aims to avoid conflicts during the transition period between the old backend implementation and the new plugins.
During the transition period will coexist both external backend plugins and internal ones.
Currently, if two plugins with the same name are detected, we just pick one randomly. It would be better to be sure to use the external one.
Main changes:
- Remove from setup.cfg
-  Store in the internal backend and stored in the dictionary in plugins.py. The dictionary is updated with the external plugins detected by pkg_resources. 
- Move the class BackendEntrypoints in common.py to resolve a circular import.  
- Add a test

Remove entrypoints in setup for internal backends

---

xarray/tests/test_backends.py

Tiny cleanup to silence a couple `CachingFileManager` warnings about files not being properly closed.

Close files in PseudoNetCDF backend to avoid CachingFileManager warnings.

---

doc/conf.py
doc/whats-new.rst
xarray/core/combine.py
xarray/core/common.py
xarray/core/computation.py
xarray/core/concat.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/rolling.py

With the release of `sphinx` 3.3 we got a bit more control on the links in sections like `Returns` or `See Also`. Unfortunately, we still have the broken links from inherited docstrings, so unless we get upstream to change their docstrings we won't be able to fix that.

fix links in the documentation

---

xarray/tests/test_interp.py

There is a small typo in xarray/tests/test_interp.py.
Should read `usually` rather than `usualy`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, usualy -> usually

---

xarray/core/common.py

As minor as they come — open to the churn being greater than the benefit...

(tweak) Remove py2 compat

---

doc/whats-new.rst
xarray/backends/cfgrib_.py
xarray/tests/test_backends.py

- No new functions/methods are listed in `api.rst`

Declare only BASIC indexing for cfgrib. Fixes #4733 and ecmwf/cfgrib#157

---

doc/whats-new.rst
xarray/coding/times.py
xarray/tests/test_coding_times.py

This PR cleans up the logic used to encode and decode times with pandas so that by default we use `int64` values in both directions for all precisions down to nanosecond.  If a user specifies an encoding (or a file is read in) such that `float` values would be required, things still work as they did before.  I do this mainly by following the approach I described here: https://github.com/pydata/xarray/issues/4045#issuecomment-626257580.
In the process of doing this I made a few changes to `coding.times._decode_datetime_with_pandas`:
- I removed the checks on the minimum and maximum dates to decode, as the issue those checks were imposed for (#975) was fixed in pandas way back in 2016 (https://github.com/pandas-dev/pandas/issues/14068).
- I used an alternate approach for fixing #2002, which …

Ensure maximum accuracy when encoding and decoding np.datetime64[ns] values

---

doc/whats-new.rst
xarray/tests/test_combine.py
xarray/tests/test_computation.py
xarray/tests/test_dask.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_extensions.py
xarray/tests/test_merge.py
xarray/tests/test_sparse.py
xarray/tests/test_variable.py

IIRC `assert_identical` shows nice pytest error messages.
This was a quick regex but did a quick check that it looked reasonable.

Replace bare assert with assert_identical

---

xarray/tests/test_dask.py

Some of the `to_dask_dataframe` tests fail on the upstream-dev CI because the behavior of `pandas.DataFrame` changed (see pandas-dev/pandas#38645). For now we can silence these by computing all `dask` arrays we pass to `pandas.DataFrame`.

silence the dask dataframe upstream-dev errors

---

doc/whats-new.rst
xarray/core/dataset.py

Significantly speeds up `_construct_dataarray` by iterating over `._coord_names` instead of `.coords`. This avoids unnecessarily constructing a `DatasetCoordinates` object and massively speeds up repr construction for datasets with large numbers of variables.
Construct a 2000 variable dataset
```python
a = np.arange(0, 2000)
b = np.core.defchararray.add("long_variable_name", a.astype(str))
coords = dict(time=np.array([0, 1]))
data_vars = dict()
for v in b:
data_vars[v] = xr.DataArray(
name=v,
data=np.array([3, 4]),
dims=["time"],
coords=coords
)
ds0 = xr.Dataset(data_vars)
```
Before:
```
%timeit ds0['long_variable_name1999']
%timeit ds0.__repr__()
1.33 ms ± 23 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
2.66 s ± 52.7 ms per loop (mean …
```

Speed up Dataset._construct_dataarray

---

doc/whats-new.rst
xarray/core/common.py
xarray/core/coordinates.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/utils.py

- make _attr_sources and _item_sources lazy
- make lookup of virtual dimension coordinates lazy
- make helper class more general so it can be used for lookup of both virtual dimension and level coordinates

speedup attribute style access and tab completion

---

xarray/tests/test_backends_file_manager.py
xarray/tests/test_computation.py
xarray/tests/test_variable.py

Supresses 3 warnings we get in the test suite. Two are trivial. The third is `PytestUnraisableExceptionWarning: Exception ignored in: CachingFileManager.__del__`:
- The test triggers an error is in `CachingFileManager.__init__`:
https://github.com/pydata/xarray/blob/31d540f9d668fc5f8c1c92165f950c568778db01/xarray/tests/test_backends_file_manager.py#L205-L207
- It then tries to run `__del__` but there is an error because an attribute is not available (as `__init__` failed)
https://github.com/pydata/xarray/blob/31d540f9d668fc5f8c1c92165f950c568778db01/xarray/backends/file_manager.py#L238
- However, errors in `__del__` are ignored, therefore we get a `PytestUnraisableExceptionWarning`
I decided to suppress the error and not fix  `CachingFileManager` as I think that's nothing user-facing...

CI: ignore some warnings

---

xarray/core/missing.py
xarray/core/utils.py

Small patch to improve typing of OrderedSet: allowing more general input type in its constructor and .update method (Iterator instead of AbstractSet) helps to get rid of ``# type: ignore``.
Side-effect: some performance gain in micro-benchmark (before and after):
```
%timeit xr.core.utils.OrderedSet(range(10))
3.46 µs ± 5.37 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
```
2.06 µs ± 6.39 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

improve typing of OrderedSet

---

xarray/backends/plugins.py
xarray/core/utils.py
xarray/tests/test_backends.py

This is a minor cleanup of the backend API v2.

Remove special case in guess_engines

---

xarray/core/missing.py

Importing scipy.interpolate is slow and should only be done when necessary. Test case from 200ms to 6ms.
<sub>By default, the upstream dev CI is disabled on pull request and push events. You can override this behavior per commit by adding a `[test-upstream]` tag to the first line of the commit message.</sub>

Speed up missing._get_interpolator

---

.github/workflows/ci-additional.yaml

#4775 changed the min_deps_check CI to require `conda` as a library. This was not an issue before because we used `conda` to install the dependencies, but now that we use `mamba` instead we have to make sure `conda` is installed.
<sub>
<h3>
</h3>
</sub>

install conda as a library in the minimum dependency check CI

---

xarray/core/formatting.py

Show the printed and total number of variables in the repr.
```python
a = np.arange(0, 15)
b = np.core.defchararray.add("long_variable_name", a.astype(str))
c = np.arange(0, 25)
d = np.core.defchararray.add("attr_", c.astype(str))
e = {k: 2 for k in d}
coords = dict(time=da.array([0, 1]))
data_vars = dict()
for v in b:
data_vars[v] = xr.DataArray(
name=v,
data=np.array([0, 1]).astype(bool),
dims=["time"],
coords=coords,
)
ds1 = xr.Dataset(data_vars)
ds1.attrs = e
print(ds1)
Out[10]: 
Dimensions:               (time: 2)
Coordinates:
* time                  (time) int32 0 1
Data variables: (12/15)
long_variable_name0   (time) bool False True
long_variable_name1   (time) bool False True
long_variable_name2   (time) bool False True …
```

Print number of variables in repr

---

xarray/core/missing.py
xarray/tests/test_missing.py

`scipy.interpolate.interp1d` always forces float so make sure that `da.blockwise` understands that as well.

Always force dask arrays to float in missing.interp_func

---

doc/whats-new.rst
xarray/plot/facetgrid.py
xarray/plot/plot.py
xarray/plot/utils.py
xarray/tests/test_plot.py

Not sure if the tests are extensive enough: should I also check that `ylabel` is correct, too?
<sub>
<h3>
</h3>
</sub>

Fix interval labels with units

---

.github/workflows/upstream-dev-ci.yaml

As pointed out by @andersy005 in https://github.com/pydata/xarray/issues/4801#issuecomment-759747669, the scheduled CI is currently skipped because we have a typo in the condition:
https://github.com/pydata/xarray/blob/fb67358ceb0c386560e6a6991dd937292ba54d46/.github/workflows/upstream-dev-ci.yaml#L35
the correct event name is `schedule`
<sub>
<h3>
</h3>
</sub>

don't skip the scheduled CI

---

.github/PULL_REQUEST_TEMPLATE.md
.github/actions/detect-ci-trigger/script.sh
.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml
.github/workflows/upstream-dev-ci.yaml

This attempts to fix the CI trigger action, which fails when trying to get the commit message.
Edit: the action only fails for merge commits
<sub>
<h3>
</h3>
</sub>

fix the ci trigger action

---

.github/workflows/upstream-dev-ci.yaml

The upstream-dev CI doesn't have the version info step the other CI have.
<sub>
<h3>
</h3>
By default, the upstream dev CI is disabled on pull request and push events. You can override this behavior per commit by adding a <tt>[test-upstream]</tt> tag to the first line of the commit message. For documentation-only commits, you can skip the CI per commit by adding a <tt>[skip-ci]</tt> tag to the first line of the commit message
</sub>

add a version info step to the upstream-dev CI

---

doc/whats-new.rst
xarray/backends/api.py

Expand user dir paths (~) in open_mfdataset.

---

doc/whats-new.rst
xarray/coding/variables.py
xarray/tests/test_coding.py

cc @gerritholl, @rabernat 
<sub>
<h3>
</h3>
</sub>

fix decode for scale/ offset list

---

doc/whats-new.rst
xarray/backends/api.py
xarray/backends/apiv2.py
xarray/backends/rasterio_.py
xarray/backends/store.py
xarray/conventions.py
xarray/core/common.py
xarray/core/dataarray.py
xarray/core/dataset.py

You can now pass a `close` argument to `xr.Dataset` that closes the backend resources. This is only useful to backend developers, we need to add the documentation as per #4803 but it may need to be hidden and not documented to end-users. 
The PR is draft pending some cleanups and the documentation.

Remove the references to `_file_obj` outside low level code paths, change to `_close`

---

doc/api.rst
doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

- Closes #4658 
- Use get_index(dim) in drop_sel

Add drop_isel

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

Allow swap_dims to take kwargs

---

doc/conf.py
doc/faq.rst

iris moved its documentation to https://scitools-iris.readthedocs.io/en/stable/

iris update doc url

---

xarray/backends/apiv2.py
xarray/backends/cfgrib_.py
xarray/backends/common.py
xarray/backends/h5netcdf_.py
xarray/backends/netCDF4_.py
xarray/backends/plugins.py
xarray/backends/pseudonetcdf_.py
xarray/backends/pydap_.py
xarray/backends/pynio_.py
xarray/backends/scipy_.py
xarray/backends/store.py
xarray/backends/zarr.py
xarray/tests/test_plugins.py

Currently, the interface between the backend and xarray is the class/container BackendEntrypoint, that must be instantiated by the backend.
With this pull request, BackendEntrypoint is replaced by AbstractBackendEntrypoint. The backend will inherit from this class.
Reason for these changes:
- This type of interface is more standard.

WIP: backend interface, now it uses subclassing 

---

asv_bench/benchmarks/repr.py
xarray/core/formatting.py

I'm not able to check if this actually works for bigger arrays, but with `xr.DataArray(pd.Series(range(25_000_000), index=idx))` I get a significant speed-up of about 180x for `repr`.

speed up the repr for big MultiIndex objects

---

xarray/plot/utils.py

It is also popular to call units `unit`. Allow both keys to be appended to labels in plots.

Allow "unit" in label_from_attrs

---

ci/requirements/environment-windows.yml
ci/requirements/environment.yml

`dask` recently released a new version, but because we do something non-standard with `dask` graphs we can't use that yet (see #4860). For now I'm pinning `dask` to avoid having the CI fail for a known issue.

temporarily pin dask

---

xarray/core/dataarray.py
xarray/tests/test_dataarray.py

fix da.pad example for numpy 1.20

---

.github/workflows/ci-additional.yaml

when we introduced the `[skip-ci]` tag we decided to skip doctests CI, too. I don't think that's correct: the doctests CI checks the docs, not the code.

don't skip the doctests CI

---

doc/whats-new.rst
xarray/coding/times.py
xarray/tests/test_coding_times.py

Modify _encode_datetime_with_cftime for compatibility with cftime > 1.4.0

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py

small fixes for the docstrings of swap_dims and integrate

---

.pre-commit-config.yaml
ci/requirements/py37-min-all-deps.yml
ci/requirements/py38-all-but-dask.yml

I issued a bugfix release for the issue detected in https://github.com/pydata/xarray/pull/4810#discussion_r569830387, so we should use that. `pre-commit autoupdate` also tried to update to `mypy=v0.800`, but this fails because `mypy` does not like the redefinition of `dask_array_type` (and the other `*_type` variables in `xarray.core.pycompat`):
```
xarray/core/pycompat.py:19: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[Any]")
xarray/core/pycompat.py:29: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[Any]")
xarray/core/pycompat.py:37: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[Any]")
```
Does anyone know how to fix that?

update pre-commit hooks

---

doc/whats-new.rst
xarray/plot/utils.py
xarray/testing.py
xarray/tests/test_testing.py

ensure warnings cannot become errors in assert_

---

.pre-commit-config.yaml
setup.cfg

mypy v0.800 was ignoring our config (https://github.com/pydata/xarray/pull/4874#issuecomment-774771523)... Adding an (empty) `[mypy]` section to `setup.cfg` seems to do the trick, this is in contrast to the [documentation](https://mypy.readthedocs.io/en/stable/config_file.html#config-file-format) and may get changed again (c.f. python/mypy#9940), but it does not hurt either.
@keewis

update pre-commit hooks (mypy)

---

doc/whats-new.rst
xarray/core/missing.py
xarray/tests/test_interp.py

Previously `bounds_error` was always passed as `False` to
`scipy.interpolate.interp1d` and the value in `kwargs` was ignored
making it impossible to get bounds errors when doing 1D interpolation.

Fix `bounds_error=True` ignored with 1D interpolation

---

xarray/testing.py

follow-up to #4864. This makes sure the decorator function does not appear in the traceback.

hide the decorator from the test traceback

---

.github/workflows/ci-pre-commit-autoupdate.yaml

Inspired by the one `pandas` is using, this adds a workflow which periodically updates the `pre-commit` hook versions. For a example, see keewis/blackdoc#84
cc @andersy005

pre-commit autoupdate CI

---

doc/examples/ERA5-GRIB-example.ipynb
doc/examples/ROMS_ocean_model.ipynb
doc/examples/monthly-means.ipynb

Fix typos in example notebooks

---

doc/conf.py

Please see: https://discourse.matplotlib.org/t/canonical-documentation-have-moved/21863

Update matplotlib's canonical

---

ci/requirements/environment-windows.yml
ci/requirements/environment.yml
ci/requirements/py38-all-but-dask.yml
doc/whats-new.rst
xarray/backends/h5netcdf_.py
xarray/coding/strings.py
xarray/tests/test_backends.py

- set `decode_vlen_strings=True` for h5netcdf backend
- unpin h5py
This is an attempt to align with `h5py=>3.0.0` string decoding changes. Now all strings are read as `bytes` objects for variable-length strings, or numpy bytes arrays ('S' dtypes) for fixed-length strings [1]. From `h5netcdf=0.10.0` kwarg `decode_vlen_strings` is available. This PR makes use of this to keep backwards compatibility with `h5py=2` and conformance with `netcdf4-python`.
[1] https://docs.h5py.org/en/stable/strings.html

FIX: h5py>=3 string decoding

---

ci/requirements/doc.yml
doc/internals.rst

As suggested in #4248, this asks not to include shape and dtype in `_repr_inline_` implementations and shows `sparse` and `dask` reprs as examples.

document restrictions to the inline repr

---

asv_bench/benchmarks/rolling.py
doc/whats-new.rst
xarray/core/dtypes.py
xarray/core/rolling.py
xarray/tests/test_dataarray.py

Implements most of https://github.com/pydata/xarray/issues/4325#issuecomment-716399575
``` python
%load_ext memory_profiler
temp = xr.DataArray(np.zeros((5000, 500)), dims=("x", "y"))
roll = temp.rolling(x=10, y=20)
%memit roll.sum()
%memit roll.reduce(np.sum)
%memit roll.reduce(np.nansum)  # master  branch behaviour
```
```
peak memory: 245.18 MiB, increment: 81.92 MiB
peak memory: 226.09 MiB, increment: 62.69 MiB
peak memory: 4493.82 MiB, increment: 4330.43 MiB
```

Better rolling reductions

---

ci/requirements/doc.yml

We pinned `sphinx` to 3.3 when that came out because there were some issues we had to fix first. Since then, 3.4 and 3.5 have been released which I think don't really affect us, so this unpins `sphinx`.

unpin sphinx

---

.git_archival.txt
.gitattributes
doc/whats-new.rst
pyproject.toml
setup.cfg

Along with [`pyproject.toml`](https://snarky.ca/what-the-heck-is-pyproject-toml/), this adds support for [git archives](https://github.com/pydata/xarray/releases) using `setuptools_scm_git_archive`.
This shouldn't be a breaking change since `python setup.py sdist bdist_wheel` still works, but it makes tools that know about it (like `pip`) behave differently.
Edit: do we need a entry to `whats-new.rst`?

add pyproject.toml

---

doc/api-hidden.rst
doc/whats-new.rst
xarray/core/rolling.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

As suggested by @dcherian, this was quite similar to `rolling`; it was useful in particular to follow how the tests were implemented there.

Add DataArrayCoarsen.reduce and DatasetCoarsen.reduce methods

---

.github/workflows/ci-pre-commit-autoupdate.yaml
.github/workflows/sync_linter_versions.py

As requested in #4929, this will automatically sync the mypy version in the `mypy_only` environment file with the hook version.
Edit: triggering the linting workflow from a automatically generated PR might need a bit more investigation. `pandas` works around that by running `pre-commit run -a` after `pre-commit autoupdate` completed, but that doesn't work if we want to also run the new `mypy` CI.

autoupdate mypy

---

xarray/core/npcompat.py

This allows application of numpy ufuncs to DataArrays to typecheck correctly with Numpy 1.20
E.g. without this fix:
```
def applyufunctodataarray() -> xr.DataArray:
a = xr.DataArray(np.array([-1,2,3]))
a.__array__
b = np.abs(a)
print(b)
return b
```
will result in:
```
test.py:9: error: Argument 1 to "__call__" of "ufunc" has incompatible type "DataArray"; expected "Union[Union[int, float, complex, str, bytes, generic], Sequence[Union[int, float, complex, str, bytes, generic]], Sequence[Sequence[Any]], _SupportsArray]"
Found 1 error in 1 file (checked 1 source file)
```
While it will type check without issues with this fix.
I have not yet documented this or added tests. 
Please let me know if this change is acceptable and I am happy to do that.

Use definition of DTypeLike from Numpy if found

---

.github/workflows/parse_logs.py
.github/workflows/upstream-dev-ci.yaml
ci/install-upstream-wheels.sh

- xref #4945
Try to limit the time of "CI Upstream" to avoid a silent failure.

Upstream CI: limit runtime

---

ci/requirements/py37-bare-minimum.yml
ci/requirements/py37-min-all-deps.yml
doc/whats-new.rst

The updated policy (see #4907) allows bumping quite a few dependencies. Not sure if bumping all of them makes sense, but I'd like to see what CI does with this.

bump the dependencies

---

doc/whats-new.rst
xarray/core/dataset.py

As pointed out in #2951 I don't think we are able to deprecate the return value. If we are fine with introducing the breaking change in 0.17, I can also remove the return value here.

document update as inplace

---

doc/whats-new.rst

Let me know any changes here, fairly soon if possible! 
And please make changes liberally — what are the important features we should highlight in the heading?
Thanks

Add 0.17.0 release notes

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_dataset.py
xarray/tests/test_units.py

raise on passing axis to Dataset.reduce methods

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/variable.py
xarray/tests/test_dask.py

Second iteration upon https://github.com/pydata/xarray/pull/4884
CI is currently failing vs. dask git tip because of https://github.com/dask/dask/issues/7263 (unrelated to this PR)

Support for dask.graph_manipulation

---

xarray/core/options.py

Add docstring for set_option('display_max_rows')

Add docstring for 'display_max_rows'

---

xarray/coding/cftimeindex.py

The exception that was raised in pandas when a `datetime.timedelta` object outside the range that could be expressed in units of nanoseconds was passed to the `pandas.TimedeltaIndex` constructor changed from an `OverflowError` to an `OutOfBoundsTimedelta` error in the development version of pandas.  This PR adjusts our exception handling logic in `CFTimeIndex.__sub__` and `CFTimeIndex.__rsub__` to account for this.
<details>
Previous versions of pandas:
```python
>>> import pandas as pd; from datetime import timedelta
>>> pd.TimedeltaIndex([timedelta(days=300 * 365)])
File "pandas/_libs/tslibs/timedeltas.pyx", line 263, in pandas._libs.tslibs.timedeltas.array_to_timedelta64
TypeError: Expected unicode, got datetime.timedelta
During handling of the above …
```

Adapt exception handling logic in CFTimeIndex.__sub__ and __rsub__

---

xarray/plot/utils.py

~I'm not quite sure what happened, but our upstream-dev CI doesn't fail anymore. Looking at the build log, the install of the dev version of `matplotlib` seems to fail, so this tries to additionally remove the `matplotlib-base` package to see if the error comes up again if we make sure we get the dev version of `matplotlib`.~
`matplotlib` released a preview version to PyPI so we can run our tests again. This follows the suggestion from https://github.com/pydata/xarray/issues/4226#issuecomment-663030222: convert single levels to degenerate levels.

fix matplotlib errors for single level discrete colormaps

---

ci/requirements/py37-min-all-deps.yml

The clean thing here would be to update `min_deps_check.py` so it works properly for this case. I am not sure it's really worth it.

pin netCDF4=1.5.3 in min-all-deps

---

xarray/core/computation.py

Should we also add a `Notes` section like the one in `apply_ufunc`?

mention map_blocks in the docstring of apply_ufunc

---

doc/whats-new.rst
xarray/backends/api.py
xarray/tests/test_backends.py

Hi folks! Thank you for the awesome project! Xarray rocks!
We have adopted xarray fully in a new project and would appreciate a review on this PR asap.

Added support for numpy.bool_

---

doc/whats-new.rst
xarray/coding/variables.py
xarray/tests/test_coding.py

netCDF3 doesn't know unsigned while OPeNDAP doesn't know signed (bytes).
Depending on which backend source is used, the original data is stored
with the wrong signedness and needs to be decoded based on the _Unsigned
attribute. While the netCDF3 variant is already implemented, this commit
adds the symmetric case covering OPeNDAP.

conventions: decode unsigned integers to signed if _Unsigned=false

---

.github/workflows/cancel-duplicate-runs.yaml
.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml
.github/workflows/upstream-dev-ci.yaml

The `styfle/cancel-workflow-action` requires a token with write permissions in order to cancel duplicate runs. It turns out that the default GitHub token access made available to pull requests from forks has read permissions only. To address this issue, this PR introduces a new workflow that uses a special `workflow_run` trigger which allows the workflow to run to run with a token with write permissions. 
Cc @keewis

GHA for automatically canceling previous CI runs

---

.github/workflows/ci.yaml
.github/workflows/upstream-dev-ci.yaml
setup.cfg

`numba=0.53.0` has been released which means that we are able to construct a full environment on `python=3.9`. This also updates the required minimum versions for `pandas` and `numpy` to match `py37-bare-minimum`.

run tests on python 3.9

---

doc/_static/style.css

- This PR reduces the max-width for `.container` divs so as to address issues with RTD's multiple version badges. 
- Latest: https://xarray.pydata.org/en/latest/index.html: the rtd badge box doesn't work 
- This PR: https://xray--5039.org.readthedocs.build/en/5039/index.html: appears to be working fine
- Fixes CSS properties to enable appropriate toggle/responsiveness when using small screens. Unfortunately, this doesn't seem to have fixed the problem on small screens:

Fix sticky sidebar responsiveness on small screens

---

ci/install-upstream-wheels.sh
xarray/tests/test_sparse.py

`sparse` issued a release yesterday, which seems to break one of our tests (`numpy.allcose` on a `ndarray` and `COO` is not implemented). This enables installing the dev version of sparse in the upstream-dev CI, and I'm planning to either xfail or fix the failing test here.
Edit: ~I can reproduce the failure with `sparse=0.11.2` so that's not the reason for the failing test...~ that's wrong, a new environment downgraded to `sparse=0.11.2` will not fail, but upgrading will introduce the failure again.

install the dev version of sparse in the upstream-dev CI

---

doc/contributing.rst
doc/getting-started-guide/installing.rst

This updates the version numbers for `pandas` and `numpy`, gets rid of the warning added for `pint<0.10` and updates the url for the asv monitoring page.
See #5064

update the install guide

---

doc/whats-new.rst
xarray/backends/cfgrib_.py

If cfgrib is installed, but libeccodes.so is not installed on the system, Xarray does not load as cfgrib will throw a RuntimeError(), which is not caught.

Disable the cfgrib backend if eccodes is not installed

---

xarray/plot/plot.py
xarray/tests/test_plot.py

I chose to implement the easier fix described in https://github.com/pydata/xarray/issues/4913#issuecomment-803281142, but if refactoring `_infer_xy_labels` would be better I can do that, too.

improve the error message for invalid hue names

---

xarray/core/combine.py
xarray/tests/test_combine.py

ensure combine_by_coords raises on different types

---

ci/min_deps_check.py
doc/whats-new.rst
setup.cfg
xarray/core/common.py
xarray/core/coordinates.py
xarray/core/dask_array_compat.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/duck_array_ops.py
xarray/core/formatting.py
xarray/core/indexes.py
xarray/core/nanops.py
xarray/core/npcompat.py
xarray/core/nputils.py
xarray/core/parallel.py
xarray/core/pdcompat.py
xarray/core/rolling.py
xarray/core/utils.py
xarray/core/variable.py
xarray/plot/plot.py
xarray/tests/test_cftime_offsets.py
xarray/tests/test_cftimeindex.py
xarray/tests/test_plot.py
xarray/tests/test_testing.py

Adds error codes to all `# type: ignore` comments. mypy should raise if a different type of error is encountered. Also enable showing the error code for typing errors. See: [mypy: displaying-error-codes](https://mypy.readthedocs.io/en/stable/error_codes.html#displaying-error-codes). Also remove some `# type: ignore` that are no longer necessary.

type: ignore - use error codes

---

xarray/plot/dataset_plot.py

Based on issue #5002, I did a few tweaks to make it clearer which parts of the generated documentation apply to `quiver`, and which apply to `scatter`. I also removed references to `contourf` because that is now documented in a separate location.

Tweaked Dataset.plot docs to better describe quiver

---

xarray/core/indexing.py

Add LazilyOuterIndexedArray alias to LazilyIndexedArray for external backends to use

---

xarray/core/common.py
xarray/core/computation.py
xarray/core/dask_array_compat.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/plot/facetgrid.py
xarray/tutorial.py

Surprisingly not many changes, most of them are adding leading */** to
args, kwargs which is not clear according to numpydoc but seem like the
thigs to do, plus it's already done in a few other places.
A couple of spaces before `:`, that semantically matter. Numpydoc
improperly parse the types if there is no space before the :,
a documented parameter that does not exist on the function, and
some casing of section names.
There are a couple errors that this was not able to autofix (like
missing blank line before `Returns` section leading Numpydoc to
inpterprete "Returns" as a parameter of the function in
xarray/core/dataset.py:roll  extra parameters: {'-------', 'rolled', 'Returns'}

DOC: Autoreformat all docstrings.

---

xarray/conventions.py
xarray/tests/test_backends.py

The behaviour is not too problematic as CF checkers don't complain about the empty string, but it is aesthetically annoying.
This happens more frequently after #2844 added the auxiliary variable to `.coords`.

Do not write an empty "coordinates" attribute to a netCDF file

---

xarray/core/groupby.py
xarray/tests/test_groupby.py

Remove trailing whitespace from DatasetGroupBy representation because
flake8 reports it as a violation when present in doctests.
Fix #5130

Remove trailing space from DatasetGroupBy repr

---

xarray/backends/plugins.py
xarray/tests/test_plugins.py

Currently, a broken engine breaks xarray.open_dataset. I have added a `try except` to avoid this problem.
Old behaviour:
```python
>>> ds = xr.open_dataset('example.nc')
File "/usr/local/Caskroom/miniconda/base/envs/xarray/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-3-0c694cae8262>", line 1, in <module>
arr = xr.open_dataset("example.nc")
File "/Users/barghini/devel/xarray/xarray/backends/api.py", line 495, in open_dataset
backend = plugins.get_backend(engine)
File "/Users/barghini/devel/xarray/xarray/backends/plugins.py", line 115, in get_backend
engines = list_engines()
File "/Users/barghini/devel/xarray/xarray/backends/plugins.py", line 97, …
```

Fix broken engine breakes xarray.open_dataset

---

doc/internals/how-to-add-new-backend.rst
xarray/backends/__init__.py

This is mostly a stylistic revamp of the documentation on "How to add a new backend" after I followed the process a couple of times:
* add import statments
* use always `my_*`/`My` (there where some `your_`)
* avoid ellipsis
The main code change is adding references to `BackendEntrypoint` and `BackendArray` in `xarray.backends`.

Simplify the user experience of a backend developer (imports and docs)

---

xarray/backends/cfgrib_.py

Depending on the kind of problem `python-eccdodes` may return `RuntimeError` or `ImportError`.

Protect against an exception raised by python-eccodes

---

xarray/coding/cftimeindex.py

It seems that pandas did not include the change that led to #5006 in their latest release.  Perhaps it is safer to just catch either error regardless of the pandas version.

Catch either OutOfBoundsTimedelta or OverflowError in CFTimeIndex.__sub__ and CFTimeIndex.__rsub__

---

xarray/backends/api.py
xarray/backends/cfgrib_.py
xarray/backends/common.py
xarray/backends/h5netcdf_.py
xarray/backends/netCDF4_.py
xarray/backends/pseudonetcdf_.py
xarray/backends/pynio_.py
xarray/backends/scipy_.py
xarray/backends/zarr.py

Fix `open_dataset` regression, expands ~ in `filepath_or_obj` when necessary. 
I have checked the behaviour of the engines. It seems that `pynio`  already expands  ~.

Fix open_dataset regression

---

xarray/core/common.py

I'm adding a method to this class — separate PR — and noticed this. 
At least for `RollingExp`, we don't need this class attribute. 
I think the others, like `Rolling` / `Coarsen` maybe require different classes for DataArray / Dataset, so I'm less confident on those.

Small simplification to RollingExp

---

doc/whats-new.rst
xarray/coding/times.py
xarray/tests/test_coding_times.py

This fixes the issue in #5093, by ensuring that we always convert the calendar to lowercase before checking if it is one of the standard calendars in the decoding and encoding process.  I've been careful to test that the calendar attribute is faithfully roundtripped despite this, uppercase letters and all.
~~I think part of the reason this went unnoticed for a while was that we could still decode times like this if cftime was installed; it is only in the case when cftime was not installed that our logic failed.  This is because `cftime.num2date` already converts the calendar to lowercase internally.~~
Upon re-reading @pont-us's issue description, while it didn't cause an error, the behavior was incorrect with cftime installed too.  I updated the test to check the dtype is `np.datetime64` …

Convert calendar to lowercase in standard calendar checks

---

xarray/core/variable.py

I saw a few of these while looking through the code — generally we're using `._replace` now, so this grows that convention to `variable.py` too. It was a regex replace but I took a look through to confirm. And fixed one mypy error which the change caught.

Use ._replace rather than reconstructing vars

---

ci/requirements/doc.yml
doc/api-hidden.rst
doc/api.rst
doc/internals/how-to-add-new-backend.rst
doc/internals/zarr-encoding-spec.rst
doc/user-guide/computation.rst
doc/user-guide/weather-climate.rst
doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py

This fixes a few broken links in our RST files and moves a few links.
Note that the module referenced here: https://github.com/pydata/xarray/blob/b5a84baa96c244a35004f940bd5f25737e984553/doc/internals/how-to-add-new-backend.rst#L430-L432
does not have a API page, yet. Should we try to fix that, or would linking to github be better? Also, were the `explicit indexing` and `numpy indexing` meant to be links or literal text?

link maintenance

---

xarray/core/dataset.py

Fixes rendering in https://github.com/pydata/xarray/pull/5163

DOC: fix link to io.zarr

---

doc/whats-new.rst
xarray/tests/test_accessor_dt.py
xarray/tests/test_backends.py
xarray/tests/test_cftimeindex.py
xarray/tests/test_coding_strings.py
xarray/tests/test_combine.py
xarray/tests/test_computation.py
xarray/tests/test_concat.py
xarray/tests/test_conventions.py
xarray/tests/test_dask.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_duck_array_ops.py
xarray/tests/test_extensions.py
xarray/tests/test_formatting.py
xarray/tests/test_groupby.py
xarray/tests/test_indexing.py
xarray/tests/test_merge.py
xarray/tests/test_missing.py
xarray/tests/test_plot.py
xarray/tests/test_ufuncs.py
xarray/tests/test_variable.py
xarray/tests/test_weighted.py

Is there a reason we have our own `raises_regex`? This replaces it with the standard pytest check.
This is another regex special, so it misses multi-line statements. I can dust off the multi-line regex manual if this ends up working.

Replace raises_regex with pytest.raises

---

doc/whats-new.rst
xarray/plot/plot.py
xarray/tests/test_plot.py

Use broadcast_like if either `x` or `y` inputs are 2d to ensure that both have dimensions in the same order as the DataArray being plotted. Convert to numpy arrays after possibly using broadcast_like. Simplifies code, and fixes #5097 (bug when dimensions have the same size).
@dcherian
> IIRC the "resolving intervals" section later will break and is somewhat annoying to fix. This is why the current ugly code exists.
This change seems to 'just work', and unit tests pass. Is there some extra check that needs doing to make sure "resolving intervals" is behaving correctly?
I can't think of a unit test that would have caught #5097, since even when the bug happens, a plot is produced without errors or warnings. If anyone has an idea, suggestions/pushes welcome!

Use broadcast_like for 2d plot coordinates

---

doc/whats-new.rst
xarray/core/duck_array_ops.py
xarray/tests/test_duck_array_ops.py

Avoids changing the datatype if the data does not have the requested
axis.

Skip mean over empty axis

---

doc/whats-new.rst
xarray/core/formatting.py
xarray/core/formatting_html.py
xarray/core/options.py
xarray/tests/test_formatting.py
xarray/tests/test_formatting_html.py

Add options to control expand/collapse of sections in display of Dataset and DataArray

---

doc/whats-new.rst
xarray/core/common.py
xarray/core/rolling.py
xarray/core/variable.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

As per https://github.com/pydata/xarray/issues/3891#issuecomment-612522628 I also changed the default to `True`.

coarsen: better keep_attrs

---

doc/whats-new.rst
xarray/backends/api.py
xarray/core/combine.py
xarray/tests/test_backends.py

Fixes bug which allowed incorrect arguments to be passed to `open_mfdataset` without complaint.
The combination `open_mfdataset(files, combine='by_coords', concat_dim='t')` should never have been permitted, and in fact it [wasn't permitted](https://github.com/pydata/xarray/blob/795926a50c690cae20e928f2514b2269f09a9b91/xarray/core/combine.py#L597) until the last part of the deprecation process from the old `auto_combine`. It makes no sense to pass this combination because the `combine_by_coords` function does not have a `concat_dim` argument at all!
The effect was pretty benign - the `concat_dim` arg wasn't really used for anything in that case, and the result of passing dodgy datasets would just be a less informative error. However there were multiple tests which assumed this behaviour …

open_mfdataset: Raise if combine='by_coords' and concat_dim=None

---

xarray/tests/test_backends.py

This consistently fails.
In general I think as soon as we see this happening, we should either fix immediately (but probably not that easy) or xfail it and if necessary open an issue. That keeps the main branch green, such that we can reliably use passing tests as an indicator of PRs.
Though as ever, very open to other thoughts. There's a reasonable argument that "keeping master green by removing any failing tests is missing the point a bit"...

xfail very flaky test

---

xarray/core/dataarray.py
xarray/core/dataset.py

Add query examples in the docstrings.
Relevent rtd buld links:
- https://xray--5249.org.readthedocs.build/en/5249/generated/xarray.Dataset.query.html?highlight=query#xarray.Dataset.query
- https://xray--5249.org.readthedocs.build/en/5249/generated/xarray.DataArray.query.html?highlight=query#xarray.DataArray.query

DOC: add query examples

---

xarray/core/dataset.py

As I understand it, the issue described in #5248 is caused by bad indentation... With this PR, we get the following:
@max-sixty, let me know if there are other instances that need to be fixed as part of this PR....

Fix bulleted list indentation in docstrings

---

doc/user-guide/io.rst
doc/whats-new.rst
xarray/backends/api.py
xarray/tests/test_backends.py

Changes error introduced in #5231 into a warning, [as discussed](https://github.com/pydata/xarray/discussions/5253).

Warn instead of error on combine='nested' with concat_dim supplied

---

doc/api.rst
doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_dataset.py

Add to_pandas method for Dataset

---

doc/whats-new.rst
xarray/backends/api.py
xarray/backends/pydap_.py
xarray/backends/zarr.py

@TomNicholas and all, sorry again for addressing this late.

More correct deprecation warning for `lock` argument

---

ci/requirements/py37-min-all-deps.yml
doc/whats-new.rst
xarray/core/dataset.py
xarray/core/missing.py

Faster interp

---

xarray/core/merge.py
xarray/tests/test_merge.py

follow-up to #4902: the way it was written, calling `xr.merge(..., combine_attrs="no_conflicts", compat="minimal")` would silence `MergeError`. The tests didn't catch this because I was trying to test both variables and dimension variables at the same time, and the dimension variable raised.
If I'm wrong in assuming that `compat="minimal"` should not interfere with `combine_attrs` I guess we can close this (or remove everything except the change to raise the merge error from the value error).

combine_attrs merge errors with compat="minimal" are silenced

---

test_sample.py
xarray/core/indexing.py
xarray/tests/test_dask.py

Parametrize test for __setitem__ (for dask array)

---

.github/workflows/pypi-release.yaml

This addresses https://github.com/pydata/xarray/issues/5232#issuecomment-830242266, and will (hopefully) reduce the time it takes to cut a new release.

Add GitHub action for publishing artifacts to PyPI

---

.github/workflows/pypi-release.yaml

follow-up to #5244: as far as I can tell, it does not run on tags. We also have to decide whether we want to fix uploading dev versions (i.e. new commits on master) because `setuptools-scm` creates versions which are rejected by PyPI.
cc @andersy005

pypi upload workflow maintenance

---

.github/workflows/pypi-release.yaml

uploading to TestPyPI works now, but the check afterwards still fails, which I think is because we use `--index-url` instead of `--extra-index-url`

fix the build wheel test

---

.github/workflows/cancel-duplicate-runs.yaml
.github/workflows/ci-additional.yaml
.github/workflows/ci-pre-commit.yml
.github/workflows/ci.yaml
.github/workflows/upstream-dev-ci.yaml

Currently, the CI runs both on a user's fork and `pydata/xarray`. This leads to duplicate runs and the user is flooded with GitHub notifications in case of failures... This PR addresses this issue by making sure the workflows are triggered on `pydata/xarray` only.

Disable workflows on forks

---

xarray/core/formatting.py
xarray/tests/test_formatting.py

See discussion in https://github.com/pydata/xarray/pull/5126#pullrequestreview-645689987

Fix exception when display_expand_data=False for file-backed array.

---

doc/whats-new.rst

@TomNicholas @dcherian & @pydata/xarray please review and propose changes
I'm at the item 6. of the how to release guide.

Initial draft of the 0.18.0 release highlights

---

doc/whats-new.rst

This mostly fixes the formatting and a few broken links.

more maintenance on whats-new.rst

---

xarray/core/parallel.py

This PR updates how we construct the `HighLevelGraph` in `subset_dataset_to_block`. Currently we create a `HighLevelGraph` and then manually add a few new layers, which are `dict`s, directly to `hlg.layers`.
https://github.com/pydata/xarray/blob/eec2b59bd08498fe3d50d8549b540d0a8409c7ac/xarray/core/parallel.py#L537-L546
However since (in more recent versions of Dask)  [`HighLevelGraph` layers are expected to be `Layer` class instances](https://github.com/dask/dask/blob/23c93d72c8fbd194b44614c29dd584ff93fc1eef/dask/highlevelgraph.py#L578-L582) this can result in unexpected errors (xref https://github.com/pydata/xarray/issues/5077#issuecomment-832359943). Instead of manually adding new layers to `hlg.layers`, this PR proposes we create a new `HighLevelGraph` altogether to ensure that …

Ensure `HighLevelGraph` layers are `Layer` instances

---

xarray/core/computation.py

while working on #5041, I noticed that there are a few examples which are not doctests (and thus won't be autoformatted).

convert the examples for apply_ufunc to doctest

---

doc/api.rst
xarray/plot/facetgrid.py

Summary:
* Add `FacetGrid.add_quiverkey` to `api.rst`
* Other edits similar to #5285

FacetGrid docstrings

---

doc/contributing.rst
doc/whats-new.rst

Inspired by a question asked in #4696, but does not close that issue

Explained what a deprecation cycle is

---

HOW_TO_RELEASE.md
doc/whats-new.rst

Updated the release guide to account for what is now automated via github actions, and any other bits I felt could be clearer.
Now only 16 easy steps!
- Motivated by #5232 and #5244

Update release guide

---

doc/whats-new.rst
xarray/coding/times.py
xarray/tests/test_coding_times.py

Although the error raised by this commit does not include the whole units string, I believe it is actually more useful and specific since it focuses on the part (reference date) that's actually causing the problem.
Also, the reference date is the only information available in `coding.times._ensure_padded_year`, so this is the simplest way of raising an error.
I had a look in `tests/test_coding_times.py` and could not find a test for this related error raising (since I'd put a test for this commit around there)
https://github.com/pydata/xarray/blob/234b40a37e484a795e6b12916315c80d70570b27/xarray/coding/times.py#L127-L129
Have I missed it?
EDIT: I've tried to substitute the error raise on line 129 with a `pass` and all the tests passed anyway.

Raise error for invalid reference date for encoding time units

---

ci/requirements/doc.yml

This can be reverted once the `nbsphinx` feedstock copies the library's pins.

pin jinja2

---

xarray/core/dataset.py

This is a minor docstr correction.
`Dataset.drop_dims` docstr said it was returning errors in golang-like way that made me double-take.
Thanks!

Remove bad extra Returns in Dataset.drop_dims docstr

---

doc/contributing.rst

Another minor doc fix. This points Pydagogue link in contributing docs to correct URL. It was a broken link.
Thanks!

Fix broken Pydagogue URL

---

ci/requirements/doc.yml

Follow-up to #5303. The feedstock has been updated (thanks for the ping, @kmuehlbauer), so we can unpin it again.

unpin jinja2

---

doc/whats-new.rst
xarray/backends/h5netcdf_.py
xarray/backends/netCDF4_.py
xarray/backends/scipy_.py
xarray/core/utils.py
xarray/tests/test_backends.py

The new version checks magic numbers in files on disk, not just already open file objects.
I've also added a bunch of unit-tests.
Fixes GH5295

More robust guess_can_open for netCDF4/scipy/h5netcdf entrypoints

---

xarray/core/dataset.py

fix drop_dims docs

---

.github/workflows/ci-pre-commit-autoupdate.yaml

This implements the easier fix described in #5241 which doesn't involve creating a personal access token (which I *think* is tied to a specific account, even though it is set on a repository). Of course, it would be great to have the `Additional CI` and `linting` workflows run on PRs created by the action.

run pre-commit on all files after autoupdating

---

xarray/core/variable.py

Having `new_shape` as a `list` broke some checks in sparse. `.shape` is usually a tuple so I changed `new_shape` to be a tuple as well. sparse arrays errors one step further down now instead, at the item assignment...
- Related to #5315

Convert new_shape from list to tuple in _unstack_once

---

xarray/core/dask_array_compat.py
xarray/core/indexing.py
xarray/core/pycompat.py
xarray/core/utils.py

It was difficult to do version checks with optional imports so I added variables in pycompat and removed some of the imports I found.

Add version variable for optional imports in pycompat

---

setup.cfg
xarray/tutorial.py

Since it seems difficult to fix the situation using the package manager, this improves the error message by explicitly suggesting to install `pooch`.

improve the error message when pooch is not installed

---

doc/conf.py
doc/whats-new.rst
xarray/plot/dataset_plot.py
xarray/plot/plot.py

Summary:
* use code-literal style for variables (arguments) and other Python identifiers
* fix some type specifications
* add more references where helpful
* italic for *x* and *y* when talking about axes, like in math
* correct a bit of grammar stuff
* tell which Matplotlib function is being wrapped at the top
* capitalize Matplotlib when referring to the library in general, since that is how they do it in their docs, like xarray is lowercase unless starting the sentence
* ~~remove `ax` from the signature of the `_dsplot` functions (unlike the `_plot2d` ones, it shows in the built docs)~~ (save for later PR, so can do deprec. cycle because users might have been using `ax` positionally)
* fix `matplotlib colormap name` Napoleon type alias
* remove unused `u` and `v` from signature of …

Clean up and enhance plot method docstrings

---

xarray/backends/plugins.py
xarray/tests/test_backends.py
xarray/tests/test_plugins.py
xarray/tutorial.py

Also includes a better error message when loading a tutorial dataset but an underlying IO dependency is not found.

Better error message when no backend engine is found.

---

HOW_TO_RELEASE.md
doc/whats-new.rst

0.18.1 release notes

---

.github/workflows/upstream-dev-ci.yaml

follow-up to #5343, which got the upstream-dev CI to run but unfortunately not the "report" job.

second attempt to fix the upstream-dev CI

---

doc/getting-started-guide/quick-overview.rst
doc/internals/duck-arrays-integration.rst
doc/user-guide/data-structures.rst

As discussed in other issues — I find this way significantly easier to read, particularly when we're passing tuples of tuples as part of the construction. I did these manually but can write something to do it more broadly if people agree.

Use dict in docs Dataset construction

---

xarray/tests/test_dataarray.py

I think we could consider gradually moving to this fixture model of tests, where we pass `da` and it's paramaterized across dask / numpy (and anything we choose to add in the future). And it's possible to select the backing array type like selecting any other fixture type.
The general proposal probably needs some socializing and refinement before we start applying it more broadly. I'd be keen to pursue it if others agree — it could bring some more robustness to our testing suite while also making it simpler.

Add dask stack tests

---

doc/whats-new.rst
xarray/coding/cftimeindex.py

Pandas recently deprecated the `kind` argument in `Index._maybe_cast_slice_bound`, and removed its use in several internal calls: https://github.com/pandas-dev/pandas/pull/41378.  This led to some errors in the CFTimeIndex tests in our upstream build.  We never made use of it in `CFTimeIndex._maybe_cast_slice_bound` so the simplest fix for backwards compatibility seems to be to make it optional for now -- in previous versions of pandas it was required -- and remove it when our minimum version of pandas is at least 1.3.0.

Make `kind` argument in `CFTimeIndex._maybe_cast_slice_bound` optional

---

xarray/tests/test_cupy.py

This change simply update CuPy tests for v9 support, where `cupy.core.core.ndarray` was removed in favor of `cupy.ndarray`. That was already available in v8 so it doesn't break backwards compatibility either.

Update test for CuPy v9

---

xarray/core/formatting.py

In preparation of pushing these upstream, this increases the priority of the `_repr_inline_` implementation of `dask` or `sparse` (once they are implemented) over our own custom functions.

prefer the objects _repr_inline_ over xarray's custom reprs

---

xarray/tests/test_dataset.py

`test_resample_loffset` failed on i586 with Python 3.9 as it used
`assert_identical`.
Changed to the more permissive `assert_allclose`.

use assert_allcose on test_resample_loffset

---

doc/examples/apply_ufunc_vectorize_1d.ipynb

I noticed that the apply_ufunc tutorial notebook says that `xarray.apply_ufunc` uses `dask.array.blockwise`, but that's no longer true as of PR #4060 .

Corrected reference to blockwise to refer to apply_gufunc instead

---

doc/whats-new.rst
xarray/core/computation.py
xarray/tests/test_computation.py

Was reading the discussion [here](https://github.com/pydata/xarray/issues/4804) and thought I'd draft a PR to implement some of the changes people suggested. It seems like the main problem is that currently in `computation.py`, `if not valid_values.all()` is not a lazy operation, and so can be a bottleneck for very large dataarrays. To get around this, I've lifted some neat tricks from #4559 so that `valid_values` remains a dask array. 
---

Dask-friendly nan check in xr.corr() and xr.cov()

---

xarray/core/dataarray.py

I found that the options for the `missing_dims` parameter where described inconsistently in the docstring (`"warning" vs "warn").
Not sure I found all occurrences of it here.

Inconsistent docstring for isel etc.

---

doc/whats-new.rst
xarray/core/utils.py
xarray/tests/test_utils.py

Cast PandasIndex to pd.(Multi)Index

---

doc/whats-new.rst
xarray/core/formatting.py
xarray/tests/test_formatting.py

In #5235 we seem to have accidentally broken the `repr` of `Variable` objects with `display_expand_data=False`. I don't think `Variable` objects benefit from the collapsed view, so the easiest fix seems to be to always use `short_data_repr` for `Variable` objects.

fix the variable repr with `display_expand_data=False`

---

xarray/tests/conftest.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

Also adds an example of parameterizing a test in dataset.py
This uses the backend fixture (though not the `dataset` fixture, like https://github.com/pydata/xarray/pull/5350/files did)

Promote backend test fixture to conftest

---

.github/workflows/ci.yaml
test-results.xml

I'm not sure this is the best approach; potentially the comment this app adds is too noisy: https://github.com/marketplace/actions/publish-unit-test-results.
But it would be good to get an idea of the test results from the PR page and to understand where the test suite spends its time

Add junit test results to CI

---

xarray/core/computation.py

The suggestion appears to be copy/paste-friendly but the format was slightly off.

Fix invalid suggestion in error in apply_variable_ufunc

---

xarray/tests/test_computation.py

This was changed in dask/dask#7669. Looks like they did not deprecate this behavior (i.e. passing both `meta` and `output_dtypes`). I'd suggest to follow dask's example here and not add a deprecation cycle. Thoughts?

fix dask meta and output_dtypes error

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_units.py

Apparently the test coverage was not high enough: we were passing a `Variable` object to `numpy.gradient`. This only adds tests for `DataArray.differentiate` because `Dataset.differentiate` doesn't seem to be as easy to check (the axis might be different).

`differentiate` should not cast to `numpy.array`

---

xarray/plot/utils.py
xarray/tests/test_plot.py

matplotlib warns: `Calling gca() with keyword arguments was deprecated in Matplotlib 3.4. Starting two minor releases later, gca() will take no keyword arguments. The gca() function should only be used to get the current axes, or if no axes exist, create new axes with default keyword arguments. To create a new axes with non-default arguments, use plt.axes() or plt.subplot().`
This only uses `plt.gca()` if there are active axes, else it calls `plt.axes(**kwargs)`. Note that this can silently ignore some arguments. However, that this is already the case.

plt.gca() no longer accepts kwargs

---

xarray/core/dataset.py
xarray/tests/test_backends.py
xarray/tests/test_dask.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_distributed.py
xarray/tests/test_indexing.py
xarray/tests/test_interp.py
xarray/tests/test_sparse.py

Silences a number of warnings that accumulated in our test suite (c.f. #3266). The changes are mostly unrelated but small.

Silence some test warnings

---

xarray/core/computation.py
xarray/core/duck_array_ops.py

Found a few more places where modules are being imported just for version checking.

Use checks from .pycompat in more places

---

xarray/tests/test_plot.py

nc-time-axis [version 1.3.0](https://github.com/SciTools/nc-time-axis/releases/tag/v1.3.0) was released today (thanks @bjlittle!), which includes various fixes for incompatibilities with the latest version of cftime.  This means that our tests that depend on nc-time-axis should now pass.

Remove `xfail` decorator from tests that depend on nc-time-axis

---

xarray/tests/test_duck_array_ops.py

This addresses the `test_datetime_mean` failures reported in #5366.  Pandas now requires that we make sure the units of datetime arrays are specified explicitly in array constructors: https://github.com/pandas-dev/pandas/issues/36615#issuecomment-860040013.

Explicitly state datetime units in array constructors in `test_datetime_mean`

---

xarray/core/dataset.py
xarray/tests/test_dataset.py

Lists passed to `__getitem__` are converted to arrays. `np.asarray` infers the dtype, and for example converts a list with str and int to an array of str. Forcing `dtype="O"` fixes the issue.

Allow selecting variables using a list with mixed data types

---

xarray/core/dataset.py
xarray/tests/test_dataset.py

Reduce methods such as `mean` drop non-numeric variables. However, there's no need to drop variables that are not actually reduced (i.e., when `"reduce_dim" not in da.dims`).
cc: @rcaneill

Don't drop unreduced variables

---

doc/user-guide/indexing.rst

Added explanation of new feature (PR #5045) that allows assigning values to a subset of a dataset to the documentation.

Dataset subset assignments in doc

---

xarray/core/merge.py

Keewis mentioned other options to `merge` are `concat` and `combine_by_coords` (https://github.com/pydata/xarray/discussions/5462#discussioncomment-861492). This PR adds `combine_by_coords` in the see also docstring of `merge`

DOC: add combine_by_coords in merge see also

---

xarray/core/duck_array_ops.py
xarray/core/npcompat.py
xarray/core/variable.py

Remove some compatibility code that doesn't seem necessary anymore.

Remove npcompat.moveaxis

---

xarray/core/dataarray.py
xarray/core/dataset.py

Attempt to fix errors found in #5365. I've changed it to integers because when does it ever make sense to input 1.5 or a complex number? It will always be forced to integers anyway: https://github.com/dask/dask/blob/8aea537d925b794a94f828d35211a5da05ad9dce/dask/array/core.py#L2815
Integers don't work with Numbers:
```
xarray/core/computation.py:1576: error: Dict entry 0 has incompatible type "Hashable": "int"; expected "Hashable": "Union[None, Number, str, Tuple[Number, ...]]"  [dict-item]
xarray/core/computation.py:1576: error: Dict entry 0 has incompatible type "Hashable": "int"; expected "Hashable": "Union[None, Number, Tuple[Number, ...]]"  [dict-item]
xarray/core/computation.py:1536: error: Dict entry 0 has incompatible type "Hashable": "int"; expected "Hashable": "Union[None, …
```

Use integer type hints in chunk functions 

---

doc/getting-started-guide/installing.rst
setup.cfg
xarray/core/utils.py

Add typing-extensions to dependencies

---

doc/whats-new.rst
xarray/plot/plot.py
xarray/plot/utils.py
xarray/tests/test_plot.py

```python
a = xr.DataArray(
[0, 1, 2],
dims=("dim_1"),
coords=dict(dim_1=(["dim_1"], ["u", "v", "w"])),
)
a.plot()
```
```python
a = xr.DataArray(
[[0, 1, 2], [3, 4, 5]],
dims=("dim_0", "dim_1"),
coords=dict(dim_0=(["dim_0"], [0, 1]), dim_1=(["dim_1"], ["u", "v", "w"])),
)
a.plot()
```

Allow plotting categorical data

---

xarray/core/dataset.py

It took me a while to realize this so I wanted to make a note in the docs for myself in the future and others uses.
I was playing with pint-xarray and I couldn't work out why I couldn't round trip a file (https://github.com/xarray-contrib/pint-xarray/issues/109). It turns out the DataArray had an enconding attribute which was being used (and overriding my unit conversion). In addition, I was also scratching my head for a while as to where my zarr store was getting chunks from which didn't correspomd to my numpy array (https://github.com/pydata/xarray/discussions/5407).
This PR just makes a note of the importance of encoding attribute of DataArray(s) when writing to a zarr store.
docs page change is here: https://xray--5427.org.readthedocs.build/en/5427/generated/xarray.Dataset.to_zarr.html …

DOC: zarr note on encoding

---

xarray/tests/__init__.py
xarray/tests/test_dataset.py
xarray/tests/test_groupby.py

- xref #5409
Just moves the tests out, in preparation for numpy_groupies work
There are a few tests for `.assign` and `.fillna` (for e.g.) still present in `test_dataset`
The DataArray tests are not a simple copy and paste :(

Refactor dataset groupby tests

---

xarray/backends/cfgrib_.py
xarray/backends/h5netcdf_.py
xarray/backends/netCDF4_.py
xarray/backends/plugins.py
xarray/backends/pseudonetcdf_.py
xarray/backends/pydap_.py
xarray/backends/pynio_.py
xarray/backends/scipy_.py
xarray/backends/store.py
xarray/backends/zarr.py
xarray/tests/test_backends.py
xarray/tests/test_plugins.py

When open_dataset() fails because no working engines are found, it suggests installing the dependencies of the compatible internal backends, providing explicitly the list.

Improve error message for guess engine

---

xarray/core/accessor_str.py
xarray/core/computation.py
xarray/core/formatting.py
xarray/core/indexes.py

The minimal typing for numpy 1.21. As always I am by no means a typing specialist.

typing for numpy 1.21

---

doc/internals/how-to-add-new-backend.rst

Copy pasting the examples in  http://xarray.pydata.org/en/stable/internals/how-to-add-new-backend.html resulted in crashes. Make the docs copy/paste friendly by removing the self arguments.
Example:
```python
expected = xr.Dataset(
dict(a=2 * np.arange(5)), coords=dict(x=("x", np.arange(5), dict(units="s")))
)
class CustomBackend(xr.backends.BackendEntrypoint):
def open_dataset(
self,
filename_or_obj,
drop_variables=None,
**kwargs,
):
return expected.copy(deep=True)
xr.open_dataset("fake_filename", engine=CustomBackend)
TypeError: open_dataset() missing 1 required positional argument: 'filename_or_obj'
```
This works if self is removed:
```python
expected = xr.Dataset(
dict(a=2 * np.arange(5)), coords=dict(x=("x", np.arange(5), dict(units="s")))
)
class …
```

Remove self from classes in How to add new backends docs

---

xarray/core/variable.py

Make the transpose faster.
* `get_axis_num` seems slow, avoid triggering it unnecessarily for example when using 1d arrays.
* .copy(deep=False) is the bottleneck for 1d arrays. Not sure if it can be dealt with though.

Faster transpose

---

xarray/core/dataarray.py

Both `set_index` and `reset_index` are wrappers to other methods that return `"DataArray"`, not `Optional["DataArray"]`. That is, they will never return None. That's why these methods should also have only `"DataArray"` in there return signature. This way it will be possible to do something like `myarray = myarray.reset_index(...)` without getting a complaint from Mypy.
For extended discussion, see https://github.com/pydata/xarray/issues/5533#issuecomment-869822366

Fix 2 type annotations in dataarray.py

---

xarray/tests/__init__.py
xarray/tests/test_cftime_offsets.py
xarray/tests/test_missing.py

The checks that didn't install cftime skipped the entire test_missing.py. Because cftime is also imported when importing the list of calenders `_CFTIME_CALENDERS`.
Added also skips for the cases that assumed cftime was installed so they are correctly skipped.

Test test_missing.py without cftime installed

---

doc/whats-new.rst
xarray/plot/plot.py
xarray/plot/utils.py
xarray/tests/test_plot.py

When inferring the interval breaks, the `coord` and first linearized if
`scale="log"` and then the intervals are brought back to the original scale
before being returned to `pcolormesh`. Raise an error if at least one of the
elements of the coodinates has a non-positive element when using a logscale.

Properly infer intervals of pcolormesh when plotting on logscale

---

ci/install-upstream-wheels.sh

check the development version of fsspec in the upstream-dev CI

---

doc/getting-started-guide/installing.rst
xarray/tests/test_backends.py
xarray/tests/test_computation.py
xarray/tests/test_dask.py
xarray/tests/test_distributed.py
xarray/tests/test_formatting_html.py

- fixes one of the issues reported in #5600
- ``distributed.utils_test.gen_cluster`` no longer accepts timeout=None for the sake of robustness
- deleted ancient dask backwards compatibility code
- clean up code around ``dask.__version__``

Fix gen_cluster failures; dask_version tweaks

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/core/variable.py
xarray/tests/test_dataset.py
xarray/tests/test_variable.py

Regarding https://github.com/pydata/xarray/issues/5550#issuecomment-875040245, inside the for loop only a Variable's dimensions are selected for the transpose, so a dimension that it's missing in all DataArrays would just be ignored silently. Hence it's necessary to check at the beginning of the function.
https://github.com/pydata/xarray/blob/5489effbe7d83451a75382f842c4f5f96ead069f/xarray/core/dataset.py#L4591

Accept missing_dims in Variable.transpose and Dataset.transpose

---

xarray/tests/test_backends.py
xarray/tests/test_interp.py

added netCDF4 requirement to failing tests

---

ci/requirements/environment-windows.yml
ci/requirements/environment.yml

As discussed this pins `fsspec` to known good versions, which should hopefully make sure the CI passes.

pin fsspec

---

.pre-commit-config.yaml
doc/getting-started-guide/installing.rst
setup.cfg
xarray/core/utils.py

Type checking may be a little worse if typing-extensions are not installed, but I don't think it's worth the trouble of adding another hard dependency just for one use for TypeGuard.
Note: sadly this doesn't work yet. Mypy (and pylance) don't like the type alias defined with try/except. Any ideas? In the worst case, we could revert the TypeGuard entirely, but that would be a shame...

Make typing-extensions optional

---

doc/api-hidden.rst
doc/whats-new.rst
xarray/core/combine.py
xarray/core/common.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/rolling.py
xarray/core/variable.py
xarray/tests/test_coarsen.py
xarray/tests/test_dask.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_variable.py

As discussed in the meeting yesterday, here's the PR for the scheduled deprecations. We also have quite a few deprecations which are not scheduled... we should check which of them can be removed / completed, but that can wait until after the release.
I tried to keep the changes for each individual deprecation in their own commit, which should make rolling back easier in case we decide removing / completing a specific deprecation is too aggressive.
`whats-new.rst` still needs to be updated, but I'll leave that until after the code changes have been approved.

remove deprecations scheduled for 0.19

---

.binder/environment.yml

As far as I can tell, the examples on binder currently fail because `pooch` is not installed.

fix the binder environment

---

asv_bench/benchmarks/repr.py
doc/whats-new.rst
xarray/core/formatting.py

Creating a ordered list for filtering purposes using `.items()` turns out being rather slow. Use `.keys()` instead as that doesn't trigger a bunch of dataarray initializations.
Test case:
```python
a = np.arange(0, 2000)
data_vars = dict()
for i in a:
data_vars[f"long_variable_name_{i}"] = xr.DataArray(
name=f"long_variable_name_{i}",
data=np.arange(0, 20),
dims=[f"long_coord_name_{i}_x"],
coords={f"long_coord_name_{i}_x": np.arange(0, 20) * 2},
)
ds0 = xr.Dataset(data_vars)
ds0.attrs = {f"attr_{k}": 2 for k in a}
```
Before:
```python
%timeit print(ds0)
14.6 s ± 215 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
After:
```python
%timeit print(ds0)
120 ms ± 2.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Speed up _mapping_repr

---

xarray/core/parallel.py

xref https://github.com/pydata/xarray/pull/5636/files#r679823542
avoid `len(index)` in two places.

Flexible Indexes: Avoid len(index) in map_blocks

---

doc/whats-new.rst
xarray/core/alignment.py
xarray/core/combine.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/indexes.py
xarray/core/indexing.py
xarray/core/merge.py
xarray/core/parallel.py
xarray/core/variable.py
xarray/tests/test_backends.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_indexes.py
xarray/tests/test_indexing.py
xarray/tests/test_utils.py
xarray/tests/test_variable.py

This implements option 3 (sort of) described in https://github.com/pydata/xarray/issues/5553#issue-933551030:
- the goal is to avoid wrapping an `xarray.Index` into an `xarray.Variable` and keep those two concepts distinct from each other.
- the `xarray.Index.from_variables` class constructor accepts a dictionary of `xarray.Variable` objects as argument and may (or should?) also return corresponding `xarray.IndexVariable` objects to ensure immutability.
- for `PandasIndex`,  the new returned `xarray.IndexVariable` wraps the underlying `pd.Index` via a `PandasIndexingAdapter` (this reverts some changes made in #5102).
- for `PandasMultiIndex`, this PR adds `PandasMultiIndexingAdapter` so that we can wrap the pandas multi-index in separate coordinate variables objects: one for the dimension …

Refactor index vs. coordinate variable(s)

---

xarray/core/options.py

Minor change to align with other booleans.

Use the same bool validator as other inputs for use_bottleneck in xr.set_options

---

doc/whats-new.rst
xarray/plot/utils.py
xarray/tests/test_plot.py
xarray/tests/test_utils.py

This PR changes the function `label_from_attrs()` to wrap text differently if we think it's a LaTeX sequence. This prevents long LaTeX names from not being rendered properly.
I tried to identify if it's a latex code if the string starts with `$` and if it has an even number of `$` in it. But I'm open to suggestions. I also increased the number of allowed columns for latex code since it generally renders to fewer characters.
CC: @dcherian @Illviljan

Improves rendering of complex LaTeX expressions as `long_name`s when plotting

---

xarray/tests/test_plot.py

There's some error in the minimum environments (for example `ubuntu-latest py37-bare-minimum`) introduced in #5682 but was hidden in all other errors because of #5654:
```
=========================== short test summary info ============================
ERROR xarray/tests/test_plot.py::test_latex_name_isnt_split - NameError: name...
= 7908 passed, 4163 skipped, 202 xfailed, 42 xpassed, 89 warnings, 1 error in 279.31s (0:04:39) =
```
But when looking further in the details it mentions a completely different function crashing because matplotlib isn't installed, which is true but the function doesn't test any mpl-specific things. 
```
==================================== ERRORS ====================================
_______________ ERROR at teardown of test_latex_name_isnt_split …
```

Fix errors in test_latex_name_isnt_split for min environments

---

properties/test_encode_decode.py
setup.cfg
xarray/core/parallel.py
xarray/tests/test_units.py

Use isort's float-to-top

---

doc/whats-new.rst
properties/test_pandas_roundtrip.py
xarray/core/accessor_str.py
xarray/core/common.py
xarray/core/computation.py
xarray/core/coordinates.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/merge.py
xarray/core/utils.py
xarray/core/variable.py
xarray/tests/test_dataset.py

IIUC:
- [This test](https://github.com/pydata/xarray/pull/5690/files#diff-2db7f6624707083db4aaab1b62eb11352200ec9d3ac1055de84877912226d7b5R6800) below would fail mypy because the key of `Mapping` is invariant (though `Any` still lets anything through)
- I've only seen this when the dict is defined in a different expression from the Dataset constructor
- Mypy doesn't type-check our test functions, [because the functions don't have any annotations](https://mypy.readthedocs.io/en/stable/common_issues.html#no-errors-reported-for-obviously-wrong-code).
If that's correct, we should change all our `Mapping` to use `Any` rather than `Hashable`, and add type annotations to our test functions (even just `-> None`)

Change annotations to allow str keys

---

xarray/core/options.py

This adds typing to the dict values. Using variables as keys is apparently not permitted by mypy so that part has been removed.
Attempts to fix issues found in #5662.

Add typing to the OPTIONS dict

---

doc/contributing.rst

DOC: Remove suggestion to install pytest-xdist in docs

---

xarray/core/options.py

While trying to figure out which types are allowed in  #5678 I felt that the `set_options` docstring was rather hard to read. Moving it to typical numpy docstring style helped at least for me.

Move docstring for xr.set_options to numpy style

---

xarray/util/print_versions.py

add `cupy`, `sparse` and `fsspec` to the output of `xr.show_versions()`

extend show_versions

---

doc/ecosystem.rst

We have released [xarray-dataclasses](https://github.com/astropenguin/xarray-dataclasses), an xarray extension for typed DataArray and Dataset creation.
This PR added the project to the "Extend xarray capabilities" section in `doc/ecosystem.rst`.
Plus we removed [xarray-custom](https://github.com/astropenguin/xarray-custom) (added by #4109) from the same section.
This is because it is not maintained and xarray-dataclasses is the successor.
It would be appreciated if you could merge it (if this PR fits the purpose of the xarray documentation).

Add xarray-dataclasses to ecosystem in docs

---

xarray/tests/test_sparse.py

ref https://github.com/pydata/xarray/issues/5654
I vote to always do this when a dependency changes, if we can't immediately fix the code. Having main be green means it's easy to see the difference between passing and failing.

Xfail failing test on main

---

xarray/core/concat.py
xarray/tests/test_concat.py

Technically this creates user visible changes, but not sure whether it's worth adding it to the whatsnew.

Set coord name concat when `concat`ing along a DataArray

---

doc/ecosystem.rst

Updating documentation to remove https://github.com/ClimateImpactLab/xshape , which says "deprecated. Use geopandas".

remove deprecated xshape from ecosystem documentation

---

doc/ecosystem.rst
doc/roadmap.rst
doc/user-guide/computation.rst
doc/user-guide/io.rst
doc/whats-new.rst

fixing typo spelling grammar and replace to correct words with reference from [merriam webster](merriam-webster.com)

fix: typo spelling grammar

---

xarray/tests/test_sparse.py

`xarray/tests/test_sparse.py::test_chunk` now passes with the latest `sparse=0.13.0` release

Update `sparse` `test_chunk` xfail

---

doc/internals/how-to-add-new-backend.rst

Reverts pydata/xarray#5532
Not being able to pass entrypoints to the `engine` parameter is a bug which should be fixed by #5684.

Add `self` back to the backend entrypoint example classes

---

README.rst
doc/api.rst
doc/contributing.rst
doc/examples/ERA5-GRIB-example.ipynb
doc/examples/multidimensional-coords.ipynb
doc/examples/visualization_gallery.ipynb
doc/getting-started-guide/faq.rst
doc/getting-started-guide/installing.rst
doc/getting-started-guide/quick-overview.rst
doc/getting-started-guide/why-xarray.rst
doc/howdoi.rst
doc/index.rst
doc/internals/duck-arrays-integration.rst
doc/internals/extending-xarray.rst
doc/internals/index.rst
doc/roadmap.rst
doc/tutorials-and-videos.rst
doc/user-guide/combining.rst
doc/user-guide/computation.rst
doc/user-guide/dask.rst
doc/user-guide/data-structures.rst
doc/user-guide/duckarrays.rst
doc/user-guide/groupby.rst
doc/user-guide/indexing.rst
doc/user-guide/interpolation.rst
doc/user-guide/io.rst
doc/user-guide/plotting.rst
doc/user-guide/time-series.rst
doc/user-guide/weather-climate.rst
doc/whats-new.rst

Updating readme and user-facing docs according to https://github.com/pydata/xarray/issues/1306 ([final comment](https://github.com/pydata/xarray/issues/1306#issuecomment-457881189))
Notes:
* I didn't yet change the contributing page, since it seems to have its own convention (though not used everywhere): **xarray** (bold and lowercase). 
* I mostly didn't touch internal docs pages / docstrings.
* Also modified some cases of NumPy, pandas, and Dask according to their conventions, but could do more there, especially with NumPy.

"Xarray" and "xarray"

---

xarray/tests/test_backends.py

IOError has been an alias of [OSError](https://docs.python.org/3/library/exceptions.html#OSError) since Python 3.3 (see [PEP 3151](https://www.python.org/dev/peps/pep-3151/)).

MAINT: IOError -> OSError

---

asv_bench/benchmarks/groupby.py

Create benchmark for groupby

---

ci/requirements/doc.yml
doc/examples/visualization_gallery.ipynb
doc/gallery/plot_rasterio.py

Using pyproj should be more efficient & simpler to use.
With latest `cartopy`, I get this error with `18N`:
```
CRSError: Invalid projection: +proj=utm +ellps=WGS84 +units=m +zone=18N +no_defs +type=crs: (Internal Proj Error: proj_create: Error 1027 (Invalid value for an argument): utm: Invalid value for zone)
```
Removing `N` fixes the issue.

DOC: Use pyproj to generate 2D latlon & fix cartopy UTM CRS

---

doc/whats-new.rst
xarray/core/combine.py
xarray/tests/test_combine.py

The update points users in the direction of the `use_cftime` argument, which can solve issues where calendars are decoded into different time classes (see also the discussion in #5767)

Update combine error

---

doc/whats-new.rst
xarray/coding/cftime_offsets.py
xarray/coding/cftimeindex.py
xarray/coding/times.py
xarray/core/common.py
xarray/plot/utils.py

No functional change, just removes a terrible perfomance bug when cftime isn't installed - previously calls to `.sel` would search your whole python path for trying to import cftime, leading to progams of mine taking 10% of time just doing this against a slow filesystem.
Tests all pass localy.

Fix performance bug from cftime import

---

doc/user-guide/io.rst
doc/whats-new.rst
xarray/backends/rasterio_.py
xarray/tests/test_backends.py
xarray/tests/test_distributed.py
xarray/tests/test_tutorial.py

DEP: Deprecate rasterio backend

---

doc/api.rst
doc/whats-new.rst
xarray/core/common.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/variable.py
xarray/tests/test_dask.py

Adds a new `.chunksizes` property to `Dataset`, `DataArray` and `Variable`, which returns a mapping from dimensions names to chunk sizes in all cases.
Supercedes #5846 because this PR is backwards-compatible.

Add .chunksizes property

---

doc/whats-new.rst

Whats-new fixes for the release. 
Feel free to push to this branch with more improvements.

[skip-ci] v0.20.0: whats-new for release

---

doc/whats-new.rst

When I worked on https://github.com/pydata/xarray/pull/5615 I did so with a couple of team mates. I added them in the commit message: https://github.com/pydata/xarray/pull/5615/commits/67ccce2f9b31eebf38fffb5dc86b90810299111c
Want to make sure they get a shout out here :)

DOC: add names of missing contributors to 0.20.0

---

doc/api-hidden.rst
doc/api.rst
doc/whats-new.rst

This PR makes a number of updates to `api.rst`. The main goal is to make it easier to navigate using the right-side "Contents" menu. By moving things from `api-hidden.rst` to `api.rst` many methods are now easier-to-discover.
**before**
**after**
I've also added sections for rolling, coarsen, groupby, resample that again list available reductions. These were previously hidden
**Before**
**after**

Explicitly list all reductions in api.rst

---

ci/requirements/py37-bare-minimum.yml
ci/requirements/py37-min-all-deps.yml
doc/whats-new.rst
xarray/backends/plugins.py

In #5845, we accidentally broke the detection of the backends. Since this has a big impact we probably need to release `v0.20.1` very soon.
I'm not sure if it's possible to add tests for this, though.

fix the detection of backend entrypoints

---

xarray/tests/test_backends.py

When zarr is not available, this test fails with `NameError: name 'zarr' is not defined`.
<details>
<summary>Full trace</summary>
```
__________________________ test_zarr_storage_options ___________________________
@requires_fsspec
def test_zarr_storage_options():
pytest.importorskip("aiobotocore")
ds = create_test_data()
store_target = "memory://test.zarr"
>       ds.to_zarr(store_target, storage_options={"test": "zarr_write"})
/build/python-xarray/src/xarray-0.20.0/xarray/tests/test_backends.py:2406: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/build/python-xarray/src/xarray-0.20.0/xarray/core/dataset.py:2037: in to_zarr
return to_zarr(
/build/python-xarray/src/xarray-0.20.0/xarray/backends/api.py:1391: in to_zarr
zstore = …
```

Fix a missing @requires_zarr in tests

---

.github/workflows/ci.yaml
.github/workflows/publish-test-results.yaml

I recommend to use the latest setup: https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.23/README.md#support-fork-repositories-and-dependabot-branches
This is unrelated to https://github.com/EnricoMi/publish-unit-test-result-action/issues/183.

Publish test results from workflow_run only

---

.github/workflows/publish-test-results.yaml

I disable the commenting, but didn't turn it off — I'm still hoping we could get cool stuff like this:
...from https://github.com/EnricoMi/publish-unit-test-result-action, which I don't know why we don't get.
Removing the commenting removes any downside, I think

Disable unit test comments

---

doc/whats-new.rst
xarray/core/formatting.py
xarray/tests/test_plot.py

Affected `xarray` versions `0.20.0`+
When dependabot recently made a PR to update  `xarray` to `0.20.0` our integration test CI failed with
```
....
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/xarray/plot/plot.py", line 447, in line
ax.set_title(darray._title_for_slice())
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/xarray/core/dataarray.py", line 3140, in _title_for_slice
v=format_item(coord.values),
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/xarray/core/formatting.py", line 146, in format_item
return f"{x:.4}"
TypeError: unsupported format string passed to numpy.ndarray.__format__
```
We use `xarray.Dataarray.plot.line(x="<dim_name>")` to plot data of shape `(N, M)` where `N` and `M` are `>=1`.
The …

Fix plot.line crash for data of shape (1, N) in _title_for_slice on format_item

---

xarray/core/variable.py
xarray/tests/test_dataarray.py
xarray/tests/test_variable.py

Not the prettiest of fixes, but this goes around the fact that mutable data types (e.g. when `self_data` is a  `np.ndarray`) get  updated inplace on the right-hand side of the following line, while the error is thrown during the  subsequent assignment to the left-hand side.
https://github.com/pydata/xarray/blob/20fddb7e3838d3cf1514476899e77a8a1749734b/xarray/core/variable.py#L2421

Do not change coordinate inplace when throwing error

---

xarray/backends/plugins.py

This was causing a mypy failure locally — it may be a dependencies issue, but I thought there was limited downside to widening this ignore

Fix mypy issue with entry_points

---

xarray/backends/plugins.py

This removes the need for the `# type: ignore` to make mypy happy. It is also clearer when this compatibillity code can be removed.

Check for py version instead of try/except when importing entry_points

---

xarray/core/dataarray.py

Single character change just fixing a misspelling of dimension in the from_dict method of dataarray.

Fixed a mispelling of dimension in dataarray documentation for from_dict

---

doc/ecosystem.rst

As it says, this is to add the https://github.com/euroargodev/argopy xarray related project to the documentation page.
[argopy](https://github.com/euroargodev/argopy) is a python library that aims to ease Argo data access, manipulation and visualisation for standard users as well as Argo experts.
[argopy](https://github.com/euroargodev/argopy) comes with a [xarray accessor ``argo`` for Argo dataset](https://argopy.readthedocs.io/en/latest/api.html#dataset-argo-xarray-accessor)

Add argopy to ecosystem.rst doc page

---

xarray/core/computation.py

This PR simplifies the fix from https://github.com/pydata/xarray/pull/5731, specifically for the benefit of xarray.corr. There is no need to use `map_blocks` instead of using `where` directly.
It is a basically an alternative version of https://github.com/pydata/xarray/pull/5284. It is potentially slightly less efficient to do this masking step when unnecessary, but I doubt this makes a noticeable performance difference in practice (and I doubt this optimization is useful insdie `map_blocks`, anyways).

Simplify missing value handling in xarray.corr

---

doc/whats-new.rst
xarray/core/missing.py
xarray/tests/test_interp.py
xarray/tests/test_missing.py

When using the `da.interp` to interpolate outside of the bounds, by default,  `fill_value` is set to `np.nan` to set the values to NaN.
This is completely fine with real values, but with complex values this will in fact set the values to `np.nan + 0j` which can be a source of confusion and bugs.
This PR propose to detect if values are complex, and if so, to use `np.nan + np.nan*1j` as the default `fill_value`

Use complex nan by default when interpolating out of bounds

---

ci/requirements/doc.yml
ci/requirements/environment-windows.yml
ci/requirements/environment.yml
ci/requirements/py37-min-all-deps.yml

Tried to reduce dependencies from installing dask via conda which installs like pip install dask[complete]. dask-core is like pip install dask. https://github.com/xgcm/xhistogram/pull/71#discussion_r752738286
Why? dask[complete] includes bokeh etc which are not needed here and likely speed up CI setup/install times
but now dask and dask-core are conda installed :( seems like iris installs dask https://github.com/conda-forge/iris-feedstock/blob/master/recipe/meta.yaml, so this would require an iris-feedstock PR first
linking https://github.com/SciTools/iris/pull/4434 and https://github.com/conda-forge/iris-feedstock/pull/77

Use condas dask-core in ci instead of dask to speedup ci and reduce dependencies

---

doc/user-guide/computation.rst

very simple fix in the [broadcasting by dimension name](http://xarray.pydata.org/en/stable/user-guide/computation.html#broadcasting-by-dimension-name) docs:
> ``DataArray`` objects ~~are~~ automatically align themselves [...] by dimension name instead of axis order.
No workflow stages - this is a very minor docs fix.

fix grammatical typo in docs

---

doc/getting-started-guide/faq.rst

If helpful - added a PR to adds a reference and link to `xr.set_options` in the section of the FAQ on "what is your approach to metadata?". I had to do a bit of digging to figure out what was meant by "there is a global flag" and thought others might find the direct ref useful.
Relevant section: https://github.com/pydata/xarray/blob/main/doc/getting-started-guide/faq.rst#what-is-your-approach-to-metadata
Current text:
> An implication of this choice is that we do not propagate ``attrs`` through most operations unless explicitly flagged (some methods have a ``keep_attrs`` option, and there is a global flag for setting this to be always True or False)
Proposed version:
> An implication of this choice is that we do not propagate ``attrs`` through most operations unless explicitly flagged …

add set_options link to FAQ on metadata

---

doc/whats-new.rst

Add release notes for 0.20.2

---

doc/contributing.rst

In the section above (http://xarray.pydata.org/en/stable/contributing.html#how-to-build-the-xarray-documentation) i.e. build the env, it assumes you are in the root directory. This holds that assumptions and makes it easier for a user to copy-paste to build the docs

DOC: cd command in build documentation

---

xarray/tests/test_cftimeindex.py

cftime 1.5.2 renames "gregorian" to "standard". AFAIK this only changes the repr of cftime indices and does not seem to influence the creation of cftime indices.

cftime: 'gregorian' -> 'standard' [test-upstream]

---

.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml

Our CI fails with some pytest-xdist error. Let's see if we get a clearer picture when disabling parallel tests. (Maybe some interaction between dask and pytest-xdist?).

disable pytest-xdist (to check CI failure)

---

doc/whats-new.rst
xarray/coding/times.py
xarray/tests/test_coding_times.py
xarray/tests/test_formatting.py

A netCDF4 dataset we use has a time variable defined as:
```
double time(time) ;
time:axis = "T" ;
time:bounds = "time_bnds" ;
time:calendar = "gregorian" ;
time:long_name = "time" ;
time:standard_name = "time" ;
time:units = "days since 1970-01-01 00:00:00 00" ;
```
Note the `units` attribute, specifically a timezone offset of `00` without any `+-` sign.
xarray can successfully open this dataset and parse the time units, making a time variable with the expeced values. However, attempting to save this dataset (e.g. after slicing some geographic bounds or selecting a subset of variables), xarray would raise an error trying to reformat the time `units`.
This fix applies the same logic used in the decoding step to the encoding step - specifically, attempt to use `pandas` but if that fails …

Attempt datetime coding using cftime when pandas fails

---

setup.cfg
xarray/core/dataset.py

We can add the current typing to this function, making the changes in #6086 easier.

Add type definitions in prep for #6086

---

.pre-commit-config.yaml
xarray/core/dataset.py

This seems to have conflicted between changing the types and updating the version in
pre-commit. Oddly, the code work when running `mypy` but not running in pre-commit.
But this code solves for both

Fix mypy precommit

---

xarray/tests/test_dataset.py

a number of assert statements in test_dataset.py::test_clip make assertions which will never fail as long as there is at least one data_variable:
```python
assert result.min(...) >= 0.5
```
this evaluates to datasets with scalar True or False values in each data_variable; however, `ds.__bool__` returns true if `len(ds.data_vars) > 0`.
related: https://github.com/pydata/xarray/pull/6122
No workflow stages here - I just made the changes in the browser. Pretty simple patch that increases the effectiveness of existing tests - no changes to the xarray core code. Let me know if you'd like me to implement any of the normal checks.

assert ds errors in test_dataset.py

---

xarray/tests/test_backends.py

Makes four changes to xarray/tests/test_backends.py::test_open_fsspec
Previously, there were four inequality tests which will always pass regardless of whether the read was successful.
`assert ds0 == ds2` will always evaluate to True if the datasets have at least one data variable. Instead, xr.testing.assert_equal should be used to test data variable equality.
No workflow stages here - I just made the changes in the browser. Pretty simple patch that increases the effectiveness of existing tests - no changes to the xarray core code.

assert ds errors in test_backends

---

asv_bench/benchmarks/import_xarray.py
xarray/plot/dataset_plot.py
xarray/plot/facetgrid.py
xarray/plot/plot.py
xarray/plot/utils.py

Revert pydata/xarray#5794, which causes failure to import when used without display (issue #6062).

Revert "Single matplotlib import"

---

xarray/core/pycompat.py

In #6096 I realized that `DuckArrayModule("dask")` is called a lot in our tests - 145'835 times. Most of those are from `is_dask_collection` (`is_duck_dask_array`)  This change avoids that the instance needs to be built every time.
```python
%timeit xr.core.pycompat.DuckArrayModule("dask").available
%timeit xr.core.pycompat.dsk.available
```
```
18.9 µs ± 97.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
77.1 ns ± 1.22 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
Which leads to an incredible speed up of our tests of about 2.7 s :grin: ((18.9 - 0.0771) * 145835 / 1e6).

is_dask_collection: micro optimization

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_dataset.py

Issues a PendingDeprecationWarning on `Dataset.__bool__`

Deprecate bool(ds)

---

xarray/tests/test_plot.py

Adds a test that says what the locator should be if the xaxis is datetime.

TST: check datetime converter is Matplotlibs

---

xarray/core/dataarray.py
xarray/core/dataset.py

This PR adds `str` type on `datarray.chunk` method the same way it is accepted on `dataset.chunk`.
The corresponding documentation has been updated.
I wanted to add a unit test for `da.chunk("auto")` but the existing tests seems to rely on zarr which I don't know at all.

DOC: Add "auto" to dataarray `chunk` method

---

xarray/core/dataset.py
xarray/tests/test_dataarray.py

`_stack_once` seemed like a reasonable place to put this check, just going from the trace of where the test failed. 
I also saw mypy failures during the local pre-commit step, but chose to ignore them for now given #6024. They seemed to pop up in unrelated areas, anyway.

Check for just `...`, rather than `[...]` in `da.stack`

---

xarray/tests/test_dataarray.py

as per https://github.com/pydata/xarray/issues/6136

remove paren from data that is fed to 1D DataArray

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_dataset.py

This reverts commit d6ee8caa84b27d4635ec3384b1a06ef4ddf2d998.

Revert "Deprecate bool(ds) (#6126)"

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/merge.py
xarray/core/pdcompat.py

Since it appears the min pandas version is 1.1, these `Panel` checks should never be true.

Remove pd.Panel checks

---

.pre-commit-config.yaml

Remove numpy from mypy pre-commit

---

xarray/backends/h5netcdf_.py
xarray/backends/netCDF4_.py

Admittedly i had a pretty broken environment (I manually uninstalled C dependencies for python packages installed with conda), but I still expected xarray to "work" with a different backend.
I hope the comments in the code explain why `ImportError` is preferred to `ModuleNotFoundError`.
Thank you for considering.

Use base ImportError not MoudleNotFoundError when testing for plugins

---

.pre-commit-config.yaml
xarray/backends/file_manager.py
xarray/core/accessor_str.py
xarray/core/dataset.py
xarray/core/duck_array_ops.py
xarray/core/formatting.py
xarray/core/indexing.py
xarray/core/utils.py
xarray/core/variable.py
xarray/tests/test_computation.py
xarray/tests/test_conventions.py

typing fixes for mypy 0.931 and numpy 1.22. Also tested with numpy 1.20 which probably many still have installed.

typing fixes for mypy 0.931 and numpy 1.22

---

doc/whats-new.rst
xarray/core/missing.py
xarray/tests/test_missing.py

@Skealz's great issue (#5994) highlighted that DataArrays with a single non-null value raise an error if `DataArray.interpolate_na` is called with `method='nearest'`. Note that this does not occur for the default (`method='linear'`).
In this PR:
* Uses the "fast track" to quickly return *any* 1-D slices with a single non-null value in addition to the previous all-nan or no-nan fasttrack
* Explicitly check this behavior for all 1-D interpolation methods using parametrized tests
* consolidate other fast-track tests (`interpolate_allnans` and `interpolate_nonans`) into a single parameterized test
For discussion:
* This patch may break existing workflows if they rely on the current behavior, which errors for slices with only a single value

allow 1 non-null value in interpolate_na with method="nearest"

---

ci/requirements/environment-windows.yml
ci/requirements/environment.yml

- dask 2022.01 is out, so we can remove the pin

unpin dask again

---

.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml
.github/workflows/publish-test-results.yaml

Here's a snippet of how this looks like when a pull request is created on the same main repository:
Cc @keewis

Trigger CI on push or pull_request but not both

---

.github/workflows/upstream-dev-ci.yaml
ci/install-upstream-wheels.sh

I think it would be good to re-enable the upstream CI, even if this means we have to stick to py3.9 for the moment. I just subscribed to pydata/bottleneck#378, so I should see when we can switch to 3.10.

don't install bottleneck wheel for upstream CI

---

xarray/coding/cftimeindex.py

Fixes the doctests for the newest version of cftime. @spencerkclark
This of course means that the doctests will fail for environments with older versions of cftime present. I don't think there is anything we can do.
Thanks for pytest-accept b.t.w @max-sixty

fix cftime doctests

---

xarray/core/indexes.py
xarray/core/missing.py

Fixed as per @shoyer & @spencerkclark suggestion from https://github.com/pydata/xarray/issues/5721#issuecomment-903095007
Now that pandas 1.4 is out it would be good to get this fixed (there are about 5000 warnings in our tests, mostly because of `interp`, though). Also leads to a warning in our docs which breaks them (although that can also be fixed with an `:okwarning:` directive).

MAINT: pandas 1.4: no longer use get_loc with method

---

doc/user-guide/computation.rst

And another tiny one... The somewhat ambiguous date string triggers a warning in pandas which makes our doc build fail.

doc: fix pd datetime parsing warning [skip-ci]

---

xarray/backends/h5netcdf_.py

MNT: prepare h5netcdf backend for (coming) change in dimension handling

---

xarray/backends/plugins.py
xarray/coding/cftimeindex.py
xarray/core/common.py
xarray/core/groupby.py
xarray/core/merge.py
xarray/core/missing.py
xarray/plot/utils.py
xarray/tests/test_accessor_dt.py
xarray/tests/test_backends.py
xarray/tests/test_coarsen.py
xarray/tests/test_computation.py
xarray/tests/test_dataarray.py
xarray/tests/test_distributed.py
xarray/tests/test_groupby.py
xarray/tests/test_sparse.py
xarray/tests/test_variable.py
xarray/tests/test_weighted.py

Fixes or suppresses a number of warnings that turn up in our upstream CI.
`pd.Index.is_monotonic` is an alias for `pd.Index.is_monotonic_increasing` and does _not_ stand for `pd.Index.is_monotonic_increasing or pd.Index.is_monotonic_decreasing`.

fix or suppress test warnings

---

xarray/core/utils.py

Make #6239 cleaner by running pyupgrade separately.
pyupgrade fixes typing only if `from __future__ import annotations` has been manually added to the file. Could probably do this in other files as well.

Run pyupgrade on core/utils

---

.github/ISSUE_TEMPLATE/bugreport.yml
.github/ISSUE_TEMPLATE/newfeature.yml

I would vote to use labels rather than strings here -- it clutters the names
(but no strong view, feel free to close if ppl disagree)

Remove default issue & PR titles

---

.pre-commit-config.yaml

With this setup, the `mypy` hook is only added to the run if you specify it:
```
pre-commit run --all-files --hook-stage manual
```
cc: @dcherian 
https://pre-commit.com/#confining-hooks-to-run-at-certain-stages

REF: Make mypy manual stage with pre-commit

---

doc/whats-new.rst
xarray/backends/zarr.py
xarray/tests/test_backends.py

When storing a dask-chunked dataset to zarr, the size of the last chunk
in each dimension does not matter, as this single last chunk will be
written to any number of zarr chunks, but none of the zarr chunks which
are being written to will be accessed by any other dask chunk.
cc'ing @rabernat who seems to have worked on this lately.

removed check for last dask chunk size in to_zarr

---

doc/whats-new.rst
xarray/coding/cftimeindex.py
xarray/tests/test_cftimeindex.py
xarray/tests/test_distributed.py

This PR tries to address some updates in the pandas library on how datetime objects are pickled. Since I was told that the datatype of the CFtimeIndex object will always be `object` I just instructed the `__new__` method to receive any additional arguments but not to evaluate them. Which feels a little awkward but does the job. If there are better ways to deal with this please let me know.  @spencerkclark @aidanheerdegen @mathause

Fix pickling issue

---

xarray/tests/test_distributed.py

``@gen_cluster`` has now been fixed upstream.

Remove xfail from tests decorated by @gen_cluster

---

xarray/tests/__init__.py
xarray/tests/test_backends.py
xarray/tests/test_coding_times.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_ufuncs.py
xarray/tests/test_variable.py

pytest v7.0.0 no longer want's us to use ` pytest.warns(None)` to test for no warning, so we can use `warnings.catch_warnings(record=True)` instead.

use `warnings.catch_warnings(record=True)` instead of `pytest.warns(None)`

---

doc/contributing.rst
doc/user-guide/io.rst
doc/whats-new.rst
xarray/core/computation.py

The existing version had it right down the page, below Iris / Pickle /
et al.

Move Zarr up in io.rst

---

.github/ISSUE_TEMPLATE/bugreport.yml
doc/contributing.rst
doc/whats-new.rst
xarray/core/computation.py

Not sure if this matters at all, but VSCode's linter was complaining

Align language def in bugreport.yml with schema

---

xarray/core/dataset.py

In [MetPy/pull#2312](https://github.com/MetPy/pull/2312), I noticed that the behavior of `Dataset.map`'s kwarg `keep_attrs` was not in line with its docstring. This is because in xarray 0.16.2 (pydata/xarray#3595 & pydata/xarray#4195) this behavior was changed.
In short, `keep_attrs=True` now copies both, the Dataset's and the variables' attributes and adds them to the new objects - preventing any change to them by the mapped function. In contrast, `keep_attrs= False` discards the Dataset's attributes and does not touch the variables' attributes, enabling the mapped function to modify them.
Here, I propose an update to the `keep_attrs` docstring of `Dataset.map` which would more accurately reflect its current behavior. Please feel free to provide alternative formulations if you feel like …

Amended docstring to reflect the actual behaviour of Dataset.map

---

doc/internals/how-to-add-new-backend.rst

When trying to install a new xarray backend with poetry, I noticed that it should be `xarray.backends` instead of `xarray_backends`.

Amended docs on how to add a new backend

---

doc/api.rst
doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

Allows for dropping duplicates over multiple dims at once, and adds `Dataset.drop_duplicates`.

Drop duplicates over multiple dims, and add Dataset.drop_duplicates

---

doc/whats-new.rst
xarray/tests/test_distributed.py

Previously, on Windows, the subject test unnecessarily failed, and the temporary directory and file remained, because the scheduler in the outer context prevented deleting the temporary directory upon exiting the inner context of the latter.
<details><summary>Example failure (with short traceback):</summary>
<p>
```
================================================ FAILURES =================================================
__________________________ test_open_mfdataset_can_open_files_with_cftime_index ___________________________
C:\Users\stan.west\Programs\Miniconda3-64\envs\xarray-dev\lib\shutil.py:616: in _rmtree_unsafe
os.unlink(fullname)
E   PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: …
```

On Windows, enable successful test of opening a dataset containing a cftime index

---

.gitignore
doc/conf.py
doc/getting-started-guide/quick-overview.rst
doc/internals/zarr-encoding-spec.rst
doc/user-guide/dask.rst
doc/user-guide/io.rst
doc/user-guide/weather-climate.rst
doc/whats-new.rst

This PR enables one to build the documentation on Windows by manually invoking `sphinx-build`.
The first commit enables *sphinx* to execute the "conf.py" file. Before the commit, *sphinx* complains:
```
Configuration error:
There is a programmable error in your configuration file:
```
with the exception `FileNotFoundError: [WinError 2] The system cannot find the file specified` where it tries to invoke *conda*. On Windows, *conda* environments other than the base environment have "conda.bat" on their path rather than "conda.exe", and one must call `subprocess.run` with "conda.bat" instead of merely "conda". However, the `CONDA_EXE` environment variable correctly points to the executable and should do so across platforms; it requires *conda* version 4.5 or later for conda/conda#6923.
The …

Enable running sphinx-build on Windows

---

.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml

This PR ensures all CI workflows are only enabled on the main repository. A few workflows were still being triggered on forks.

Disable CI runs on forks

---

.github/ISSUE_TEMPLATE/misc.yml

Add General issue template

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/groupby.py
xarray/core/variable.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_groupby.py
xarray/tests/test_variable.py

`skipna=None` did not skip missing values for `quantile`, inconsistent with other methods. Discovered while testing #6059.

quantile: use skipna=None

---

doc/whats-new.rst

Lengthening the underline resolves the following warning from *sphinx-build*:
```
[...]\xarray\doc\whats-new.rst:20: WARNING: Title underline too short.
v2022.03.1 (unreleased)
---------------------
```

Lengthen underline, correct spelling, and reword

---

doc/internals/how-to-add-new-backend.rst

Adding the import resolves the following exception that *sphinx-build* raises when one builds only "doc/internals/how-to-add-new-backend.rst":
```
NameError                                 Traceback (most recent call last)
Input In [1], in <module>
----> 1 var = xr.Variable(
2     dims=("x",), data=np.arange(10.0), attrs={"scale_factor": 10, "add_offset": 2}
3 )
NameError: name 'xr' is not defined
```
While in the file, I revised headings to have only their first letter capitalized (except for case-sensitive code), which seems to be the majority convention in the documentation.

In documentation on adding a new backend, add missing import and tweak headings

---

ci/requirements/doc.yml

This can be reverted once the `nbconvert` package on `conda-forge` has been updated.

explicitly install `ipython_genutils`

---

xarray/backends/zarr.py

Allow write_empty_chunks to be set in Zarr encoding

---

xarray/tests/test_backends.py

This test has been failing with a 404 error for a while. Remove the test because a lot of the functionality is implemented in rioxarray.

Remove test_rasterio_vrt_network

---

doc/whats-new.rst
xarray/coding/times.py
xarray/tests/test_conventions.py

#6367 Fix for time units checking could produce "unhashable type" error

---

xarray/core/concat.py
xarray/tests/test_concat.py

Fix concat with variable or dataarray as dim (propagate attrs)

---

xarray/core/dataset.py
xarray/tests/test_dataset.py

isel: convert IndexVariable to Variable if index is dropped

---

xarray/core/concat.py
xarray/tests/test_concat.py

Fix concat with scalar coordinate

---

asv_bench/benchmarks/groupby.py

[skip-ci] Add benchmarks for groupby math

---

xarray/core/dataset.py
xarray/tests/test_dataset.py

Re-index: fix missing variable metadata

---

xarray/core/groupby.py
xarray/tests/test_groupby.py

Fix DataArray groupby returning a Dataset

---

doc/whats-new.rst
xarray/core/indexing.py
xarray/tests/test_units.py

(detected while trying to implement a `PintMetaIndex` in xarray-contrib/pint-xarray#163)
This fixes position-based indexing of `duck dask arrays`:
``` python
In [1]: import xarray as xr
...: impIn [1]: import xarray as xr
...: import dask.array as da
...: import pint
...: 
...: ureg = pint.UnitRegistry(force_ndarray_like=True)
...: 
...: a = da.zeros((20, 20), chunks=(10, 10))
...: q = ureg.Quantity(a, "m")
...: 
...: arr1 = xr.DataArray(a, dims=("x", "y"))
...: arr2 = xr.DataArray(q, dims=("x", "y"))
In [2]: arr1.isel(x=[0, 2, 4], y=[1, 3, 5])
Out[2]: 
<xarray.DataArray 'zeros_like-d81259c3a77e6dff3e60975e2afe4ff9' (x: 3, y: 3)>
dask.array<getitem, shape=(3, 3), dtype=float64, chunksize=(3, 3), chunktype=numpy.ndarray>
Dimensions without coordinates: x, y
In [3]: arr2.isel(x=[0, 2, 4], …
```

use the `DaskIndexingAdapter` for `duck dask` arrays

---

doc/whats-new.rst
xarray/core/formatting.py
xarray/core/indexing.py
xarray/core/options.py
xarray/tests/test_formatting.py

This adds `PandasMultiIndexingAdapter._repr_html_` that can greatly speed-up the html repr of Xarray objects with
multi-indexes.
This optimized `_repr_html_` implementation is now used for formatting the array detailed view of all multi-index coordinates in the html repr, instead of converting the full index and each levels to numpy arrays before formatting them.
```python
ds = xr.tutorial.load_dataset("air_temperature")
da = ds["air"].stack(z=[...])
da.shape 
%timeit -n 1 -r 1 da._repr_html_()
```

Speed-up multi-index html repr + add display_values_threshold option

---

asv_bench/benchmarks/groupby.py
doc/whats-new.rst
xarray/core/groupby.py
xarray/tests/test_groupby.py

Doing the math is  easy. Keeping backward compatibility with respect to non-dimension coordinates is hard! (e.g. #2145)

Vectorize groupby binary ops

---

ci/requirements/doc.yml

`nbconvert` released a fixed version today, so we can remove the pin of `jinja2`.

unpin `jinja2`

---

doc/internals/how-to-add-new-backend.rst
doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_backends.py
xarray/tests/test_backends_api.py

In backends, support expressing a dimension's preferred chunk sizes as a tuple of integers

---

doc/user-guide/plotting.rst
xarray/backends/api.py

Small tweak since I just saw this error message

Suggest `.drop_vars` rather than `.drop`

---

doc/ecosystem.rst

Adds a mention of [xarray-einstats](https://xarray-einstats.readthedocs.io/en/latest/) to the ecosystem page. Related to #3322.

Add xarray-einstats to ecosystem page

---

doc/whats-new.rst
xarray/core/dataset.py
xarray/tests/test_backends.py

No chunk warning if empty

---

xarray/conventions.py
xarray/tests/test_conventions.py

As discussed in #6310, when setting "coordinates" as a variable attribute instead of as an encoding, the value of that variable attribute is overwritten when writing to a NetCDF file. This PR fixes it.

Don't overwrite user-defined coordinates attributes

---

.github/stale.yml

We're almost at the 1000 mark of issues, and when browsing I see a non-trivial number that look stale. I'm not sure why stalebot doesn't seem to be awake; I'll try this and see if it helps

Try waking up stalebot

---

.github/stale.yml
doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/utils.py
xarray/core/variable.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_variable.py

Also adds some explicit tests (and type hinting) for `Variable.chunk()`, as I don't think it had dedicated tests before.

Support **kwargs form in `.chunk()`

---

doc/whats-new.rst
xarray/core/computation.py
xarray/tests/test_computation.py

Fixes a bug introduced by #4687 where passing a non-xarray object to `x` in `xr.where(cond, x, y, keep_attrs=True)` caused a failure. The `keep_attrs` callable passed to `merge_attrs()` tries to access the attributes of `x` which do not exist in this case. This fix just checks to make sure `x` has attributes, and if not will pass through `keep_attrs=True`.

Fix `xr.where(..., keep_attrs=True)` bug

---

xarray/backends/scipy_.py

Very small fix.
When opening gz files, in the case of the TypeError exception, another exception would be raised:
AttributeError: 'TypeError' object has no attribute 'message'
As python 3 exceptions have no attribute message, I replace it for e.args[0] following the pattern a few lines below.

Accessing the Exception message via e.args[0]

---

README.rst

I'm not sure this is the best place to put a link, but binder is great,
and we could advertise it more prominently (I couldn't find a hit to
`binder` in the docs either — probably it's under something else?). Any
thoughts on how to do that?
Just now, my M1 Mac seems to have its netcdf installation failing, so I used this
to repro an example — very fast & easy!

Add link to xarray binder to readme

---

doc/whats-new.rst
xarray/conventions.py
xarray/core/common.py
xarray/tests/test_conventions.py

It seems rare that `decode_cf_variable` would be called on variables that contain datetime-like objects already, but in the case that it is, it seems best to let those variables pass through unmodified.

Ensure datetime-like variables are left unmodified by `decode_cf_variable`

---

doc/whats-new.rst
xarray/static/css/style.css

HTML repr fix for Furo Sphinx theme

---

xarray/backends/plugins.py

With Python 3.10, the entry_points() method returning a SelectableGroups dict interface was deprecated. The preferred way is to now filter by group through a keyword argument.

Use new importlib.metadata.entry_points interface where available

---

.github/workflows/ci-additional.yaml
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/indexing.py
xarray/core/utils.py
xarray/tests/test_coding_times.py
xarray/tests/test_formatting.py

Unfortunately these have crept back in. I'll add a workflow job, since the pre-commit is not covering everything on its own

Fix some mypy issues

---

.github/workflows/ci.yaml
ci/requirements/environment.yml

Currently we get a lot of duplicates:

Restrict annotations to a single run in GHA

---

.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml

Unfortunately this seems to have failed in https://github.com/pydata/xarray/runs/6232061193?check_suite_focus=true — the cache seems to have thought it was hit, but there's nothing in the cache, so it didn't install dependencies
To ensure nothing is blocked, I'm reverting this — fast merges and fast reverts make for a good combo. I'll try and figure it out (but will be out for a few days so likely not until then — though if anyone can see the problem and wants to have a go, please feel free to go ahead)
Reverts pydata/xarray#6534

Revert "Attempt to improve CI caching"

---

.github/workflows/ci-additional.yaml

So we can at least see the result

Run mypy tests (but always pass)

---

ci/requirements/min-all-deps.yml
doc/getting-started-guide/installing.rst
doc/whats-new.rst
setup.cfg
xarray/core/dask_array_compat.py

Still need to search for outdated code. Help is welcome!

Bump min deps

---

.github/workflows/ci-additional.yaml
xarray/backends/api.py
xarray/backends/locks.py
xarray/core/_typed_ops.pyi
xarray/core/computation.py
xarray/core/dask_array_compat.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/duck_array_ops.py
xarray/core/nanops.py
xarray/core/types.py
xarray/tests/test_computation.py
xarray/tests/test_testing.py
xarray/util/generate_ops.py

I'm still not sure what caused this, but I got the errors showing locally and so could fix them. I'm guessing it was a dependency issue

Fix mypy issues & reenable in tests

---

xarray/core/common.py
xarray/tests/test_formatting.py

This is a first try at formatting dataarray scalars. Here is the current behavior:
```python
In [1]: import xarray as xr
...: import numpy as np
In [2]: a = np.array(1)
...: da = xr.DataArray(a)
In [3]: print(a)
1
In [4]: print(da)
<xarray.DataArray ()>
array(1)
In [5]: print('{}'.format(a))
1
In [6]: print('{}'.format(da))
<xarray.DataArray ()>
array(1)
In [7]: print('{:.3f}'.format(a))
1.000
In [8]: print('{:.3f}'.format(da))
1.000
In [9]: a = np.array([1, 2])
...: da = xr.DataArray(a)
In [10]: print('{}'.format(a))
[1 2]
In [11]: print('{}'.format(da))
<xarray.DataArray (dim_0: 2)>
array([1, 2])
Dimensions without coordinates: dim_0
In [12]: print('{:.3f}'.format(a))
---------------------------------------------------------------------------
TypeError …
```

Allow string formatting of scalar DataArrays

---

doc/user-guide/terminology.rst

This content has been moved to the NetCDF User Guide [1] and the link 
currently points to a non-existing URL.
Fix the link.
[1] https://docs.unidata.ucar.edu/nug/current/netcdf_data_set_components.html

terminology.rst: fix link to Unidata's "netcdf_dataset_components"

---

doc/user-guide/dask.rst

This adds some warnings at the right places when rechunking a dataset opened with `open_mfdataset` (see https://github.com/pangeo-data/rechunker/issues/100#issuecomment-1116189019 for context)
Thanks to @dcherian for the wisdom of the day!

Add some warnings about rechunking to the docs

---

doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/indexes.py
xarray/core/types.py
xarray/core/utils.py
xarray/core/variable.py
xarray/tests/test_dataset.py

Additionally I have added new literal types for error handling (Only applied to functions related to isel such that mypy stops complaining).

Fix Dataset/DataArray.isel with drop=True and scalar DataArray indexes

---

xarray/core/common.py

Closes #6336 
Adds `Dataset.assign_coords` example to https://docs.xarray.dev/en/latest/generated/xarray.Dataset.assign_coords.html

[docs] add Dataset.assign_coords example (#6336)

---

xarray/core/dataset.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

Restore old MultiIndex dropping behaviour

---

xarray/core/computation.py
xarray/tests/test_computation.py

Attempt to fix the typing issues in `xr.polyval`.
Some problems are still occuring and require a `type: ignore`.
They seem more like mypy issues to me.

Fix polyval overloads

---

xarray/core/dataset.py

The summary line in the docstr for `Dataset.map()` says that it operates on variables in the dataset. This is a very minor update clarifying that it operates on *data* variables, as opposed to all variables (data + coord) in the Dataset.

Minor Dataset.map docstr clarification

---

xarray/core/computation.py
xarray/tests/test_computation.py

re-add timedelta support for polyval

---

asv_bench/asv.conf.json

Adding `setuptools_scm[toml]` and `setuptools_scm_git_archive` appears to fix the issue.
Not sure why this is needed though.

Add setuptools as dependency in ASV benchmark CI

---

doc/whats-new.rst
xarray/coding/times.py
xarray/tests/test_coding_times.py

Fix overflow issue in decode_cf_datetime for dtypes <= np.uint32

---

xarray/core/common.py
xarray/core/computation.py
xarray/core/missing.py
xarray/core/npcompat.py
xarray/tests/test_dataset.py
xarray/tests/test_variable.py

(partial) typing for functions `full_like`, `zeros_like`, `ones_like`.
I could not figure out how to properly use TypeVars so many things are "hardcoded" with overloads.
I have added a `DTypeLikeSave` to `npcompat`, not sure that this file is supposed to be edited.
Problem1: `TypeVar["T", Dataset, DataArray, Variable]` can only be one of these three, but never with `Union[Dataset, DataArray]` which is used in several other places in xarray.
Problem2: The official mypy support says: use `TypeVar["T", bound=Union[Dataset, DataArray, Variable]` but the the `isinstance(obj, Dataset)` could not be correctly resolved (is that a mypy issue?).
So if anyone can get it to work with TypeVars, feel free to change it. :)

{full,zeros,ones}_like typing

---

xarray/core/common.py
xarray/tests/test_dataarray.py

forgot to add defaults to the dtype argument, so the typing defaulted back to the Union definition...

fix {full,zeros,ones}_like overloads

---

xarray/backends/api.py

So far we have not found a good way of typing dynamically added custom backends (installed via pip).
So the only fallback option is to allow str.
I have decided to leave the Literal as type, since it gives the user a nice list of supported backends in the editor.

Typing support for custom backends

---

xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/missing.py
xarray/core/types.py

Allow all interp methods in typing

---

doc/user-guide/interpolation.rst
xarray/core/dataarray.py
xarray/core/dataset.py

The current version of xarray tries to call scipy's interp1d whenever
possible, and kwargs used in the user guide should reflect this.
Closes #6617

Fix kwargs used for extrapolation in docs

---

.pre-commit-config.yaml

Following the discussion in #6252, I am adding a pre-commit hook to check the CITATION.cff upon changes.

Add pre-commit hook to check CITATION.cff

---

doc/whats-new.rst
xarray/backends/api.py
xarray/backends/zarr.py
xarray/tests/test_backends.py

- ~New functions/methods are listed in `api.rst`~
I think we can just use zarr to validate attributes, so we can support all types allowed by zarr.
Note that I removed the checks on the keys, as I believe we can rely on zarr for that as well. However, there is an issue with mixed types (e.g., `attrs={"a": "foo", 1: "foo"}`), but I think that needs to be addressed in zarr. See: https://github.com/zarr-developers/zarr-python/issues/1037
cc: @wankoelias @rabernat

Use `zarr` to validate attrs when writing to zarr

---

xarray/core/groupby.py

Closes #6666
False by default following Dataset.reduce

Set keep_attrs for flox

---

.github/workflows/testpypi-release.yaml

fix the python version for the TestPyPI release workflow

---

.github/workflows/configure-testpypi-version.py

This works around a incompatibility between `setuptools>=60` and `setuptools_scm`.

pin setuptools in the testpypi configure script

---

.github/workflows/testpypi-release.yaml
doc/getting-started-guide/installing.rst

Hopefully the final follow-up to #6660.

more testpypi workflow fixes

---

doc/whats-new.rst

The only thing it contains so far is the known regression, do we want to have a summary of the most notable changes like in the previous releases?
cc @pydata/xarray

release notes for the pre-release

---

ci/install-upstream-wheels.sh

install the development version of `matplotlib` into the upstream-dev CI

---

.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml
.github/workflows/upstream-dev-ci.yaml
ci/requirements/bare-minimum.yml

I'm not sure if this is exactly equal to what we had before, but we might be able to save 3-4 minutes of CI time with this.

use micromamba instead of mamba

---

doc/user-guide/indexing.rst

Just some minor documentation tweaks, feel free to cherry pick.
FYI: for https://docs.xarray.dev/en/stable/user-guide/indexing.html#indexing-with-dimension-names  I swapped the two ways for dimension name based indexing, to be in line with order from the "quick overview"
Side question: is it intentional to use `dict(space=0)`  in dimension name based indexing  instead of `{"space": 0}` (which is shorter and probably more widely known) everywhere?

Docs: indexing.rst finetuning

---

doc/whats-new.rst
xarray/core/common.py
xarray/tests/test_dataset.py

Fix Dataset.where with drop=True and mixed dims

---

.github/workflows/parse_logs.py
.github/workflows/upstream-dev-ci.yaml

We currently use the output of `pytest` to generate our test results, which is both fragile and does not detect import errors on test collection.
Instead, we can use `pytest-reportlog` to generate a machine-readable file that is easy to parse (`junit` XML would probably work, too, but apparently does not entirely fit the different failure modes of `pytest`).
The new script will collect failure summaries like the old version, but it should be fairly easy to create a fancy report with more information.

use `pytest-reportlog` to generate upstream-dev CI failure reports

---

doc/whats-new.rst
xarray/backends/pydap_.py

pdyap version dependent client.open_url call

---

xarray/core/dataset.py

Some tiny overlap with https://github.com/pydata/xarray/pull/6542.
I feel this minor changes helps it easy to navigate to other parts of the docs.
Some motivation behind the PR here: https://github.com/pydata/xarray/discussions/6697
Note: i've forgotten the syntax for how to create a link to https://xarray.pydata.org/en/stable/generated/xarray.Dataset.chunk.html

DOC: note of how `chunks` can be defined

---

xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

try to import `UndefinedVariableError` from the new location

---

doc/api.rst
doc/whats-new.rst
xarray/core/coordinates.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

Currently returns a Mapping from variable names to dtypes for ALL variables in the Dataset, including coordinates.
Possibly better to only return data_vars dtypes? Give me your thoughts on that, it is easy to change.

Add `Dataset.dtypes` property

---

doc/api.rst

It's currently listed under "Missing Value Handling" but is also an Aggregation

[skip-ci] List count under Aggregation

---

doc/whats-new.rst
xarray/coding/times.py

The development version of pandas raises an `OutOfBoundsTimedelta` error instead of an `OverflowError` in `pd.to_timedelta` if the timedelta cannot be represented with nanosecond precision.  Therefore we must also be ready to catch that when decoding times.
The `OutOfBoundsTimedelta` exception [was added](https://github.com/pandas-dev/pandas/pull/34448) in pandas version 1.1, which is prior to [our current minimum version (1.2)](https://github.com/pydata/xarray/blob/main/ci/requirements/min-all-deps.yml#L37), so it should be safe to import without a version check.

Accommodate `OutOfBoundsTimedelta` error when decoding times

---

doc/user-guide/io.rst

The reason the changes introduced in #6542 caused timeouts is that they redefined `ds` to a bigger dataset, which would then be used to demonstrate `to_dict`.
The fix is to explicitly set the dataset before calling `to_dict`, which also makes that section a bit easier to follow.

resolve the timeouts on RTD

---

doc/whats-new.rst
xarray/core/alignment.py
xarray/core/common.py
xarray/core/coordinates.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/groupby.py
xarray/core/resample.py
xarray/core/rolling.py
xarray/core/rolling_exp.py
xarray/core/types.py
xarray/core/utils.py
xarray/core/variable.py
xarray/core/weighted.py
xarray/tests/test_coarsen.py
xarray/tests/test_groupby.py

This PR adds typing support for groupby, coarsen, rolling, weighted and resample.
There are several open points:
1. Coarsen is missing type annotations for reductions like `max`, they get added dynamically.
2. The `Groupby` group-key type is quite wide. Does anyone have any idea on how to type it correctly? For now it is still Any.
3. Several function signatures were inconsistent between the DataArray and Dataset versions (looking at you: `map`). I took the freedom to align them (required for mypy), hopefully this does not break too much.
4. I was moving the generation functions from `DataWithCoords` to `DataArray` and `Dataset`, which adds some copy-paste of code (I tried to keep it minimal) but was unavoidable for typing support. (Adds the bonus that the corresponding modules are now …

Typing of GroupBy & Co.

---

doc/whats-new.rst
xarray/core/common.py
xarray/tests/test_dataset.py

@shoyer is there a way to test this?

Fix .chunks loading lazy backed array data

---

xarray/coding/cftimeindex.py
xarray/core/dataset.py
xarray/core/formatting.py
xarray/core/utils.py
xarray/core/variable.py
xarray/testing.py
xarray/tests/test_plot.py
xarray/tests/test_sparse.py
xarray/tutorial.py

Use `math` instead of `numpy` where possible, looks better and seems faster as well. 
Idea from https://github.com/pydata/xarray/pull/6702#discussion_r903986442, https://github.com/dask/dask/pull/9232
Example:
```python
%timeit math.prod((1, 2, 3))
161 ns ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
%timeit int(np.prod((1, 2, 3)))
11.9 µs ± 248 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

Use `math` instead of `numpy`  in some places

---

xarray/backends/pydap_.py
xarray/backends/rasterio_.py
xarray/coding/strings.py
xarray/core/indexing.py
xarray/core/utils.py
xarray/tests/test_formatting.py

The shape methods can have multiple integers inside the tuple, this fixes that and adds to typing to all shape methods I found.

Type `shape` methods

---

setup.cfg
xarray/tests/conftest.py
xarray/tests/test_coarsen.py
xarray/tests/test_computation.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py
xarray/tests/test_indexes.py
xarray/tests/test_ufuncs.py

This PR renames the `da` and `ds` fixtures (to `da_fixture` and `ds_fixture`) and moves them to conftest.py. This allows to remove the flake8 error suppression for the tests and seems more how the fixtures are [intended to be used](https://docs.pytest.org/en/6.2.x/fixture.html#conftest-py-sharing-fixtures-across-multiple-files) (from the pytest side). I think the name changes makes it a bit more obvious what happens but moving them to may make it a bit less obvious (if you don't know where to look).
Removing the flake8 error ignores also unearthed some unused imports:
https://github.com/pydata/xarray/blob/787a96c15161c9025182291b672b3d3c5548a6c7/setup.cfg#L155-L156
(What I actually wanted to do is move the tests for `rolling` to it's own file - but I think it makes sense to do this …

move da and ds fixtures to conftest.py

---

xarray/plot/dataset_plot.py
xarray/plot/utils.py

Move _infer_meta_data and _parse_size to utils

---

xarray/core/parallel.py
xarray/tests/test_dask.py

Raise nicer error if provided template has no dask arrays.

Update map_blocks to use chunksizes property.

---

doc/user-guide/io.rst
doc/user-guide/plotting.rst
xarray/coding/calendar_ops.py
xarray/coding/cftime_offsets.py
xarray/core/alignment.py
xarray/core/concat.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/indexes.py
xarray/core/rolling.py
xarray/tests/test_cftime_offsets.py
xarray/tests/test_dataset.py
xarray/tests/test_groupby.py

The `inferrable` → `inferable` change is debatable, but the most common spelling does appear to be the latter (Google hits support that):
* [Merriam-Webster](https://www.merriam-webster.com/dictionary/inferable)
* [Collins](https://www.collinsdictionary.com/dictionary/english/infer)
* [Wiktionary](https://en.wiktionary.org/wiki/inferable)
* [Lexico](https://www.lexico.com/definition/inferable)

Fix typos found by codespell

---

xarray/core/groupby.py

Cleaner implementation; also broken out from #6689

Refactor groupby binary ops code.

---

doc/whats-new.rst
xarray/core/duck_array_ops.py
xarray/core/indexing.py
xarray/core/utils.py
xarray/core/variable.py
xarray/tests/test_array_api.py

Note: I haven't actually tested this with pytorch (which is the motivating example for #3232).

Support NumPy array API (experimental)

---

xarray/core/coordinates.py
xarray/core/dataset.py
xarray/core/indexes.py
xarray/tests/test_dataarray.py
xarray/tests/test_dataset.py

Drop multi-indexes when assigning to a multi-indexed variable

---

doc/api.rst
doc/whats-new.rst

Release notes for v2022.06.0

---

doc/api.rst
doc/whats-new.rst
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/variable.py
xarray/tests/test_array_api.py
xarray/tests/test_sparse.py

This implements the suggestion in https://github.com/pydata/xarray/issues/4842#issuecomment-769198581 to leave the nbytes calculation to the backend array.
Also removed the duplicate docs entry reported in #6565

Pull xarray's nbytes from nbytes attribute on arrays

---

xarray/backends/api.py

This adds a short docstring example to `xr.open_mfdataset` to showcase how to pass arguments into `preprocess` for `xr.open_mfdataset`.
It wasn't very clear before how to do this, and this hopefully will show an easy and minimal pathway to doing so.

Add docstring example for xr.open_mfdataset

---

xarray/plot/utils.py
xarray/tests/test_plot.py

Make sure name is a string. Use the same `.format` method as in `_get_units_from_attrs` to convert to string.

Convert name to string in label_from_attrs

---

ci/requirements/environment.yml
doc/whats-new.rst
xarray/core/npcompat.py

This PR removes the `_SupportsDType` dependency from numpy and introduces its own.
Closes https://github.com/pydata/xarray/issues/6818

Fix numpy 1.20 incompatibility

---

doc/whats-new.rst
xarray/plot/facetgrid.py
xarray/tests/test_plot.py

Added `handle.update(kwargs)` after `handle.set_text(title)` so that the title properties sent using keyword arguments are also updated.

Fix FacetGrid.set_titles #6839

---

xarray/coding/variables.py

`_pop_to` does a pop operation - it removes the key/value pair. So the line above this change will remove `add_offset` from `attrs` if it exists. The second line then checks for `add_offset` in `attrs` which should always be `False`. 
This is implemented in #6812 but the work there is significantly more involved (see for example different PR addressing the same problem, #2304), so I'm pulling this fix out and submitting it as its own PR.

Fix logic bug - add_offset is in encoding, not attrs.

---

xarray/plot/utils.py

Reduce diffs in #6778. `_interval_to_double_bound_points` was returning a `list` instead of `ndarray` which I had some issues with.

Add typing to some interval functions

---

xarray/tests/test_variable.py

We could probably replace the default indexes with `cudf` indexes, but with `pandas` indexes this test doesn't make too much sense.

skip creating a cupy-backed IndexVariable

---

xarray/plot/utils.py
xarray/tests/test_plot.py

Reduce diffs in #6778. 
* Handle `None` as the error message suggest should be possible 
* Add some typing while at it. 
mypy noticed that Hashable cannot use `", ".join`-method so forcing them to `str` instead. 
Should be the same problem in #6856 but `Frozen` returns `Any` instead of `Hashable` for some reason.

Handle None in assert_valid_xy

---

xarray/tests/test_distributed.py

This is a quickfix similar to https://github.com/dask/dask/pull/9337. Note there's a conversation happening over in https://github.com/dask/distributed/issues/6806 around what testing utilities in `distributed` should be considered public.

Temporarily import `loop_in_thread` fixture from `distributed`

---

doc/whats-new.rst
xarray/core/common.py
xarray/tests/test_formatting.py

* Rely on array backend for string formatting instead of forcing to numpy arrays. The previous implementation used `.values` to force to numpy arrays which doesn't work for sparse arrays and might be scary in the case of large dask arrays.
* Only allow `format_spec` when dealing with scalar arrays, shape=(). Using f-strings is a common method to print the repr. If we want to have full support of `.__format__` we should probably add `format_spec` as input to `formatting.array_repr`. 
```python
import pandas as pd
s = pd.Series(
range(4),
index=pd.MultiIndex.from_product([list("ab"), list("cd")]),
)
da = xr.DataArray.from_series(s, sparse=True)
print(f"Error: {da} is sparse")
Error: <xarray.DataArray (level_0: 2, level_1: 2)>
<COO: shape=(2, 2), dtype=float64, nnz=4, …
```

Rely on array backend for string formatting

---

xarray/tests/test_backends_file_manager.py

Fixes:
```
xarray/tests/test_backends_file_manager.py:56: error: Incompatible types in assignment (expression has type "_GeneratorContextManager[Any]", variable has type "WarningsChecker")  [assignment]
```
Just added a ignore.

Fix mypy CI

---

xarray/core/nanops.py
xarray/tests/test_units.py

At the moment, `nanprod` and `nansum` will replace any `nan` values with `1` for `nanprod` or `0` for `nansum`. For `pint`, inserting dimensionless values into quantities is explicitly not allowed, so our version of `nanprod` cannot be used on `pint` quantities (`0` is a exception so `nansum` does work).
I'm proposing to rely on `numpy`'s version for that, which would allow `pint` to customize the behavior.

rely on `numpy`'s version of `nanprod` and `nansum`

---

doc/whats-new.rst
xarray/coding/times.py
xarray/tests/test_coding_times.py

Allow decoding of size-0 datetimes

---

xarray/plot/facetgrid.py

Prepare to be able to use a `.set_zlabels` in facetgrids. Reduces diffs in #6778.

Generalize set_(x, y, z)labels in facetgrids

---

licenses/SCIKIT_LEARN_LICENSE
xarray/tests/test_deprecation_helpers.py
xarray/util/deprecation_helpers.py

Adds a helper function to deprecate positional arguments. IMHO this offers a good trade-off between magic and complexity. (As mentioned this was adapted from scikit-learn).
edit: I suggest to actually deprecate positional arguments in another PR.

decorator to deprecate positional arguments

---

xarray/core/types.py

Adds `typing_extensions.Self` wrapped in some safety checks.
Wont really become useful until https://github.com/python/mypy/issues/11871 is fixed. But it can be used with pyright at least.

Add Self in xarray.core.types

---

doc/whats-new.rst
xarray/core/concat.py
xarray/tests/test_concat.py

In the current implementation, the `concat` function does not ensure that the indexes that belong to the same `MultiIndex` relate to the same `MultiIndex` object in `Dataset.indexes` when concatenating along a new dimension. This becomes a problem as soon as the returned dataset needs to be aligned (for broadcasting, reindexing etc.), see #6881 for example. As far as I understand, this bug was introduced in https://github.com/pydata/xarray/pull/5692 following the idea that the `concat` function should disentangle indexes and dimensions. 
It can be fixed by not removing the index name from the list of indexes which should be merged, see https://github.com/pydata/xarray/blob/9050a8b9efc28142b762475c7285603a87b00e83/xarray/core/concat.py#L493. All indexes contained in this list will get a …

Harmonize returned multi-indexed indexes when applying `concat` along new dimension 

---

doc/whats-new.rst
xarray/plot/utils.py
xarray/tests/test_plot.py

This PR fixes the broadcasting error when trying to plot multiple step plots, like `arr.plot.step(..., hue=...)` or `arr.plot(..., drawstyle="steps-mid")`. Previously, this raised a shape error, as mentioned in https://github.com/pydata/xarray/issues/4288#issuecomment-666485140. Some other relevant work was started (but apparently unfinished) in #4868 and #4866, this doesn't implement those.

Fix step plots with hue

---

doc/whats-new.rst
xarray/tests/test_weighted.py

Avoid use of random numbers in `test_weighted.test_weighted_operations_nonequal_coords`

---

doc/whats-new.rst
xarray/core/alignment.py
xarray/tests/test_dataset.py

Fix aligned index variable metadata side effect

---

setup.cfg

no longer install pydap for 'io' extras in py3.10

---

ci/requirements/environment-windows.yml
ci/requirements/environment.yml
xarray/tests/test_backends.py

#5844 excluded pydap from our tests - but the new version has been released in the meantime (on conda not on pypi, though, pydap/pydap#268) - so let's see if this still works.

enable pydap in tests again

---

xarray/tests/test_deprecation_helpers.py
xarray/util/deprecation_helpers.py

I tried to use the `_deprecate_positional_args` decorator from #6934 & it turns out that it still had some errors - passing on the arguments did not work properly in certain cases... I now added tests for this as well (which I should have done in the first place...).

fix _deprecate_positional_args helper

---

CITATION.cff
setup.cfg

This PR improves CITATION.cff to add abstract, license and repository-code fields, and to modify url to https://xarray.dev/
Also, update the metadata licence from "Apache", to "[Apache-2.0](https://spdx.org/licenses/Apache-2.0.html)", which is the short identifier defined by SPDX.

Improve CITATION.cff, specify license version in metadata

---

xarray/coding/times.py
xarray/core/common.py
xarray/core/merge.py
xarray/tests/test_array_api.py
xarray/tests/test_duck_array_ops.py
xarray/tests/test_weighted.py

This PR tries to get rid of several warnings in the tests.
I could not get rid of `RuntimeWarning: All-NaN slice encountered` for tests with dask.
Does anyone know why is that? pytest.mark.filterwarnings does not seem to capture them...

Remove some warnings in tests

---

xarray/tests/test_accessor_dt.py

This PR simplifies the tests for the calendar attribute on the `dt` accessor when using a `datetime64[ns]`-dtype DataArray.  Instead of creating random-valued datetime arrays, we can use arrays of zeros (i.e. 1970-01-01), since the values of the datetimes should not be relevant to these tests (only their type matters).
I suspect this should address #6906, because it eliminates the need to convert to `datetime64[ns]`, though I still feel as though there is a more fundamental pandas issue lurking there.

Simplify datetime64 `dt.calendar` tests

---

doc/internals/how-to-add-new-backend.rst

Noticed a tiny typo when reading through https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html

`kwargs` typo in custom backend docs

---

.github/workflows/pypi-release.yaml
.github/workflows/testpypi-release.yaml
pyproject.toml

This PR does a few related things:
- Remove `wheel` from `pyproject.toml`, since it is no longer needed/documented (e.g. [here](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)), and rename other dependencies to their names in PyPI
- Remove `pip install` build dependencies already specified in `pyproject.toml`
- Remove [`check-manifest`](https://pypi.org/project/check-manifest/), since it isn't used
- The command `python -m build` has defaults to build both sdist and wheel outputs
- Use `twine check --strict` to return non-zero status on warnings

Remove unnecessary build dependencies, use build defaults, strict twine check

---

setup.cfg
xarray/core/computation.py
xarray/core/dataarray.py
xarray/core/dataset.py
xarray/core/types.py
xarray/core/variable.py
xarray/core/weighted.py
xarray/tests/test_computation.py
xarray/tests/test_dataarray.py

This PR adds an `Ellipsis` typehint to some functions.
Interestingly mypy did not complain at the tests before, I assume it is because "..." is Hashable or something like that?
I don't know what to do with reductions, since they also support ellipsis, but it is basically the same as using None.
Therefore, I assume it is not necessary to expose this feature.
Did I miss any functions where ellipsis is supported? It is hard to look for "..."... xD

Add Ellipsis typehints
