pydata/xarray

- doc/whats-new.rst
- xarray/backends/api.py
- xarray/tests/test_backends.py
Closes #5888. At the moment if you pass a `Path` object, the `source` will not be encoded in, only if a string is passed in. Given there is already a function to handle this, `_normalize_path`, I've simplified the logic to just run that over the `str/Path` to ensure it is always encoded.
I'm not sure if this needs including in the `whats-new.rst`. I'm happy to add it if desired.
> Ensure encoding["source"] is available for a pathlib.Path object

- xarray/core/types.py
Self should be as permissive as possible until it works properly.
Using `Any` instead of `TypeVar` avoids errors like these:
`C:\users\j.w\documents\github\xarray\xarray\plot\facetgrid.py:462: error: Incompatible return value type (got "FacetGrid", expected "Self")`
xref: #6923
> Self should be Any

- doc/whats-new.rst
- xarray/backends/zarr.py
- xarray/tests/test_backends.py
I've often been tripped up by the stack trace noted in #6484. This PR changes two things:
1. Handles the zarr `GroupNotFoundError` error with a more informative `FileNotFoundError`, displaying the path where we didn't find a zarr store.
2. Moves the consolidated metadata warning to after the step of successfully opening the zarr with non-consolidated metadata. This way the warning isn't shown if we are actually trying to open a non-existent zarr store, in which case we only get the error above and no warning.
> More informative error for non-existent zarr store

- doc/whats-new.rst
- xarray/backends/api.py
- xarray/tests/test_distributed.py
@dcherian Writing NetCDFs containing only dimensionless variables only failed with the distributed or multiprocessing schedulers. I have thus thought a unit test would fit better in `test_distributed` rather than in `test_backends` - but let me know if you think otherwise!
> Writing dimensionless variables to NetCDF

- doc/user-guide/groupby.rst
This is a very small change to the group-by title and an intro sentence.   I think sometimes the user docs assume knowledge of pandas GroupBy, whereas I think a decent chunk of xarray users don't have background with pandas.  The rest of the tutorial is a really nice overview, but if you are scanning docs, its nice to have the end goal explained.
> DOC: improve name and intro to groupby

- doc/whats-new.rst
- xarray/core/rolling.py
- xarray/tests/test_rolling.py
This just tests to make sure we at least get the same dtype whether we have a numpy or dask array.
> Better dtype preservation for rolling mean on dask array

- xarray/core/indexes.py
- xarray/tests/test_indexes.py
> Misc. fixes for Indexes with pd.Index objects

- README.md
I updated the dead link under the contributing tab.
This is my first time contributing to any open source project, so if I have done anything wrong please let me know.
> Fixed readme to have correct link for contributing page

- xarray/plot/facetgrid.py
This PR adds a helper method that sets the same axis limits for all plots in a facetgrid.
Helpful when
* wanting specific limits for all plots.
* you want to make sure all data is visible by simply using the method without any inputs. Which is not certain if sharex/sharey isn't used, relevant when using 3d plots as they don't work.
Split up from #6778.
> Add helper for setting axis limits in facetgrid

- xarray/plot/facetgrid.py
Matplotlibs 3d plots appears to not support sharex/sharey. So reset to default values instead. This improves the look of the plot as axis values aren't deleted. 
Example:
```python
import matplotlib.pyplot as plt
fig = plt.figure()
subplot_kws = {"projection":"3d"}
ax1 = fig.add_subplot(211, **subplot_kws)
ax1.plot([0, 1, 2], [5,6,6])
ax2 = fig.add_subplot(212, sharex = ax1, **subplot_kws)
ax2.plot([0, 1, 2], [5,4,2])  # x axis is not linked.
```
Split up from #6778.
> Set sharex/sharey to False if using 3d plots

- doc/user-guide/indexing.rst
I have attempted to add an example of dictionary-based assignment to the documentation following the discussion with @mathause and @dcherian. Any further clarifications are appreciated.
> add dictionary-based integer assignment example (GH7043)

- doc/whats-new.rst
- xarray/plot/plot.py
- xarray/plot/utils.py
- xarray/tests/test_plot.py
> Fix `utils.get_axis` with kwargs

- xarray/core/coordinates.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_dataset.py
@dcherian the `DeprecationWarning` was ignored by default for `.assign_coords()` because of https://github.com/pydata/xarray/pull/6798#discussion_r924653224. I changed it to `FutureWarning` so that it is shown for both `.assign()` and `.assign_coords()`.
> Fix Dataset.assign_coords overwriting multi-index

- .coveragerc
- pyproject.toml
tiny PR that disables coverage on `types.py` and all typing-only imports a.la. `if TYPE_CHECKING: ...`
> Exclude typechecking stuff from coverage

- doc/whats-new.rst
- xarray/tests/test_dataarray.py
> Added test_deepcopy_nested_attrs() (#2835).

- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/indexes.py
- xarray/core/variable.py
- xarray/tests/test_dataarray.py
> Fix deepcopy of Variables and DataArrays

- doc/whats-new.rst
- xarray/core/dataset.py
- xarray/tests/test_dataset.py
Closes #6502 
~~- [ ] New functions/methods are listed in `api.rst`~~
> More informative error for passing a list to dataset.transpose

- xarray/backends/api.py
- xarray/backends/common.py
- xarray/backends/plugins.py
- xarray/core/dataset.py
- xarray/tests/__init__.py
- xarray/tests/test_backends.py
- xarray/tests/test_dataset.py
- xarray/tests/test_distributed.py
- xarray/tests/test_groupby.py
- xarray/tests/test_plugins.py
While adding type hints to `test_backends` I noticed that the `open_dataset` method and the abstract `BackendEntrypoint` were missing stream types as inputs.
> Fix typing of backends

- doc/whats-new.rst
- xarray/core/indexes.py
Forgot to add this to #7112 
Also, correct the date of the 2022.09 release in whats-new, see #7135
> Fixes deepcopy of Index

- .pre-commit-config.yaml
We started to pin the version of `black` used in the environment of `blackdoc`, but the version becomes out-of-date pretty quickly. The new hook I'm adding here is still experimental, but pretty limited in what it can destroy (the `pre-commit` configuration) so for now we can just review any new autoupdate PRs from the `pre-commit-ci` a bit more thoroughly.
> use a hook to synchronize the versions of `black`

- doc/whats-new.rst
- xarray/conventions.py
- xarray/tests/test_conventions.py
I'm not sure if there is a better way to do this, but this is one way to address #7145.  The error message for the example now looks like:
```
>>> xr.decode_cf(ds)
File "/Users/spencer/software/xarray/xarray/coding/times.py", line 275, in decode_cf_datetime
dates = _decode_datetime_with_pandas(flat_num_dates, units, calendar)
File "/Users/spencer/software/xarray/xarray/coding/times.py", line 210, in _decode_datetime_with_pandas
raise OutOfBoundsDatetime(
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Cannot decode times from a non-standard calendar, 'noleap', using pandas.
During handling of the above exception, another exception occurred:
File "/Users/spencer/software/xarray/xarray/coding/times.py", line 180, in …
```
> Include variable name in message if `decode_cf_variable` raises an error

- doc/whats-new.rst
- xarray/backends/api.py
- xarray/tests/test_backends_api.py
Based on feedback on this issue: #7139
> Update open_dataset backend to ensure compatibility with new explicit index model

- xarray/tests/test_formatting.py
Technically does not close all fails, but if we close it, the CI will open a new issue anyway and the discussion is not relevant anymore :)
> Fix broken test that fails CI upstream

- xarray/plot/dataarray_plot.py
- xarray/plot/facetgrid.py
- xarray/plot/utils.py
Fix some issues with scatter plots:
* Always use markersize widths for scatter.
* Fix issue with `.values_unique` not returning the same values as `.values`
* Added more type hints to _Normalize, some rework had to be done to make mypy pass.
xref: #6778
> Fix some scatter plot issues

- asv_bench/benchmarks/import.py
related to https://github.com/pydata/xarray/issues/6726
> Add import ASV benchmark

- xarray/conventions.py
- xarray/core/duck_array_ops.py
- xarray/core/nanops.py
- xarray/core/variable.py
- xarray/tests/test_array_api.py
Including aggregation with nans, astype, where, stack.
This is a follow-on to #6804, delegating more functions to `np` or `xp` as appropriate.
> More Array API changes

- doc/whats-new.rst
- xarray/__init__.py
- xarray/backends/locks.py
I was auditing the import time of my software and found that distributed added a non insignificant amount of time to the import of xarray:
Using `tuna`, one can find that the following are sources of delay in import time for xarray:
To audit, one can use the the command
```
python -X importtime -c "import numpy as np; import pandas as pd; import dask.array; import xarray as xr" 2>import.log && tuna import.lo
```
The command as is, breaks out the import time of numpy, pandas, and dask.array to allow you to focus on "other" costs within xarray.
Main branch:
Proposed:
One would be tempted to think that this is due to xarray.testing and xarray.tutorial but those just move the imports one level down in tuna graphs.
> Lazy import dask.distributed to reduce import time of xarray

- doc/user-guide/computation.rst
- doc/user-guide/reshaping.rst
- doc/whats-new.rst
I realised there is very little documentation on `Coarsen.construct`, so I added this example.
Unsure whether it should instead live in the page on reshaping and reorganising data though, as it is essentially a reshape operation. EDIT: Now on the reshape page
cc @jbusecke @paigem
> Example using Coarsen.construct to split map into regions

- xarray/tests/test_tutorial.py
- xarray/tutorial.py
This test has been quite troublesome and since `.open_rasterio` has been deprecated since 0.20 I think it's fine removing the test.
> Remove rasterio tutorial test

- doc/user-guide/plotting.rst
- doc/whats-new.rst
- xarray/plot/facetgrid.py
I noticed that the normal notation for `fig, axs = plt.subplots(2, 1)` wasn't used in facetgrid so did a quick find replace to change that.
This feels better for my pedantic brain at least but I'm not sure it's worth the effort?
> Align naming convention with plt.subplots

- .github/workflows/ci-additional.yaml
- .github/workflows/ci.yaml
- .github/workflows/upstream-dev-ci.yaml
In order to follow the minor releases of `ci-trigger`, we can use the new `v1` release tag that will always point to the most recent release.
> use the moving release tag of ci-trigger

- .github/workflows/upstream-dev-ci.yaml
I'm not sure if we actually need the dedicated "report" job, or whether adding an additional step to the main ci job would suffice?
I can see two reasons for a separate job:
1. we get to control the python version independently from the version of the main job
2. we upload the reportlog files as artifacts
I think if we can change the action to abort if it is run on a python version it does not support the first concern would not matter anymore, and for 2 we might just keep the "upload artifact" action (but is it even possible to manually access artifacts? If not we might not even need the upload).
Since I don't think either is a major concern, I went ahead and joined the jobs.
> use the new action to create an issue from the output of reportlog

- doc/api-hidden.rst
- doc/api.rst
- doc/whats-new.rst
- xarray/backends/__init__.py
- xarray/backends/h5netcdf_.py
- xarray/backends/netCDF4_.py
- xarray/backends/pseudonetcdf_.py
- xarray/backends/pydap_.py
- xarray/backends/scipy_.py
- xarray/backends/store.py
- xarray/backends/zarr.py
> Backends descriptions

- xarray/core/alignment.py
In relation to my other PR.
Without this PR
With the early return
<details><summary>Removing the frivolous copy (does not pass tests)</summary>
</details>
<details><summary>Code for benchmark</summary>
```python
from tqdm import tqdm
from time import perf_counter
N = 1000
dummy_dataset = xr.Dataset()
dummy_dataset['a'] = 1
dummy_dataset['b'] = 1
del dummy_dataset
time_elapsed = np.zeros(N)
dataset = xr.Dataset()
for i in tqdm(range(N)):
time_start = perf_counter()
dataset[f"var{i}"] = i
time_end = perf_counter()
time_elapsed[i] = time_end - time_start
from matplotlib import pyplot as plt
plt.plot(np.arange(N), time_elapsed * 1E3, label='Time to add one variable')
plt.xlabel("Number of existing variables")
plt.ylabel("Time to add a variables (ms)") …
```
> Actually make the fast code path return early for Aligner.align

- xarray/plot/dataarray_plot.py
Removes a warning in the plotting tests, related to https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.5.0.html#auto-removal-of-grids-by-pcolor-and-pcolormesh.
I just added `ax.grid(False)` but maybe we just want whatever is the default of matplotlib?
```python
airtemps = xr.tutorial.open_dataset("air_temperature")
air = airtemps.air - 273.15
air.attrs = airtemps.air.attrs
air.attrs["units"] = "deg C"
air2d = air.isel(time=500)
fig, axs = plt.subplots(2,1)
air2d.plot(ax=axs[0])  # No grid.
air2d.plot(ax=axs[1])  # With grid.
axs[1].grid(True)
```
> Explicitly remove grids for pcolormesh

- asv_bench/benchmarks/merge.py
I don't think this affects what is displayed that is determined by param_names
> Fix type in benchmarks/merge.py

- .github/workflows/ci.yaml
While working on #7241, I realized that I forgot to specify the python in our main CI, with the effect that we've been testing python 3.10 twice for each OS since the introduction of the `micromamba` action.
> fix the environment setup: actually use the python version

- doc/whats-new.rst
- xarray/core/dataarray.py
Added examples to the docstring of the following methods:
`DataArray.drop_vars()`
`DataArray.reindex_like()`
`DataArray.interp_like()`
I will gradually edit this PR and add more examples to other methods.
I'll gladly accept feedback to improve upon my work :)
> DOC: Added examples to docstrings of DataArray methods (#7123)

- xarray/backends/api.py
The example in `xarray.open_mfdataset` mentions usage of partial function, but does not use it correctly:
(`_preprocess` should not be used as a parameter, but `partial_func` should be used)
```python
partial_func = partial(_preprocess, lon_bnds=lon_bnds, lat_bnds=lat_bnds)
ds = xr.open_mfdataset(
"file_*.nc", concat_dim="time", preprocess=_preprocess
) 
```
This PR fixes the example, to use `partial_func`:
```python
partial_func = partial(_preprocess, lon_bnds=lon_bnds, lat_bnds=lat_bnds)
ds = xr.open_mfdataset(
"file_*.nc", concat_dim="time", preprocess=partial_func
) 
```
> Use partial function in open_mfdataset example

- xarray/core/utils.py
- xarray/core/variable.py
- xarray/tests/test_utils.py
Thanks for the feedback @hmaarrfk.  Is this what you had in mind?
For example running this script:
```python
times = [np.datetime64("2000-01-01", "us")]
var = xr.Variable(["time"], times)
da = xr.DataArray(times)
```
leads to the following warnings:
```
$ python test_warning.py
test_warning.py:6: UserWarning: Converting non-nanosecond precision datetime values to nanosecond precision. This behavior can eventually be relaxed in xarray, as it is an artifact from pandas which is now beginning to support non-nanosecond precision values. This warning is caused by passing non-nanosecond np.datetime64 or np.timedelta64 values to the DataArray or Variable constructor; it can be silenced by converting the values to nanosecond precision ahead of time.
var = …
```
> Improve non-nanosecond warning

- .github/workflows/upstream-dev-ci.yaml
Like most github actions (or at least all the official `actions/*` ones), `issue-from-pytest-log` maintains a moving release tag that points to the most recently released version.
In order to decrease the amount of updating PRs, this makes use of that tag.
> use the moving release tag of `issue-from-pytest-log`

- .github/workflows/ci-additional.yaml
The type checking CI has started to fail with the new upgrade. In order not to disturb unrelated PRs, this pins `mypy` to a known good version (`mypy<0.990`).
> pin mypy to a known good version

- xarray/plot/utils.py
Found an issue when constant values was used. Now if constant values are found it'll default to the minimum width value instead.
> Handle division by zero in _Normalize._calc_widths

- xarray/core/pycompat.py
Fixes these errors that I've been seeing locally for a while:
```python
!mypy C:\Users\J.W\Documents\GitHub\xarray\xarray\core\coordinates.py --ignore-missing-imports
C:\Users\J.W\Documents\GitHub\xarray\xarray\core\pycompat.py:48: error: Incompatible types in assignment (expression has type "Tuple[]", variable has type "Tuple[Any]")
C:\Users\J.W\Documents\GitHub\xarray\xarray\core\pycompat.py:50: error: Incompatible types in assignment (expression has type "Optional[Module]", variable has type "Optional[Literal['dask', 'pint', 'cupy', 'sparse']]")
Found 2 errors in 1 file (checked 1 source file)
```
Not sure why the CI isn't catching these?
> Fix some typing errors in DuckArrayModule

- xarray/util/print_versions.py
It's a little tricky getting the mypy version, so adding it to the show_versions function as well.
> Add mypy version to xr.show_versions

- pyproject.toml
- xarray/core/pycompat.py
dask has added py.typed files so now the ignores shouldn't be needed anymore:
https://github.com/dask/dask/pull/8854
https://github.com/dask/distributed/pull/5328
As does numpy and pint
pycompat.py doesn't error anymore, so it's good to type check that one as well. Fixed also a python 3.8 related error in it.
> mypy - Remove some ignored packages and modules

- ci/requirements/all-but-dask.yml
- ci/requirements/environment-windows.yml
- ci/requirements/environment.yml
- ci/requirements/min-all-deps.yml
- doc/user-guide/io.rst
- doc/whats-new.rst
- xarray/backends/pynio_.py
This PR finally deprecates the PyNIO backend. PyNIO is technically in maintenance mode but it hasn't had any maintenance in 4+ years. Its conda packages cannot be installed in any of our test environments. I have added a future warning to the `NioDataStore.__init__` method and noted the deprecation in the IO docs.
> deprecate pynio backend

- doc/whats-new.rst
I noticed the PR number was off in my what’s new entry in #7284.  This fixes that.
> Fix PR number in what’s new

- xarray/backends/h5netcdf_.py
It seems that the relevant issue was fixed in 2.10.0 https://github.com/h5py/h5py/commit/466181b178c1b8a5bfa6fb8f217319e021f647e0
I'm not sure how far back you want to fix things. I'm hoping to test this on the CI.
I found this since I've been auditing slowdowns in our codebase, which has caused me to review much of the reading pipeline.
Do you want to add a test for h5py>=2.10.0? Or can we assume that users won't install things together.
https://pypi.org/project/h5py/2.10.0/
I could for example set the backend to not be available if a version of h5py that is too old is detected.
One could alternatively, just keep the code here.
> Remove code used to support h5py<2.10.0

- asv_bench/benchmarks/renaming.py
- xarray/core/alignment.py
- xarray/core/indexes.py
- xarray/core/variable.py
I have passed along some more memo dicts, which could prevent some double deep-copying of the same data (don't know how exactly, but who knows :P)
Also, I have found some copy calls that did not pass along the deep argument (I am not sure if that breaks things, lets find out).
And finally I have found some places where shallow copies are enough.
All together it should improve the performance a lot when copying things around.
> Optimize some copying

- doc/whats-new.rst
- xarray/core/utils.py
- xarray/tests/test_backends.py
Instead of raising a ValueError about the file pointer not being at the start of the file, reset the file pointer automatically to zero, and warn that the pointer has been reset.
> Reset file pointer to 0 when reading file stream

- doc/user-guide/io.rst
- doc/whats-new.rst
> Docs: add example of writing and reading groups to netcdf

- doc/whats-new.rst
- xarray/core/merge.py
- xarray/tests/test_dataset.py
> Fix assign_coords resetting all dimension coords to default index

- doc/whats-new.rst
- xarray/core/variable.py
- xarray/tests/test_dataarray.py
Using `.data` accidentally tries to load the whole lazy arrays into memory.
Sad.
> Avoid loading entire dataset by getting the nbytes in an array

- doc/whats-new.rst
- xarray/coding/cftimeindex.py
With the upcoming pandas 2.0 release, we are enforcing a deprecation in `pd.Index.get_loc` to remove `method` and `tolerance`.  Just in case `get_loc` isn't 100% compatible with `get_indexer`, I structured the `elif` to use `get_loc` as much as possible. Let me know if any other adjustments are needed
> COMPAT: Adjust CFTimeIndex.get_loc for pandas 2.0 deprecation enforcement

- doc/whats-new.rst
- xarray/core/indexing.py
- xarray/tests/test_indexes.py
Just what @benbovy said to do in #7250. Thank you!
> Preserve original dtype when accessing MultiIndex levels

- ci/install-upstream-wheels.sh
Using the `numpy` HEAD together with `numba` is, in general, not supported (see numba/numba#8615). So in order to avoid the current failures and still be able to test `numpy` HEAD, this (temporarily) removes `numbagg` and `numba` (pulled in through `numbagg`), from the upstream-dev CI.
> remove `numbagg` and `numba` from the upstream-dev CI

- xarray/core/duck_array_ops.py
- xarray/tests/test_array_api.py
This change is needed to run @dcherian's Transformed Eulerian Mean diagnostic example in https://github.com/dcherian/ncar-challenge-suite/blob/main/tem.ipynb using the Array API (on Cubed, see https://github.com/tomwhite/cubed/issues/145).
> Make `broadcast` and `concat` work with the Array API

- asv_bench/benchmarks/indexing.py
- doc/whats-new.rst
- xarray/core/alignment.py
- xarray/core/indexes.py
May fix some performance regressions, e.g., see https://github.com/pydata/xarray/issues/7376#issuecomment-1352989233.
@ravwojdyla with this PR `ds.assign(foo=~ds["d3"])` in your example should be much faster (on par with version 2022.3.0).
> Some alignment optimizations

- .github/labeler.yml
- .github/workflows/benchmarks.yml
- .github/workflows/label-prs.yml
* Workaround for Pull Request Labeler The PR labeler keeps removing manually added labels. xref: https://github.com/actions/labeler/issues/112
* ASV benchmarks starts also when `topic-performance` label is added now. Bot is allowed to change this one, but not `run-benchmarks`.
> Pull Request Labeler - Workaround sync-labels bug

- asv_bench/benchmarks/dataset_io.py
This tests xr.open_dataset without any slow file reading that can quickly become the majority of the performance time.
Related to #7374.
Timings for the new ASV-tests:
```
[ 50.85%] ··· dataset_io.IOReadCustomEngine.time_open_dataset                 ok
[ 50.85%] ··· ======== ============
chunks              
-------- ------------
None     265±4ms   
{}     1.17±0.02s 
======== ============
[ 54.69%] ··· dataset_io.IOReadSingleFile.time_read_dataset                   ok
[ 54.69%] ··· ========= ============= =============
--                   chunks          
--------- ---------------------------
engine       None           {}     
========= ============= =============
scipy     4.81±0.1ms   6.65±0.01ms 
netcdf4   8.41±0.08ms    10.9±0.2ms 
========= ============= =============
```
From the …
> Add lazy backend ASV test

- xarray/backends/api.py
This adds a sentence (below) under "chunks" in doctoring of `open_dataset()` to clarify current usage for those who want the same behavior as `open_zarr()` used to provide:
```
In order to reproduce the default behavior of xr.open_zarr(...) use `xr.open_dataset(..., engine='zarr', chunks={})`.
```
> Refer to open_zarr in open_dataset docstring

- xarray/core/computation.py
Since #5041, `apply_ufunc()`'s `keep_attrs` parameter accepts `combine_attrs`-style strings. (First included  [v0.18.1](https://docs.xarray.dev/en/stable/whats-new.html#id192) release)
But this was not explained in its documentation.
> Update description of `keep_attrs` parameter in documentation of `apply_ufunc()`

- doc/whats-new.rst
Should update the date and delete empty sections before merging
> v2023.01.0 whats-new

- doc/whats-new.rst
- xarray/core/alignment.py
- xarray/core/concat.py
- xarray/tests/test_concat.py
This is another attempt to solve #508. Took inspiration from #3545 by @scottcha.
This follows along @dcherian's comment in the same above PR (https://github.com/pydata/xarray/pull/3545#issuecomment-586346637).
Update:
After review the variable order is estimated by order of appearance in the list of datasets. That keeps full backwards compatibility and is deterministic. Thanks @dcherian and @keewis for the suggestions.
> Fill missing data_vars during concat by reindexing

- ci/requirements/all-but-dask.yml
- ci/requirements/doc.yml
- ci/requirements/environment-windows.yml
- ci/requirements/environment.yml
It seems there is a `numbagg` package on `conda-forge` now.
Not sure what to do about the `min-all-deps` CI, but given that the most recent version of `numbagg` happened more than 12 months ago (more than 18 months, even) maybe we can just bump it to the version on `conda-forge`?
> install `numbagg` from `conda-forge`

- .readthedocs.yaml
RTD somewhat recently introduced the [build.jobs](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-jobs) setting, which allows [skipping builds](https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition) (technically it's more of a "automated cancel" with a special error code instead of a skip) on user-defined conditions. We can use that to manually "skip" builds we don't need a documentation build for.
Edit: the only downside seems to be that the build is not actually marked as "skipped"
Edit2: apparently that's a bug that's being worked on, see readthedocs/readthedocs.org#9807
> allow skipping RTD builds

- asv_bench/benchmarks/pandas.py
> Add benchmarks for to_dataframe and to_dask_dataframe

- .readthedocs.yaml
We can't use the example `grep` options because we usually enclose tags with `[]`, which `grep` will interpret as character classes.
> fix the RTD build skipping feature

- doc/whats-new.rst
- xarray/core/dataset.py
- xarray/tests/test_dataset.py
Should I describe in  `whats-new.rst`?
> Follow keep_attrs in Dataset binary ops

- xarray/tests/__init__.py
I'm not totally sure why `single-threaded` was being set to begin with, so I might be missing some important context here 
Closes https://github.com/pydata/xarray/issues/7483
> Remove Dask single-threaded setting in tests

- doc/whats-new.rst
- xarray/coding/cftime_offsets.py
- xarray/core/pdcompat.py
- xarray/core/types.py
- xarray/tests/test_cftime_offsets.py
- xarray/tests/test_cftimeindex_resample.py
Following pandas, this PR adds an `inclusive` argument to `xarray.cftime_range` and `xarray.date_range` and deprecates the `closed` argument.  Pandas will be removing the `closed` argument soon in their `date_range` implementation, but we will continue supporting it to allow for our own deprecation cycle.  
I think we may also need to update our minimum pandas version to 1.4 for this, since earlier versions of pandas do not support the `inclusive` argument.
> Add `inclusive` argument to `cftime_range` and `date_range` and deprecate `closed` argument

- doc/whats-new.rst
- xarray/backends/zarr.py
- xarray/tests/test_backends.py
> Zarr: drop "source" and  "original_shape" from encoding

- doc/whats-new.rst
- xarray/core/computation.py
- xarray/tests/test_computation.py
> Update apply_ufunc output_sizes error message

- doc/whats-new.rst
Oops. I used "Github Codespaces" to edit whats-new, but it turns if you commit in there, it just commits to main!
This fixes the pre-commit error.
> Fix whats-new for 2023.02.0

- xarray/tests/__init__.py
Suppress the `pkg_resources.namespace_package` `DeprecationError` to make the doctest pass again (similar to #7322). This is reported upstream: pydap/pydap#277 and matplotlib/matplotlib#25244
> supress namespace_package deprecation warning (doctests)

- xarray/core/dataarray.py
- xarray/core/dataset.py
There are probably many more of these that could be done, but xarray has great explainers that are not linked in the API reference.  Not sure if that is on purpose (obviously they are kind of useless if you aren't looking at the http version), but if not, this at least does them for `groupby`, which is something I always need the explainer for...
> DOC: cross ref the groupby tutorial

- xarray/core/types.py
I don't know how I feel about using private numpy classes that might change anytime.
Maybe within a if TYPE_CHECKING block it is not too bad?
> use numpys SupportsDtype

- xarray/backends/zarr.py
- xarray/tests/test_backends.py
~User visible changes (including notable bug fixes) are documented in `whats-new.rst`~
~New functions/methods are listed in `api.rst`~
The latest version of netcdf-c does not allow writing a NCZarr file without the xarray's `_ARRAY_DIMENSIONS` attribute.
Also, nczarr attributes are now lowercase.
> fix nczarr when libnetcdf>4.8.1

- doc/whats-new.rst
- xarray/core/dask_array_ops.py
- xarray/core/duck_array_ops.py
- xarray/core/nputils.py
- xarray/tests/test_dask.py
- xarray/tests/test_duck_array_ops.py
Use dask.array.reduction. For this we need to add support for the `keepdims` kwarg to `nanfirst` and `nanlast`. Even though the final result is always keepdims=False, dask runs the intermediate steps with keepdims=True.
> Support first, last with dask arrays

- doc/user-guide/time-series.rst
Fixed the link to [Indexing using Datetime Components](https://docs.xarray.dev/en/stable/user-guide/time-series.html#datetime-component-indexing) under the [Datetime Indexing](https://docs.xarray.dev/en/stable/user-guide/time-series.html#datetime-indexing) section.
> Fixed broken link in Issue 7556

- doc/whats-new.rst
- xarray/plot/dataarray_plot.py
- xarray/tests/test_plot.py
> Fix `pcolormesh` with str coords

- doc/whats-new.rst
- xarray/core/missing.py
- xarray/tests/test_missing.py
* Add missing dim argument (GH7597)
* Append a nan gap at the end of existing tests cases
> Fix missing 'dim' argument in _get_nan_block_lengths

- doc/contributing.rst
- doc/developers-meeting.rst
- doc/user-guide/computation.rst
- doc/user-guide/dask.rst
- doc/user-guide/groupby.rst
- doc/user-guide/indexing.rst
- doc/user-guide/io.rst
- doc/user-guide/pandas.rst
- doc/user-guide/time-series.rst
- doc/user-guide/weather-climate.rst
Hey @TomNicholas! This closes issue #7617, please review. Thanks!
> Use more descriptive link texts

- ci/requirements/all-but-dask.yml
- ci/requirements/doc.yml
- ci/requirements/environment-py311.yml
- ci/requirements/environment-windows-py311.yml
- ci/requirements/environment-windows.yml
- ci/requirements/environment.yml
- requirements.txt
- setup.cfg
Pandas is expecting to release v2 in two weeks (pandas-dev/pandas#46776 (comment)). But we are still incompatible with their main branch: 
- #7441 
- #7420
This PR pins pandas to `<2`
> Pin pandas < 2

- .github/workflows/label-prs.yml
Seems https://github.com/actions/labeler/issues/112 is fixed. So using false should work.
xref: #7431
> Pull Request Labeler - Undo workaround sync-labels bug

- doc/whats-new.rst
- xarray/backends/plugins.py
```bash
(xr) $ chmod 000 testfile.nc
(xr) $ python -c 'import xarray as xr
f=xr.open_dataarray("testfile.nc").load()'
MY_HOME/miniconda3/envs/xr/lib/python3.9/site-packages/xarray/backends/plugins.py:139: RuntimeWarning: 'netcdf4' fails while guessing
warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
MY_HOME/miniconda3/envs/xr/lib/python3.9/site-packages/xarray/backends/plugins.py:148: RuntimeWarning: 'netcdf4' fails while guessing
warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
MY_HOME/miniconda3/envs/xr/lib/python3.9/site-packages/xarray/backends/plugins.py:148: RuntimeWarning: 'h5netcdf' fails while guessing
warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
MY_HOME/miniconda3/envs/xr/lib/python3.9/site-packages/xarray/backends/plugins.py …
```
> Raise PermissionError when insufficient permissions

- asv_bench/benchmarks/groupby.py
> [skip-ci] Add compute to groupby benchmarks

- xarray/core/formatting_html.py
Apparently, `read_binary` has been marked as deprecated in `python=3.11`, and is to be replaced by `importlib.resources.files`, which has been available since `python=3.9`. Since we dropped support for `python=3.8` a while ago, we can safely follow the instructions in the deprecation warning.
> use the `files` interface instead of the deprecated `read_binary`

- doc/user-guide/time-series.rst
It cannot be run with python since previous dataset is unidimensionnal. Feel free to make it more rigorous if you want.
> [DOC] resample and then apply func on time+other variables

- xarray/tests/test_dask.py
Closes #1533
Seems to have been fixed by the indexes refactor
> Test: new index from dask.array computes only once

- doc/whats-new.rst
- xarray/coding/variables.py
- xarray/conventions.py
- xarray/tests/test_conventions.py
This PR implements remaining functionality in `encode_cf_variable`/`decode_cf_variable` as `VariableCoders` (as left as todo by @shoyer). It adapts the needed tests and adds some typing (thanks @Illviljan). Otherwise there are no changes in function to code.
It splits out of #7654 which turns out to be hard to follow (at least for me).
> Implement more Variable Coders

- asv_bench/asv.conf.json
- asv_bench/benchmarks/alignment.py
> [skip-ci] Add alignment benchmarks

- doc/whats-new.rst
- xarray/coding/variables.py
- xarray/tests/test_backends.py
Split out of #7654. Follow up to #7719. Needs rebase after #7719 is merged.
> preserve boolean dtype in encoding

- doc/whats-new.rst
- xarray/core/alignment.py
> align: Avoid reindexing when join="exact"

- doc/internals/extending-xarray.rst
Super minor docs updates that try to clarify that "accessors" are the tool used to "extend" xarray (for those of us who have spent time trying to figure out where/when to use which term).
> minor doc updates to clarify extensions using accessors

- ci/requirements/all-but-dask.yml
- ci/requirements/doc.yml
- ci/requirements/environment-py311.yml
- ci/requirements/environment-windows-py311.yml
- ci/requirements/environment-windows.yml
- ci/requirements/environment.yml
- doc/api-hidden.rst
- doc/user-guide/weather-climate.rst
- doc/whats-new.rst
- setup.cfg
- xarray/coding/cftime_offsets.py
- xarray/coding/cftimeindex.py
- xarray/coding/times.py
- xarray/core/pdcompat.py
- xarray/tests/test_cftime_offsets.py
- xarray/tests/test_concat.py
- xarray/tests/test_conventions.py
- xarray/tests/test_dataset.py
- xarray/tests/test_groupby.py
- xarray/tests/test_interp.py
- xarray/tests/test_plot.py
- xarray/tests/test_variable.py
This addresses the remaining cftime-related test failures in #7707 by introducing a function that always returns a nanosecond-precision Timestamp object.  Despite no corresponding test failures, for safety I grepped and went ahead and replaced the `pd.Timestamp` constructor with this function in a few other areas.  I also updated our documentation to replace any mentions of the "Timestamp-valid range" with "nanosecond-precision range" since Timestamps are now more flexible, and included a note that we have an issue open for relaxing this nanosecond-precision assumption in xarray eventually.
While in principle I think it would be fine if `CFTimeIndex.to_datetimeindex` returned a `DatetimeIndex` with non-nanosecond-precision values, since we don't use `to_datetimeindex` anywhere outside of …
> Continue to use nanosecond-precision Timestamps in precision-sensitive areas

- .pre-commit-config.yaml
Apparently, in addition to formatting notebooks, `black-jupyter` does exactly the same thing as `black`.
> remove the `black` hook

- .github/workflows/ci-additional.yaml
- doc/internals/extending-xarray.rst
- xarray/core/combine.py
- xarray/core/concat.py
- xarray/core/rolling.py
- xarray/core/utils.py
- xarray/tests/test_concat.py
- xarray/tests/test_plot.py
- xarray/tests/test_variable.py
Fixes typing errors when using newest mypy version.
> Fix typing errors using mypy 1.2

- .github/workflows/benchmarks-last-release.yml
This adds a benchmark of `HEAD` vs the latest tag on `main`.
> Add benchmark against latest release on main.

- doc/whats-new.rst
- xarray/core/groupby.py
- xarray/tests/test_groupby.py
@gsieros can you try this out please?
> Fix groupby_bins when labels are specified

- xarray/plot/dataarray_plot.py
Matplotlib has recently introduced type hints on our main version (due to be released with mpl v3.8 in a couple months) xref matplotlib/matplotlib#24976
As part of this, the dynamically generated aliases of certain functions are not included in static type hints (since they are dynamic).
So, a type hinted codebase should prefer the canonical names so that they can be type checked.
I encourage maintainers over here to run type checking with our new type hints, as this is not the only thing flagged.
Much of the remaining flags have to do with interactions with 3D axes, which are currently not type hinted in mpl (along with the rest of mpl_toolkits, for that matter).
Feel free to ping me if you have any questions regarding mpl's type hints and interactions here.
Partly opening this as a …
> Use canonical name for set_horizonalalignment over alias set_ha

- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/variable.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_dataset.py
- Added @pytest.mark.parametrize("numpy_data", [True, False]) to existing and edited existing
- Extended documentation for ds.to_dict and da.to_dict
> `ds.to_dict` with data as arrays, not lists

- doc/contributing.rst
- `asv` is on PyPI, so install from there instead of the git repo
- Update some links that are out of date
> Update asv links in contributing guide

- ci/min_deps_check.py
- doc/getting-started-guide/installing.rst
- doc/whats-new.rst
As discussed in #7765, this extends the policy months by 6 to a total of 30 months. With that, the support for a python version can be removed as soon as the *next* version is at least 30 months old. Together with the 12 month release cycle python has, we get the 42 month release window from NEP 29.
Note that this is still missing the release overview proposed in #7765, I'm still thinking about how to best implement the automatic update / formatting, and how to coordinate it with the (still manual) version overrides.
> adjust the deprecation policy for python

- doc/whats-new.rst
- xarray/core/groupby.py
- xarray/tests/test_groupby.py
> Fix groupby binary ops when grouped array is subset relative to other

- .github/workflows/benchmarks.yml
- asv_bench/asv.conf.json
- asv_bench/benchmarks/groupby.py
> [skip-ci] Add cftime groupby, resample benchmarks

- ci/requirements/all-but-dask.yml
- ci/requirements/environment-py311.yml
- ci/requirements/environment-windows-py311.yml
- ci/requirements/environment-windows.yml
- ci/requirements/environment.yml
Newest pint crashes our tests for some reason, pin it for now.
> Pin pint to 0.20

- xarray/tests/test_backends.py
Previously, the first context manager in this test was closed before accessing the data. This resulted in key errors when trying to access the opened dataset.
> test: Fix test_write_read_select_write for Zarr V3

- doc/whats-new.rst
- xarray/core/variable.py
- xarray/tests/test_variable.py
> Fix as_compatible_data for read-only np.ma.MaskedArray

- HOW_TO_RELEASE.md
- doc/whats-new.rst
Summary:
This release adds some new methods and operators, updates our deprecation policy for python versions, fixes some bugs with groupby, and introduces experimental support for alternative chunked parallel array computation backends via a new plugin system!
> Whats new for release of v2023.05.0

- xarray/tests/test_dtypes.py
Split out from #7858.
Improve mypy coverage in order to understand better what the functions are actually used for.
> Add type hints to test_dtypes

- xarray/core/utils.py
Following recommendation from: https://github.com/pydata/xarray/pull/7824#discussion_r1196114696
```python
a = tuple(f"dim_{i}" for i in range(500))
%timeit OrderedSet(a)
46 µs ± 2.26 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
a = tuple(f"dim_{i}" for i in range(500))
%timeit OrderedSet(a)
28.9 µs ± 476 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
> Avoid explicit loop when updating OrderedSet

- asv_bench/benchmarks/pandas.py
- xarray/core/dataset.py
* ds.chunks loops all the variables, do it once.
* Faster to create a meta dataframe once than letting dask guess 2000 times.
> Improve to_dask_dataframe performance

- doc/whats-new.rst
- xarray/core/pycompat.py
As described in issue #7870, there is a name-collision with the astrophysics package `pint-pulsar`, which is used to do high-precision pulsar timing. That other package would get imported as `pint`, and an `AttributeError` is thrown because that imported package is not the expected package.
By generalizing the duck typing exception to catch an `ImportError` and an `AttributeError`, we catch such name-collisions. It fits the idea and goal of duck typing.
This PR is a single-line change
> Changed duck typing exception to: (ImportError, AttributeError)

- xarray/tests/test_ufuncs.py
`numpy` has recently changed the result of `np.cos(0)` by a very small value, which makes our tests break.
I'm not really sure what the best fix is, so I split the changes into two parts: the first commit uses
```python
xr.testing.assert_allclose(a + 1, np.cos(a))
```
to test the result, while the second commit uses
```python
expected = xr.full_like(a, fill_value=np.cos(0), dtype=float)
actual = np.cos(a)
xr.testing.assert_identical(actual, expected)
```
> defer to `numpy` for the expected result

- ci/requirements/environment-py311.yml
`numba=0.57.0` has been out for quite some time already and is available on `conda-forge` as-of last week, which means we can almost retire the separate `python=3.11` environment file.
I'm not sure what to do about `cdms2` (we will see if that fails in CI), but in any case we should just deprecate and remove any functions that use it: if I understand correctly, `cdms2` is in maintenance mode until the end of the year and will be discontinued afterwards.
> add `numba` to the py3.11 environment

- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/tests/test_dataarray.py
As the `cdms2` library has been deprecated and will be retired at the end of this year, maintaining conversion functions does not make sense anymore. Additionally, one of the tests is currently failing on the upstream-dev CI (`cdms2` is incompatible with a recent change to `numpy`), and it seems unlikely this will ever be fixed (*and* there's no `python=3.11` release, blocking us from merging the `py311` environment with the default one).
cc @tomvothecoder for visibility
> deprecate the `cdms2` conversion methods

- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/tests/test_dataarray.py
With this PR, it's possible to pass an initial guess to `curvefit` that is a DataArray, which will be broadcast to the data dimensions. This way, the initial guess can vary with the data coordinates.
I also added examples of using `curvefit` to the documentation, both a basic example and one with the multidimensional guess.
I have a couple of questions:
- Should we change the signature to `p0: dict[str, float | DataArray] | None`, instead of `dict[str, Any]` (and same for bounds)? scipy only optimizes over scalars, so I think it would be safe to assume that the values should either be those, or arrays that can be broadcast.
- The usage example of curvefit is only in the docstring for DataArray, so now the docs differ between DA and dataset. But the example uses a DataArray only, so this …
> Implement multidimensional initial guess and bounds for `curvefit`

- xarray/core/groupby.py
- xarray/tests/test_groupby.py
> Fix .groupby(multi index level)

- doc/whats-new.rst
- xarray/core/dataset.py
- xarray/tests/test_dataset.py
~New functions/methods are listed in `api.rst`~
> fix polyfit changing the original object

- xarray/core/dataarray.py
Fix flaky doctest introduced in #7821, see https://github.com/pydata/xarray/pull/7821#issuecomment-1537142237.
This uses the `NUMBER` option to compare the output with less decimal precision. It's not part of standard doctest but an extension from pytest: https://docs.pytest.org/en/7.1.x/how-to/doctest.html#using-doctest-options
Another option would be to use `...` and the built-in `+ELLIPSIS` option, but IMO the current version is less confusing for someone reading the example.
> Fix flaky doctest for curvefit

- doc/whats-new.rst
- xarray/core/dtypes.py
- xarray/tests/test_dataarray.py
> Ensure dtype of reindex result matches dtype of the original DataArray

- doc/whats-new.rst
Release summary:
This release adds features to ``curvefit``, improves the performance of concatenation, and fixes various bugs.
---
For some reason when I try to use 
`git log "$(git tag --sort=v:refname | tail -1).." --format=%aN | sort -u | perl -pe 's/\n/$1, /'`
to return the list of all contributors since last release, it only returns Deepak :laughing: I'm not sure what's going wrong there - I definitely have all the git tags fetched, and other people have definitely contributed since the last version!
> Release summary for v2023.06.0

- doc/whats-new.rst
- xarray/backends/zarr.py
- xarray/tests/test_backends.py
Zarr stores implement the `__len__` method and thus checking if a store is truthy returns if the store is non-empty, not if the `chunk_store` variable is still `None`. With this fix, empty stores can be passed as `chunk_store` to the `to_zarr(...)` method and will actually be used.
> Fix check for chunk_store in zarr backend

- xarray/core/variable.py
* Relevant Cupy PR: https://github.com/cupy/cupy/pull/7575
>  fixing rolling_window issue with cupy

- doc/whats-new.rst
- xarray/core/_aggregations.py
- xarray/core/utils.py
- xarray/util/generate_aggregations.py
Generalizes a small check for chunked arrays in groupby so it now allows cubed arrays through to flox rather than just dask arrays. Does not actually mean that flox groupby will work with cubed yet though, see https://github.com/tomwhite/cubed/issues/223 and https://github.com/xarray-contrib/flox/issues/224
> Allow cubed arrays to be passed to flox groupby

- .pre-commit-config.yaml
Attempt to fix the pre-commit build failure I keep seeing in the CI (e.g. [this failure](https://results.pre-commit.ci/run/github/13221727/1688407091.YvAQyUabR0mkXgYloCyiVQ) from https://github.com/pydata/xarray/pull/7881)
> Update minimum version of typing extensions in pre-commit

- .readthedocs.yaml
RTD is deprecating the feature flag we made use of before.
> manually unshallow the repository on RTD

- doc/whats-new.rst
- xarray/backends/h5netcdf_.py
- xarray/backends/netCDF4_.py
- xarray/core/dataset.py
- xarray/tests/test_backends.py
> ensure no forward slashes in names for HDF5-based backends

- xarray/backends/api.py
- xarray/backends/common.py
A simple refactor to make it easier to retrieve the proper paths that `open_mfdataset` uses and passes on the engine.
I've been thinking how to make use of DataTree and one idea I wanted to try was:
* Open file (using` _find_absolute_path`).
* Get all groups in the file.
* For each group run `xr.open_mfdataset(..., group=group)`
> Move absolute path finder from open_mfdataset to own function

- ci/install-upstream-wheels.sh
Use https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/ instead.
> Use another repository for upstream testing

- xarray/tests/test_units.py
Temporally skip tests in order to make CI pass again, the troublesome tests are reported in #7971.
> Skip broken tests on Python 3.11 and Windows

- doc/examples/multidimensional-coords.ipynb
This PR aims to clarify that `xc` represents the longitudes of the data and `yc` the latitudes in the example [Working with Multidimensional Coordinates](https://docs.xarray.dev/en/stable/examples/multidimensional-coords.html).
> Improve explanation in example "Working with Multidimensional Coordinates"

- doc/whats-new.rst
Needed because I started the release process earlier this week by writing a whatsnew, that apparently got merged, but the release hasn't been issued since. I'll self-merge this and release now.
> Update whats-new.rst for new release

- doc/whats-new.rst
- xarray/core/variable.py
This is more consistent with the other exceptions raised in this function, and helps to more quickly diagnose issues when e.g. creating datasets.
Is this a large enough change to warrant an entry in `whats-new`?
> Use variable name in all exceptions raised in `as_variable`

- doc/whats-new.rst
- xarray/core/indexes.py
- xarray/core/variable.py
- xarray/testing.py
- xarray/tests/test_dataset.py
- xarray/tests/test_variable.py
Avoid automatic creating of Index variable when nD variable shares name with one of its dimensions.
Closes #2233
```python
url = "http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_GOM3_FORECAST.nc"
ds = xr.open_dataset(url, engine="netcdf4")
display(ds)
xr.testing._assert_internal_invariants(ds, check_default_indexes=False)  ! no raise on #7368
```
~The internal invariants assert fails on `main` but succeeds on #7368~. EDIT: now fixed the invariants check.
> Allow opening datasets with nD dimenson coordinate variables.

- xarray/core/dataset.py
> improved docstring of to_netcdf (issue #7127)

- doc/whats-new.rst
- xarray/conventions.py
- xarray/tests/test_conventions.py
- ~~[ ] New functions/methods are listed in `api.rst`~~
The PR changes `conventions._encode_coordinates` to add `sorted` during the creation of "coordinates" strings *de novo*. It does not touch user-specified coordinates attributes or encodings.
The PR adds a test, but also changes two pre-existing tests that allowed for non-deterministic ordering of the coordinates string.
In reviewing the netCDF data model and CF convenstions, I confirmed that there is no requirement on the ordering of names in the coordinates attribute. I also learned that the global coordinates attribute created by XArray for non-dimension coordinates that are not associated with a variable is not compliant with CF conventions, as was [discussed in 2014](https://mailman.cgd.ucar.edu/pipermail/cf-metadata/2014/007571.h …
> sort when encoding coordinates for deterministic outputs

- design_notes/named_array_design_doc.md
- design_notes/xarray_lite_design_doc.md
This PR contains the design document for "named-array" a proposed new package aimed at providing a lightweight, efficient array structure with named dimensions. the main objective of named-array  is to provide a more accessible version of Xarray's Variable class without the heavy dependencies like Pandas.
~~## proposed name~~
~~The "Xarray-lite" name is a placeholder for the time being. we have considered two main candidates for the package's name: "narray" and "yarray." feedback on the proposed names or other suggestions is welcome.~~
Related issues:
- https://github.com/pydata/xarray/issues/5081
- https://github.com/pydata/xarray/issues/3981
> add design document for "named-array"

- doc/whats-new.rst
- xarray/core/coordinates.py
- xarray/core/dataset.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_dataset.py
This refactor should better handle multi-coordinate indexes when updating (or assigning) new coordinates.
It also fixes, better isolates and better warns a bunch of deprecated pandas multi-index special cases (i.e., directly passing `pd.MultiIndex` objects or updating a multi-index dimension coordinate). I very much look forward to seeing support for those cases dropped :).
> Refactor update coordinates to better handle multi-coordinate indexes

- doc/whats-new.rst
- xarray/core/coordinates.py
- xarray/tests/test_coordinates.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_dataset.py
After working more on `Coordinates` I realize that the default behavior of its constructor could be more consistent with other Xarray objects. This PR changes this default behavior such that:
- Pandas indexes are created for dimension coordinates if `indexes=None` (default). To create dimension coordinates with no index, just pass `indexes={}`.
- If another `Coordinates` object is passed as input, its indexes are also added to the new created object. Since we don't support alignment / merge here, the following call raises an error: `xr.Coordinates(coords=xr.Coordinates(...), indexes={...})`.
This PR introduces a breaking change since `Coordinates` are now exposed in v2023.8.0, which has just been released. It is a bit unfortunate but I think it may be OK for a fresh feature, especially if …
> Better default behavior of the Coordinates constructor

- xarray/core/dataarray.py
Changed the docstring of `xarray.DataArray.differentiate`, according to #8006,  to only list available datetime_units(excluded `"Y"` and `"M"`) and additionally noting that `"Y"` and `"M"` can not be used.
> adapted the docstring of xarray.DataArray.differentiate

- doc/api-hidden.rst
- doc/whats-new.rst
- xarray/core/coordinates.py
- xarray/tests/test_coordinates.py
This is consistent with the Dataset and DataArray `assign` methods (now that `Coordinates` is also exposed as public API).
This allows writing:
```python
midx = pd.MultiIndex.from_arrays([["a", "a", "b", "b"], [0, 1, 0, 1]])
midx_coords = xr.Coordinates.from_pandas_multiindex(midx, "x")
ds = xr.Dataset(coords=midx_coords.assign(y=[1, 2]))
```
which is quite common (at least in the tests) and a bit nicer than
```python
ds = xr.Dataset(coords=midx_coords.merge({"y": [1, 2]}).coords)
```
> Add `Coordinates.assign()` method

- xarray/tests/test_missing.py
Pandas no longer has a `fill_value` parameter for `interpolate`.
Weirdly I wasn't getting this locally, on pandas 2.1.0, only in CI on https://github.com/pydata/xarray/actions/runs/6054400455/job/16431747966?pr=8138.
Removing it passes locally, let's see whether this works in CI
Would close #8125
> Fix pandas' `interpolate(fill_value=)` error

- .github/workflows/ci.yaml
Testing for 3.10 seems fairly low value — is there a realistic case where 3.10 would fail but 3.9 & 3.11 would pass?
Merging this would cut the CI queue...
> Cut middle version from CI

- xarray/tests/test_dataset.py
- xarray/tests/test_variable.py
Reason is that US/Eastern symlink moved from tzdata to tzdata-legacy package, causing FTBFS. Since America/New_York is better supported by tzdata, the switch makes the package stronger against future failures
> tests: Update US/Eastern timezone to America/New_York

- xarray/core/dataset.py
- xarray/tests/test_dataset.py
I found the error message in `ds.to_stacked_array` confusing, so I tried to make it clearer. Also renames some if the _internal_ symbols (so should have no user facing change).
> to_stacked_array: better error msg & refactor

- xarray/core/dataset.py
Fixes the mypy error we're seeing in the CI at the moment:
```
xarray/core/dataset.py:5286: error: Value of type variable "SupportsRichComparisonT" of "sorted" cannot be "Hashable"  [type-var]
```
Can't sort Hashables apparently.
> Don't try to sort hashable, map to string

- asv_bench/benchmarks/pandas.py
- xarray/tests/test_dataset.py
- xarray/tests/test_variable.py
> Fix `PeriodIndex` deprecation in xarray tests

- xarray/core/computation.py
- xarray/core/formatting.py
- xarray/tests/test_computation.py
This makes debugging much easier!
> Display data returned in `apply_ufunc` error message

- pyproject.toml
- setup.py
Pandas asserts that the xarray version that's running is above `2022.`; locally it was set to `999` which failed this. It only applies when developing locally.
> Set dev version above released version

- pyproject.toml
I wasn't sufficiently careful in #8181...
> Fix comment alignment in `pyproject.toml`

- ci/requirements/doc.yml
- doc/getting-started-guide/installing.rst
- pyproject.toml
- xarray/plot/dataarray_plot.py
- xarray/plot/dataset_plot.py
The docs have been failing because of a malformatted docstring we inherit from `pandas`, and this caused us to miss another error in #8183. The fix is to avoid installing `pandas=2.1.0`, which should be the only version with the malformatted docstring, and to apply the missing changes from #8183 here.
> fix the failing docs

- pyproject.toml
My mistake from #8183. I added `--strict-markers` so we can't make this sort of mistake again.
> Fix pytest markers

- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/missing.py
- xarray/core/types.py
- xarray/tests/test_missing.py
While working on #8146 this came up. Aligning with upstream naming convention.
> FIX: use "krogh" as interpolator method-string instead of "krog"

- xarray/tests/test_plot.py
In doing the final checks prior to release of Matplotlib 3.8.0, we noticed that there were two test failures here
due to the return type/artist tree changing for contourf calls (while the type is reasonably back-compatible itself,
we have moved from a "QuadContourSet makes a PathCollection" to "QuadContourSet is a full artist/collection"
xref matplotlib/matplotlib#25247
Unfortunately this change is not really possible to make with deprecations/etc, so we are kind of stuck just making it.
However, in practice, it has only ever seemed to matter for test code which is pretty easy to make work (like here),r
so we have decided to go forward with the change.
> Update contourf call check for mpl 3.8

- xarray/core/computation.py
- xarray/tests/test_computation.py
Based on the correct observation in https://github.com/pydata/xarray/pull/8179#discussion_r1327429229 (slightly adjusted message)
> Adjust ufunc error message

- pyproject.toml
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/nputils.py
- xarray/plot/dataarray_plot.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_dataset.py
This disallows redundant casts
FWIW I thought we had gone through many of the tests and forced them to have typed defs, maybe with the intention of turning on some elements of strict mode. But then I don't think we have any strictness checks at the moment, and I see many functions in the tests which don't have typing. Am I mis-rembering?? Or maybe we started but didn't get far enough (it is a big project...)
> Add some more mypy checks

- doc/user-guide/reshaping.rst
The "Reshaping" document has two identical links to the `sortby()` method for DataArrays.
The proposed fix replaces one and links to the appropriate Dataset method for ease of use.
> Fix sortby link in reshaping.rst

- doc/user-guide/io.rst
> remove invalid statement from doc/user-guide/io.rst

- doc/whats-new.rst
- xarray/core/computation.py
- xarray/core/rolling_exp.py
- xarray/tests/test_rolling.py
A similar change should solve #6528, but let's get one finished first...
~Posting for discussion, will comment inline~ Ready for merge
> Move `.rolling_exp` functions from `reduce` to `apply_ufunc`

- xarray/core/types.py
> Add comments on when to use which `TypeVar`

- pyproject.toml
- xarray/core/rolling_exp.py
Notes inline. Just one module so far!
> Start a list of modules which require typing

- xarray/core/indexes.py
I wanted to do this separately from #8216 , as it's the only one that adds a couple `ignore`s. And given the ratio of impact-to-potential-merge-conflicts, I didn't want to slow the other PR down.
> Convert `indexes.py` to use `Self` for typing

- pyproject.toml
- xarray/core/accessor_str.py
- xarray/core/common.py
- xarray/core/concat.py
- xarray/core/coordinates.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/variable.py
- xarray/tests/test_dataarray.py
This should also allow for subtyping
> Use `Self` rather than concrete types, remove `cast`s

- pyproject.toml
- xarray/__init__.py
This is stable in 3.8, so we can remove the fallback now
> Remove an import fallback

- doc/whats-new.rst
- xarray/coding/times.py
- xarray/tests/test_coding_times.py
> override `units` for datetime64/timedelta64 variables to preserve integer dtype

- doc/whats-new.rst
- xarray/tests/test_missing.py
Update: The enhanced test works well in Upstream-dev tests, Pandas 2.1.1 is available for safe merge.
> test_interpolate_pd_compat with range of fill_value's

- doc/whats-new.rst
- xarray/backends/api.py
- xarray/conventions.py
- xarray/tests/test_conventions.py
- decode variable with mismatched coordinate attribute
- propagate `coordinates` to encoding in any case
> decode variable with mismatched coordinate attribute

- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/types.py
- xarray/core/variable.py
I noticed that `"auto"` wasn't allowed as a value in a dict. So this normalizes all chunk types, and defines the mapping as containing the inner type.
Allows removing some ignores (though also adds one).
One question — not necessary to answer now — is whether we should allow a tuple of definitions, for each dimension. Generally we use names, which helps prevent mistakes, and allows us to be less concerned about dimension ordering.
> Fix & normalize typing for chunks

- xarray/coding/variables.py
- xarray/core/dtypes.py
- xarray/core/types.py
> Add type hints to maybe_promote in dtypes.py

- xarray/core/dataset.py
Based on comment in https://github.com/pydata/xarray/pull/8247. This doesn't make it perfect, but allows the warning to get hit and clarifies the type comment, as a stop-gap
> Refine `chunks=None` handling

- doc/whats-new.rst
- xarray/core/accessor_dt.py
- xarray/core/computation.py
- xarray/core/duck_array_ops.py
- xarray/core/nanops.py
- xarray/core/variable.py
- xarray/tests/test_coarsen.py
- xarray/tests/test_variable.py
This uses `duck_array_ops` in some more places that were found to cause failures in https://github.com/xarray-contrib/cubed-xarray/issues/8
> Use duck array ops in more places

- doc/whats-new.rst
- xarray/coding/times.py
- xarray/tests/test_coding_times.py
This PR proposes a fix to #8271.  I think the basic issue is that the only time we need to update the `needed_units` is if the `data_delta` does not evenly divide the `ref_delta`.  If it does evenly divide it--as it does in the example in #8271--and we try to update the `needed_units` solely according to the value of the `ref_delta`, we run the risk of resetting them to something that would be coarser than the data requires.  If it does not evenly divide it, we are safe to reset the `needed_units` because they will be guaranteed to be finer-grained than the data requires.
I modified `test_roundtrip_float_times` to reflect the example given by @larsbuntemeyer in #8271.  @kmuehlbauer let me know if this fix makes sense to you.
> Fix datetime encoding precision loss regression for units requiring floating point values

- .github/workflows/ci-additional.yaml
- pyproject.toml
It can be helpful to get a second opinion from another typer checker than mypy. 
The CI activates when the `run-pyright` label is added.
> Add pyright type checker

- xarray/tests/test_units.py
Not sure why this only breaks tests for me, vs. in CI, but hopefully no downside to this change...
> Fix `GroupBy` import

- doc/whats-new.rst
- xarray/core/rolling_exp.py
- xarray/tests/test_rolling.py
Another benefit of the move to `.apply_ufunc`...
> Enable `.rolling_exp` to work on dask arrays

- doc/api-hidden.rst
- doc/api.rst
- doc/user-guide/io.rst
- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/variable.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_dataset.py
- xarray/tests/test_variable.py
> Rename `reset_encoding` to `drop_encoding`

- pyproject.toml
- xarray/core/_typed_ops.py
- xarray/core/alignment.py
- xarray/util/generate_ops.py
I did the easy things, but will need help for the final couple on `_typed_ops.py`
Because we don't pin mypy (should we?), this blocks other PRs if we gate them on mypy passing
> mypy 1.6.0 passing

- doc/whats-new.rst
- xarray/backends/zarr.py
- xarray/tests/test_backends.py
Modify ZarrArrayWrapper to avoid re-reading metadata each time data is read from the array.
> Avoid redundant metadata reads in `ZarrArrayWrapper`

- xarray/core/duck_array_ops.py
This is how our get_array_namespace works:
https://github.com/pydata/xarray/blob/dafd726c36e24ac77427513a4a149a6933353b66/xarray/core/duck_array_ops.py#L44-L48
Which usually works. But not for astype.
Using np.array_api doesn't work because you have to use np.array_api.Array instead of np.ndarray:
```python
import numpy.array_api as nxp
nxp.astype(np.array([1, 2,]), np.dtype(float))
File "C:\Users\J.W\AppData\Local\Temp\ipykernel_8616\23329947.py", line 1, in <cell line: 1>
nxp.astype(np.array([1, 2,]), np.dtype(float))
File "C:\Users\J.W\anaconda3\envs\xarray-tests\lib\site-packages\numpy\array_api\_data_type_functions.py", line 20, in astype
return Array._new(x._array.astype(dtype=dtype, copy=copy))
AttributeError: 'numpy.ndarray' object has no …
```
> Handle numpy missing the array api function astype

- xarray/core/variable.py
Seen in #8294.
It's usually better to switch if-checks so that the wider type is defined first. Especially when relying on the implicit type casting like we do here.
> Reverse type checks for better type inheritance

- xarray/core/variable.py
Reverts a few things from #8313. An IndexVariable can only have PandasIndexAdapter as self._data, which makes the for MemoryCachedArray unnecessary. 
Seen in #8294.
> Remove redundant check in IndexVariable

- xarray/core/nputils.py
- xarray/core/options.py
> Enable numbagg for reductions

- doc/whats-new.rst
- xarray/coding/variables.py
- xarray/tests/test_conventions.py
> fix regression in time-like check when decoding masked data

- pyproject.toml
Would it be possible to not have this config? It overrides the local VS Code config, and means VS Code constantly is reporting errors for me.
Totally open to other approaches ofc. Or that we decide that the tradeoff is worthwhile
> Request to adjust pyright config

- ci/requirements/doc.yml
- doc/conf.py
- doc/internals/how-to-add-new-backend.rst
Uses `sphinx-inline-tabs` for pretty and compact options.
Also reword surrounding text a little for clarity.
> Docs: Add syntax for registering backends in `pyproject.toml`

- pyproject.toml
I believe this was missed in v2023.08.0 (Aug 18, 2023).
xref: https://github.com/conda-forge/xarray-feedstock/pull/97
> Bump minimum numpy version

- asv_bench/benchmarks/dataset.py
> [skip-ci] Add benchmarks for Dataset binary ops, chunk

- xarray/core/dataset.py
When using dask (e.g., `chunks={}` with a zarr dataset), each dask.array gets a token. Calculating this token currently hits a recursive path within dask and is relatively slow (~10ms), which adds up for many variables. This PR makes a simpler but still unique token.
An example profile of open_dataset before: 
and after
> Reduce dask tokenization time

- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/types.py
- xarray/core/variable.py
- xarray/tests/test_backends.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_variable.py
(I was planning on putting an issue in, but then thought it wasn't much more difficult to make the PR. But it's totally fine if we don't think this is a good idea...)
Allowing a tuple of dims means we're reliant on dimension order, which we really try and not be reliant on. It also makes the type signature even more complicated.
So are we OK to encourage a dict of `dim: chunksize`, rather than a tuple of chunksizes?
> Deprecate tuples of chunks?

- xarray/core/variable.py
Noticed an unnecessary for loop when playing around with `self.get_axis_num` in #8344.
> Remove unnecessary for loop when using get_axis_num

- doc/whats-new.rst
- xarray/core/formatting.py
- xarray/namedarray/_array_api.py
Use the normal repr now that NamedArray has one.  
Noticed a bug as well, that sometimes the repr attempts to call `NamedArray._in_memory` which doesn't exist.
Seen in #8344.
> Use namedarray repr in _array_api docstrings

- xarray/core/variable.py
- xarray/namedarray/core.py
- xarray/tests/test_namedarray.py
> add `.imag` and `.real` properties  to `NamedArray`

- xarray/core/variable.py
- xarray/namedarray/_typing.py
- xarray/namedarray/core.py
- xarray/tests/test_namedarray.py
> fix `NamedArray.imag` and `NamedArray.real` typing info

- xarray/namedarray/_typing.py
Add more chunkedarray typing options.
Also clean up some ideas that didn't work out. Using TypeVar for arrays for example has turned out to not work that great because of the very common dtype changes.
If you want to check if an ArrayLike is a chunked array:
```python
if isinstance(data, _chunkedarrayfunction_or_api):
data.chunk()
```
However try to rely on mypy in private functions over isinstance checks for better performance:
```python
def _do_compute(data: chunkedduckarray[Any, _DType]) -> duckarray[Any, _DType]:
return data.compute()
```
> Add chunkedduckarray to _typing 

- ci/install-upstream-wheels.sh
- ci/requirements/environment.yml
- doc/conf.py
- doc/whats-new.rst
- pyproject.toml
- xarray/core/computation.py
- xarray/core/duck_array_ops.py
- xarray/core/options.py
- xarray/tests/test_units.py
> Use `opt_einsum` by default if installed.

- xarray/core/concat.py
Given the following excerpt from the `xr.concat()` source code
https://github.com/pydata/xarray/blob/bb489fa7fbdf5017c1c31a7a8344477c9991c6eb/xarray/core/concat.py#L475-L480
it seems like it's explicitly intended that the `dim=` argument can be of type `xr.Variable`. However, it's not indicated as such in the type hints or the documentation. This leads to a type error in pyright when a `Variable` type is used for `dim`.
I'm submitting this PR to fix this apparent shortcoming. Or have I overlooked some reason why this should not be the case? Thanks for your consideration!
> Allow Variable type as dim argument to concat

- doc/conf.py
Fixes:
```
Running Sphinx v6.2.1
File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/8387/lib/python3.10/site-packages/sphinx/config.py", line 353, in eval_config_file
code = compile(f.read(), filename.encode(fs_encoding), 'exec')
File "/home/docs/checkouts/readthedocs.org/user_builds/xray/checkouts/8387/doc/conf.py", line 240
navigation_with_keys=False,
^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: keyword argument repeated: navigation_with_keys
The above exception was the direct cause of the following exception:
File "/home/docs/checkouts/readthedocs.org/user_builds/xray/conda/8387/lib/python3.10/site-packages/sphinx/cmd/build.py", line 280, in build_main
app = Sphinx(args.sourcedir, args.confdir, …
```
> Remove duplicated navigation_with_keys in docs config

- xarray/namedarray/_typing.py
- xarray/tests/test_namedarray.py
Check if the Array object from numpy.array_api is a valid duckarray. 
If it isn't we're likely doing something wrong.
Comments:
* array_api standard does not specify a `__array__`-method. 
* Move `__array__` to _arrayfunction only
* We therefore have to use `np.asarray(namedarray.data)` when comparing ndarrays in the tests
Seen in #8344
> Add duckarray test for np.array_api

- xarray/namedarray/_typing.py
Use _DType_co instead, otherwise the dtype wont be correctly passed along.
Quick follow up to #8387.
> Correct typing for _sparsearray

- doc/whats-new.rst
- xarray/core/resample_cftime.py
- xarray/tests/test_cftimeindex_resample.py
The remaining failing cftime resample tests in https://github.com/pydata/xarray/issues/8091 happen to be related to a bug that was fixed in the pandas implementation, https://github.com/pandas-dev/pandas/pull/55283, leading answers to change in some circumstances.  This PR ports that bug fix to xarray's implementation of resample for data indexed by a `CFTimeIndex`.  
A simple example where answers change in pandas is the following:
```
>>> import numpy as np; import pandas as pd
>>> index = pd.date_range("2000", periods=5, freq="5D")
>>> series = pd.Series(np.arange(index.size), index=index)
>>> series.resample("2D", closed="right", label="right", offset="1s").mean()
2000-01-01 00:00:01    0.0
2000-01-03 00:00:01    NaN
2000-01-05 00:00:01    1.0
2000-01-07 00:00:01    NaN
2000-01-09 …
```
> Port fix from pandas-dev/pandas#55283 to cftime resample

- xarray/namedarray/core.py
- xarray/tests/test_namedarray.py
Add a test for masked array in order to make sure it works.
Be consistent and use the shapetype dtype generics style instead. 
Starting to think it's easier to just stick to one style of typing, even though the other option might be a little shorter.
> Test masked array

- xarray/core/formatting.py
- xarray/tests/test_formatting.py
This gives us better reprs where only differing attributes are shown in the diff.
On main:
```
...
Differing coordinates:
L * x        (x) <U1 'a' 'b'
foo: bar
same: same
R * x        (x) <U1 'a' 'c'
source: 0
foo: baz
same: same
...
```
With this PR:
```
Differing coordinates:
L * x        (x) %cU1 'a' 'b'
Differing variable attributes:
foo: bar
R * x        (x) %cU1 'a' 'c'
Differing variable attributes:
source: 0
foo: baz
```
> Better attr diff for `testing.assert_identical`

- doc/whats-new.rst
- xarray/core/resample_cftime.py
- xarray/tests/test_cftimeindex_resample.py
Closes #8399.
Reverting this minor change from #7206 allows for [offset aliases](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#dateoffset-objects) to again be used with the `loffset` argument to `resample`.
Hopefully this doesn't break anything from that older PR (all tests pass).  It wasn't entirely clear to me why the change was made initially.  Perhaps just to simplify and this was an oversight?
> Fix for date offset strings with resample loffset 

- xarray/core/_typed_ops.py
- xarray/core/dataset.py
- xarray/util/generate_ops.py
Declare `Dataset`, `DataArray`, `Variable`, `DatasetGroupBy`, and `DataArrayGroupBy` unhashable by adding the following type declaration to each class's OpsMixin class:
```python
__hash__: None  # type:ignore[assignment]
```
This is a follow-up to #8384 (attn: @max-sixty). There I observed that pyright was objecting that `Variable` is not a valid type to the `dim` argument of `concat`. On the other hand mypy accepted this because mypy recognizes `Variable` as `Hashable` even though it is not.
The appropriate place to do declare `Variable` unhashable seems to be beside the definition of `__eq__` in `VariableOpsMixin` since defining `__eq__` without `__hash__` is what renders an object unhashable.
For a reference to how types are marked as non-hashable, see …
> Declare Dataset, DataArray, Variable, GroupBy unhashable

- doc/api.rst
- doc/whats-new.rst
- xarray/core/accessor_dt.py
- xarray/tests/test_accessor_dt.py
Add `.total_seconds()` to match the Pandas API.
> Add missing DataArray.dt.total_seconds() method

- doc/api.rst
- doc/howdoi.rst
- doc/user-guide/reshaping.rst
- doc/whats-new.rst
- xarray/core/common.py
- xarray/core/computation.py
- xarray/core/dataset.py
- xarray/core/groupby.py
- xarray/tests/test_concat.py
- xarray/tests/test_dask.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_dataset.py
- xarray/tests/test_groupby.py
- xarray/tests/test_rolling.py
- xarray/tests/test_sparse.py
This is a _very_ minor nit, so I'm not sure it's worth changing.
What do others think?
(I would have opened an issue but it's just as quick to just do the PR)
> Rename `to_array` to `to_dataarray`

- .binder/environment.yml
- ci/requirements/all-but-dask.yml
- ci/requirements/environment-py311.yml
- ci/requirements/environment-windows-py311.yml
- ci/requirements/environment-windows.yml
- ci/requirements/environment.yml
- ci/requirements/min-all-deps.yml
- doc/whats-new.rst
- xarray/tests/test_units.py
We were previously pinned to `<0.21`
Removing the pin didn't change the env but with `>=0.21` we get `0.22` which works.
> Pin pint to >=0.22

- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/tests/test_dataarray.py
Let me know if you think the error message is unclear or too verbose or too fancy or something.
> Raise exception in to_dataset if resulting variable is also the name of a coordinate

- doc/user-guide/io.rst
- doc/whats-new.rst
Also fixes the RTD failure on main
> [skip-ci] Small updates to IO docs.

- ci/requirements/min-all-deps.yml
- doc/whats-new.rst
- xarray/backends/h5netcdf_.py
- xarray/backends/netCDF4_.py
- xarray/coding/variables.py
- xarray/conventions.py
- xarray/tests/test_backends.py
> preserve vlen string dtypes, allow vlen string fill_values

- xarray/core/rolling_exp.py
Am changing this a bit so starting with consolidating it rather than converting twice
> Consolidate `_get_alpha` func

- xarray/core/parallel.py
Was looking funky. Not 100% sure this is correct but seems consistent with the others
> Fix `map_blocks` docs' formatting

- xarray/core/variable.py
- xarray/tests/test_variable.py
> Allow `rank` to run on dask arrays

- doc/whats-new.rst
- xarray/core/dataset.py
- xarray/core/formatting.py
- xarray/tests/test_error_messages.py
One very small step as part of https://github.com/pydata/xarray/issues/8264.
The existing error is just `KeyError: 'foo`, which is annoyingly terse. Future improvements include searching for similar variable names, or even rewriting the user's calling code if there's a close variable name.
This PR creates a new test file. I don't love the format here — it's difficult to snapshot an error message, so it requires copying & pasting things, which doesn't scale well, and the traceback contains environment-specific lines such that it wouldn't be feasible to paste tracebacks.
([here's](https://github.com/PRQL/prql/blob/7ef5ba9a074772fc26e8fcdf12a2a05768071948/prqlc/prql-compiler/tests/sql/error_messages.rs) what we do in PRQL, which is (immodestly) great)
An alternative is just to put these in …
> Improve "variable not found" error message

- doc/whats-new.rst
- xarray/core/utils.py
- xarray/tests/test_dataset.py
This will become a lot more common when we start inferring strings as arrow backed strings in pandas
> Fix bug for categorical pandas index with categories with EA dtype

- doc/whats-new.rst
- xarray/backends/zarr.py
- xarray/core/dask_array_ops.py
- xarray/core/duck_array_ops.py
- xarray/core/missing.py
- xarray/core/nputils.py
- xarray/core/pycompat.py
- xarray/core/rolling_exp.py
- xarray/tests/__init__.py
- xarray/tests/test_missing.py
- xarray/tests/test_plugins.py
The main perf advantage here is the array doesn't need to be unstacked & stacked, which is a huge win for large multi-dimensional arrays... (I actually was hitting a memory issue running an `ffill` on my own, and so thought I'd get this done!)
We could move these methods to `DataWithCoords`, since they're almost the same implementation between a `DataArray` & `Dataset`, and exactly the same for numbagg's implementation
---
For transparency — the logic of "check for numbagg, check for bottleneck" I wouldn't rate at my most confident. But I'm more confident that just installing numbagg will work. And if that works well enough, we could consider only supporting numbagg for some of these in the future.
I also haven't done the benchmarks here — though the functions are relatively well …
> Use numbagg for `ffill` by default

- xarray/core/rolling_exp.py
(Sorry, copy & pasted too liberally!)
> Refine rolling_exp error messages

- doc/whats-new.rst
- xarray/backends/zarr.py
- xarray/tests/test_backends.py
This wasn't working on an unregion-ed write; I think because `new_var` was being lost.
> Fix Zarr region transpose

- doc/whats-new.rst
- xarray/core/alignment.py
- xarray/core/computation.py
- xarray/core/dataarray.py
- xarray/core/variable.py
- xarray/core/weighted.py
- xarray/tests/test_computation.py
- xarray/tests/test_dataarray.py
- xarray/util/deprecation_helpers.py
Begins the process of #6646. I don't think it's feasible / enjoyable to do this for everything at once, so I would suggest we do it gradually, while keeping the warnings quite quiet, so by the time we convert to louder warnings, users can do a find/replace easily.
> Start renaming `dims` to `dim`

- doc/user-guide/time-series.rst
- doc/whats-new.rst
- xarray/core/common.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
Improve the text of the `FutureWarning` re: deprecation of the `loffset` parameter in the `DataWithCoords._resample()`.
Add deprecation notices about `loffset` to the `Dataset.resample()` and DataArray.resample()` docstrings.
Add illustration of updating the time coordinate values of a resampled dataset using  time offset arithmetic to the Time series data - Resampling and grouped operations section of the user guide.
> Update resample time offset FutureWarning and docs

- xarray/backends/zarr.py
- xarray/tests/test_backends.py
We already get the underlying Zarr array in 
https://github.com/pydata/xarray/blob/bb8511e0894020e180d95d2edb29ed4036ac6447/xarray/backends/zarr.py#L529-L531
and then pass it to `open_store_variable`. Just pass that array down to `ZarrArrayWrapper` instead of reading it from the datastore again.
> Avoid duplicate Zarr array read

- .github/workflows/ci-additional.yaml
- doc/whats-new.rst
- xarray/core/alignment.py
- xarray/core/dataset.py
I guess we update manually for now?
> Update to mypy1.7

- doc/whats-new.rst
- xarray/core/dataset.py
- xarray/tests/test_dataset.py
> Fully deprecate `.drop`

- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/resample.py
- xarray/tests/test_dataarray.py
This can be used as a nice more general alternative to `.drop_indexes` or `.reset_coords(drop=True)`
> Allow callables to `.drop_vars`

- xarray/core/common.py
- xarray/core/coordinates.py
> Fix type of `.assign_coords`

- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/rolling.py
- xarray/tests/test_rolling.py
A couple of tests are failing for the multi-dimensional case, which I'll fix before merge.
> Use numbagg for `rolling` methods

- xarray/core/formatting.py
- xarray/tests/test_formatting.py
Uses `max` with a default, which work with empty iterators, in contrast to `if col_items else 0`.
> test and fix empty xindexes repr

- doc/whats-new.rst
> Whats-new for 2023.12.0

- doc/api.rst
- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/rolling.py
- xarray/tests/test_rolling.py
> Add Cumulative aggregation

- xarray/core/utils.py
Its somewhat annoying to get warnings that point to a line within a library where the warning is issued. It really makes it unclear what one needs to change.
This points to the user's access of the `dims` attribute.
> Point users to where in their code they should make mods for Dataset.dims

- .github/workflows/ci-additional.yaml
- pyproject.toml
Trying to fix #8537. Not sure it'll work and can't test locally so seeing if it passes CI
> Filter out doctest warning

- xarray/core/concat.py
Small change to avoid triggering several if-checks unnecessarily.
> Check that compat is equal to identical only once in dataset concat

- doc/whats-new.rst
- xarray/plot/dataarray_plot.py
- xarray/tests/test_plot.py
I noticed that seaborn's plot was responding much faster than xarray's version with the same data. 
Turn's out seaborn drops any nulls: https://github.com/mwaskom/seaborn/blob/056413d7393e3daec597d430c076e45938d53376/seaborn/relational.py#L399
> Filter null values before plotting

- xarray/tests/conftest.py
- xarray/tests/test_rolling.py
Some tests are literally copy & pasted between DataArray & Dataset tests. This change allows them to use a single test. Not everything will be able to use this — sometimes we want to check specifics — but some will — I've change the `.cumulative` tests to use this fixture.
> Offer a fixture for unifying DataArray & Dataset tests

- doc/ecosystem.rst
Suggestion to include [xeofs](https://github.com/nicrie/xeofs) in the xarray ecosystem documentation.
xeofs enables fully multidimensional PCA / EOF analysis and related techniques with large datasets, thanks to the integration of xarray and dask.
References:
- [Github repository](https://github.com/nicrie/xeofs)
- [Documentation](https://xeofs.readthedocs.io/en/latest/)
- [JOSS review](https://github.com/openjournals/joss-reviews/issues/6060)
> Add xeofs to ecosystem.rst

- xarray/core/coordinates.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/parallel.py
- xarray/tests/test_dask.py
Fixes roundtripping of string dtype indexes
> Adapt map_blocks to use new Coordinates API

- doc/whats-new.rst
- xarray/core/rolling.py
- xarray/tests/test_rolling.py
- reverse index output of bottleneck move_argmax/move_argmin functions
- add move_argmax/move_argmin to bottleneck tests
> FIX: reverse index output of bottleneck move_argmax/move_argmin functions

- .github/workflows/ci-additional.yaml
- xarray/tests/__init__.py
Not sure if this is something that we'll only see on `main` after the next release of `pandas` (if ever), though.
I also moved the `hdf5` warning to `xarray/tests/__init__.py`, as that is usually the source of these warnings.
> ignore a `DeprecationWarning` emitted by `seaborn`

- xarray/coding/strings.py
- xarray/conventions.py
- xarray/tests/test_coding_times.py
Spotted when profiling some write workloads.
1. Speeds up the check for multi-index
2. Speeds up one string encoder by not re-creating variables when not necessary.
@benbovy is there a better way?
> Faster encoding functions.

- xarray/tests/test_backends.py
> Remove xfails related to SerializeableLock

- xarray/coding/variables.py
- xarray/tests/test_backends.py
- xarray/tests/test_conventions.py
Using 255 as fillvalue for int8 arrays will not be allowed any more. Previously this overflowed to -1. Now specify that instead.
On numpy 1.24.4
```
>>> np.array([255], dtype="i1")
DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 255 to int8 will fail in the future.
array([-1], dtype=int8)
```
> Silence another warning in test_backends.py

- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/tests/__init__.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_hashable.py
Probably we should add a whole bunch of tests for this. For now only testing the constructor.
> Support non-str Hashables in DataArray

- .github/workflows/ci.yaml
- ci/requirements/environment-3.12.yml
- ci/requirements/environment-windows-3.12.yml
- pyproject.toml
> run CI on `python=3.12`

- xarray/tests/test_utils.py
As per https://github.com/pydata/xarray/pull/8606#discussion_r1452680454
> Re-enable mypy checks for parse_dims unit tests

- doc/whats-new.rst
Fixes
`./doc`
`make html` 
Following Pandas 2.2.0 release, pd.date_range [freq arguments](https://pandas.pydata.org/docs/whatsnew/v2.2.0.html#deprecate-aliases-m-q-y-etc-in-favour-of-me-qe-ye-etc-for-offsets) were depreciated.
Question why old releases in doc/whats-new.rst are compiled and not static to avoid breaking changes for old releases.
Error from building doc:
```
WARNING:
>>>-------------------------------------------------------------------------
Warning in /Users/sam/Documents/GitHub/xarray/doc/whats-new.rst at block ending on line 7231
Specify :okwarning: as an option in the ipython:: block to suppress this message
----------------------------------------------------------------------------
<ipython-input-92-be0529fe0129>:1: FutureWarning: 'M' is deprecated and will be removed …
```
> Fix building doc following depreciation in Pandas 2.2.0

- xarray/tests/test_dask.py
While fixing the previous issue, I introduced another (but didn't see it because of the errors from the test suite, probably should have looked closer...)
This doesn't fix the behavior, but I think it's minor so fine to push off. I do prioritize getting the tests where pass vs failure is meaningful again
> Workaround broken test from pyarrow

- xarray/tests/test_dask.py
Sorry for the repeated PR -- some tests passed but some failed without pyarrow installed. So this xfails the test for the moment
> xfail pyarrow test

- xarray/core/utils.py
Was previously seeing:
```
<frozen _collections_abc>:801: FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
```
Now:
```
/Users/maximilian/workspace/xarray/xarray/tests/test_dataset.py:701: FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
assert ds.dims == ds.sizes
```
It's a heuristic, so not perfect, but I think very likely to be accurate. Any contrary cases very welcome...
> Don't show stdlib paths for `user_level_warnings`

- xarray/core/utils.py
- xarray/tests/test_dask.py
Unsure why this wasn't showing prior -- having tests fail in the good state does make it much more difficult to ensure everything is fixed before merging.
> xfail another dask/pyarrow test

- doc/whats-new.rst
- xarray/coding/cftime_offsets.py
- xarray/tests/test_cftime_offsets.py
This renames the frequency string `"Y"` (formerly `"A"`) to `"YE"` to achieve pandas parity. It could be better to wait for the conclusion of pandas-dev/pandas#56840 before doing this (but fixing the related failure in #8623 seemed a good reason as any to do it know).
Let me know what you think @spencerkclark @aulemahal
> rename "Y" freq string to "YE" (pandas parity)

- xarray/tests/test_backends.py
I see this failing quite a lot of the time...
Ofc open to a proper solution but in the meantime setting this to xfail
> xfail zarr test on Windows

- xarray/core/nputils.py
This is a very small change to silence a `numpy`-related warning. If more information/documentation is needed, I can adjust as needed!
> use first element of residual in _nonpolyfit_1d

- xarray/tests/test_backends.py
As ever, very open to approaches to fix these. But unless we can fix them, xfailing them seems like the most reasonable solution
> xfail another test on windows

- HOW_TO_RELEASE.md
Clarify step 8. by pointing to where the ReadTheDocs build actually is
> Small improvement to HOW_TO_RELEASE.md

- .github/workflows/nightly-wheels.yml
* For security best practices, use the action from known commit shas that correspond to tagged releases. These can be updated via dependabot.
- Amends PR https://github.com/pydata/xarray/pull/7865
c.f. https://github.com/scientific-python/upload-nightly-action/pull/13 for additional context.
I'll suggest @martinfleis and @keewis for reviewers.
- [N/A] Closes #xxxx
- [N/A] Tests added
- [N/A] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [N/A] New functions/methods are listed in `api.rst`
> CI: Pin scientific-python/upload-nightly-action to release sha

- doc/whats-new.rst
- xarray/core/dataset.py
> Fix `variables` arg typo in `Dataset.sortby()` docstring

- doc/whats-new.rst
- xarray/core/missing.py
- xarray/core/variable.py
- xarray/tests/test_array_api.py
> Fix unstack method when wrapping array api class

- doc/whats-new.rst
- xarray/core/variable.py
- xarray/tests/test_array_api.py
> Fix automatic broadcasting when wrapping array api class

- doc/whats-new.rst
- xarray/core/groupby.py
- xarray/tests/test_groupby.py
> groupby: Don't set `method` by default on flox>=0.9

- ci/requirements/all-but-dask.yml
- ci/requirements/bare-minimum.yml
- ci/requirements/environment-3.12.yml
- ci/requirements/environment-windows-3.12.yml
- ci/requirements/environment-windows.yml
- ci/requirements/environment.yml
- ci/requirements/min-all-deps.yml
> Fix CI: temporary pin pytest version to 7.4.*

- xarray/core/common.py
- xarray/namedarray/core.py
Add overloads to `.get_axis_num` because you will get the same type out as you put in.
Seen in #8344.
> Add overloads to get_axis_num

- .pre-commit-config.yaml
- pyproject.toml
use ruff.flake8-tidy-imports to enforce absolute imports
- https://github.com/MarcoGorelli/absolufy-imports has been archived (no reason given)
- removes a pre-commit hook which should make it faster locally
> use ruff.flake8-tidy-imports to enforce absolute imports

- doc/contributing.rst
The URL in the section about [creating a local development environment](https://docs.xarray.dev/en/stable/contributing.html#creating-a-development-environment) was pointing to itself. The new URL is pointing to the (I assume) correct section further down in the same guide.
> Docs: Fix url in "Contribute to xarray" guide

- doc/whats-new.rst
- xarray/conventions.py
- xarray/tests/test_backends.py
> Fix multiindex level serialization after reset_index

- xarray/core/utils.py
- xarray/namedarray/utils.py
Our application creates many small netcdf3 files: https://github.com/equinor/ert/blob/9c2b60099a54eeb5bb40013acef721e30558a86c/src/ert/storage/local_ensemble.py#L593 .
A significant time in xarray.backends.common.py:AbstractWriteableDataStore.set_variables is spent on common.py:is_dask_collection as it checks for the presence of the module dask which takes about 0.3 ms.
This time becomes significant in the case of many small files. This PR uses lru_cache to avoid rechecking for the presence of dask as it should not change for the lifetime of the application.
In one stress test we called dataset.py:2201(to_netcdf) 13634 times which took 82.27 seconds, of which 46.8 seconds  was spent on utils.py:1162(module_available). With the change in this PR, the same test spends only 50s on to_netcdf …
> Add lru_cache to named_array.utils.module_available and core.utils.module_available

- xarray/tests/test_dataarray.py
- xarray/tests/test_formatting.py
- xarray/tests/test_variable.py
Follow up #8702 / https://github.com/pydata/xarray/pull/8702#issuecomment-1932851112
The goal is to remove the not elegant OS-dependant checks introduced during the testing of #8702 
A simple way to do so is to use unsigned integer as dtypes for tests involving data array representations on multiple OSes. Indeed, this solves the issue of the default dtypes being not printed in the repr, with  default dtyps varying according to the OS. The tests show that the concerned dtypes are `int32` (for the Windows CI) and `int64` (for Ubuntu and macOS CIs). Using `uint64` should fix both the varying size and the varying numpy array repr.
~~- [ ] Closes #xxxx~~
~~- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`~~
~~- [ ] New functions/methods are listed in …
> Test formatting platform

- pyproject.toml
Fix a warning from ruff concerning the config:
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section.
Please update the following options in `pyproject.toml`:
- `'extend-safe-fixes'` -> `'lint.extend-safe-fixes'`
- `'per-file-ignores'` -> `'lint.per-file-ignores'`
> ruff: move some config to lint section

- doc/internals/extending-xarray.rst
In the recent version of the pydata-sphinx-theme (that you use through the sphinx-book-theme) we implemented a link shortener that would (I think) be a good replacement for the custom `:issue:` role. I was passing by, I made a small adjustment so you can see the diff and if you don't like it, simply close my PR.
https://xray--8700.org.readthedocs.build/en/8700/internals/extending-xarray.html
> docs: use the link shortener

- doc/whats-new.rst
- xarray/core/indexes.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_dataset.py
- xarray/tests/test_indexes.py
Unstacking non-unique MultiIndex can lead to silent data loss, so we raise an error.
> unstack: require unique MultiIndex

- doc/ecosystem.rst
Related issue #8741 
Hi, thanks for taking time to review this PR!
We propose to add [`sarxarray`](https://tudelftgeodesy.github.io/sarxarray/) to the ecosystem list. This is an Xarray extension for handling [Synthetic Aperture Radar (SAR)](https://en.wikipedia.org/wiki/Synthetic-aperture_radar) data. We implemented read/write and basic implementation functions as Xarray extension, and integrated Dask to allow chunk-wise operations.
> add sarxarray into ecosystem list

- xarray/tests/test_cftimeindex_resample.py
Supress some more internal warnings in the test suite.
> suppress base & loffset deprecation warnings

- doc/whats-new.rst
- xarray/core/indexing.py
- xarray/tests/test_dask.py
this pull request removes the ["unnecessary optimization"](https://github.com/pydata/xarray/issues/8377#issuecomment-1781406355) introduced in https://github.com/pydata/xarray/pull/3588 that attempts to rewrite the indexer key for `BasicIndexer` and `OuterIndexer`
> refactor DaskIndexingAdapter `__getitem__` method

- design_notes/named_array_design_doc.md
This adds a proposal for decoupling the lazy indexing array machinery, indexing adapter machinery, and Variable's setitem and getitem methods, so that the latter can be migrated to NamedArray.
cc @andersy005
> [skip-ci] NamedArray: Add lazy indexing array refactoring plan

- doc/whats-new.rst
- xarray/coding/cftime_offsets.py
- xarray/tests/test_cftime_offsets.py
This Pull Request addresses the issue reported regarding the default setting of the frequency (freq) parameter in Xarray. Currently, the frequency is explicitly set to "D" by default, which may not always be appropriate behavior. The proposed improvement adjusts the logic to set the frequency to "D" only if any of the parameters (periods, start, or end) are None, providing more flexibility and aligning with expected behavior.
Changes:
Updated logic for setting the frequency parameter to consider periods, start, or end values.
Added checks to ensure that the frequency is set to "D" only when necessary.
Please review and provide feedback on the proposed changes. Any suggestions for further improvements are welcome.
> Fixing issue #8770: Improved frequency parameter logic to set it to 'D' only if periods, start, or end are None.

- doc/whats-new.rst
- xarray/core/variable.py
- xarray/tests/test_dataset.py
- xarray/tests/test_variable.py
This PR fixes the issue noted in https://github.com/pydata/xarray/issues/7493#issuecomment-1953091000 that non-nanosecond precision datetime or timedelta values passed to `expand_dims` would not be cast to nanosecond precision.  The underlying issue was that the `_possibly_convert_datetime_or_timedelta_index` function did not appropriately handle being passed `PandasIndexingAdapter` objects.
> Fix non-nanosecond casting behavior for `expand_dims`

- xarray/__init__.py
`Coordinate` is in `__all__` but isn't imported.
Thus a 
```
from xarray import *
``` 
raises an error. 
IMHO, this should have been caught by ruff, but ruff doesn't catch undefined entries in `__all__`, see https://github.com/astral-sh/ruff/issues/10095 
I suggest to watch that issue for resolution to potentially adjust the ruff config of this project such that these things will be caught in the future.
> fix: remove Coordinate from __all__ in xarray/__init__.py

- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/variable.py
- xarray/namedarray/core.py
- xarray/namedarray/utils.py
- xarray/tests/test_dask.py
- xarray/tests/test_sparse.py
> tokenize() should ignore difference between None and {} attrs

- design_notes/grouper_objects.md
xref #8509, #6610
**Rendered version** [here](https://github.com/dcherian/xarray/blob/grouper-proposal/design_notes/grouper_objects.md)
-----
@pydata/xarray I've been poking at this on and off for a year now and finally figured out how to do it cleanly (#8509).
I wrote up a design doc for `Grouper` objects that allow custom conversion of DataArrays to integer group codes, following the NEP template (which is absolutely great!). Such Grouper objects allow us to generalize the GroupBy interface to a much larger class of problems, and eventually provide a nice path to grouping by multiple variables (#6610)
#8509 implements two custom Groupers for you to try out :)
```python
from xarray.core.groupers import SeasonGrouper, SeasonResampler
ds = …
```
> Grouper object design doc

- ci/install-upstream-wheels.sh
- ci/requirements/all-but-dask.yml
- ci/requirements/environment-3.12.yml
- ci/requirements/environment-windows-3.12.yml
- ci/requirements/environment-windows.yml
- ci/requirements/environment.yml
- ci/requirements/min-all-deps.yml
- pyproject.toml
- xarray/tests/test_array_api.py
There's a couple of accumulated failures now, including a crash because `pandas` apparently depends on `pyarrow` now, which on `conda-forge` is not built for `numpy>=2.0`.
> try to get the `upstream-dev` CI to complete again

- xarray/core/groupby.py
> Return a dataclass from Grouper.factorize

- doc/whats-new.rst
- xarray/backends/scipy_.py
- xarray/coding/strings.py
- xarray/coding/variables.py
- xarray/core/indexing.py
- xarray/core/variable.py
- xarray/tests/test_coding_strings.py
- xarray/tests/test_indexing.py
this is a follow-up to previous PRs (#8780 and #8750), continuing the efforts outlined in the [plan for decoupling lazy indexing functionality from NamedArray](https://github.com/pydata/xarray/blob/main/design_notes/named_array_design_doc.md#plan-for-decoupling-lazy-indexing-functionality-from-namedarray). the primary focus of this PR is the removal of vectorized and orthogonal indexing logic from the `__getitem__` method. Now, `__getitem__` exclusively handles basic indexers, aligning with points 3 and 4 of the plan:
- as per point 3, lazy indexing arrays will now implement `__getitem__` solely for basic indexing. For orthogonal indexing, .oindex will be used, and for vectorized indexing, .vindex will be utilized.
- following point 4, IndexingAdapter classes have been updated to …
> Expand use of `.oindex` and `.vindex`

- xarray/core/indexing.py
- xarray/core/variable.py
- xarray/tests/test_indexing.py
this is another follow-up to previous Prs
- #8780
- #8750
- #8790
, continuing the proposal outlined in [plan for decoupling lazy indexing functionality from NamedArray](https://github.com/pydata/xarray/blob/main/design_notes/named_array_design_doc.md#plan-for-decoupling-lazy-indexing-functionality-from-namedarray)
Cc @maxrjones for visibility
> Implement setitem syntax for `.oindex` and `.vindex` properties

- doc/whats-new.rst
- xarray/backends/scipy_.py
> FIX: adapt handling of copy keyword argument in scipy backend for numpy >= 2.0dev

- xarray/core/indexing.py
- xarray/namedarray/core.py
- xarray/tests/test_indexing.py
> increase typing annotations coverage in `xarray/core/indexing.py`

- xarray/tests/test_dataset.py
- xarray/tests/test_interp.py
> upstream-dev CI: Fix interp and cumtrapz

- xarray/core/indexing.py
> Handle .oindex and .vindex for the PandasMultiIndexingAdapter and PandasIndexingAdapter

- doc/whats-new.rst
- xarray/backends/h5netcdf_.py
- xarray/tests/test_backends.py
> warn and return bytes undecoded in case of UnicodeDecodeError in h5netcdf-backend

- doc/whats-new.rst
- xarray/backends/api.py
- xarray/backends/common.py
- xarray/backends/h5netcdf_.py
- xarray/backends/netCDF4_.py
- xarray/backends/zarr.py
- xarray/core/datatree.py
- xarray/core/treenode.py
- xarray/datatree_/datatree/__init__.py
- xarray/datatree_/datatree/extensions.py
- xarray/datatree_/datatree/formatting.py
- xarray/datatree_/datatree/io.py
- xarray/datatree_/datatree/mapping.py
- xarray/datatree_/datatree/render.py
- xarray/datatree_/datatree/testing.py
- xarray/datatree_/datatree/tests/conftest.py
- xarray/datatree_/datatree/tests/test_dataset_api.py
- xarray/datatree_/datatree/tests/test_extensions.py
- xarray/datatree_/datatree/tests/test_formatting.py
- xarray/datatree_/datatree/tests/test_formatting_html.py
- xarray/datatree_/datatree/tests/test_mapping.py
- xarray/tests/conftest.py
- xarray/tests/test_datatree.py
This PR migrates the `datatree.py` module to `xarray/core/datatree.py`, as part of the on-going effort to merge `xarray-datatree` into `xarray` itself.
Most of the changes are import path changes, and type-hints, but there is one minor change to the methods available on the `DataTree` class: `to_array` has been converted to `to_dataarray`, to align with the method on `Dataset`. (See conversation [here](https://github.com/flamingbear/xarray/pull/6#discussion_r1504959971))
This PR was initially published as a draft [here](https://github.com/flamingbear/xarray/pull/6).
> Migrate datatree.py module into xarray.core.

- doc/whats-new.rst
- xarray/backends/api.py
- xarray/tests/test_backends.py
> Don't allow overwriting indexes with region writes

- doc/whats-new.rst
- xarray/core/merge.py
- xarray/tests/test_coordinates.py
- xarray/tests/test_dataset.py
Supercedes #8884 as a way to close #8883, in light of me having learnt that this is now allowed! https://github.com/pydata/xarray/issues/8883#issuecomment-2024645815. So this is really a follow-up to #7989.
> Allow multidimensional variable with same name as dim when constructing dataset via coords

- xarray/plot/dataarray_plot.py
- xarray/tests/test_plot.py
Upstream numpy has become a bit more particular with which types you can use for inplace operations. This PR fixes
```
_______________ TestImshow.test_imshow_rgb_values_in_valid_range _______________
self = <xarray.tests.test_plot.TestImshow object at 0x7f88320c2780>
def test_imshow_rgb_values_in_valid_range(self) -> None:
da = DataArray(np.arange(75, dtype="uint8").reshape((5, 5, 3)))
_, ax = plt.subplots()
>       out = da.plot.imshow(ax=ax).get_array()
/home/runner/work/xarray/xarray/xarray/tests/test_plot.py:2034: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/runner/work/xarray/xarray/xarray/plot/accessor.py:421: in imshow
return dataarray_plot.imshow(self._da, *args, **kwargs)
/home/runner/work/xarray/xarray/xarray/plot/dataarray_plot.py:1601: …
```
> Avoid in-place multiplication of a large value to an array with small integer dtype

- xarray/core/dataarray.py
- xarray/core/dataset.py
* Updates the docstring for persist to mention that it is not altering the original object.
* Adds a return value to the docstring for compute and persist on both Dataset and DataArray
> Update docstring for compute and persist

- xarray/core/variable.py
- xarray/tests/test_dataarray.py
This seems to have been around since 2016-ish, so presumably our backend code path is passing arrays around, not Variables.
cc @ilan-gold
> Don't access data when creating DataArray from Variable.

- pyproject.toml
- xarray/tests/test_plot.py
Enforce typing on all tests in `test_plot.py` and add the remaining type hints.
> Add typing to test_plot.py

- xarray/core/variable.py
This fix enhances the issue [8860](https://github.com/pydata/xarray/issues/8860).
I did not add any test since I believe it is not needed for this case since we did not add any functionality.
> Enhance the ugly error in constructor when no data passed

- xarray/tests/test_missing.py
`pandas` recently removed the deprecated `unit` kwarg to `TimedeltaIndex`.
> use `pd.to_timedelta` instead of `TimedeltaIndex`

- xarray/tests/test_dataarray.py
- xarray/tests/test_missing.py
> adapt more tests to the copy-on-write behavior of pandas

- xarray/backends/api.py
Noticed the `**kwargs` part of the docstring was mangled - [see here](https://docs.xarray.dev/en/latest/generated/xarray.save_mfdataset.html)
> Correct save_mfdataset docstring

- xarray/backends/common.py
- xarray/backends/h5netcdf_.py
- xarray/backends/netCDF4_.py
- xarray/backends/pydap_.py
- xarray/backends/pynio_.py
- xarray/backends/scipy_.py
- xarray/backends/zarr.py
- xarray/core/indexing.py
- xarray/tests/test_backends.py
this PR builds towards 
- https://github.com/pydata/xarray/pull/8870
- https://github.com/pydata/xarray/pull/8856
the primary objective is to partially address 
>  2. Implement fall back `.oindex`, `.vindex` properties on `BackendArray` base class. These will simply rewrap the `key` tuple with the appropriate `*Indexer` object, and pass it on to `__getitem__` or `__setitem__`. These methods will also raise DeprecationWarning so that external backends will know to migrate to `.oindex`, and `.vindex` over the next year.
----
> add `.oindex` and `.vindex` to `BackendArray`

- doc/whats-new.rst
- xarray/core/datatree.py
- xarray/core/datatree_mapping.py
- xarray/core/iterators.py
- xarray/datatree_/datatree/__init__.py
- xarray/datatree_/datatree/formatting.py
- xarray/datatree_/datatree/ops.py
- xarray/tests/test_datatree_mapping.py
This PR continues the overall work of [migrating DataTree into xarray](https://github.com/pydata/xarray/issues/8572).
`datatree_mapping.py` is the renamed version of `mapping.py` from the `datatree` repository.
> Migrate datatree mapping.py

- xarray/tests/test_calendar_ops.py
FYI @aulemahal, `numpy.NaN` will be removed in the upcoming `numpy=2.0` release.
> use `nan` instead of `NaN`

- xarray/tests/test_backends.py
Don't just xfail, and not only on windows, since it can crash the worked
> Skip flaky `test_open_mfdataset_manyfiles` test

- ci/install-upstream-wheels.sh
In trying to install packages that are compatible with `numpy>=2` I added several projects that are built in CI without build isolation (so that they will be built with the nightly version of `numpy`). That was a temporary workaround, so we should start thinking about cleaning this up.
As it seems `numcodecs` is now compatible (or uses less of `numpy` in compiled code, not sure), this is an attempt to see if CI works if we use the version from `conda-forge`.
`bottleneck` and `cftime` now build against `numpy>=2.0.0rc1`, so we can stop building them without build isolation.
> clean up the upstream-dev setup script

- xarray/tests/__init__.py
- xarray/tests/test_backends.py
Per https://github.com/pydata/xarray/issues/8844#issuecomment-2089427222, for the time being this marks `test_use_cftime_false_standard_calendar_in_range` as an expected failure under NumPy 2.  Hopefully we'll be able to fix the upstream issue in pandas eventually.
> Mark `test_use_cftime_false_standard_calendar_in_range` as an expected failure

- xarray/core/variable.py
I noticed that slicing into `datetime64[ns]` arrays was really starting to limit our overall performance.
What is strangest is that it is faster to do it on a lazy array than an in-memory array.
I think it comes down to the code on the main branch triggers:
https://github.com/pydata/xarray/blob/aaa778cffb89baaece31882e03a7f4af0adfe798/xarray/core/variable.py#L220
which does a numpy->pandas -> numpy conversion for safety.
But that seems a little over the top.
My benchmark of interest is:
> Indexing into a 1D array with a scalar to get a single entry from it out.
This often occurs when we slice into our larger datasets.
on main
```
python software_timestamp_benchmark.py
software_timestamp.nc
h5netcdf  lazy      : 100%|███████████| 100000/100000 [00:11<00:00, 8664.24it/s]
h5netcdf  computed …
```
> Faster fastpath

- doc/whats-new.rst
- xarray/coding/cftime_offsets.py
- xarray/tests/__init__.py
- xarray/tests/test_cftime_offsets.py
Like `pandas.date_range`, `cftime_range` would previously return dates outside the range of the specified start and end dates if provided a negative frequency:
```
>>> start = cftime.DatetimeGregorian(2023, 10, 31)
>>> end = cftime.DatetimeGregorian(2021, 11, 1)
>>> xr.cftime_range(start, end, freq="-1YE")
CFTimeIndex([2023-12-31 00:00:00, 2022-12-31 00:00:00, 2021-12-31 00:00:00],
dtype='object', length=3, calendar='standard', freq='-1YE-DEC')
```
This PR ports a bug fix from pandas (https://github.com/pandas-dev/pandas/issues/56147) to prevent this from happening.  The above example now produces:
```
>>> start = cftime.DatetimeGregorian(2023, 10, 31)
>>> end = cftime.DatetimeGregorian(2021, 11, 1)
>>> xr.cftime_range(start, end, freq="-1YE")
CFTimeIndex([2022-12-31 00:00:00, 2021-12-31 …
```
> Port negative frequency fix for `pandas.date_range` to `cftime_range`

- .github/workflows/ci-additional.yaml
- .github/workflows/ci.yaml
> Trigger CI only if code files are modified.

- doc/user-guide/io.rst
- xarray/backends/api.py
- xarray/backends/zarr.py
1. This moves the region detection code into `ZarrStore` so we only open the store once. 
2. Instead of opening the store as a dataset, construct a `pd.Index` directly to "auto"-infer the region.
The diff is large mostly because a bunch of code moved from `backends/api.py` to `backends/zarr.py`
> Zarr: Optimize `region="auto"` detection

- asv_bench/benchmarks/indexing.py
See benchmark results from: https://github.com/pydata/xarray/pull/9003#issuecomment-2097169851
> Add a benchmark to monitor performance for large dataset indexing

- xarray/core/indexes.py
> Avoid extra read from disk when creating Pandas Index.

- .github/workflows/benchmarks.yml
- asv_bench/asv.conf.json
- asv_bench/benchmarks/groupby.py
- asv_bench/benchmarks/indexing.py
> Fix benchmark CI

- .gitignore
- xarray/backends/api.py
- xarray/backends/zarr.py
- xarray/tests/test_backends.py
~Builds on #8997~
Continues moving checks one level down to `ZarrStore.store` where we already have a bunch of checks, and a loop over existing variables in the store.
> Zarr: Optimize appending

- doc/whats-new.rst
Towards #9018
I noticed that we've gotten quite lax at writing `whatsnew` entries for PRs, meaning that when you go to write the release summary it looks like we've added much less since the last release than we actually have! I would say maybe half the PRs merged since the last release don't have whatsnew entries.
> Release summary for v2024.05.0

- ci/min_deps_check.py
I think we want to show the age of the 'user-requested' package (i.e. the one in min-all-deps.yml) and not of the 'policy-required' when running min_deps_check.py.
> [skip-ci] min_deps_check: show age of required pkg on error

- xarray/tests/__init__.py
It only seems to be used in 1 place:
```
$ rg requires_numbagg_or_bottleneck
xarray/tests/test_missing.py
28:    requires_numbagg_or_bottleneck,
416:@requires_numbagg_or_bottleneck
xarray/tests/__init__.py
147:requires_numbagg_or_bottleneck = pytest.mark.skipif(
```
> TEST: Fix numbagg or bottlekneck skip

- xarray/tests/test_plot.py
```
pytest xarray/tests/test_plot.py::TestNcAxisNotInstalled::test_ncaxis_notinstalled_line_plot
```
would return the following error. Is my configuation wrong? I don't think I have a global pytest.ini on my system but maybe....
```
xarray/tests/test_plot.py E                                                    [100%]
======================================= ERRORS =======================================
____ ERROR at setup of TestNcAxisNotInstalled.test_ncaxis_notinstalled_line_plot _____
self = <xarray.tests.test_plot.TestNcAxisNotInstalled object at 0x78ed1992aa10>
@pytest.fixture(autouse=True)
def setUp(self) -> None:
"""
Create a DataArray with a time-axis that contains cftime.datetime
objects.
"""
month = np.arange(1, 13, 1)
data = np.sin(2 * np.pi * month / 12.0)
darray = …
```
> Use ME in test_plot instead of M

- xarray/core/extension_array.py
- xarray/tests/test_duck_array_ops.py
Something I just discovered, this snuck in while making changes elsewhere during the PR :(
> (fix): equality check against singleton `PandasExtensionArray`

- ci/install-upstream-wheels.sh
~Nightly `zarr` appears to have new dependencies we don't get from the version on `conda-forge`.~ Apparently `xarray` is not ready for `zarr` v3, yet, so this pins nightly `zarr` to v2.
Additionally, this allows using `ci/install-upstream-wheels.sh` if `micromamba` is not installed.
cc @jhamman
> pin nightly `zarr` to v2

- doc/whats-new.rst
- xarray/backends/h5netcdf_.py
- xarray/backends/netCDF4_.py
Accessing `.shape` on a netCDF4 variable is ~20-40ms. This can add up for large numbers of variables, e.g.: https://github.com/pydata/xarray/discussions/9058
We already request the shape when creating NetCDF4ArrayWrapper, so we can reuse that.
> Speed up netCDF4, h5netcdf backends

- doc/examples/multidimensional-coords.ipynb
> Remove empty code cell in examples/multidimensional-coords.ipynb

- xarray/coding/cftime_offsets.py
- xarray/tests/test_backends.py
- xarray/tests/test_coding_times.py
- xarray/tests/test_combine.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_groupby.py
- xarray/tests/test_plot.py
- xarray/tests/test_variable.py
This PR addresses the upstream failures described in https://github.com/pydata/xarray/issues/8844#issuecomment-2155521159 with a few minor changes to ensure that, for the time being, nanosecond precision times continue to be used in xarray.  These failures stem from https://github.com/pandas-dev/pandas/pull/55901, which causes `pandas.to_datetime` to infer the precision to use based its input instead of always using nanosecond precision.
See the review comments for an explanation of the changes.
> Address latest pandas-related upstream test failures

- asv_bench/benchmarks/dataarray_missing.py
Fix a small typo, where ffill was tested twice in asv benchmarks instead of bfill
> Fix Typo in Bfill benchmark

- doc/user-guide/io.rst
- doc/whats-new.rst
> add link to CF conventions on packed data in doc/user-guide/io.rst

- properties/test_pandas_roundtrip.py
This does not fix #9098: the issue seems to be wrong expectations, the result looks correct. I briefly tried fixing it but couldn't figure out how to, so in the interest of getting the release out I'm skipping the test for `pandas>=3.0`.
> skip the `pandas` datetime roundtrip test with `pandas=3.0`

- doc/_static/style.css
- doc/conf.py
Updating the doc announcement banner to include a link to the active user survey: https://forms.gle/pDRtaTx6GtNn91959
This is already live on our landing page: https://xarray.dev
See also #9076
> Add user survey announcement to docs

- xarray/core/types.py
- xarray/tests/test_dask.py
xref https://github.com/pydata/xarray/pull/9109#issuecomment-2166056509
> Add test for rechunking to a size string

- xarray/backends/api.py
Per this discussion: https://github.com/pydata/xarray/discussions/9119
> Update docstring in api.py for open_mfdataset(), clarifying "chunks" argument

- xarray/core/common.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/groupby.py
- xarray/core/groupers.py
- xarray/core/resample.py
- xarray/core/types.py
Simply moves a large chunk of code from `groupby.py` to `groupers.py`.
Minimizing the diff in #8840
> Grouper refactor

- xarray/tests/test_dataarray.py
- xarray/tests/test_dataset.py
- xarray/tests/test_formatting.py
Adjust the expectations in repr tests to account for different object sizes and numpy type representations across platforms, particularly fixing the tests on 32-bit platforms.
Firstly, this involves getting the object type size from NumPy and using it to adjust the expectations in DataArray and Dataset tests.  The tests were already using int64 type consistently, so only the sizes used for Python objects needed to be adjusted.
Secondly, this involves fixing `test_array_repr_dtypes_unix`.  The test specifically focuses on testing a 32-bit, 64-bit and "native" data type, which affect both size and actual representation (NumPy skips the dtype attribute for the native data type).  Get the expected size from NumPy for the native int type, and reuse `repr()` from NumPy for all array types.
> adjust repr tests to account for different platforms (#9127)

- doc/user-guide/io.rst
This section was under 'Modifying existing Zarr stores', which I understand from a dev perspective but isn't what folks will be scanning for
Edit: I also reordered the sections, any thoughts?
> Split out distributed writes in zarr docs

- xarray/core/dataset.py
Promoted `region='auto'`, refine the langague slightly
> Improve `to_zarr` docs

- xarray/core/groupby.py
- xarray/core/groupers.py
Builds on #9122 removes internal use of IndexVariable
Toward #8840
> groupby: remove some internal use of IndexVariable

- doc/whats-new.rst
- xarray/backends/api.py
- xarray/backends/zarr.py
Makes them more structure, consistent. I think removes a mistake re the default chunks arg in `open_zarr` (it's not `None`, it's `auto`).
Adds a comment re performance with `chunks=None`, closing https://github.com/pydata/xarray/issues/9111
> Improve zarr chunks docs

- pyproject.toml
- xarray/tests/test_plot.py
I can't get this to fail locally, so adding a test to assess what's going on.
Alos excludes matplotlib from type exclusions
> Add test for #9155

- xarray/tests/test_missing.py
This attempts to fix the failing missing data interpolation tests, which are apparently the result of a `pandas` deprecation.
cc @spencerkclark
> switch to datetime unit `"D"`

- xarray/backends/file_manager.py
While reading through the docs I noticed that the code examples for the CachingFileManager were all one block of text and not respecting the newlines in the source. This PR changes `:` to `::` to tell restruturedtext/sphinx that the code blocks are literal blocks and not new paragraphs. Alternatively I could do `.. code-block:: python`, but I feel like that hurts readability of the source, but it may be needed if sphinx doesn't format the literal block as python code (syntax highlighting).
There may be other parts of the API docs like this, but this was the first one I saw and I didn't look very hard otherwise.
> Fix example code formatting for CachingFileManager

- doc/whats-new.rst
- xarray/testing/assertions.py
- xarray/tests/test_assertions.py
Replace a reference to np.core.defchararray with np.char.chararray in xarray.testing.assertions, since the former no longer works on NumPy 2.0.0 and the latter is the "preferred alias" according to NumPy docs. See Issue #9165.
> Change np.core.defchararray to np.char (#9165)

- ci/requirements/doc.yml
- ci/requirements/environment-windows.yml
- ci/requirements/environment.yml
To give us a bit more time while fixing the various issues related to `numpy>=2` without affecting other PRs, this temporarily pins `numpy` to below version 2 in CI.
We didn't detect these issues before `2024.06.0` because we didn't run the doctests / docs, because some dependencies didn't support it at that point, and because the tests don't cover everything. We will most likely never solve the last point, but we can at least continuously improve.
> temporarily pin `numpy<2`

- ci/requirements/all-but-dask.yml
- ci/requirements/environment-windows.yml
- ci/requirements/environment.yml
The issue is that with `numpy>=2` `import pydap` works, but `import pydap.lib` raises.
Still left to do: open an issue [upstream](https://github.com/pydap/pydap) (and maybe on `conda-forge`, too?).
> temporarily remove `pydap` from CI

- ci/requirements/all-but-dask.yml
Looks like I forgot that environment in #9181.
> also pin `numpy` in the all-but-dask CI

- doc/whats-new.rst
- xarray/coding/times.py
- xarray/tests/test_coding_times.py
It seems that because of the changed dtype casting rules in `numpy>=2`, the numeric timestamps are not automatically promoted to 64-bit floating point values anymore so we have to do this manually.
> promote floating-point numeric datetimes to 64-bit before decoding

- doc/whats-new.rst
- properties/test_properties.py
- xarray/core/formatting.py
- xarray/testing/strategies.py
- xarray/tests/test_formatting.py
> properly diff objects with arrays as attributes on variables

- doc/whats-new.rst
- xarray/static/css/style.css
This is similar to https://github.com/pydata/xarray/issues/6500 and https://github.com/pydata/xarray/pull/6501 : In my docs, the dark-theme is noted in the html-part as 
```
html< ... data-theme=dark ... >
```
and xarray-tables look therefore awful with the dark theme, as they are not rendered properly, as can be seen, e.g., here: https://emsig.xyz/emg3d-gallery/gallery/tutorials/simulation.html#create-survey.
This can be fixed by extending
https://github.com/pydata/xarray/blob/fff82539c7b0f045c35ace332c4f6ecb365a0612/xarray/static/css/style.css#L16-L18
to 
```
html[theme=dark],
html[data-theme=dark],
body[data-theme=dark],
body.vscode-dark {
```
> Fix dark-theme in `html[data-theme=dark]`-tags

- properties/test_pandas_roundtrip.py
This tries to use a composite strategy to generate a dataframe with a single timezone-aware datetime column. This works, but it feels somewhat weird to have to jump through hoops just get a standard timezone-aware datetime column.
@Zac-HD, do you have any advice here (as usual, time permitting)? Am I missing anything, or is this something that currently is not supported by `hypothesis.extra.pandas`? For context, what we have right now on `main` returns object dtypes, not the timezone-aware extension dtypes.
> use a `composite` strategy to generate the dataframe with a tz-aware datetime column

- doc/whats-new.rst
- xarray/core/formatting.py
- xarray/tests/test_formatting.py
This would attempt to convert custom indexes to `pandas` indexes (by calling `.indexes` instead of `.xindexes`), which for some implementations may raise.
(I need this for xarray-contrib/pint-xarray#163)
> avoid converting custom indexes to pandas indexes when formatting coordinate diffs

- xarray/core/datatree.py
- xarray/tests/test_datatree.py
1. Fix handling of coordinates on a Dataset argument (previously these were silently dropped).
2. Do not copy inherited coordinates down to lower level nodes.
> Fix two bugs in DataTree.update()

- doc/whats-new.rst
- xarray/plot/dataset_plot.py
- xarray/tests/test_plot.py
> Only use necessary dims when creating temporary dataarray

- xarray/tests/test_coding_times.py
* Removed `coding.times`-prefix, importing instead.
* `np.around` to `np.round` instead.
A small cleanup to avoid a bunch of pyright errors such as:
```
\GitHub\xarray\xarray\tests\test_coding_times.py:1012:47 - error: "times" is not a known member of module "xarray.coding" (reportAttributeAccessIssue)
```
Split from #8933
> Cleanup test_coding_times.py

- xarray/coding/times.py
The method `.reshape()` and `.ravel()` is not supported by the array api standard, they propose using the function `xp.reshape` instead. Use the functions from duck_array_ops instead.
Split from #8933
> Use reshape and ravel from duck_array_ops in coding/times.py

- xarray/tests/test_coding_times.py
Some more minor tweaks. Split from #8933
> Use duckarray assertions in test_coding_times

- .github/release.yml
As described in the [scientific-python guide on github actions](https://learn.scientific-python.org/development/guides/gha-basic/#changelog-generation), this excludes bots from the release notes. We'll still have to update the code snippet in the release guide, though.
> exclude the bots from the release notes

- pyproject.toml
Seems to require adding an exclude for `build` and an `__init__.py` file in the `properties` directory...
> Allow mypy to run in vscode

- xarray/tests/test_plot.py
Fixes mypy errors related to plotting seen in CI.
xref: #9231
> Fix typing for test_plot.py

- doc/user-guide/terminology.rst
There was a small spelling mistake. Just wanted to quickly fix it, as it low key bothered me. Sorry.
> Added a space to the documentation

- xarray/core/npcompat.py
- Towards #9231
Fixes the npcompat error
> fix typing of fallback isdtype method

- xarray/core/dataset.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_dataset.py
- xarray/tests/test_namedarray.py
- xarray/tests/test_strategies.py
- Solve the numpy issues with appropriate ignores
- Hide the NamedArray issues with blanket ignores
> Fix mypy on main

- doc/whats-new.rst
- xarray/core/common.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/groupers.py
- xarray/core/pdcompat.py
- xarray/core/resample_cftime.py
- xarray/tests/test_cftimeindex_resample.py
- xarray/tests/test_groupby.py
Builds on #8840 
Finishes the deprecations of ``base`` and ``loffset`` parameters in resample.
> Delete ``base`` and ``loffset`` parameters to resample

- asv_bench/benchmarks/coding.py
Per https://github.com/pydata/xarray/pull/8324#issuecomment-2228724126 this adds a benchmark for encoding times via `encoding_cf_datetime`.  I think we'll see a nice speedup for the cftime case from #8324.
cc: @headtr1ck @antscloud
> Add `encode_cf_datetime` benchmark

- xarray/namedarray/_typing.py
- xarray/namedarray/core.py
- xarray/tests/test_namedarray.py
I believe numpy updated the signature of `__array__` in numpy2. 
It currently looks like this now: https://github.com/numpy/numpy/blob/de1ca2676e0f1db5a1b95e1d05e86ca87321cac2/numpy/__init__.pyi#L1471-L1478
xref #9231, #9252
> Update signature for _arrayfunction.__array__

- xarray/coding/variables.py
- xarray/tests/test_backends.py
See #9136 for the longer discussion of this. In #9136 numpy 2 compatibility was fixed by working around integer overflow errors when a `_FillValue` was specified in an unsigned dtype (ex. `np.uint8(255)`) but needed to be cast to the signed dtype to be stored to a NetCDF file. This is all related to the use of the special `_Unsigned` attribute. However, the referenced PR broke the ability to specify `_FillValue` with native python integers (ex. `-1`).
This PR restores this behavior by handling both primary use cases:
1. `_FillValue` corresponds to the unsigned in-memory data
2. `_FillValue` corresponds to the signed on-disk data
I'm sure there are at least 10 ways of interpreting what the best solution should be. This one I think causes the least amount of disruption and restores previous …
> Restore ability to specify _FillValue as Python native integers

- xarray/backends/h5netcdf_.py
- xarray/backends/netCDF4_.py
> Adding `open_datatree` backend-specific keyword arguments

- doc/whats-new.rst
- xarray/core/_aggregations.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/groupby.py
- xarray/core/groupers.py
- xarray/core/resample.py
- xarray/tests/test_computation.py
- xarray/tests/test_groupby.py
- xarray/util/generate_aggregations.py
Closes #9279
Closes #1460
Closes #2157
This was deprecated in January, so perhaps a bit soon.
OTOH this has been the source of some quite confusing behaviour (see linked issues above).
> Fully deprecate squeeze kwarg to groupby

- doc/user-guide/dask.rst
- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/groupers.py
- xarray/core/types.py
- xarray/core/variable.py
- xarray/namedarray/core.py
- xarray/tests/test_dataset.py
Now uses syntax `ds.chunk(time=TimeResampler("YE"))`
> Support rechunking to a frequency.

- HOW_TO_RELEASE.md
- ci/release_contributors.py
Since I've been doing a few releases recently, I noticed that the code snippets in the release guide to produce the list of contributors is inaccurate (we credit bots by default), there's a trailing comma, and, most importantly, we don't include co-authors.
In an attempt to fix this, here's a script that searches the commit messages for any `Co-authored-by:` lines and adds them to the set of contributors. As an example, for #9287 the old snippets would exclude @kmuehlbauer.
> automate extracting the contributors

- doc/whats-new.rst
- xarray/core/datatree.py
- xarray/tests/test_datatree.py
> Fix `DataTree.from_dict` to be insensitive to insertion order

- xarray/backends/plugins.py
I just had an interaction with a researcher over at [LEAP](leap.columbia.edu) and they did not have zarr installed but were confused by the error message they got when trying to access an ARCO zarr dataset in the cloud like this:
```python
store = 'gs://gcp-public-data-arco-era5/ar/model-level-1h-0p25deg.zarr-v1'
ds = xr.open_dataset(store, engine='zarr', chunks={})
```
I reproduced their error by removing zarr from the `pangeo/pangeo-notebook:2024.06.02` docker image manually and got:
<details>
```
--------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 3
1 import xarray as xr
2 store = 'gs://gcp-public-data-arco-era5/ar/model-level-1h-0p25deg.zarr-v1'
----> …
```
> Increased verbosity for Value Error raised if backend not installed

- xarray/core/datatree.py
- xarray/datatree_/docs/source/io.rst
> DOC: Add note to docs on DataTree root-group naming conventions

- doc/ecosystem.rst
> Add grib2io to ecosystem.rst

- doc/user-guide/terminology.rst
Reading through the documentation and noticed some missing spaces.
> Add missing spacing in documentation

- xarray/tests/test_dask.py
- xarray/tests/test_variable.py
> Fix some dask tests

- xarray/tests/test_namedarray.py
It is rather annoying trying to figure out why some arrays aren't valid duckarrays. This PR logs the missing attributes instead of just saying it isn't valid.
Example:
```python
def test_duck_array_class_pd_index(self) -> None:
import pandas as pd
a: duckarray[Any, Any] = pd.Index([])
check_duck_array_typevar(a)
```
```
FAILED xarray/tests/test_namedarray.py::TestNamedArray::test_pd_index_duckarray - TypeError: a (<class 'pandas.core.indexes.base.Index'>) is not a valid _arrayfunction or _arrayapi. Missing following attrs:
_arrayfunction - {'imag', '__array_function__', 'real'}
_arrayapi - {'__array_namespace__'}
```
Further reading: https://github.com/python/cpython/issues/104873
> Verbose error handling for non-valid duckarrays

- xarray/tests/test_backends.py
- xarray/tests/test_coding_times.py
- xarray/tests/test_conventions.py
- xarray/tests/test_formatting.py
https://github.com/pandas-dev/pandas-stubs/issues/956 has been closed so it is time to remove the ignores.
> Remove ignores due to pandas-stubs

- xarray/coding/variables.py
- xarray/core/duck_array_ops.py
Another change to use `duck_array_ops` to fix the case in https://github.com/cubed-dev/cubed/issues/539
> Use duck array ops for `around` and `round`

- .github/workflows/benchmarks.yml
Hi! I'm Diogo from Google's Open Source Security Team([GOSST](https://opensource.googleblog.com/2023/04/googles-open-source-security-upstream-team-one-year-later.html)) and I'm dropping by to suggest this small change that will enhance the security of your repository by preventing script injection attacks through your GitHub workflows.
In the piece of code I changed, you were directly using the value of a variable that comes from a user's input, so a malicious user could exploit that input and use it to run arbitrary code. By using an intermediate environment variable, the value of the expression is stored in memory, used as a variable and doesn't interact with the script generation process. This mitigates the script injection risks and also keeps your workflow running exactly as before. …
> fix: github workflow vulnerable to script injection

- ci/requirements/environment.yml
- xarray/core/computation.py
- xarray/tests/test_computation.py
xref #9327
Can't figure out how to fix it.
Also forces numpy>=2 to make doctests and mypy pass.
> xfail np.cross tests; force numpy>=2 in main CI 

- doc/whats-new.rst
> whats-new entry for dropping python 3.9

- doc/whats-new.rst
- xarray/core/dataset.py
- xarray/tests/test_dataset.py
> Fix rechunking to a frequency with empty bins.

- doc/internals/chunked-arrays.rst
- doc/whats-new.rst
- xarray/core/options.py
- xarray/namedarray/parallelcompat.py
- xarray/tests/test_parallelcompat.py
It would be useful to have a way to choose a chunk manager if more than one is found (see https://docs.xarray.dev/en/latest/internals/chunked-arrays.html#user-interface for how it works). The use case I have is a codebase that uses Xarray and Dask (and has lots of Dask imports), and which I'd like to be able to run on Cubed too (as well as Dask). Rather than converting it all in one go, it would be easier to convert it to use Xarray-only APIs gradually. The changes involve moving `da.map_blocks` to `xr.apply_ufunc`, for example.
Using the the current PR I can have both Dask and Cubed packages installed and switch to use Cubed with `xr.set_option(chunk_manager="cubed")`. This allows me to run a subset of the tests on Cubed while not having to worry about the rest of the Dask imports in the …
> Make chunk manager an option in `set_options`

- xarray/tests/test_backends.py
Hopefully stops the flaky test seen in #9368.
> Add flaky to TestNetCDF4ViaDaskData

- xarray/core/combine.py
- xarray/tests/test_combine.py
This simple PR improves the error message for cases where a coordinate is missing its corresponding index. Previously, a generic ValueError was raised, but now the error message specifically mentions which coordinate is without an index.
> Improve error message for missing coordinate index

- xarray/core/dataset.py
- xarray/tests/test_dataset.py
While trying to help with #9372, I realize the error message for this could be much better, and so putting this PR in as some penance for my tardiness in helping there
> Improve error message on `ds['x', 'y']`

- xarray/core/coordinates.py
- xarray/core/groupby.py
- xarray/groupers.py
- xarray/tests/__init__.py
- xarray/tests/test_groupby.py
1. Simplify ResolvedGrouper by moving logic to EncodedGroups
2. Stack outside ResolvedGrouper in GroupBy.__init__ to prepare for
multi-variable GroupBy
Broken out form #9372
> refactor GroupBy internals

- ci/requirements/doc.yml
> pyarrow dependency added to doc environment

- ci/install-upstream-wheels.sh
- ci/requirements/all-but-dask.yml
- ci/requirements/environment-windows.yml
- ci/requirements/environment.yml
- doc/whats-new.rst
`pydap=3.5` has a been released that is compatible with numpy 2 (among other features).
- This PR largely reverses [pydata/xarray#9183](https://github.com/pydata/xarray/pull/9183).
Don't know if I have the right permissions to push this PR, but at the very least this will bring up the attention that pydap is compatible with numpy>=2.0. Also, this has the potential to bring up additional issues to fix (even though tests on my local computer ran smoothly). Feel free to close/comment/etc etc.
> `numpy 2` compatibility in the `pydap` backend

- doc/whats-new.rst
- xarray/core/common.py
- xarray/tests/test_dataarray.py
xarray has been raising some deprecation warnings whenever `np.array` is called on an `xr.DataArray`. This is the same message as documented in #9312, but the issue is not specifically related to the `interpolate_na` method. Instead, the issue can be produced when using NumPy>=2.0.0 as:
```
>>> import xarray as xr
>>> import numpy as np
>>> da = xr.DataArray([0])
>>> np.array(da)
DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
```
It is caused by the `AbstractArray.__array__` method not containing a `copy` kwarg that NumPy 2.0 now expects.
A fix was proposed in #9312 by @kmuehlbauer, but upon testing it I found that this fix is not backwards compatible when using NumPy …
> Adds copy parameter to __array__ for numpy 2.0

- properties/test_encode_decode.py
> Encode/decode property tests use variables()

- doc/user-guide/groupby.rst
- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/groupby.py
- xarray/tests/test_groupby.py
Builds on #9389 
-----
This PR takes an approach similar to that in #924. 
The GroupBy(multiple array) problem can be reduced to the GroupBy(single nD variable) problem:
1. First convert each `by` array to integer codes ("factorize"). I do this first because factorization is expensive, and so it's cheaper to do it before any possible broadcasting.
2.  Broadcast DataArrays of integer codes against each other.
3. Then `np.ravel_multi_index` them to construct a single nD array of integer codes.
4. At this point, we treat it as a GroupBy(single nD array) problem i.e. reshape down to 1D problem. This isn't great for dask/cubed but it is simple and matches what we do today. That means we can apply all the operations we do with GroupBy today.
- Importantly UDFs receive "stacked arrays" as they …
> GroupBy(multiple groupers)

- .github/workflows/benchmarks.yml
> Use `python-build` instead of `build` in benchmark workflow

- .pre-commit-config.yaml
In the disabled `mypy` hook we explicitly install `types-pkg_resources`. This project has been yanked on PyPI, with the notice that instead we should use `types-setuptools`. This applies that change, but if I remember correctly, we stopped depending on `setuptools` / `pkg_resources` a while ago, so we might also be able to just remove that?
> fix the failing `pre-commit.ci` runs

- xarray/static/css/style.css
The default html view generated via XArray uses hidden checkboxes to achieve collapse expand behaviour. This PR -
Makes the hidden checkboxes visible with 0 opacity , to make them accessible via keyboard Make style changes to associated labels for focus, to highlight where the keyboard focus is Change the grid layout to account for the invisible checkboxes
https://github.com/user-attachments/assets/3f7cb0c9-2b10-4abd-9098-96e653d2392b
issue - https://github.com/pydata/xarray/issues/9397
> Accessibility: Add keyboard handling for XArray HTML view

- .github/workflows/ci-additional.yaml
We should test that a simple `mypy` invocation works, because that's what's expected to run locally, and instead move any arguments to config files
(I hit this because I'm getting type errors locally, though this doesn't fix them, it eliminates a source of difference)
> Don't specify a subdir in mypy CI cli

- .github/workflows/ci-additional.yaml
- xarray/core/accessor_str.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/datatree.py
- xarray/core/weighted.py
- xarray/plot/dataset_plot.py
- xarray/tests/test_backends.py
- xarray/tests/test_backends_api.py
- xarray/tests/test_coding_times.py
- xarray/tests/test_conventions.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_formatting.py
- xarray/tests/test_plot.py
- xarray/tests/test_plugins.py
This does a few things:
- Upgrades mypy
- Adds lots of ignores for mpl & pandas type issues in tests -- not as good as fixing them, but better than staying on mypy 1.8
- Removes some old ignores
- Adds a couple of ignores with notes where it's our issue and I'm not sure what's going on
- Starts using the `EllipsisType` in a couple of places
Note that I used a tool to mass-add ignores, I didn't add them all manually
> Upgrade mypy to 1.11

- xarray/backends/api.py
- xarray/tests/conftest.py
- xarray/tests/test_backends.py
> Byte attr support

- xarray/tests/test_dataset.py
Looks like `pd.DatetimeIndex.to_numpy` will return a immutable view by default, so we have to specify that we want a copy instead.
(Note: this, together with #9403, allows us to close the upstream-dev issue #9277)
> copy the data of the `DatetimeIndex` in the `Dataset.chunk`-by-frequency tests

- xarray/core/accessor_dt.py
- xarray/core/variable.py
- xarray/testing/assertions.py
- xarray/tests/test_accessor_dt.py
- xarray/tests/test_dataarray.py
I *think* it makes sense to limit how much we expose IndexVariable to users so I removed it.
This PR also auto-converts IndexVariable to Variable when unstacking.
> Don't return IndexVariable with .dt accessor

- doc/user-guide/groupby.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/groupby.py
- xarray/core/types.py
- xarray/tests/test_groupby.py
Closes #9396
Quite messy, and ~typing is broken atm (help!)~
> GroupBy(multiple strings)

- asv_bench/benchmarks/groupby.py
- doc/whats-new.rst
- xarray/groupers.py
```
| Change   | Before [a8c98967]    | After [948366dc]    |   Ratio | Benchmark (Parameter)                            |
|----------|----------------------|---------------------|---------|--------------------------------------------------|
| -        | 117±0.6ms            | 14.8±0.2ms          |    0.13 | groupby.GroupByLongTime.time_mean(True, False)   |
| -        | 115±0.6ms            | 14.0±0.1ms          |    0.12 | groupby.GroupByLongTime.time_mean(False, False)  |
| -        | 113±0.9ms            | 9.23±0.3ms          |    0.08 | groupby.GroupByLongTime.time_mean(True, True)    |
| -        | 112±0.6ms            | 8.28±0.2ms          |    0.07 | groupby.GroupByLongTime.time_mean(False, True)   |
| -        | 105±0.5ms            | 3.45±0.03ms         |    0.03 | …
```
> Avoid deep-copy when constructing groupby codes

- xarray/tests/__init__.py
Otherwise, creating test data can fail randomly, depending on how the random number generator is seeded.
(Note: we would ideally avoid using a random number generator or fix the random seed so test data is entirely deterministic, but that's a bigger refactor...)
> Always include at least one category in random test data

- ci/requirements/bare-minimum.yml
- ci/requirements/min-all-deps.yml
- doc/whats-new.rst
- pyproject.toml
- xarray/tests/__init__.py
- xarray/tests/test_groupby.py
> Bump minimum versions for dependencies

- xarray/core/datatree.py
- xarray/core/datatree_render.py
- xarray/core/iterators.py
- xarray/core/treenode.py
- xarray/tests/conftest.py
- xarray/tests/test_datatree.py
- xarray/tests/test_datatree_mapping.py
- xarray/tests/test_formatting.py
- xarray/tests/test_treenode.py
This seems to fix the examples in #9196, but causes other tests to fail, which I think just reveals that we have existing tests that assume this in-place modification is desired. I will change those tests to match the new intended behaviour.
> Shallow copy parent and children in DataTree constructor

- doc/whats-new.rst
- xarray/coding/cftime_offsets.py
- xarray/core/common.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/resample_cftime.py
- xarray/core/types.py
- xarray/groupers.py
- xarray/tests/test_groupby.py
pandas.BaseOffset, pandas.Timedelta, datetime.timedelta, and BaseCFTimeOffset are now all supported datatypes for resampling.
Closes #9408
> Support additional dtypes in `resample`

- xarray/core/datatree.py
- xarray/tests/test_datatree.py
I don't think there's a good reason to support syntax like `DataTree(DataArray(...))`, when it's easy enough to explicitly convert with `to_dataset()`. `Dataset(DataArray(...))` currently raises an error, so this feels a bit inconsistent.
If this was intended for the sake of usability, then I think supporting a dict (that gets coerced into a Dataset) in the DataTree constructor would be much helpful. We can consider adding this later.
@TomNicholas
> Disallow passing a DataArray as data into the DataTree constructor

- xarray/core/datatree.py
- xarray/tests/test_datatree.py
DataTree isn't a Generic tree type. It's a specific tree type -- the nodes are DataTree objects.
This was resulting in many cases where mypy insisting on explicit type annotations, e.g., `tree: DataTree = DataTree(...)`, which is unnecessary and annoying boilerplate.
> DataTree should not be "Generic"

- xarray/core/datatree.py
- xarray/tests/test_datatree.py
- xarray/tests/test_datatree_mapping.py
The fact that it has the non-descriptive name "d" is a good indication that users should not be supplying it as a keyword argument.
(Alternatively, we could make a more descriptive name, but I think positional only is also fine for now.)
> Make the first argument in DataTree.from_dict positional only

- xarray/core/datatree.py
- xarray/core/treenode.py
- xarray/tests/test_datatree.py
> Implement `DataTree.__delitem__`

- asv_bench/benchmarks/datatree.py
- xarray/core/datatree.py
- xarray/core/formatting.py
- xarray/core/formatting_html.py
- xarray/tests/test_datatree.py
Previously, we were copying parent coordinates/dimensions onto all child nodes. This is not obvious in the current repr, but you can see it from looking at the private `._node_coord_variables` and `._node_dims`.
To make the use of `_to_dataset_view()` little more obvious, I've added a required boolean `inherited` argument.
> Fix inheritance in DataTree.copy()

- xarray/core/datatree.py
This somehow got missed from #9297, see https://github.com/pydata/xarray/pull/9297#issuecomment-2335347554.
> Remove parent argument from DataTree.__init__

- asv_bench/benchmarks/datatree.py
- xarray/core/formatting.py
- xarray/tests/test_datatree.py
- xarray/tests/test_formatting.py
Still need a few more tests.
The HTML formatter will also need updates (not as part of this PR)
> Update DataTree repr to indicate inheritance

- xarray/backends/zarr.py
- xarray/core/datatree.py
- xarray/core/datatree_mapping.py
- xarray/core/formatting.py
- xarray/tests/test_backends_datatree.py
- xarray/tests/test_datatree.py
- xarray/tests/test_formatting.py
- xarray/tests/test_formatting_html.py
`.ds` is kept around as a soft-deprecated alias to facilitate the transition from xarray-contrib/datatree, though I verified that all tests pass without it.
> Rename DataTree's "ds" and "data" to "dataset"

- doc/whats-new.rst
This PR updates `doc/whats-new.rst` in order to release v2024.09.0, per discussion on today's xarray developers meeting.
Let me know if I've not called attention to enough of the items included in this release, but it felt like the dropping of Python 3.9 was the biggest thing that needs highlighting.
- ~~Closes #xxxx~~ (Let me know if I should create an issue for this release, though)
- ~~Tests added~~
- ~~New functions/methods are listed in `api.rst`~~
> Release notes for v2024.09.0

- doc/whats-new.rst
This PR just adds in the new section to `doc/whats-new.rst` after the v2024.09.0 release. (The instructions for a release said to push to main, but the branch was protected against that)
- ~~Closes #xxxx~~
- ~~Tests added~~
- ~~User visible changes (including notable bug fixes) are documented in `whats-new.rst`~~
- ~~New functions/methods are listed in `api.rst`~~
> New whatsnew section

- xarray/core/datatree.py
- xarray/core/treenode.py
- xarray/tests/test_treenode.py
Solves #9478 by implementing steps 1 through 4 of https://github.com/pydata/xarray/issues/9478#issue-2519949243. Steps 5 and 6 were not necessary, so `TreeNode` and `NamedNode` are still separate.
Changes the in-place behaviour of `TreeNode` in a way that is now consistent with the changes made to `DataTree` in #9297. The tests for treenode are changed but as the tests for datatree are not changed, there are no changes to user API.
> Ensure TreeNode doesn't copy in-place

- doc/whats-new.rst
- xarray/core/datatree.py
- xarray/tests/test_datatree.py
- Original issue on the DataTree repository : https://github.com/xarray-contrib/datatree/issues/311
- Original PR on the DataTree repository : https://github.com/xarray-contrib/datatree/pull/314 
Note: DataTree keys are `Hashable`. I only check for slashes in the variable names if they are instance of `str`. 
I never encountered a case (yet) where a Dataset keys are not `str` but `Hashable` in the broader case. 
We can imagine corner-cases where keys would be other types of `Hashable`, eg `Path` from `pathlib`
```python
In [2]: from pathlib import Path
In [3]: hash(Path("/"))
Out[3]: -3809984204556177651
```
The choice I made is (1): only apply the check of slashes in the key if the key is an instance of `str`.
Another choice  (2)would be to project the `Hashable` space onto `str` space: …
> Make illegal path-like variable names when constructing a DataTree from a Dataset

- xarray/core/treenode.py
- xarray/tests/test_datatree.py
This ensures that the tree cannot be in an inconsistent state.
> Forbid modifying names of DataTree objects with parents

- doc/whats-new.rst
- xarray/coding/times.py
- xarray/tests/test_coding_times.py
This PR provides a quick fix for #9488. 
Previously for `datetime64[ns]` and `timedelta64[ns]` values we would always use floor division to encode times if we knew that all non-`"NaT"` values could be represented with integers with the given units, even if we would ultimately cast the values to floats later based on the specified `dtype`.  This causes a problem when encoding `"NaT"` values, because the placeholder integer value is converted to a float [here](https://github.com/pydata/xarray/blob/18e5c87696c2233202bc67066408e6f495d0327d/xarray/coding/times.py#L805-L806), which prevents it from properly being filled with the fill value later in the encoding process.  
This PR changes things such that if we know that we will convert to floats eventually, we will use floating point division …
> Opt out of floor division for float dtype time encoding

- doc/whats-new.rst
- xarray/coding/times.py
- xarray/tests/test_coding_times.py
This PR addresses the issue that @langmore brought up in https://github.com/pydata/xarray/pull/9498#pullrequestreview-2307790147.  Thanks again for noting this and suggesting the fix.
I modified an existing test such that it will no longer fall back to cftime, so that it fails without this fix even if cftime is installed.
> Fix pandas datetime decoding with NumPy >= 2.0 for small integer dtypes

- xarray/core/datatree.py
- xarray/tests/test_datatree.py
Was this the easiest feature addition ever? 😅
> Datatree setitem dataset

- xarray/core/dataarray.py
- xarray/tests/test_groupby.py
> Make _replace more lenient.

- xarray/core/concat.py
- xarray/tests/test_concat.py
- Not notable
Before:
`AttributeError: 'IndexVariable' object has no attribute 'minimal'`
After:
`ValueError: compat='minimal' invalid: must be 'broadcast_equals', 'equals', 'identical', 'no_conflicts' or "override"`
> Update `compat` error checking to disallow "minimal" in `concat()`

- xarray/core/formatting.py
- xarray/tests/test_datatree.py
> Fix DataTree repr to not repeat inherited coordinates

- xarray/core/dataset.py
Also remove the internal object, which is referenced from `Returns:` already
> Add `.rolling_exp` onto `.rolling`'s 'See also'

- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/missing.py
- xarray/core/types.py
- xarray/tests/__init__.py
- xarray/tests/test_interp.py
- xarray/tests/test_missing.py
> Support vectorized interpolation with more scipy interpolators

- .github/workflows/ci.yaml
- ci/requirements/all-but-numba.yml
In response to help with: https://github.com/pydata/xarray/pull/9403#issuecomment-2368005828
> Add yet an other CI for numpy 2.1

- .github/FUNDING.yml
- README.md
I am a consultant working for NumFOCUS. Please feel free to reach out to me if you have any concerns about the content of this pull request.
- Update donation link in README to point at current xarray donation page on NumFOCUS' website. NumFOCUS no longer uses Salsa Labs, so the previous link no longer works.
- Update link in `.github/FUNDING.yml` to use HTTPS.
Based on past updates to this link (#2421, #2829), I think this doesn't count as a user-facing change, so I have not updated the What's New file.
> Update donation links

- xarray/core/datatree.py
- xarray/tests/test_datatree.py
- xarray/tests/test_datatree_mapping.py
This is a _partial_ solution to the duplicate coordinates issue from #9475.
Here we remove all duplicate coordinates between parent and child nodes with an index (these are already checked for equality via the alignment check).
Other repeated coordinates (which we cannot automatically check for equality) are still allowed for now. We will need an alternative solution for these, as discussed in #9475, but it is less obvious what the right solution is so I'm holding off on it for now.
> Remove duplicate coordinates with indexes on sub-trees

- doc/user-guide/pandas.rst
> Typos in pandas.rst

- xarray/core/formatting.py
- xarray/tests/test_namedarray.py
This crashes on main:
```python
from xarray.namedarray.core import NamedArray
x = NamedArray(("x",), np.array([1, 2, 3]))
x._repr_html_()
```
> Fix NamedArray html repr crashing

- xarray/core/indexing.py
- xarray/core/nanops.py
- xarray/tests/test_indexing.py
As discussed in https://github.com/pydata/xarray/issues/8834#issuecomment-2124914727, this swaps the order of special casing for types implementing both `__array_function__` and `__array_namespace__`, such that the Array API is preferred over `__array_function__`.
I've also disabled passing the `out` kwarg to `nanprod`, as that was the only occurrence where we actually do that, all other `nan*` functions silently ignore that kwarg.
cc @tomwhite
> allow using `__array_function__` as a fallback for missing Array API functions

- doc/ecosystem.rst
This PR is just a tiny typo fix, removing a double ":" in `doc/ecosystem.rst`.
> DOC/ecosystem: Fix tiny typo

- .github/workflows/nightly-wheels.yml
Our nightly wheels are currently failing because #9556 upgraded to a version of the action that later has been declared broken.
> bump `scientific-python/upload-nightly-action`

- pyproject.toml
- Add `sparse` to an `etc` category (or put in `io`?)
- In `complete`, don't include `dev` -- `dev` contains `complete` + dev tools (or could adjust `dev` so it's dev-only). And `complete` is everything a user might want. (Fine to adjust but currently they're recursive, which doesn't make sense
> Adjust pip extra dependencies

- pyproject.toml
So we're compatible with https://github.com/astral-sh/uv/issues/7881. Notes inline
> Add numba constraint

- xarray/backends/zarr.py
Saw this when was reviewing a PR, didn't want to delay the PR so pushing now
> Remove unneeded indentation

- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/datatree.py
- xarray/core/utils.py
- xarray/tests/test_datatree.py
- xarray/tests/test_utils.py
This is option (4) from https://github.com/pydata/xarray/issues/9475#issuecomment-2357004264
> Stop inheriting non-indexed coordinates for DataTree

- doc/api.rst
- doc/getting-started-guide/quick-overview.rst
- xarray/core/datatree.py
- xarray/tests/test_datatree.py
This PR deletes the many Dataset methods that were copied onto DataTree without unit tests, along with a few that are not implemented properly yet, e.g.,
1. Arithmetic methods were removed, because `DataTree + Dataset` should probably raise an error.
2. Indexing and aggregation methods were removed, because these should allow for dimensions that are missing only on some nodes.
3. The untested `map_over_subtree_inplace` and `render` methods were removed.
3. A few other methods (e.g., `merge` and `plot`) that were only implemented by raising `NotImplementedError`` are entirely removed instead.
> Remove unvetted DataTree methods

- doc/api.rst
- xarray/core/datatree.py
- xarray/tests/test_datatree.py
These methods handle dimensions that are not missing on some nodes properly, as discussed in https://github.com/pydata/xarray/issues/8949 
Adding additional indexing methods (e.g., `head`, `tail`, `thin`, `interp`, `reindex`), should be pretty easy to do in this style.
> Implement DataTree.isel and DataTree.sel

- xarray/core/datatree.py
- xarray/tests/test_datatree.py
Should have been done as part of #9531
> Datatree deduplicate setitem

- doc/api.rst
- xarray/core/_aggregations.py
- xarray/core/computation.py
- xarray/core/dataset.py
- xarray/core/datatree.py
- xarray/core/utils.py
- xarray/namedarray/_aggregations.py
- xarray/tests/test_dataset.py
- xarray/tests/test_datatree.py
- xarray/tests/test_utils.py
- xarray/util/generate_aggregations.py
They now allow for dimensions that are missing on particular nodes, and use Xarray's standard generate_aggregations machinery, like aggregations for DataArray and Dataset.
> Reimplement DataTree aggregations

- doc/getting-started-guide/quick-overview.rst
- doc/user-guide/data-structures.rst
- xarray/core/coordinates.py
- xarray/core/datatree.py
- xarray/core/datatree_io.py
- xarray/core/formatting.py
- xarray/core/formatting_html.py
- xarray/tests/test_backends_datatree.py
- xarray/tests/test_datatree.py
- xarray/tests/test_datatree_mapping.py
`inherit` is a little shorter than `inherited`, which I think makes for a slightly cleaner API. I believe this is also more consistent with other xarray method arguments, which are typically in the present tense.
Eventually, we can consider adding non-boolean options (e.g., `inherit='indexed_coordinates'` (default) vs `inherit='all_coordinates'`).
> Rename inherited -> inherit in DataTree.to_dataset

- .github/workflows/ci-additional.yaml
Mypy 1.12 broke our typing tests today. Pinning to 1.11.2 until we've figured out a fix.
> pin mypy to 1.11.2

- xarray/core/dataset.py
As mentioned in #2157, the docstring of `Dataset.groupby` does not reflect deprecation of squeeze (as the docstring of `DataArray.groupby` does) and states an incorrect default value.
> docs(groupby): mention deprecation of `squeeze` kwarg

- DATATREE_MIGRATION_GUIDE.md
- xarray/core/datatree.py
- xarray/core/treenode.py
- xarray/tests/test_datatree.py
This PR adds a inherit=False option to DataTree.copy, so users can decide if they want to inherit coordinates from parents or not when creating a subtree.
The default behavior is `inherit=True`, which is a breaking change from the current behavior where parent coordinates are dropped (which I believe should be considered a bug).
> Add inherit=False option to DataTree.copy()

- xarray/core/datatree.py
- xarray/core/treenode.py
As suggested by @headtr1ck in https://github.com/pydata/xarray/pull/9628#discussion_r1801635289
> Add missing `memo` argument to DataTree.__deepcopy__

- xarray/tests/test_datatree.py
Just adds `-> None` to every test in `test_datatree.py` as per @headtr1ck 's request in https://github.com/pydata/xarray/pull/9619#discussion_r1801583926
> Type check datatree tests

- xarray/backends/api.py
If the file is empty (or contains no variables matching any filtering done by the backend), use a different error message indicating that, rather than suggesting that the file has too many variables for this function.
I feel like the new message could be longer, but there's not really a way to fix "no data" in python, unless the writing process decided to add everything to the global `coordinates` attribute or something.
> DOC: Clarify error message in open_dataarray

- xarray/core/datatree.py
- xarray/tests/test_datatree.py
`DataTree.from_dict` now supports indicating the root node with "", ".", "/" or "./".
This makes the handling of the root node a bit more consistent with handling of other nested paths. For example, we can use relative paths, which allows for removing special cases for the root from some internal uses of from_dict.
I've also fixed a bug where the `name` argument was sometimes ignored.
> Support alternative names for the root node in DataTree.from_dict

- doc/whats-new.rst
- xarray/core/coordinates.py
- xarray/core/groupby.py
- xarray/groupers.py
- xarray/tests/__init__.py
- xarray/tests/test_groupby.py
> flox: Properly propagate multiindex

- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/groupby.py
- xarray/tests/test_groupby.py
> Fix multiple grouping with missing groups

- xarray/core/dataset.py
Closes #9653.
This behavior was introduced in #4333 but was then changed in #4753. See discussion in #9653 for more details.
> Update to_dataframe doc to match current behavior

- xarray/backends/api.py
- xarray/tests/test_backends_datatree.py
In trying to support `chunks` the way we do for `open_dataset` I had to add a lot of parameters to the top-level `open_datatree` and `open_groups` functions.
I'm also still looking for the equivalent of `_protect_dataset_variables_inplace`, and finally `_dataset_from_backend_dataset` has been the place to call `set_close`, while #9651 pushed this to the backends for datatree.
No tests yet, and I also want to improve the docstrings before merging.
(the chunked array methods – `chunk`, `load`, `compute`, and `persist` – should be a separate PR)
cc @TomNicholas, @shoyer
> support `chunks` in `open_groups` and `open_datatree`

- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/datatree.py
- xarray/namedarray/core.py
- xarray/tests/test_datatree.py
For now this only contains `compute` and `load`, but in implementing those I've found a bug in `copy`: we don't actually (shallow) copy the variables, which means that my implementation of `compute` would modify the original tree.
> implement `dask` methods on `DataTree`

- xarray/backends/zarr.py
This fixes an error in upstream dev (seen in https://github.com/pydata/xarray/issues/9277 and https://github.com/pydata/xarray/pull/9669)
xref: https://github.com/zarr-developers/zarr-python/pull/2413
> fix(zarr): use inplace array.resize for zarr 2 and 3

- xarray/backends/zarr.py
- xarray/tests/test_backends.py
- ~New functions/methods are listed in `api.rst`~
> Use zarr v3 dimension_names

- doc/whats-new.rst
I think it's obvious what the new features to highlight this time are!
> v2024.10.0 release summary

- doc/whats-new.rst
- xarray/core/datatree.py
- xarray/tests/test_datatree.py
> Fix inadvertent deep-copying of child data in DataTree

- xarray/core/dataarray.py
- xarray/tests/test_dataarray.py
https://github.com/pydata/xarray/pull/9450 introduced strict handling of `zip()`.
In `DataArray.chunk()`, this leads to a breaking change when passing a tuple/list as `chunks` where the length doesn't match `self.dims`. Previously these were just discarded.
https://github.com/pydata/xarray/blob/2c8f2e81e2ac8c49cbdad86367c571cfef9cdba7/xarray/core/dataarray.py#L1452
Since passing a tuple/list as `chunks` is deprecated anyway, this PR simply adds a `ValueError` to make the problem clear to the user instead of this ambiguous strict zip error.
Current error:
``` bash
File "/Users/../.venv/lib/python3.12/site-packages/xarray/util/deprecation_helpers.py", line 118, in inner
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File …
```
> Raise `ValueError` for unmatching chunks length in `DataArray.chunk()`

- .github/workflows/ci-additional.yaml
- pyproject.toml
- xarray/core/_typed_ops.py
- xarray/util/generate_ops.py
This change explicitly adds annotations for arithmetic like DataArray + Dataset in `_typed_ops.py`.
To test this, I've updated mypy on GitHub actions to use Python 3.12
Note: I've added a dependency on jinja2, a standard Python templating engine. It is only required for manually regenerating typed operations, which should impact only a handful of xarray developers.
> Typing annotations for arithmetic overrides (e.g., DataArray + Dataset)

- doc/whats-new.rst
- xarray/core/dataset.py
- xarray/tests/test_dataset.py
The coordinate on which the fit is computed in `da.polyfit` is transformed into a `float` using the same function as in `xr.polyval`. This ensures a symmetry between the two operations. Fixes a bug where `da.polyfit` would transform datetime coordinate to nanoseconds, but starting at 0 on the first element, while in `polyval` the transformation puts the 0 on 1970-01-01.
This solution seemed the most easiest to me, but I can see how importing a private function from a sub-module to another might not be the best.  Maybe, `_ensure_numeric` could be moved elsewhere ? `duck_array_ops.py` ?
> Use the same function to floatize coords in polyfit and polyval

- xarray/backends/api.py
- xarray/backends/zarr.py
Tiny refactoring to clean up `to_zarr`. No functional changes, just moving code out to helper functions. This will help us add support for icechunk soon.
> Refactor out utility functions from to_zarr

- .github/workflows/ci-additional.yaml
- xarray/backends/api.py
- xarray/backends/common.py
- xarray/backends/netCDF4_.py
- xarray/core/combine.py
- xarray/core/datatree_io.py
- xarray/core/types.py
- xarray/plot/facetgrid.py
- xarray/tests/test_backends.py
> update mypy to 1.13

- ci/requirements/environment.yml
This adds the pydap server dependencies needed to operate the pydap-tests in flaky CI.
See #9708
> add pydap-server dependencies to environment.yml

- doc/getting-started-guide/faq.rst
- doc/user-guide/data-structures.rst
- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/variable.py
> DOC: mention attribute peculiarities in docs/docstrings

- doc/whats-new.rst
- xarray/core/datatree.py
- xarray/core/datatree_io.py
- xarray/tests/test_backends_datatree.py
Consider a DataTree with a group, e.g.,
`tree = DataTree.from_dict({'/': ... '/child': ...})`
If we write `tree['/child']` to disk, the result should have groups relative to `'/child'`, so writing and reading from the same path restores the same object.
In addition, coordinates defined at the root should be written to disk instead of being omitted.
> Fix writing of DataTree subgroups to zarr or netCDF

- xarray/tests/test_dataarray.py
xarray.core.missing is only imported inside DataArray.interp(), which means that it is not necessarily defined in this test, unless `interp()` happened to be called first.
> Add missing xarray.core.missing import

- xarray/tests/test_groupby.py
> Fix groupby tests

- .github/workflows/benchmarks-last-release.yml
- .github/workflows/benchmarks.yml
- .github/workflows/ci-additional.yaml
- .github/workflows/ci.yaml
- .github/workflows/hypothesis.yaml
- .github/workflows/upstream-dev-ci.yaml
- ci/min_deps_check.py
> Move to micromamba 2

- doc/user-guide/interpolation.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/missing.py
- xarray/core/types.py
- xarray/tests/test_interp.py
_Outstanding uncertainty: dask/chunking behavior? Nothing about this PR touches the chunking of interpolation but I am a bit worried about this. Many interpolants, including those previously supported in one dimension, require nearby/all points from the original coordinate, and also don't parallelize well over the new coordinate. I'm not quite sure how this is currently being handled._
> support for additional scipy nd interpolants 

- pyproject.toml
- xarray/groupers.py
- xarray/tests/test_groupby.py
RUF007 Prefer `itertools.pairwise()` over `zip()` when iterating over successive pairs
> Apply ruff rule RUF007

- pyproject.toml
Use the same rule ordering as the ruff documentation:
https://docs.astral.sh/ruff/rules/
> Reorganise ruff rules

- ci/requirements/all-but-dask.yml
- ci/requirements/all-but-numba.yml
- ci/requirements/environment-windows.yml
- ci/requirements/environment.yml
Pinning array-api-strict<=2.1 for now until issues with new version (2.1.2) are sorted out.
> pin array-api-strict<=2.1

- .github/workflows/benchmarks-last-release.yml
- .github/workflows/benchmarks.yml
- .github/workflows/ci-additional.yaml
- .github/workflows/ci.yaml
- .github/workflows/hypothesis.yaml
- .github/workflows/upstream-dev-ci.yaml
- ci/min_deps_check.py
Since micromamba 2.0 installing conda seems to be broken in CI. In #9732 conda was removed from the install where not absolutely needed and the micromamba version was pinned to 2.0.2-0 due to broken 2.0.3-0.
The broken version was yanked and this PR reverts to the default micromamba version (now 2.0.2-0). In CI runs where conda is absolutely needed the micromamba-version is set to 1.5.10-0 (last version of v1-release line).
- When https://github.com/airspeed-velocity/asv/pull/1439 is resolved, we can remove the pin in the benchmark CI runs. 
- By resolving https://github.com/pydata/xarray/pull/9737#issuecomment-2463397879 the pin in the min-deps-check CI run will be removed.
conda.api and libmambapy are not API compatible
In https://github.com/pydata/xarray/blob/main/ci/min_deps_check.py …
> Use micromamba 1.5.10 where conda is needed

- xarray/core/utils.py
From [PEP 3101](https://peps.python.org/pep-3101/):
> #### [Explicit Conversion Flag](https://peps.python.org/pep-3101/#explicit-conversion-flag)
> 
> The explicit conversion flag is used to transform the format field value before it is formatted. This can be used to override the type-specific formatting behavior, and format the value as if it were a more generic type.
In the absence of an explicit conversion flag, the value is simply formatted. The default formatting converts to a `str`:
> #### [Controlling Formatting on a Per-Type Basis](https://peps.python.org/pep-3101/#controlling-formatting-on-a-per-type-basis)
> [...]
> The `object.__format__` method is the simplest: It simply converts the object to a string, and then calls format again:
> ```python
> class object:
>     def …
```
> Discard useless `!s` conversion in f-string

- xarray/core/formatting_html.py
- xarray/static/css/style.css
The changes introduced in #9412 caused display issues in the "Indexes" section (+ lots of vertical space between the main repr sections). This PR should fix that (in a kind of hacky way).
@srijan55 hopefully this doesn't break accessibility.
Main branch:
This PR:
> Fix html repr indexes section

- xarray/core/dask_array_ops.py
- xarray/core/rolling.py
- xarray/tests/test_rolling.py
This enables Dasks map_overlap for rolling reductions, the [previous issues](https://github.com/pydata/xarray/issues/3165) with memory consumption are now handled in map_overlap as far as I can tell
> Use `map_overlap` for rolling reductions with Dask

- doc/whats-new.rst
- xarray/core/dask_array_compat.py
- xarray/core/dask_array_ops.py
- xarray/core/dataset.py
- xarray/core/nputils.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_dataset.py
Closes #5629
1. Use Variable instead of DataArray
2. Use `reshape_blockwise` when possible following https://github.com/pydata/xarray/issues/5629#issuecomment-960133879
cc @phofl
> Optimize polyfit

- doc/whats-new.rst
- xarray/tutorial.py
> add 'User-Agent'-header to pooch.retrieve

- xarray/backends/common.py
- xarray/tests/test_backends.py
> Fix open_mfdataset for list of fsspec files

- xarray/backends/api.py
- xarray/backends/common.py
- xarray/backends/h5netcdf_.py
- xarray/backends/netCDF4_.py
- xarray/backends/plugins.py
- xarray/backends/pydap_.py
- xarray/backends/scipy_.py
- xarray/backends/store.py
- xarray/backends/zarr.py
- xarray/core/types.py
- xarray/tests/test_backends_api.py
Follow up to https://github.com/pydata/xarray/pull/9785
This introduces a `ReadBuffer` Protocol (stolen from pandas).
Also I finally took the courage to fix the Liskov violation in `open_dataset` by removing the `**kwargs` in the ABC.
> Buffer types

- xarray/backends/plugins.py
I got this error (forgot to install `h5netcdf`) and noticed a missing ". " right before "To install additional". This PR just adds that. Also quoted the unrecognized engine to match what's displayed in `list(engines)`.
> Minor format tweak to unrecognized engine error

- doc/whats-new.rst
- xarray/core/dataset.py
> Faster chunk checking for backend datasets

- xarray/plot/utils.py
- xarray/tests/test_plot.py
matplotlib/matplotlib#29135 deprecated passing `N` to `ListedColormap`. This PR avoids the deprecation warnings once the new matplotlib version is released.
> ListedColormap: don't pass N colors

- doc/whats-new.rst
> release notes for v2024.11.0

- doc/whats-new.rst
- xarray/plot/dataarray_plot.py
- xarray/tests/test_plot.py
As the docstring says, `xr.DataArray.load` loads the data inplace. So the dataset is affected as well which was not intended.
> Use compute instead of load in plot

- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/rolling.py
Extended the documentation of the centre argument of the following functions:
- xarray.DataArray.rolling
- xarray.Dataset.rolling
- xarray.core.rolling.DataArrayRolling
- xarray.core.rolling.DatasetRolling
> Described default centre argument behaviour in rolling functions

- doc/whats-new.rst
- xarray/core/common.py
- xarray/namedarray/core.py
Explicitly annotate that a single `str` argument leads to an `int` return, overriding the match against Iterable.
I haven't added tests since I didn't spot any existing tests of type annotations, but let me know if I missed them.
> Fix type annotations for `get_axis_num` (GH 9822)

- xarray/plot/utils.py
xref: https://github.com/pydata/xarray/pull/9561#discussion_r1861273284
Fixes  a regression I introduced in #9561
MWE:
On current `main`, this code will fail if `seaborn` is not installed _even if matplotlib is installed_:
```bash
conda create -n xr-test python=3.10 xarray pooch scipy matplotlib
```
```python
air = xr.tutorial.open_dataset("air_temperature")
air.air.isel(time=0).plot.contourf(colors="k")
```
As mentioned in https://github.com/pydata/xarray/pull/9561#discussion_r1861273284 , it seems that this wasn't caught by a CI because there isnt' a CI that has matplotlib but _not_ seaborn installed.
EDIT: AFAICT - The behavior before #9561 was that if you pass a single color to the `colors` parameter like in the MWE, xarray will try to use Seaborn for this but …
> FIX: gracfully handle missing seaborn dependency

- doc/whats-new.rst
- xarray/backends/common.py
- xarray/backends/zarr.py
- xarray/conventions.py
- xarray/tests/test_backends.py
- xarray/tests/test_backends_common.py
- xarray/tests/test_conventions.py
This is an internal change, moving non-CF related `ensure_dtype_not_object`-function from `conventions` to `backends`. Tests moved accordingly.
This was a longstanding ToDo which should now be resolved.
> move ensure_dtype_not_object from conventions to backends

- xarray/core/dataarray.py
- xarray/core/dataset.py
The "See Also" sections of 12 methods were edited to restore hyperlinks within the documentation.
DataArray
- isel
- sel
- coarsen
- weighted
- map_blocks
- groupby
Dataset
- isel
- sel
- coarsen
- weighted
- map_blocks
- groupby
> Fixed function links in dataarray.py and dataset.py

- asv_bench/benchmarks/__init__.py
- asv_bench/benchmarks/reindexing.py
- asv_bench/benchmarks/unstacking.py
- doc/user-guide/computation.rst
- doc/user-guide/dask.rst
- doc/user-guide/pandas.rst
- xarray/tests/__init__.py
- xarray/tests/test_backends.py
- xarray/tests/test_computation.py
- xarray/tests/test_dask.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_dataset.py
- xarray/tests/test_duck_array_ops.py
- xarray/tests/test_formatting_html.py
- xarray/tests/test_groupby.py
- xarray/tests/test_missing.py
Also switch to using the recommended `default_rng` instead of `RandomState`.
> Fix seed for random test data.

- xarray/backends/zarr.py
Avoids a few useless gets with Zarr v3 stores.
Not sure how to test it, or even if a test is needed.
cc @TomAugspurger
> Set `zarr_format` for `zarr.consolidate_metadata`

- .pre-commit-config.yaml
- pyproject.toml
Changes:
- add taplo (toml formatting) hook
- add `validate-pyproject` hook
Heyo! Looks like Taplo (https://github.com/tamasfe/taplo) would be a good option (same project as VScode extension [Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) with 2.3M downloads) . They don't have an official hook (https://github.com/tamasfe/taplo/issues/535) but there's an unofficial one at https://github.com/ComPWA/taplo-pre-commit. I don't think they'll get an official one soon as they would need to set up a mirror repo (and best to transfer both repos to an org for that).
> Add Pyproject pre-commit hooks

- xarray/core/dask_array_ops.py
See https://github.com/dask/dask/pull/11576 for the dask sibling
Using local functions is rather expensive to serialize because the function body has to be serialized instead of merely a reference. That's exacerbated if the function is accessing non-local state since that requires the serialization of the entire context that function is referring to. It is therefore always better for performance to define these functions, regardless of how small they are, as global, top-level functions such that pickle works properly.
The same is true for lambdas which have the same problem.
I'm looking into whether we can have automated tests for this (difficult since our and likely your tests suite is using locals all over the place...)
> Avoid local functions in push

- .github/workflows/ci.yaml
Without this, we can't upload on `main`, I think. I added a token into our Actions Secrets.
ref https://github.com/pydata/xarray/issues/9860
> Add token to codecov

- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/groupby.py
- xarray/core/weighted.py
I wanted to do https://github.com/pydata/xarray/issues/9805, but realize there is already deprecated behavior on `.quantile`; figured it would make sense to complete that cycle before doing another
> Remove deprecated behavior for non-dim positional args

- doc/whats-new.rst
- xarray/core/dataset.py
- xarray/tests/test_interp.py
We were calling align with no indexers, which just returned the input object
> Fix interpolation when non-numeric coords are present.

- asv_bench/benchmarks/__init__.py
New code should use the [integers](https://numpy.org/doc/2.1/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers) method of a [Generator](https://numpy.org/doc/2.1/reference/random/generator.html#numpy.random.Generator) instance instead of `randint`.
References:
https://numpy.org/doc/2.1/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers
https://numpy.org/doc/2.1/reference/random/generated/numpy.random.randint.html
> Use integers instead of randint

- doc/api.rst
This PR is meant to fix missing links in https://docs.xarray.dev/en/latest/generated/xarray.DataTree.html by adding the attributes to the API documentation.
> Add missing DataTree attributes to docs

- doc/whats-new.rst
- xarray/core/variable.py
> move scalar-handling logic into `possibly_convert_objects`

- xarray/tests/test_plot.py
> remove unused "type: ignore" comments in test_plot.py

- xarray/core/computation.py
- xarray/core/indexing.py
- xarray/tests/test_dask.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_indexing.py
cc @phofl here we need to index a numpy array with a dask array (commonly a much larger array) in a sane manner.
We now preserve chunksizes for
```
x, y, t = 1000, 1000, 57
rang = np.arange(t*x*y)
da = xr.DataArray(rang.reshape(t, x, y), coords={'time':range(t), 'x': range(x), 'y':range(y)})
da = da.chunk(dict(time=-1, x=256, y=256))
da.idxmin('time')
```
***After***
***Before***
> Optimize idxmin, idxmax with dask

- asv_bench/benchmarks/rolling.py
Skip the rolling tests using dask so the CI becomes usable again. 
Test with terrible performance, feel free to fix it and reactivate this test:
```python
import pandas as pd
def randn(shape, frac_nan=None, chunks=None, seed=0):
rng = np.random.default_rng(seed)
if chunks is None:
x = rng.standard_normal(shape)
else:
import dask.array as da
rng = da.random.default_rng(seed)
x = rng.standard_normal(shape, chunks=chunks)
if frac_nan is not None:
inds = rng.choice(range(x.size), int(x.size * frac_nan))
x.flat[inds] = np.nan
return x
nx = 3000
long_nx = 30000
ny = 200
nt = 1000
window = 20
randn_xy = randn((nx, ny), frac_nan=0.1)
randn_xt = randn((nx, nt))
randn_t = randn((nt,))
randn_long = randn((long_nx,), frac_nan=0.1)
ds = xr.Dataset(
{
"var1": …
```
> Skip dask rolling

- doc/whats-new.rst
- properties/test_encode_decode.py
- xarray/coding/cftime_offsets.py
- xarray/coding/cftimeindex.py
- xarray/coding/times.py
- xarray/testing/strategies.py
- xarray/tests/test_cftimeindex.py
This enhances the ISO-8601 parser to check for signed years (eg, -0300 or +0010) as well as 5 digit years (eg. -10000, +20000, 10000). The relevant parsing code is moved to coding.times (to prevent circular import) as these functionality will be used in #9618 within coding.times.
> Enhance and move ISO-8601 parser to coding.times

- xarray/core/utils.py
When passing a directory to open_dataset(), the scipy backend fails and a "RuntimeWarning: 'scipy' fails while guessing" is produced.
This affects me since I'm implementing a backend to read data written by the adios2 package, whose data "files" are actually a directory.
This tiny patch treats this case just like file not found, that is, the scipy backend will now return that it cannot open such a "file", but without raising an exception.
> fix warning from scipy backend guess_can_open on directory

- doc/whats-new.rst
- xarray/coding/times.py
- xarray/core/pdcompat.py
- xarray/tests/test_coding_times.py
This introduces some changes in the encoding/decoding pipeline to prepare for other units beside `ns`. It also fixes some inconsistencies wrt the exact ns.resolution datetime64 bounds.
Finally it will reduce the "noise" over in #9618 quite substantial.
> time coding refactor

- pyproject.toml
- xarray/tests/test_backends.py
- xarray/tests/test_variable.py
> Silence upstream Zarr warnings

- doc/whats-new.rst
I'll merge by tomorrow (Friday, Jan 3) so we can be compatible with the upcoming Zarr 3 Release (Jan 6)
> Whats-new 2025.01.0

- doc/api.rst
- doc/whats-new.rst
- xarray/__init__.py
- xarray/backends/api.py
- xarray/coders.py
- xarray/coding/times.py
- xarray/conventions.py
- xarray/convert.py
- xarray/tests/test_backends.py
- xarray/tests/test_coding_times.py
- xarray/tests/test_conventions.py
- xarray/tests/test_dataarray.py
This makes something like this possible:
```python
from xarray.coders import CFDatetimeCoder
ds = xr.open_mfdataset(..., decode_times=CFDatetimeCoder(use_cftime=True))
ds = xr.open_mfdataset(..., decode_times=CFDatetimeCoder(time_unit="s"))
```
> split out CFDatetimeCoder, deprecate use_cftime as kwarg

- xarray/backends/zarr.py
- xarray/tests/test_backends.py
Apparently I was over-eager in clicking the release button on Friday :( 
cc @d-v-b
> Fix zarr upstream tests

- xarray/tests/test_groupby.py
dask now auto-rechunks for quantile.
Closes #9860
> Remove outdated quantile test.

- doc/internals/time-coding.rst
- doc/user-guide/io.rst
- doc/user-guide/time-series.rst
- doc/user-guide/weather-climate.rst
- doc/whats-new.rst
- xarray/coding/cftimeindex.py
- xarray/coding/times.py
- xarray/coding/variables.py
- xarray/conventions.py
- xarray/core/common.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/indexing.py
- xarray/core/options.py
- xarray/core/variable.py
- xarray/tests/test_backends.py
- xarray/tests/test_cftimeindex.py
- xarray/tests/test_coding_times.py
- xarray/tests/test_computation.py
- xarray/tests/test_concat.py
- xarray/tests/test_conventions.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_dataset.py
- xarray/tests/test_groupby.py
- xarray/tests/test_interp.py
- xarray/tests/test_plot.py
- xarray/tests/test_variable.py
This is another attempt to resolve #7493. This goes a step further than #9580.
The idea of this PR is to automatically infer the needed resolutions for decoding/~encoding~ and only keep the constraints pandas imposes ("s" - lowest resolution, "ns" - highest resolution). There is still the idea of a `default resolution`, but this should only take precedence if it doesn't clash with the automatic inference. This can be discussed, though. Update: I've implemented `time-unit`-kwarg ~a first try to have default resolution~ on decode, which will override the current inferred resolution only to higher resolution (eg. `'s'` -> `'ns'`). To work towards #4490 the time decoding options (`decode_time` and `use_cftime` are bundled within `CFDatetimeCoder` which is distributed via `decode_times` kwarg. …
> Relax nanosecond datetime restriction in CF time decoding

- doc/whats-new.rst
- xarray/coding/times.py
- xarray/tests/test_variable.py
> fix upstream dev issues

- doc/whats-new.rst
- xarray/core/dataset.py
- xarray/core/utils.py
I found the error when I make a typo on the dataset keys not so helpful. The truncated list of variables hides all the ones that I wanted to see. Instead, add a fuzzy matching function that does the typical "Did you mean X". 
```python
possibilities = ("blech", "gray_r", 1, None, (2, 56))
t = np.arange(80)
var = xr.Variable(dims=("time",), data=np.arange(t.size))
data_vars = {v: ("time", var) for v in possibilities}
ds = xr.Dataset(data_vars, coords={"T": t})
ds["bluch"]
```
```python
%timeit xr.core.utils.did_you_mean("long_name9o5", tuple(f"long_name_{i}" for i in range(0, 1000)))
35.1 ms ± 1.95 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
%timeit xr.core.utils.did_you_mean("long_name9o5", tuple(f"long_name_{i}" for i in range(0, 100)))
3.29 ms ± 104 μs per loop (mean ± std. …
```
> Suggest the correct name when no key matches in the dataset

- doc/whats-new.rst
- xarray/tests/test_backends.py
- xarray/tests/test_coding_times.py
Per https://github.com/pydata/xarray/pull/9618#discussion_r1903352134, this PR updates relevant time coding tests to assert exact equality rather than equality with a tolerance, since xarray's minimum supported version of cftime has been greater than 1.2.1 for a while now.
cc: @kmuehlbauer
> Update time coding tests to assert exact equality

- ci/requirements/all-but-numba.yml
- ci/requirements/doc.yml
- ci/requirements/environment-3.13.yml
- ci/requirements/environment-windows-3.13.yml
- ci/requirements/environment-windows.yml
- ci/requirements/environment.yml
- doc/whats-new.rst
- xarray/tests/__init__.py
- xarray/tests/test_dataarray.py
> remove dask-expr from CI runs, fix related tests

- doc/whats-new.rst
- xarray/core/dataset.py
- xarray/tests/test_dataset.py
> fix weighted polyfit for arrays with more than 2 dimensions

- xarray/tests/test_datatree.py
... by using a fixed-endian input.
- [n/a] Closes #xxxx
- [n/a] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [n/a] New functions/methods are listed in `api.rst`
> Fix test_doc_example on big-endian systems

- doc/whats-new.rst
- xarray/core/groupby.py
- xarray/core/resample.py
- xarray/tests/test_groupby.py
cc @max-sixty . Alas I struggled with using a plain indexing operation when possible (see the first commit). We have the indices in `.encoded.group_indices`
> Use flox for grouped first, last

- xarray/backends/zarr.py
- xarray/tests/test_backends.py
Adds `shards` to the list of `valid_encodings` in the zarr backend, so that sharded Zarr V3s can be written.
> Add `shards` to `valid_encodings` to enable sharded Zarr writing

- doc/ecosystem.rst
Acting on https://github.com/pydata/xarray/issues/9992, this PR adds a link to the xarray extension [shxarray](https://github.com/ITC-Water-Resources/shxarray) in the ecosystem doc.
> Add shxarray to the xarray ecosystem list

- doc/whats-new.rst
- xarray/core/datatree_io.py
- xarray/tests/test_backends_datatree.py
As far as I can tell there is no reason this needs to be disabled, since we just call `ds.to_zarr` repeatedly in the current implementation.
> Enable `DataTree.to_zarr(compute=False)`

- doc/whats-new.rst
- xarray/core/duck_array_ops.py
- xarray/tests/test_duck_array_ops.py
> fix mean for datetime-like using the respective time resolution unit

- doc/whats-new.rst
- xarray/coding/frequencies.py
- xarray/tests/test_cftimeindex.py
> Fix infer_freq, check for subdtype "datetime64"/"timedelta64"

- xarray/tests/test_backends.py
Simply reorganizes the existing `region="auto"` tests in to a class. I'm finding this useful for downstream icechunk development.
> Migrate Zarr region="auto" tests to a class

- xarray/tests/test_coding_times.py
`freq="d"` is deprecated, so we make sure to use `freq="D"` to avoid warnings.
> Use `freq="D"` instead of `freq="d"` in `pd.timedelta_range`

- doc/whats-new.rst
- xarray/namedarray/core.py
- xarray/tests/test_namedarray.py
> cast `numpy` scalars to arrays in `NamedArray.from_array`

- xarray/core/dataset.py
- xarray/core/dtypes.py
> remove outdated type-ignores

- xarray/coding/times.py
- xarray/core/duck_array_ops.py
- xarray/core/formatting.py
- xarray/core/indexing.py
- xarray/core/nanops.py
- xarray/core/weighted.py
- xarray/groupers.py
- xarray/testing/assertions.py
Another change to use `duck_array_ops` for some instances of `all` and `any`.
> Duck array ops for `all` and `any`

- xarray/core/datatree_mapping.py
- xarray/tests/test_datatree_mapping.py
The error message did not indicate the name of the node which is fixed here.
It shows `'.'` for the root node while the repr uses `/` which is maybe confusing. This comes from using `NodePath()` - maybe this should be changed to `NodePath("/")`?
https://github.com/pydata/xarray/blob/c25215299c02cd36781cf3aa38e8583d1fe14849/xarray/core/treenode.py#L432
> `map_over_datasets`: fix error message for wrong result type

- doc/whats-new.rst
- xarray/coding/times.py
- xarray/tests/test_coding_times.py
When lazily encoding non-nanosecond times, the appropriate optimal integer encoding units are resolution-dependent.  This PR updates our encoding pipeline accordingly.  
Note that due to our internal reliance on pandas for date string parsing, we are still not able to round trip times outside the range -9999-01-01 to 9999-12-31 with pandas / NumPy, but this at least should pick more natural default units than nanoseconds for chunked arrays of non-nanosecond precision times.  This gives users another way of addressing #9154 (i.e. use non-nanosecond time arrays).
> Use resolution-dependent default units for lazy time encoding

- doc/internals/chunked-arrays.rst
:)
Also ctrl+f'ed for other copies of this broken link
> DOC: Fix 404 on Cubed's documentation

- doc/whats-new.rst
- xarray/core/duck_array_ops.py
- xarray/tests/test_duck_array_ops.py
This calculates the mean out of min and max years and uses that as the offset, effectively moving the offset right in the middle of the available datetime64. This decreases the maximum value of the calculated timedelta64 values by half, such that overflow is prevented.
> use mean of min/max years as offset in calculation of datetime64 mean

- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/tests/test_dataarray.py
This PR is related to Issue #10027
It fixes the issue and adds tests to prevent similar issues in future.
I did not document the change in whats-new.
I'm also not 100 % happy with the solution. I would welcome an experienced contributor to review the changes.
> Fix dataarray drop attrs

- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/dataset_utils.py
- xarray/core/dataset_variables.py
- xarray/core/datatree.py
Currently, `dataset.py` is 10956 lines long. This makes doing any work with current LLMs basically impossible — with Claude's tokenizer, the file is 104K tokens, or >2.5x the size of the _per-minute_ rate limit for basic accounts. Most of xarray touches it in some way, so you generally want to give it the file for context.
Even if you don't think "LLMs are the future, let's code with vibes!", the file is still really long; can be difficult to navigate (though OTOH it can be easy to just grep, to be fair...).
So I would propose:
- We start breaking it up, while also being cognizant that big changes can cause merge conflicts
- Start with the low-hanging fruit
- For example, this PR moves code outside the class (but that's quite limited)
- Then move some of the code from the big methods into …
> Start splitting up `dataset.py`

- doc/whats-new.rst
- xarray/core/datatree.py
- xarray/core/datatree_mapping.py
- xarray/tests/test_datatree_mapping.py
> implement map_over_datasets kwargs

- doc/whats-new.rst
- xarray/backends/h5netcdf_.py
- xarray/tests/test_backends.py
- xarray/tests/test_backends_datatree.py
- Warn user about behaviour change.
> Default to phony_dims="access" in h5netcdf-backend

- xarray/core/indexes.py
- `Index.isel`: more permissive return type (any Xarray Index)
This allows an index to return a new index of another type, e.g., a
1-dimensional CoordinateTransformIndex to return a PandasIndex when a
new transform cannot be computed (selection at arbitrary locations).
- `Index.equals`: more permissive `other` type (any Xarray Index)
Xarray alignment logic is such that Xarray indexes are always compared
with other indexes of the same type. However, this is not necessarily
the case for "meta" indexes (i.e., indexes encapsulating one or more
index objects that may have another type) that are dispatching `equals`
to their wrapped indexes.
More context and concrete examples in https://github.com/corteva/rioxarray/pull/846#discussion_r1965142497 and …
> More permissive Index typing

- doc/whats-new.rst
- xarray/core/indexes.py
- xarray/tests/test_dataset.py
Implement https://github.com/pydata/xarray/issues/10063#issuecomment-2672005278. Since we use `type(idx) is ...` instead of `isinstance(idx, ...)` this should be even faster.
The only performance degradation would be in the case of single coordinate custom indexes implemented in 3rd-party libraries, which could go through the fastpath as well but is harder to detect, but I think that's ok for now.
@hmaarrfk @dcherian
> Restrict fastpath isel indexes to the case of all PandasIndex

- doc/whats-new.rst
- xarray/core/indexes.py
- xarray/core/indexing.py
- xarray/tests/test_indexing.py
This helps us support reading from Zarr to GPU memory: https://zarr.readthedocs.io/en/stable/user-guide/gpu.html
Confirmed working by @TomAugspurger @weiji14 @negin513 @kafitzgerald !
> Generalize lazy backend indexing a little more

- doc/whats-new.rst
- xarray/coding/times.py
- xarray/tests/test_coding_times.py
As reported in #10071, false warnings for resolution changes can be emitted when decoding timedeltas encoded with floating point values.  In addition, the warning message could be clearer when resolution changes do occur.  This PR fixes both issues.  
The warning message in the event of a resolution change now reads:
```
>>> import xarray as xr
>>> var = xr.Variable(["time"], [0, 0.1], attrs={"units": "seconds"})
>>> xr.conventions.decode_cf_variable("foo", var, decode_timedelta=xr.coders.CFTimedeltaCoder(time_unit="s")).compute()
<stdin>:1: SerializationWarning: Can't decode floating point timedeltas to 's' without precision loss; decoding to 'ms' instead. To silence this warning pass decode_timedelta=CFTimedeltaCoder(time_unit='ms') to your opening function.
<xarray.Variable (time: 2)> …
```
> Fix false timedelta decoding `SerializationWarning` and improve warning message

- .pre-commit-config.yaml
- doc/whats-new.rst
- pyproject.toml
- xarray/core/alignment.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/indexes.py
- xarray/testing/strategies.py
- xarray/tests/test_backends.py
- xarray/tests/test_coding_times.py
- xarray/tests/test_dataset.py
- xarray/tests/test_datatree.py
- xarray/tests/test_rolling.py
- xarray/tests/test_variable.py
Also fixes a bunch of typos. The work here was adding the exclusions (I had an LLM do them but also checked them)
> Add typos check to pre-commit hooks

- doc/whats-new.rst
- xarray/coding/common.py
- xarray/coding/times.py
- xarray/coding/variables.py
- xarray/conventions.py
- xarray/tests/test_coding_times.py
- xarray/tests/test_conventions.py
Expecially for datetime/timedelta decoding we are still running into issue when partly decoding or issues when trying to roundtrip partially decoded data. Another issue is with keeping track of state for packed data / masked data. This PR solves this by adding state to CFMaskCoder/CFScaleOffsetCoder.
> Improve handling of dtype and NaT when encoding/decoding masked and packaged datetimes and timedeltas

- README.md
Old url leads to a 404. Based on the [pandas benchmarks page](https://pandas.pydata.org/community/benchmarks.html#pandas-benchmarks-servers), this seems to be a working alternative
> Update asv badge url in README.md

- xarray/tests/test_backends.py
Zarr's implementation of `attrs.__delitem__` is broken.
https://github.com/zarr-developers/zarr-python/issues/2903
> Fix broken Zarr test

- xarray/coding/strings.py
- xarray/coding/times.py
- xarray/core/formatting.py
- xarray/namedarray/pycompat.py
- xarray/tests/arrays.py
- xarray/tests/namespace.py
- xarray/tests/test_coding_times.py
This is the smallest set of changes I could find to make our time decoding handle duck arrays. Really we just explicitly convert to numpy arrays using `to_numpy`. Note that the cftime code path uses Cython, and so, it requires numpy
The second (now-reverted) [commit](https://github.com/pydata/xarray/pull/10081/commits/856b299a610b0734fd75a2ce5981173aa4714922) makes more invasive changes to avoid the numpy conversion if we can. I think it's best saved for a different PR.
cc @TomAugspurger
> Use `to_numpy` in time decoding

- pyproject.toml
- xarray/core/duck_array_ops.py
- xarray/core/groupby.py
- xarray/tests/test_array_api.py
(this is necessary because `array-api-strict` raises an error otherwise)
> explicitly cast the dtype of `where`'s condition parameter to `bool`

- pyproject.toml
`uv sync` now installs dev dependencies automatically. I don't think this should affect other tools negatively, lmk if I'm unaware of something
> Better `uv` compatibility

- pyproject.toml
I was getting a warning from the existing scalar value
> Change `python_files` in `pyproject.toml` to a list

- conftest.py
For some reason, my local was skipping tests when on a branch named `mypy`, or at least something was setting a `mypy` keyword on the test items.
This changes the check to whether the test has the `mypy` marker set, which is more precise than just looking at the keywords.
> Don't skip tests when on a `mypy` branch

- ci/requirements/environment.yml
- conftest.py
- pyproject.toml
- xarray/core/coordinates.py
- xarray/core/groupby.py
- xarray/core/indexes.py
- xarray/tests/test_dataset.py
for transparency, claude code also helped here, but I did more auditing & fixing than the idxmax PR (sorry to externalize that to reviewers...)
> Fix type issues from pandas stubs

- doc/user-guide/data-structures.rst
I think this is no longer possible?
> [docs] `DataTree` cannot be constructed from `DataArray`

- xarray/backends/api.py
- xarray/tests/conftest.py
- xarray/tests/test_backends_datatree.py
Harmonizes behavior with dataset for the same situation. When the dataarray has an attribute that triggers cf_convention decoding, passing `decode_cf=False` had not effect.
I also updated the text rendering of the `simple_datatree` test fixture to the current rendering which looks nicer and also correctly indentifies the type of each array.
As a side note (for follow up) it seems that `assert_equal` as is used in the other tests does not check for dtype.
attn @TomNicholas 
- [NA?] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [NA ] New functions/methods are listed in `api.rst`
> Fix `open_datatree` when `decode_cf=False`

- doc/user-guide/indexing.rst
The link to the numpy advanced indexing page is broken, fix it
> Fix numpy advanced indexing docs link

- doc/whats-new.rst
- xarray/core/dataarray.py
> Update DataArray.to_zarr to match Dataset.to_zarr.

- .github/workflows/upstream-dev-ci.yaml
- doc/whats-new.rst
- xarray/core/groupby.py
- xarray/tests/conftest.py
- xarray/tests/test_groupby.py
cc @aulemahal 
This will need flox v0.10.1 for CI to succeed.
> Fix GroupBy first, last with flox

- doc/user-guide/io.rst
- doc/whats-new.rst
- xarray/backends/zarr.py
- xarray/tests/test_backends.py
> Allow setting `fill_value` on Zarr format 3 arrays

- ci/install-upstream-wheels.sh
The name of the repo has changed from `zarr` to `zarr-python` it was still working due to github re-direct, but better to be explicit about which repo this is aiming at
- [NA] Closes #xxxx
- [NA] Tests added
- [NA] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [NA] New functions/methods are listed in `api.rst`
> Use explicit repo name in upstream wheels

- doc/whats-new.rst
- xarray/plot/facetgrid.py
- xarray/tests/test_plot.py
> Fix: Correct axis labelling with units for FacetGrid plots

- xarray/backends/zarr.py
- xarray/tests/test_backends.py
Prevent passing `write_empty_chunks` from raising an error. Prior to this PR `Dataset.to_zarr(...,write_empty_chunks=)` would raise:
```python
TypeError: Group.create_array() got an unexpected keyword argument 'write_empty_chunks'
```
This seems like the shortest path to prevent this bug without changing the xarray api at all, in the future it might be good to better align the xarray api with the zarr api. I also added `order` to this fix for create array as it underwent a similar deprecation.
@sotosoul I independently encountered this issue and set out to fix it, I hadn't seen the fix in your fork. Can you try this out and see if it fixes it for you.
**Test Changes**
The test that would have caught this issue was not enabled for zarr v3. I enabled it but had to make some modifications to …
> Support zarr `write_empty_chunks` for zarr-python 3 and up

- pyproject.toml
- xarray/core/resample_cftime.py
RUF046 Value being cast to `int` is already an integer
> Apply ruff preview rule RUF046

- xarray/tests/test_sparse.py
> Fix sparse dask repr test

- doc/internals/how-to-create-custom-index.rst
- doc/internals/internal-design.rst
- doc/internals/interoperability.rst
- doc/user-guide/combining.rst
- doc/whats-new.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
> Fix references to core classes in docs

- doc/whats-new.rst
- xarray/core/dataset.py
- xarray/tests/test_dataset.py
`xarray.Dataset.to_stacked_array` now uses dimensions in order of appearance.
This fixes the issue where using `xarray.Dataset.transpose` before `xarray.Dataset.to_stacked_array` had no effect.
(Mentioned in #9921)
> Fixes dimension order in `xarray.Dataset.to_stacked_array`

- asv_bench/benchmarks/repr.py
Add a performance test for #10139.
> Add datatree repr asv

- doc/whats-new.rst
- xarray/core/datatree.py
- xarray/tests/test_datatree.py
Allow setting `keep_attrs` in `DatasetView.map` as per the comment in the method. I copied the logic over from `xr.Dataset.map`.
> `DatasetView.map` fix `keep_attrs`

- xarray/computation/fit.py
- xarray/core/utils.py
- xarray/plot/dataarray_plot.py
- xarray/plot/utils.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_datatree.py
- xarray/tests/test_pandas_to_xarray.py
Closes #10231
Some of these look like they might have come from upstream changes. The only one that is maybe concerning is that `np.array.tolist()` is not guaranteed to return a list - for instance if the array is 0D.
> Fix mypy failures on main

- ci/requirements/min-all-deps.yml
- doc/user-guide/io.rst
- doc/whats-new.rst
- xarray/backends/pydap_.py
- xarray/core/datatree_io.py
- xarray/tests/test_backends.py
- xarray/tests/test_backends_datatree.py
There have been some (revitalizing) upgrades over the last year to [pydap](https://pydap.github.io/pydap/en/intro.html) (with some more to come), including authentication, pydap data model (dap2 vs dap4). This ~Draft~ PR aims to
This PR enables, for example (check [test opendap dap4 url](http://test.opendap.org/opendap/dap4/SimpleGroup.nc4.h5.dmr.html))
```python
URL = "dap4://test.opendap.org/opendap/dap4/SimpleGroup.nc4.h5"
ds = xr.open_datatree(URL, engine='pydap')
```
> opendap / dap4 support for pydap backend

- doc/internals/time-coding.rst
- doc/user-guide/io.rst
When building the documentation, a couple of example files are written to disk but never deleted. 
Currently affected:
- `doc/user-guide/io.rst`
- In line 608 `saved_on_disk.h5` is written to disk but never removed
(note: .h5 files are not exlcuded by .gitignore)
-  `doc/internals/time-coding.rst`
-  `test-datetimes1.nc`
-   `test-datetimes2.nc`
-   `test-timedeltas1.nc`
-   `test-timedeltas2.nc`
This PR adds a simple clean up snippet at the end of each affected file / section to get rid of them:
```rst
.. ipython:: python
:suppress:
import os
for f in ["i_am_a_tmp_example.nc", "tmp_file.h5"]:
if os.path.exists(f):
os.remove(f)
```
> Fix: Docs generation create temporary files that are not cleaned up.

- xarray/tests/test_dask.py
This test is intended to break after https://github.com/dask/dask/pull/11881
This test was implemented as part of https://github.com/pydata/xarray/pull/2603 at a time when HighLevelGraphs were just introduced. The test itself ensures pretty much that if a collection is passed to a Delayed objects, the underlying dask graph is a superset of the graph of the original collection. In different terms, the delayed is only adding additional tasks but is keeping the original graph as is.
One of the changes in https://github.com/dask/dask/pull/11881 is that it now respects optimization of the collection when passed to the delayed function. In earlier dask versions, the collection would've been passed (and be computed) unoptimized, i.e. no culling, no fusion, no slicing, just the raw graph. That is …
> Remove `test_dask_layers_and_dependencies`

- ci/minimum_versions.py
- ci/requirements/min-all-deps.yml
- pyproject.toml
- xarray/tests/test_backends.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_duck_array_wrapping.py
- xarray/tests/test_variable.py
Quickly gets CI to green.
Closes #10189
> Fix mypy, min-versions CI, xfail Zarr tests

- doc/whats-new.rst
- xarray/core/groupby.py
Now we completely avoid constructing a  very large MultiIndex in memory. I'm relying on the existing test suite, but I also manually checked that we never use `self._group_dim` or `self.group1d` when grouping by a chunked array
> Avoid stacking when grouping by chunked array

- xarray/groupers.py
- xarray/tests/test_groupby.py
Removes a pandas limitation that we don't need.
> BinGrouper: Support setting labels when provided with IntervalIndex

- xarray/core/groupby.py
- xarray/tests/test_groupby.py
> Fix reduction by subset of grouper dimensions

- doc/whats-new.rst
- xarray/coding/calendar_ops.py
- xarray/tests/test_calendar_ops.py
When calling `convert_calendar` on dataset with non-temporal variable (no  `time` dimension), the `time` dimension was added. This is because the function was using `where(time.notnull(), drop=True)` to drop the time elements of the source that did not map to a valid time in the target calendar. 
Given that  `time` is always 1D and always loaded (no dask), using `sel(time=time.notnull())` fixes the bug, and, in fact, makes more sense to me. (I don't remember why I didn't use that in my first version of the method...)
I added a minimal test that detects the bug raised in the issue.
> Fix convert calendar on non-temporal data in datasets

- doc/conf.py
- doc/user-guide/ecosystem.rst
- xarray/core/dataarray.py
- xarray/core/dataset.py
Hi! I am the author of [xarray-lmfit](https://github.com/kmnhan/xarray-lmfit) and would like to propose adding it to the ecosystem documentation. This package extends xarray with curve fitting capabilities using the [lmfit](https://github.com/lmfit/lmfit-py) library. Please let me know if there are any changes needed. Thank you for your consideration!
> Add `xarray-lmfit` extension for curve fitting to ecosystem documentation

- doc/user-guide/ecosystem.rst
The first release is out of the [xarray-eopf](https://github.com/EOPF-Sample-Service/xarray-eopf) backend, which allows to open ESA EOPF data products in Zarr format via `xarray.open_dataset` and `xarray.open_datatree`. With this PR we would like to link the GitHub repo of the backend to the [xarray related projects page](https://docs.xarray.dev/en/stable/user-guide/ecosystem.html).
> Adding xarray-eopf to ecosystem.rst

- doc/conf.py
This is a follow on to https://github.com/pydata/xarray/pull/8708 which changed the docs organization with a few new subfolders. I overlooked redirecting existing links. Could merge as is, but I could also spend a bit more time next week how to figure out testing for any other broken links in the docs.
> Add redirect for contributing guide

- doc/contribute/contributing.rst
#8680 removed absolufy from the codebase, this PR brings the contributing guide up to date.
> DOC: Remove reference to `absolufy-imports` from contributing guide

- xarray/core/variable.py
- xarray/tests/test_dataset.py
Just a small fix since I noticed that `repr(ds)` could include `PandasExtensionArray(array=` as it was not being recognized as in memory, and therefore its own `repr` method was used (via inheritance of `NDArrayMixin`)
Much cleaner now!
> (fix): remove `PandasExtensionArray` from repr

- doc/whats-new.rst
- xarray/groupers.py
- xarray/tests/test_groupby.py
> Fix BinGrouper when labels is not specified

- doc/whats-new.rst
- xarray/core/coordinate_transform.py
- xarray/core/indexes.py
- xarray/indexes/range_index.py
- xarray/structure/alignment.py
- xarray/tests/test_coordinate_transform.py
- xarray/tests/test_dataset.py
Support checking exact alignment of indexes that use multiple dimensions in the cases where some of those dimensions are included in alignment while others are excluded.
Add the `exclude_dims` keyword argument to `Index.equals()` (still support old signature with `FutureWarning`).
Also fixed a bug: indexes associated with scalar coordinates were ignored during alignment.
TODO:
> Alignment of n-dimensional indexes with partially excluded dims

- doc/whats-new.rst
- xarray/computation/rolling.py
Use dtype from intermediate sum for casting of count instead of current "int" when calculating mean in rolling operations to prevent unnecessary casting to/from int
> FIX: prevent unnecessary type casts in rolling mean

- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/types.py
Since `"Y"` and `"M"` represent variable intervals of time, these are not valid options for the `datetime_unit` in `integrate`, `cumulative_integrate`, or `differentiate`. This PR updates our typing and documentation to account for this.
xref: https://github.com/pydata/xarray/discussions/8000
> Remove `"Y"` and `"M"` from `DatetimeUnitOptions`

- doc/whats-new.rst
- xarray/coding/times.py
- xarray/tests/test_coding_times.py
> fix roundtripping zero-size timedelta arrays

- xarray/computation/ops.py
- xarray/tests/test_dask.py
> Set `.conjugate` as alias of `.conj`, #10302

- CONTRIBUTING.md
The "[Contributing to xarray](https://docs.xarray.dev/en/stable/contribute/contributing.html)" page is great but the link to it was broken ([see here](https://github.com/pydata/xarray/blob/main/CONTRIBUTING.md)), which gave a bad impression when I prepared to make my first pull request.
Let me know if I have to open an issue too.
> The URL in CONTRIBUTING.md was broken and didn't automatically redirect.

- asv_bench/benchmarks/indexing.py
- doc/whats-new.rst
- xarray/core/indexing.py
While investigating #10311, I noticed that the large memory usage described there was exacerbated by duplicating the passed indexes in `VectorizedIndexer.__init__`. While this could be a defensive copy to avoid someone else mutating the passed ndarrays, looking at the [PR it was introduced](https://github.com/pydata/xarray/pull/5873/files#diff-44298663560e4e667c3235f546e7e4a92866f69619a0503a9171148e934d5cc9R386) I would guess this was an unintentional regression as part of supporting duck arrays, since `asarray` defaults to *not* copying the data and `astype` defaults to copying the data, but cc @dcherian in case that's not true.
Also included in this PR is increasing the size of the benchmark to show the improvement more clearly. (On my machine, it's a ~20% time savings.) Happy to break …
> Avoid copying vectorized indexes

- xarray/structure/merge.py
- xarray/tests/test_computation.py
- xarray/tests/test_merge.py
- xarray/tests/test_ufuncs.py
Fixing #8047 (and at least the #8480 duplicate) by copying coordinate-variables before overwriting their .attrs in `structure.merge.merge_collected()`.
In a call to `apply_ufunc()`, the output coordinates and their attributes are produced in `merge_collected()` based on the combine_attrs argument (which is "override" or "drop" depending on the keep_attrs argument). However, a side effect of the line `merged_vars[name].attrs = merge_attrs(`... was that also the .attrs of the coordinate on the _input_ arrays would be changed to the output arrays', i.e. dropped or changed to those of the first input array.
The proposed solution of creating a shallow copy of the input coordinate before assigning attributes works, according to the new tests I added in in test_ufuncs.py and test_computation.py, …
> apply_ufunc: don't modify attrs on input variables

- doc/get-help/howdoi.rst
- xarray/core/common.py
- xarray/core/duck_array_ops.py
> Fix "a array" misspelling

- xarray/tests/test_accessor_dt.py
- xarray/tests/test_coding_times.py
- xarray/tests/test_dask.py
- xarray/tests/test_datatree.py
- xarray/tests/test_distributed.py
- xarray/tests/test_formatting_html.py
- xarray/tests/test_plot.py
Other `PT` rules either result in too many changes ([`PT006`](https://docs.astral.sh/ruff/rules/pytest-parametrize-names-wrong-type/), [`PT007`](https://docs.astral.sh/ruff/rules/pytest-parametrize-values-wrong-type/)) or seem less interesting to me in the short term ([`PT011`](https://docs.astral.sh/ruff/rules/pytest-parametrize-values-wrong-type/), [`PT012`](https://docs.astral.sh/ruff/rules/pytest-raises-with-multiple-statements/), [`PT018`](https://docs.astral.sh/ruff/rules/pytest-composite-assertion/), [`PT022`](https://docs.astral.sh/ruff/rules/pytest-useless-yield-fixture/)).
> Apply assorted ruff/flake8-pytest-style rules (PT)

- xarray/backends/h5netcdf_.py
- xarray/backends/locks.py
- xarray/backends/netcdf3.py
- xarray/backends/zarr.py
- xarray/coding/frequencies.py
- xarray/coding/times.py
- xarray/computation/computation.py
- xarray/conventions.py
- xarray/core/dataset.py
- xarray/core/formatting.py
- xarray/core/groupby.py
- xarray/core/missing.py
- xarray/core/parallel.py
- xarray/core/utils.py
- xarray/core/variable.py
- xarray/groupers.py
- xarray/indexes/range_index.py
- xarray/plot/facetgrid.py
- xarray/plot/utils.py
- xarray/structure/alignment.py
- xarray/structure/concat.py
- xarray/tests/test_backends.py
- xarray/tests/test_backends_datatree.py
- xarray/tests/test_computation.py
- xarray/tests/test_dataset.py
- xarray/tests/test_distributed.py
- xarray/tests/test_interp.py
- xarray/tests/test_plot.py
- xarray/tests/test_units.py
- xarray/util/print_versions.py
These are debatable rules, sometimes the result is less readable. I have selected those rules that do seem to make sense in this repository.
>  Apply assorted ruff/flake8-simplify rules (SIM)

- xarray/core/duck_array_ops.py
The `unravel_index` import was added by cd6065e / #5571.
> Ignore ruff/Pyflakes rule F401 more precisely

- pyproject.toml
Rules already applied in #9722.
> Enforce ruff/flake8-implicit-str-concat rules (ISC)

- xarray/backends/zarr.py
in `main` the zarr backend uses the `zarr_array.metadata.data_type` attribute to get the dtype of the zarr array. If the goal is to ultimately get a numpy data type, it's simpler and safer to retrieve the data type from from the `dtype` attribute of the zarr array. This PR makes that change. 
This addresses on of the incompatibilities noted in https://github.com/pydata/xarray/issues/10329
> use numpy dtype exposed by zarr array instead of metadata.data_type

- doc/_static/style.css
- xarray/static/css/style.css
<br>
Main branch:
<br><br>
This PR:
<br>
Main branch:
<br><br>
This PR:
> Improve html repr in dark mode (Jupyterlab + Xarray docs)

- doc/user-guide/time-series.rst
- doc/whats-new.rst
Looks like we missed one last month and have accumulated some nice fixes and features
> Release v2025.06.0

- doc/whats-new.rst
- xarray/tests/test_backends.py
> Fix Pydap tests for numpy 2.3.0 changes (scalar string to unicode)

- xarray/plot/dataset_plot.py
- xarray/tests/test_plot.py
In https://github.com/pydata/xarray/blob/f1a2c08f21a8237c082913fcad2d77469448cf4c/xarray/plot/dataset_plot.py#L622-L633
`x`, `y`, `u`, `v` are all transposed, if the dataset only gives a 1D array for both `x` and `y`, which is a pretty nice addition to mpl's behavior. However, the color was left out. If one has a spatial grid of shape `(nx, ny)` and uses `hue`,  and `nx` is different from `ny`, then `matplotlib.streamplot` will raises a value error caused by `color.shape != grid.shape`.
This PR simply adds the same condition to transpose `hue` if  `x`, `y`, `u`, `v` are transposed.
I could not find a unittest corresponding to `streamplot`. But here is a minimal working example that does not work under current code but works after the simple change.
```python
import …
```
> Fixed color.shape != grid.shape in streamplot when nx != ny

- doc/whats-new.rst
- xarray/backends/common.py
- xarray/backends/h5netcdf_.py
- xarray/backends/netCDF4_.py
- xarray/backends/netcdf3.py
- xarray/backends/scipy_.py
- xarray/backends/zarr.py
- xarray/coding/strings.py
- xarray/tests/test_coding_strings.py
- xarray/tests/test_conventions.py
> Check and fix chararray string dimension names

- xarray/structure/alignment.py
- xarray/tests/test_dataset.py
> Fix reindex on Dataset from MultiIndex DataFrame with RuntimeError

- doc/api.rst
- doc/whats-new.rst
- xarray/__init__.py
- xarray/indexes/__init__.py
Also expose CoordinateTransformIndex
Closes #10424
> Expose top-level xarray.indexes in __init__

- xarray/core/indexing.py
> Redundant list comprehension can be replaced using generator

- xarray/tests/test_computation.py
- xarray/tests/test_datatree.py
Rewrite as set literal syntax.
> Unnecessary tuple/list literal

- xarray/core/utils.py
`ModuleNotFoundError` is a subclass of `ImportError`:
[Exception hierarchy](https://docs.python.org/3/library/exceptions.html#exception-hierarchy)
> Exceptions are overlapping

- pyproject.toml
- xarray/coding/strings.py
- xarray/core/duck_array_ops.py
> Enforce ruff/Pylint Refactor rules (PLR)

- CODE_OF_CONDUCT.md
When Xarray joined NumFOCUS in 2018, we adopted the "Contributor Covenant" Code of Conduct because that was recommended by NumFOCUS, and having a Code of Conduct was a requirement for NumFOCUS affiliation. Our code of conduct suggests contacting the core project team to report any issues,  but in practice we have never had a code of conduct report.
Recently, NumFOCUS introduced a standard [NumFOCUS code of conduct](https://numfocus.org/code-of-conduct), which it has encourraged all NumFOCUS projects to adopt. In practice, the main difference is that the NumFOCUS Code of Conduct Working Group would handle all reports, rather than Xarray's project core team. We have the option to either have the Working Group recommendations (with final decisions by Xarray project leadership) or to let the …
> Switch to using the NumFOCUS Code of Conduct

- properties/test_index_manipulation.py
- xarray/coding/cftime_offsets.py
- xarray/coding/cftimeindex.py
- xarray/computation/apply_ufunc.py
- xarray/computation/computation.py
- xarray/computation/fit.py
- xarray/computation/nanops.py
- xarray/core/dataset.py
- xarray/core/datatree.py
- xarray/core/duck_array_ops.py
- xarray/core/groupby.py
- xarray/core/treenode.py
- xarray/groupers.py
- xarray/plot/utils.py
- xarray/structure/concat.py
- xarray/tests/test_datatree.py
- xarray/tests/test_groupby.py
- xarray/tests/test_units.py
These issue appear not to be part of the _ruff_ Pylint rule set.
> More Pylint issues

- xarray/computation/rolling.py
> More f-strings, less format()

- doc/whats-new.rst
- xarray/testing/assertions.py
- xarray/tests/test_assertions.py
`assert_equal(..., check_dim_order=False)` did not do anything when two `DataTree` objects are passed.
Requires #10440 for the tests to pass, so a draft for now.
> assert_equal: ensure check_dim_order=False works for DataTree

- asv_bench/benchmarks/dataset_io.py
- xarray/namedarray/_typing.py
Issue introduced by 16b53ac / #8937.
It looks like the `sys.version_info >= (3, 11)` test is incorrect, as [`typing.TypeAlias`](https://docs.python.org/3/library/typing.html#typing.TypeAlias)  was added in version 3.10, not 3.11:
> _Added in version 3.10._
Note that [`TypeAlias`](https://docs.python.org/3/library/typing.html#typing.TypeAlias) itself will be deprecated:
> _Deprecated since version 3.12:_ [`TypeAlias`](https://docs.python.org/3/library/typing.html#typing.TypeAlias) is deprecated in favor of the [`type`](https://docs.python.org/3/reference/simple_stmts.html#type) statement, which creates instances of [`TypeAliasType`](https://docs.python.org/3/library/typing.html#typing.TypeAliasType) and which natively supports forward references. Note that while …
> Branches of the `if` statement have similar implementation

- xarray/backends/chunks.py
- xarray/backends/pydap_.py
- xarray/backends/zarr.py
- xarray/coding/times.py
- xarray/computation/nanops.py
- xarray/core/accessor_str.py
- xarray/core/common.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/datatree.py
- xarray/core/datatree_mapping.py
- xarray/core/extension_array.py
- xarray/core/types.py
- xarray/core/utils.py
- xarray/namedarray/_typing.py
- xarray/plot/facetgrid.py
- xarray/plot/utils.py
- xarray/structure/chunks.py
- xarray/structure/combine.py
- xarray/tests/test_dataarray.py
- xarray/tests/test_datatree.py
- xarray/tests/test_duck_array_ops.py
- xarray/tests/test_interp.py
- xarray/tests/test_plot.py
- xarray/tests/test_rolling.py
- xarray/tests/test_utils.py
- xarray/tutorial.py
> Apply assorted ruff preview rules

- pyproject.toml
- xarray/backends/netCDF4_.py
- xarray/backends/pydap_.py
- xarray/coding/times.py
- xarray/computation/rolling.py
- xarray/core/common.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/formatting.py
- xarray/core/indexes.py
- xarray/core/parallel.py
- xarray/core/resample_cftime.py
- xarray/groupers.py
- xarray/plot/facetgrid.py
- xarray/plot/utils.py
- xarray/structure/merge.py
- xarray/tests/test_backends.py
- xarray/tests/test_backends_datatree.py
- xarray/tests/test_coding.py
- xarray/tests/test_combine.py
- xarray/tests/test_dask.py
- xarray/tests/test_dataset.py
- xarray/tests/test_groupby.py
- xarray/tests/test_strategies.py
- xarray/tests/test_units.py
- xarray/util/print_versions.py
Reverts pydata/xarray#10462
apparently an error on `main`; we can redo when we're confident we've fixed that (not sure why it didn't show in tests?!)
> Revert "Enforce ruff/flake8-simplify rules (SIM)"

- xarray/indexes/range_index.py
- xarray/tests/test_range_index.py
> Fix RangeIndex slicing

- doc/whats-new.rst
- xarray/backends/netcdf3.py
- xarray/coding/times.py
- xarray/tests/test_backends.py
- xarray/tests/test_coding_times.py
This PR fixes the critical `np.timedelta64` encoding bugs introduced in #10101. We now always encode `np.timedelta64` values with a `dtype` attribute corresponding to the in-memory `dtype`, and use the same encoding path that we did previously, which by default selects the coarsest units that support integer serialization.  This enables storing `"timedelta64[ns]"` values in netCDF3 format, which was not supported by the "literal" encoding approach implemented in #10101.
For consistency with the previous `units`-based decoding approach, this update also now enables controlling the decoded resolution of `dtype`-decoded values via the `time_unit` parameter of the `CFTimedeltaCoder` class. By default the `time_unit` parameter is now `None`. If the `time_unit` is `None` the `dtype` attribute …
> Fix critical `np.timedelta64` encoding bugs

- ci/requirements/min-all-deps.yml
- doc/whats-new.rst
- xarray/tests/test_backends.py
> Prevent pydap (dap4) to change string arrays to unicode type (testing). Fixed upstream

- doc/whats-new.rst
- xarray/backends/common.py
- xarray/conventions.py
- xarray/tests/test_backends_common.py
We now always add variable names and contents when encoding fails, in contrast to the current practice where variable names and values are only sometimes specified, based on the `name` passed into `VariableCoder.encode()`. This provides better debugging experience for users.
In the future, we might remove `name` from `VariableCoder.encode()` because this makes it redundant.
For example, attempting to save a int64 fail in netCDF3 file now shows something like the following:
ValueError: could not safely cast array from int64 to int32...
Raised while encoding variable 'invalid' with value <xarray.Variable (invalid: 1)> Size: 8B
array([9223372036854775807])
Note that `Exception.add_note()` is a Python 3.11+ feature, so this PR will need to wait until #10438 is submitted.
> Use add_note() to annotate exceptions when encoding fails

- xarray/tests/conftest.py
- xarray/tests/test_backends.py
Fixess the test test failures introduced by https://github.com/pydata/xarray/pull/10469/ 
That PR introduced a new test that used the `time_unit` fixture which is scoped to `module`. This was somehow resulting in leakage of state across tests. Normally this doesn't seem to matter (e.g. other fixtures also use that scope) but it was affecting the get/set counting.
See also: https://docs.pytest.org/en/stable/how-to/fixtures.html#fixture-scopes
This also reverts: https://github.com/pydata/xarray/commit/8d2e563b969da9b540a3d6fb62c769f37ee48f28 to restore the initial values
@maxrjones your bisecting was very helpful! also @TomNicholas 
- [NA] Tests added
- [NA] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [NA] New functions/methods are listed in …
> Fix Zarr 'number of requests' test

- ci/release_contributors.py
I tried to run the [`ci/release_contributors.py`](https://github.com/pydata/xarray/blob/main/ci/release_contributors.py) script using uv, but got a weird error
```
tom@Toms-MacBook-Air xarray % uv run python ci/release_contributors.py
<class 'list'>
File "/Users/tom/Documents/Work/Code/xarray/ci/release_contributors.py", line 51, in <module>
main()
~~~~^^
File "/Users/tom/Documents/Work/Code/xarray/ci/release_contributors.py", line 15, in main
most_recent_release = last(repo.tags)
File "/Users/tom/Documents/Work/Code/xarray/.venv/lib/python3.13/site-packages/toolz/itertoolz.py", line 407, in last
return tail(1, seq)[0]
~~~~^^^^^^^^
File "/Users/tom/Documents/Work/Code/xarray/.venv/lib/python3.13/site-packages/toolz/itertoolz.py", line 342, in tail
return …
```
> Fix bug with `ci/release_contributors.py` script

- xarray/core/indexes.py
- xarray/core/treenode.py
- xarray/groupers.py
> Unnecessary generator

- xarray/plot/utils.py
- xarray/tests/test_units.py
> Use `is` when comparing type of two objects

- xarray/indexes/nd_point_index.py
> Use a set comprehension

- doc/api.rst
Added missing directive.
Intersphinx couldn't find the reference.
> DOC: add Pandas(Multi)Index to API reference

- doc/api-hidden.rst
- doc/api.rst
- xarray/core/coordinate_transform.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/indexes.py
A couple of xarray-tutorial paths have changed.
> Update Custom Indexes section in api.rst

- doc/api.rst
- doc/whats-new.rst
- xarray/indexes/__init__.py
Release in prep for a talk at SciPy 2025 on flexible indexes. See https://xarray-indexes.readthedocs.io/ for more!
> Add release notes for v2025.07.1

- doc/whats-new.rst
- xarray/tests/test_backends_datatree.py
> Pydap flaky tests

- .github/labeler.yml
So, looks like there was a bug in #10201 that made it so it was labeling _every PR_ as `topic-documentation`, even this PR.
I think its because the `any-glob-to-any-file:` is an OR, and technically everything is either in 'doc/**/*' or in '!doc/whats-new.rst'.
Fixed now
> Fix labeler for `topic-documentation`

- xarray/testing/strategies.py
In the next version of `hypothesis` subclasses of `hypothesis.strategies.SearchStrategy` will be required to call `super().__init__()` in their `__init__` method (https://github.com/HypothesisWorks/hypothesis/pull/4473).  This PR addresses this in the two subclasses in our codebase: `CFTimeStrategy` and `CFTimeStrategyISO8601`.  
Apparently this kind of subclassing is not actually part of the public API ([link](https://github.com/HypothesisWorks/hypothesis/pull/4473/files#diff-9abc0311b216f25f0b71cfff6b7043b22071d09a58cb949f6bc5022ddeaa8e7f)), so maybe we should adjust the approach here long term, but this at least gets the tests passing for now.
> Call `super().__init__()` in `st.SearchStrategy` subclasses

- doc/whats-new.rst
- xarray/coding/variables.py
- xarray/tests/test_backends.py
- xarray/tests/test_conventions.py
> Fix transpose of BoolTypeArray, NativeEndiannessArray

- ci/install-upstream-wheels.sh
The `pyarrow` nightly wheels (which we needed for upstream `pandas` when that moved to depending on `pyarrow`) have moved to a different place, so this updates our upstream-dev script.
Alternatively, we could just not install `pyarrow` separately, as we don't use it directly and the version pulled in from conda-forge by pandas should be recent enough.
> install `pyarrow` from its official repo

- pyproject.toml
This bumps the build deps to `setuptools>=77.0.3` and ``setuptools-scm>=8`. The bump in `setuptools` became necessary because we use a SPDX identifier for the license metadata, which is only supported for that version, and `setuptools-scm=8` has been out for almost 2 years.
> bump the build metadata

- xarray/core/coordinates.py
> Make warning message clearer when assigning to `PandasMultiIndex`

- doc/whats-new.rst
- xarray/backends/api.py
- xarray/backends/common.py
- xarray/backends/file_manager.py
- xarray/backends/h5netcdf_.py
- xarray/backends/netCDF4_.py
- xarray/backends/plugins.py
- xarray/backends/pydap_.py
- xarray/backends/scipy_.py
- xarray/backends/store.py
- xarray/backends/zarr.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/datatree.py
- xarray/core/datatree_io.py
- xarray/core/utils.py
- xarray/tests/test_backends.py
- xarray/tests/test_backends_common.py
- xarray/tests/test_backends_datatree.py
And some other related improvements to reading and writing of NetCDF files to/from bytes or file-like objects.
* Allows use of h5netcdf engine when writing to file-like objects (such as `BytesIO`), stop forcing use of scipy backend in this case (which is incompatible with groups and `DataTree`). Makes h5netcdf the default engine for `DataTree.to_netcdf` rather than leaving the choice of default up to `Dataset.to_netcdf`.
* Allows use of h5netcdf engine to read from a bytes object.
* Allows `DataTree.to_netcdf` to return bytes when filepath argument is omitted (similar to `Dataset.to_netcdf`).
> Support for DataTree.to_netcdf to write to a file-like object or bytes

- xarray/core/indexing.py
- xarray/tests/test_indexing.py
The lazy indexing machinery currently uses `_index_indexer_1d` to keep indexing lazy (for orthogonal indexing only), which tries very hard to combine multiple sequential indexers into a single indexer.
However, it currently uses `_expand_slice` when indexing a `slice` with an array, which has the potential to run out of memory for very large dimension sizes of the indexed array.
Instead of materializing, we can just combine the slice (`s`) with the array (`idx`) by:
``` python
new_idx = idx * s.step + s.start
```
Interestingly, this works regardless of whether `step` is negative or positive, but we do have to raise an `IndexError` if there's any value `>= size`.
> slicing a slice with an array without expanding the slice

- doc/whats-new.rst
- xarray/backends/api.py
- xarray/backends/zarr.py
> clarify lazy behaviour and eager loading chunks=None in open_*-functions

- doc/whats-new.rst
- xarray/core/variable.py
- xarray/structure/merge.py
- xarray/tests/test_merge.py
~So far this PR just adds some tests demonstrating how~ Using certain join values ("exact" and "override") on `merge` can alter the original objects.
I discovered this in the context of https://github.com/pydata/xarray/pull/10062#issuecomment-3141367913 but it's not really related to changes in that PR.
> Fix `ds.merge` to prevent altering original object depending on join value

- doc/examples/multidimensional-coords.ipynb
- doc/get-help/faq.rst
- doc/getting-started-guide/installing.rst
- doc/user-guide/io.rst
- doc/user-guide/plotting.rst
- doc/user-guide/weather-climate.rst
- doc/whats-new.rst
The Cartopy docs have a new home on ReadTheDocs and the Iris docs have been there for a while.
I notice this change will conflict with #10526, so I am happy to wait and rebase when that is done if preferred.
> Update Cartopy and Iris references

- xarray/backends/api.py
- xarray/core/datatree.py
- xarray/core/datatree_io.py
- xarray/core/datatree_mapping.py
- xarray/core/treenode.py
- xarray/tests/test_backends_datatree.py
- xarray/tests/test_datatree.py
- xarray/tests/test_treenode.py
I switched typing in `treenode.py` to use `Self` instead of using type variables, which we can do now that  Xarray requries Python 3.11+.
This is simpler than using `TypeVar` and a `Generic` base class, and as a bonus type checkers seem to be a bit happier with `Self`, e.g., this turned up a bunch of other type errors with `DataTree`, which I also fixed here.
> Improve DataTree typing

- doc/api/io.rst
- doc/whats-new.rst
- xarray/__init__.py
- xarray/backends/api.py
- xarray/tests/test_backends.py
`load_datatree` loads `DataTree` objects into memory from disk, similar to `load_dataarray` and `load_dataset`.
This is particularly useful now that `DataTree` objects can be loaded from `bytes`, so you write something like `tree = xr.load_datatree(netcdf_bytes)`.
> Add load_datatree function

- xarray/core/coordinates.py
- xarray/tests/test_dataarray.py
Reverting a problematic change from https://github.com/pydata/xarray/pull/10694 (@max-sixty )
The test I added failed on the latest release, and passes with these changes.
> fix: don't destroy dtypes in to_dataframe

- doc/whats-new.rst
- xarray/coding/times.py
- xarray/tests/test_coding_times.py
This PR fixes the bug identified in #10722 related to encoding an empty `numpy.datetime64` array.  
Note we are still not able to encode an empty array of `cftime.datetime` objects, but there is a bit of ambiguity since there is no way to infer the calendar type in that circumstance, so I will punt on fixing that for now.
> Fix bug when encoding an empty `numpy.datetime64` array

- .github/ISSUE_TEMPLATE/bugreport.yml
Currently, bugreport is not offered as issue template, as it contains an error.
This PR fixes the Github template `bugreport.yml` (was messed by PR #10707) and allows creation of bugreport issues again.
> fix bugreport.yml

- CLAUDE.md
- Added instruction to include co-authorship trailer in commits
This ensures proper attribution when Claude assists with code contributions.
[This is Claude Code on behalf of the user]
> Add co-authorship instruction to CLAUDE.md

- xarray/tests/test_backends_datatree.py
Fixes the upstream test failure per advice here: https://github.com/zarr-developers/zarr-python/issues/3462#issuecomment-3299862585
If someone could label this with the "test-upstream" that would be fantastic
> Fix Blosc import in test for zarr 3.1.13

- .github/ISSUE_TEMPLATE/bugreport.yml
The template code was missing a closing quote!
And hopefully my new note will encourage people to actually test their reproducer rather than just leaving in the header when they haven't used it.
> Fix bug in bug-fix template

- xarray/static/css/style.css
> Less vertical whitespace in HTML reprs

- doc/whats-new.rst
> release notes for 2025.10.0

- doc/whats-new.rst
- xarray/backends/api.py
- xarray/backends/writers.py
- xarray/core/dataarray.py
- xarray/core/dataset.py
- xarray/core/options.py
- xarray/tests/test_backends_api.py
> Fix reverting default netCDF engine (and prepare 2025.10.1 release)

- doc/whats-new.rst
- xarray/core/datatree.py
- xarray/core/datatree_mapping.py
- xarray/core/treenode.py
- xarray/structure/merge.py
- xarray/tests/test_datatree.py
- xarray/tests/test_datatree_mapping.py
- xarray/tests/test_merge.py
> Add support for DataTree to xarray.merge()
